#!/bin/bash
#
# build_esq_fullc.sh -- one-command build of the whole-program C application.
#
# Runs the three-stage pipeline in order and prints where the executable landed:
#   1. compile_all_sasc_far.sh  -- sc DATA=FAR IDLEN=64 : every restored .c -> .o
#   2. build_data_segment.sh    -- vasm : all src/data + equates -> datasegment.o
#   3. link_full_program.sh     -- slink : startup + objects + data + libs -> ESQ_fullc
#
# Output: src/decomp/sas_c/ESQ_fullc  (also refreshed into build/decomp/phase3/).
#
# NOTE: the hand-authored stub/glue objects in src/decomp/sas_c/_farobj/
# (oscall_stubs.o, *_jmptbl_stubs.o, _missing_stubs.o, ...) are prerequisites that
# this pipeline does NOT regenerate -- it only rebuilds the .c-derived objects.
# This script verifies they are present and aborts with guidance if they are not.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$ROOT"

SCRIPTS="src/decomp/scripts"
OBJ="src/decomp/sas_c/_farobj"
OUT_CANON="src/decomp/sas_c/ESQ_fullc"
OUT_COPY="build/decomp/phase3/ESQ_fullc"
LINKLOG="build/decomp/phase3/link.log"
VASM="${VASM_BIN:-$HOME/Downloads/vasm/vasmm68k_mot}"

step() { printf '\n\033[1m===== %s =====\033[0m\n' "$*"; }
die()  { printf '\033[31mBUILD FAILED: %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- preflight ----
step "Preflight"
[ -x "$VASM" ] || die "vasm not found at $VASM (set VASM_BIN=/path/to/vasmm68k_mot)."
command -v vamos >/dev/null 2>&1 || source "$HOME/Downloads/vamos/bin/activate" 2>/dev/null || true
command -v vamos >/dev/null 2>&1 || die "vamos not on PATH (expected ~/Downloads/vamos/bin/activate)."
for s in compile_all_sasc_far build_data_segment link_full_program; do
    [ -f "$SCRIPTS/$s.sh" ] || die "missing pipeline script $SCRIPTS/$s.sh"
done
# Stub/glue objects are non-rebuildable prerequisites; require the key ones.
missing_stubs=()
for o in oscall_stubs _missing_stubs; do
    [ -f "$OBJ/$o.o" ] || missing_stubs+=("$o.o")
done
stub_count=$(ls "$OBJ"/*stub*.o "$OBJ"/*jmptbl*.o 2>/dev/null | wc -l | tr -d ' ')
if [ "${#missing_stubs[@]}" -ne 0 ] || [ "$stub_count" -lt 50 ]; then
    die "stub/glue objects missing from $OBJ (need ${missing_stubs[*]:-<jmptbl stubs>}). These are prebuilt artifacts, not regenerated by this pipeline; restore them before building."
fi
echo "  toolchain OK; $stub_count stub/glue objects present in _farobj/"

# ------------------------------------------------------------ 1. compile ----
step "1/3  Compiling restored C  (sc DATA=FAR IDLEN=64)"
bash "$SCRIPTS/compile_all_sasc_far.sh" || true   # resumable; per-file failures are tolerated (backed by stubs)
if grep -q '^FAIL' build/decomp/phase3/compile.log 2>/dev/null; then
    nfail=$(grep -c '^FAIL' build/decomp/phase3/compile.log)
    # Since the --cwd fix (see compile_all_sasc_far.sh) every real function .c
    # compiles; the only expected FAILs are the *_jmptbl_* wrapper sources, which
    # are intentionally served by the behaviorally-identical vasm JMP stubs in
    # build/decomp/phase3/jmptbl_stubs.asm. A non-jmptbl FAIL is a real regression.
    echo "  note: $nfail source(s) not compiled (expected: *_jmptbl_* wrappers, served by jmptbl_stubs.o):"
    grep '^FAIL' build/decomp/phase3/compile.log | sed 's/^/    /'
    if grep '^FAIL' build/decomp/phase3/compile.log | grep -qv 'jmptbl'; then
        echo "  WARNING: a non-jmptbl source failed to compile -- investigate (this used to be the --cwd bug)."
    fi
fi

# --------------------------------------------------------- 2. data segment ----
step "2/3  Assembling data segment  (vasm)"
bash "$SCRIPTS/build_data_segment.sh" || die "build_data_segment.sh failed"
[ -f build/decomp/phase3/datasegment.o ] || die "datasegment.o was not produced"

# ---------------------------------------------------------------- 3. link ----
step "3/3  Linking  (slink)"
rm -f "$OUT_CANON"
bash "$SCRIPTS/link_full_program.sh" || true

# ------------------------------------------------------------ verify + report --
step "Result"
[ -f "$OUT_CANON" ] || die "ESQ_fullc was not produced (see $LINKLOG)."
# real unresolved-symbol lines (not the empty 'Undefined symbols' header)
unresolved=$(grep -iE 'unresolved|undefined' "$LINKLOG" 2>/dev/null \
             | grep -viE 'Undefined symbols|First Referenced' | sort -u)
if [ -n "$unresolved" ]; then
    echo "$unresolved" | sed 's/^/  UNRESOLVED: /'
    die "link produced unresolved symbols (see $LINKLOG)."
fi

# multiply-defined = a broken link: slink aborts and leaves a TRUNCATED binary.
# This must fail the build (it previously printed "0 multiply-defined" without
# checking and deployed the truncated binary).
muldef=$(grep -ci 'multiply defined' "$LINKLOG" 2>/dev/null); muldef=${muldef:-0}
if [ "$muldef" -gt 0 ]; then
    grep -i 'multiply defined' "$LINKLOG" | head | sed 's/^/  MULTIPLY-DEFINED: /'
    die "$muldef multiply-defined symbol(s) -- broken link (see $LINKLOG). NOT deploying."
fi

# size sanity: a healthy ESQ_fullc is ~490 KB. A truncated link is far smaller.
size=$(stat -f%z "$OUT_CANON" 2>/dev/null || stat -c%s "$OUT_CANON")
if [ "$size" -lt 400000 ]; then
    die "ESQ_fullc is only $size bytes (expected ~490 KB) -- truncated/broken link. NOT deploying."
fi

mkdir -p "$(dirname "$OUT_COPY")"
cp "$OUT_CANON" "$OUT_COPY"
objs=$(ls "$OBJ"/*.o | wc -l | tr -d ' ')

printf '\n\033[32m*** ESQ_fullc BUILT — 0 undefined / 0 multiply-defined ***\033[0m\n'
printf '  size    : %s bytes\n' "$size"
printf '  objects : %s linked\n' "$objs"
printf '  binary  : %s\n' "$ROOT/$OUT_CANON"
printf '  copy    : %s\n' "$ROOT/$OUT_COPY"

# deploy to the FS-UAE Prevue HDD only after all integrity checks pass
cp "$OUT_CANON" "$HOME/Downloads/Prevue/ESQ"
printf '  deployed: %s\n' "$HOME/Downloads/Prevue/ESQ"
