#!/bin/bash
set -euo pipefail
SRC_C="src/decomp/c/replacements/script_esq_capture_ctrl_bit4_stream_buffer_byte_gcc.c"
ORIG_ASM="src/modules/groups/b/a/script2.s"
OUT_DIR="build/decomp/c_trial_gcc"
GEN_ASM="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.generated.gcc.s"
ORIG_SLICE="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.original_slice.s"
GEN_SLICE="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.generated_slice.s"
ORIG_NORM="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.original_slice.norm.s"
GEN_NORM="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.generated_slice.norm.s"
ORIG_SEM="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.original_slice.semantic.txt"
GEN_SEM="${OUT_DIR}/script_esq_capture_ctrl_bit4_stream_buffer_byte.generated_slice.semantic.txt"
CC_BIN="${CROSS_CC:-/opt/amiga/bin/m68k-amigaos-gcc}"
GCC_CFLAGS="${GCC_CFLAGS:--O1 -m68000 -ffreestanding -fno-builtin -fno-inline -fomit-frame-pointer}"
mkdir -p "$OUT_DIR"
"$CC_BIN" -S $GCC_CFLAGS -Isrc/decomp/c/include "$SRC_C" -o "$GEN_ASM"
awk '$0~/^SCRIPT_ESQ_CaptureCtrlBit4StreamBufferByte:?$/{in_func=1} in_func{if($0~/^;!======/){exit} print}' "$ORIG_ASM" > "$ORIG_SLICE"
awk '$0~/^_?SCRIPT_ESQ_CaptureCtrlBit4StreamBufferByte:?$/{in_func=1} in_func{print}' "$GEN_ASM" > "$GEN_SLICE"
sed -e 's/\r$//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]\+/ /g' -e '/^#APP$/d' -e '/^#NO_APP$/d' -e '/^| /d' -e 's/^_//' -e 's/ _/ /g' -e 's/:[[:space:]]*$/:/' "$ORIG_SLICE" > "$ORIG_NORM"
sed -e 's/\r$//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]\+/ /g' -e '/^#APP$/d' -e '/^#NO_APP$/d' -e '/^| /d' -e 's/^_//' -e 's/ _/ /g' -e 's/:[[:space:]]*$/:/' -e 's/%sp/A7/g' -e 's/%a\([0-7]\)/A\1/g' -e 's/%d\([0-7]\)/D\1/g' "$GEN_SLICE" | awk '{ if ($0 ~ /^[a-z]/) { first=$1; $1=toupper(first) } print }' > "$GEN_NORM"
awk -f src/decomp/scripts/semantic_filter_script_esq_capture_ctrl_bit4_stream_buffer_byte.awk "$ORIG_NORM" > "$ORIG_SEM"
awk -f src/decomp/scripts/semantic_filter_script_esq_capture_ctrl_bit4_stream_buffer_byte.awk "$GEN_NORM" > "$GEN_SEM"
diff -u "$ORIG_SEM" "$GEN_SEM" || true
