__asm__(
    ".globl _CLEANUP_ParseAlignedListingBlock\n"
    "_CLEANUP_ParseAlignedListingBlock:\n"
    "    LINK.W  A5,#-128\n"
    "    MOVEM.L D2-D7/A2-A3/A6,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    CLR.B   -57(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEQ   #22,D1\n"
    "    MOVE.B  D1,-97(A5)\n"
    "    MOVEQ   #23,D2\n"
    "    MOVE.B  D2,-96(A5)\n"
    "    MOVE.B  #$3,-95(A5)\n"
    "    MOVE.B  #$4,-94(A5)\n"
    "    MOVEQ   #16,D3\n"
    "    MOVE.B  D3,-93(A5)\n"
    "    MOVEQ   #5,D4\n"
    "    MOVE.B  D4,-92(A5)\n"
    "    MOVE.L  D0,-70(A5)\n"
    "    MOVE.L  D0,-66(A5)\n"
    "    MOVE.L  D0,-62(A5)\n"
    "    MOVEQ   #15,D0\n"
    "    MOVE.B  D0,-91(A5)\n"
    "    MOVEQ   #6,D0\n"
    "    MOVE.B  D0,-90(A5)\n"
    "    MOVEQ   #20,D0\n"
    "    MOVE.B  D0,-89(A5)\n"
    "    MOVE.B  D1,-125(A5)\n"
    "    MOVE.B  D2,-124(A5)\n"
    "    MOVE.B  D3,-123(A5)\n"
    "    MOVE.B  D4,-122(A5)\n"
    "    MOVE.B  #$f,-121(A5)\n"
    "    MOVE.B  #$6,-120(A5)\n"
    "    MOVE.B  D0,-119(A5)\n"
    "    CLR.W   -32(A5)\n"
    "\n"
    ".init_slot_table_loop:\n"
    "    MOVE.W  -32(A5),D0\n"
    "    MOVEQ   #10,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .after_slot_init\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    MOVE.W  #(-1),-52(A5,D1.L)\n"
    "    ADDQ.W  #1,-32(A5)\n"
    "    BRA.S   .init_slot_table_loop\n"
    "\n"
    ".after_slot_init:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A3),D0\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "    AND.L   D1,D0\n"
    "    ADDQ.L  #1,-66(A5)\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    MOVE.B  D0,-57(A5)\n"
    "    CMP.B   D0,D1\n"
    "    BNE.S   .check_service_type_b\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    SUBQ.B  #1,D1\n"
    "    BNE.S   .check_service_type_b\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D5\n"
    "    MOVE.B  D0,CTASKS_PendingSecondaryOiDiskId\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.B  D1,CTASKS_SecondaryOiWritePendingFlag\n"
    "    BRA.S   .skip_separator\n"
    "\n"
    ".check_service_type_b:\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D1\n"
    "    CMP.B   D0,D1\n"
    "    BNE.S   .invalid_service_type\n"
    "\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D5\n"
    "    MOVE.B  D0,CTASKS_PendingPrimaryOiDiskId\n"
    "    MOVE.B  #$1,CTASKS_PrimaryOiWritePendingFlag\n"
    "    BRA.S   .skip_separator\n"
    "\n"
    ".invalid_service_type:\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".skip_separator:\n"
    "    MOVEQ   #49,D0\n"
    "    MOVE.L  -66(A5),D1\n"
    "    CMP.B   0(A3,D1.L),D0\n"
    "    BNE.S   .parse_field_offsets\n"
    "\n"
    "    ADDQ.L  #1,-66(A5)\n"
    "\n"
    ".parse_field_offsets:\n"
    "    MOVEA.L A3,A0\n"
    "    MOVE.L  -66(A5),D0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  ESQIFF_RecordLength,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   COI_CountEscape14BeforeNull\n"
    "\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A3,A0\n"
    "    MOVE.L  -66(A5),D1\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  ESQIFF_RecordLength,D2\n"
    "    SUB.L   D1,D2\n"
    "    EXT.L   D2\n"
    "    PEA     1.W\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    PEA     -97(A5)\n"
    "    PEA     9.W\n"
    "    PEA     -88(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D0,-62(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(PC)\n"
    "\n"
    "    LEA     36(A7),A7\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #0,D7\n"
    "    CLR.W   -32(A5)\n"
    "    MOVE.L  D0,-70(A5)\n"
    "\n"
    ".scan_candidate_loop:\n"
    "    CMP.W   D5,D7\n"
    "    BGE.S   .after_candidate_scan\n"
    "\n"
    "    CMPI.W  #10,-32(A5)\n"
    "    BGE.S   .after_candidate_scan\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    MOVE.B  -57(A5),D1\n"
    "    CMP.B   D0,D1\n"
    "    BNE.S   .use_alt_entry_table\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D0\n"
    "    SUBQ.B  #1,D0\n"
    "    BNE.S   .use_alt_entry_table\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    BRA.S   .compare_candidate_entry\n"
    "\n"
    ".use_alt_entry_table:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "\n"
    ".compare_candidate_entry:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    ADDA.W  #12,A0\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.S   .store_candidate_slot\n"
    "\n"
    "    MOVE.W  -32(A5),D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,D0\n"
    "    MOVE.W  D7,-52(A5,D0.L)\n"
    "    ADDQ.W  #1,-32(A5)\n"
    "\n"
    ".store_candidate_slot:\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .scan_candidate_loop\n"
    "\n"
    ".after_candidate_scan:\n"
    "    MOVE.W  -52(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .select_first_entry\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".select_first_entry:\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    MOVE.B  -57(A5),D1\n"
    "    CMP.B   D0,D1\n"
    "    BNE.S   .select_alt_entry\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D0\n"
    "    SUBQ.B  #1,D0\n"
    "    BNE.S   .select_alt_entry\n"
    "\n"
    "    MOVE.W  -52(A5),D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    BRA.S   .populate_entry_fields\n"
    "\n"
    ".select_alt_entry:\n"
    "    MOVE.W  -52(A5),D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "\n"
    ".populate_entry_fields:\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    BSR.W   COI_ClearAnimObjectStrings\n"
    "\n"
    "    MOVE.L  -4(A5),(A7)\n"
    "    BSR.W   COI_FreeSubEntryTableEntries\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  48(A0),-12(A5)\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  -66(A5),A0\n"
    "    ADDA.W  -84(A5),A0\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVE.L  4(A1),(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,4(A0)\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    MOVEA.W -82(A5),A2\n"
    "    MOVE.L  A2,D0\n"
    "    MOVE.B  0(A1,D0.W),(A0)\n"
    "    MOVE.B  1(A1,D0.W),1(A0)\n"
    "    MOVE.B  2(A1,D0.W),2(A0)\n"
    "    CLR.B   3(A0)\n"
    "    ADDA.W  -80(A5),A1\n"
    "    MOVE.L  12(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,12(A0)\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -78(A5),A1\n"
    "    MOVE.L  20(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,20(A0)\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -76(A5),A1\n"
    "    MOVE.L  8(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,8(A0)\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -74(A5),A1\n"
    "    MOVE.L  16(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,16(A0)\n"
    "    MOVE.L  -62(A5),D0\n"
    "    MOVE.W  D0,36(A0)\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -88(A5),A1\n"
    "    TST.B   (A1)\n"
    "    BEQ.S   .build_title_from_field\n"
    "\n"
    "    LEA     24(A0),A2\n"
    "    LEA     28(A0),A6\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A6,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    BSR.W   CLEANUP_FormatEntryStringTokens\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .after_title_format\n"
    "\n"
    ".build_title_from_field:\n"
    "    MOVE.L  24(A0),-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,24(A0)\n"
    "    MOVE.L  28(A0),(A7)\n"
    "    PEA     CLOCK_STR_MISSING_TITLE_TEMPLATE\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,28(A0)\n"
    "\n"
    ".after_title_format:\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  -66(A5),A0\n"
    "    ADDA.W  -86(A5),A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.S   .set_missing_extra\n"
    "\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,32(A0)\n"
    "    BRA.S   .advance_entry_offset\n"
    "\n"
    ".set_missing_extra:\n"
    "    MOVEQ   #-1,D0\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,32(A0)\n"
    "\n"
    ".advance_entry_offset:\n"
    "    MOVE.W  -74(A5),D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,-66(A5)\n"
    "    TST.L   16(A0)\n"
    "    BEQ.S   .alloc_subentry_table\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 16(A1),A0\n"
    "\n"
    ".count_entry_text_loop:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .count_entry_text_loop\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  16(A1),A0\n"
    "    MOVE.L  A0,D0\n"
    "    ADD.L   D0,-66(A5)\n"
    "\n"
    ".alloc_subentry_table:\n"
    "    ADDQ.L  #1,-66(A5)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    BSR.W   COI_AllocSubEntryTable\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".subentry_loop:\n"
    "    MOVEA.L -12(A5),A0\n"
    "    CMP.W   36(A0),D6\n"
    "    BGE.W   .begin_merge\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-20(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  -66(A5),D1\n"
    "    MOVE.B  0(A3,D1.L),D0\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.W  D0,(A0)\n"
    "    ADDQ.L  #1,-66(A5)\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  -66(A5),D0\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  ESQIFF_RecordLength,D1\n"
    "    SUB.L   D0,D1\n"
    "    EXT.L   D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    PEA     -125(A5)\n"
    "    PEA     7.W\n"
    "    PEA     -116(A5)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVE.W  -112(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .select_subentry_title\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 12(A1),A0\n"
    "    BRA.S   .store_subentry_title\n"
    "\n"
    ".select_subentry_title:\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  -66(A5),A0\n"
    "    ADDA.W  -112(A5),A0\n"
    "\n"
    ".store_subentry_title:\n"
    "    MOVEA.L -20(A5),A1\n"
    "    MOVE.L  6(A1),-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A0,-56(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,6(A0)\n"
    "    MOVE.W  -110(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .select_subentry_desc\n"
    "\n"
    "    MOVEA.L -12(A5),A2\n"
    "    MOVEA.L 20(A2),A1\n"
    "    BRA.S   .store_subentry_desc\n"
    "\n"
    ".select_subentry_desc:\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -110(A5),A1\n"
    "\n"
    ".store_subentry_desc:\n"
    "    MOVE.L  14(A0),-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A1,-56(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,14(A0)\n"
    "    MOVE.W  -108(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .select_subentry_alt\n"
    "\n"
    "    MOVEA.L -12(A5),A2\n"
    "    MOVEA.L 8(A2),A1\n"
    "    BRA.S   .store_subentry_alt\n"
    "\n"
    ".select_subentry_alt:\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -108(A5),A1\n"
    "\n"
    ".store_subentry_alt:\n"
    "    MOVE.L  2(A0),-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A1,-56(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,2(A0)\n"
    "    MOVE.W  -106(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .select_subentry_more\n"
    "\n"
    "    MOVEA.L -12(A5),A2\n"
    "    MOVEA.L 16(A2),A1\n"
    "    BRA.S   .store_subentry_more\n"
    "\n"
    ".select_subentry_more:\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  -66(A5),A1\n"
    "    ADDA.W  -106(A5),A1\n"
    "\n"
    ".store_subentry_more:\n"
    "    MOVE.L  10(A0),-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A1,-56(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,10(A0)\n"
    "    MOVE.W  -116(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .format_subentry_extra\n"
    "\n"
    "    MOVE.L  18(A0),-(A7)\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVE.L  24(A1),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,18(A0)\n"
    "    MOVE.L  22(A0),(A7)\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVE.L  28(A1),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,22(A0)\n"
    "    BRA.S   .store_subentry_extra\n"
    "\n"
    ".format_subentry_extra:\n"
    "    LEA     18(A0),A1\n"
    "    LEA     22(A0),A2\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  -66(A5),A0\n"
    "    ADDA.W  -116(A5),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    BSR.W   CLEANUP_FormatEntryStringTokens\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".store_subentry_extra:\n"
    "    MOVE.W  -114(A5),D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .load_subentry_icon\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVEA.L -20(A5),A1\n"
    "    MOVE.L  32(A0),26(A1)\n"
    "    BRA.S   .advance_subentry_offset\n"
    "\n"
    ".load_subentry_icon:\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  -66(A5),A0\n"
    "    ADDA.W  -114(A5),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,26(A0)\n"
    "\n"
    ".advance_subentry_offset:\n"
    "    MOVE.W  -104(A5),D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,-66(A5)\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.W   .subentry_loop\n"
    "\n"
    ".begin_merge:\n"
    "    MOVE.W  #1,-32(A5)\n"
    "\n"
    ".merge_candidate_loop:\n"
    "    MOVE.W  -32(A5),D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,D0\n"
    "    MOVEQ   #-1,D1\n"
    "    CMP.W   -52(A5,D0.L),D1\n"
    "    BEQ.W   .return_success\n"
    "\n"
    "    MOVE.W  -32(A5),D0\n"
    "    MOVEQ   #10,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.W   .return_success\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    MOVE.B  -57(A5),D2\n"
    "    CMP.B   D1,D2\n"
    "    BNE.S   .select_merge_table\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    SUBQ.B  #1,D1\n"
    "    BNE.S   .select_merge_table\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    MOVE.W  -52(A5,D1.L),D2\n"
    "    EXT.L   D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    MOVE.L  (A0),-8(A5)\n"
    "    BRA.S   .merge_entry_copy\n"
    "\n"
    ".select_merge_table:\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    MOVE.W  -52(A5,D1.L),D2\n"
    "    EXT.L   D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    MOVE.L  (A0),-8(A5)\n"
    "\n"
    ".merge_entry_copy:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  48(A0),-12(A5)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  48(A0),-16(A5)\n"
    "    ADDQ.W  #1,-32(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   COI_ClearAnimObjectStrings\n"
    "\n"
    "    MOVE.L  -8(A5),(A7)\n"
    "    BSR.W   COI_FreeSubEntryTableEntries\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  4(A0),(A7)\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVE.L  4(A1),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,4(A0)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVEA.L -16(A5),A1\n"
    "    MOVE.B  (A0),(A1)\n"
    "    MOVE.B  1(A0),1(A1)\n"
    "    MOVE.B  2(A0),2(A1)\n"
    "    MOVE.B  3(A0),3(A1)\n"
    "    MOVE.L  12(A1),(A7)\n"
    "    MOVE.L  12(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,12(A0)\n"
    "    MOVE.L  20(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  20(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,20(A0)\n"
    "    MOVE.L  8(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  8(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,8(A0)\n"
    "    MOVE.L  16(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  16(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,16(A0)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVEA.L -16(A5),A1\n"
    "    MOVE.W  36(A0),36(A1)\n"
    "    MOVE.L  24(A1),(A7)\n"
    "    MOVE.L  24(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,24(A0)\n"
    "    MOVE.L  28(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  28(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  D0,28(A0)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVEA.L -16(A5),A1\n"
    "    MOVE.L  32(A0),32(A1)\n"
    "    MOVE.L  -8(A5),(A7)\n"
    "    BSR.W   COI_AllocSubEntryTable\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".merge_subentry_loop:\n"
    "    MOVEA.L -12(A5),A0\n"
    "    CMP.W   36(A0),D7\n"
    "    BGE.W   .merge_candidate_loop\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-20(A5)\n"
    "    MOVEA.L -16(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-24(A5)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVEA.L -24(A5),A1\n"
    "    MOVE.W  (A0),(A1)\n"
    "    MOVE.L  6(A1),-(A7)\n"
    "    MOVE.L  6(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,6(A0)\n"
    "    MOVE.L  14(A0),(A7)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  14(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,14(A0)\n"
    "    MOVE.L  2(A0),(A7)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  2(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,2(A0)\n"
    "    MOVE.L  10(A0),(A7)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  10(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,10(A0)\n"
    "    MOVE.L  18(A0),(A7)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  18(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,18(A0)\n"
    "    MOVE.L  22(A0),(A7)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  22(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,22(A0)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVEA.L -24(A5),A1\n"
    "    MOVE.L  26(A0),26(A1)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.W   .merge_subentry_loop\n"
    "\n"
    ".return_success:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".return_status:\n"
    "    MOVEM.L (A7)+,D2-D7/A2-A3/A6\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
