__asm__(
    ".globl _CLEANUP_TestEntryFlagYAndBit1\n"
    "_CLEANUP_TestEntryFlagYAndBit1:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D5-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVE.L  16(A5),D6\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     7.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    BEQ.S   .return_false\n"
    "\n"
    "    TST.L   D6\n"
    "    BMI.S   .return_false\n"
    "\n"
    "    MOVEQ   #5,D1\n"
    "    CMP.L   D1,D6\n"
    "    BGT.S   .return_false\n"
    "\n"
    "    MOVEQ   #89,D0\n"
    "    MOVEA.L -4(A5),A0\n"
    "    CMP.B   0(A0,D6.L),D0\n"
    "    BNE.S   .return_false\n"
    "\n"
    "    BTST    #1,40(A3)\n"
    "    BEQ.S   .return_false\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   .done\n"
    "\n"
    ".return_false:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".done:\n"
    "    MOVE.L  D0,D5\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEM.L (A7)+,D5-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
