__asm__(
    ".globl _CLEANUP_DrawBannerSpacerSegment\n"
    "_CLEANUP_DrawBannerSpacerSegment:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D2-D3,-(A7)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  4(A0),-4(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #7,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  32(A0),D0\n"
    "    ANDI.W  #$fff7,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  D0,32(A0)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  #256,D0\n"
    "    MOVEQ   #34,D1\n"
    "    MOVE.L  #447,D2\n"
    "    MOVEQ   #67,D3\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVORectFill(A6)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    PEA     34.W\n"
    "    PEA     256.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     BEVEL_DrawBevelFrameWithTopRight(PC)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -4(A5),4(A0)\n"
    "    MOVEM.L -12(A5),D2-D3\n"
    "    UNLK    A5\n"
    "    RTS\n");
