__asm__(
    ".globl _CLEANUP_FormatEntryStringTokens\n"
    "_CLEANUP_FormatEntryStringTokens:\n"
    "    LINK.W  A5,#-32\n"
    "    MOVEM.L D7/A2-A3/A6,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    TST.L   16(A5)\n"
    "    BEQ.W   .empty_input\n"
    "\n"
    "    MOVEA.L 16(A5),A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.W   .empty_input\n"
    "\n"
    "    PEA     58.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,-26(A5)\n"
    "    TST.L   D0\n"
    "    BEQ.W   .empty_input\n"
    "\n"
    "    LEA     CLOCK_STR_TOKEN_PAIR_DEFAULTS,A0\n"
    "    LEA     -22(A5),A1\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    MOVE.W  (A0),(A1)+\n"
    "    CLR.B   (A1)\n"
    "    LEA     CLEANUP_TokenPairScratch,A0\n"
    "    LEA     -11(A5),A1\n"
    "\n"
    ".copy_prefix_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_prefix_loop\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".scan_input_loop:\n"
    "    MOVEQ   #5,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .after_scan\n"
    "\n"
    "    MOVEQ   #58,D0\n"
    "    MOVEA.L 16(A5),A0\n"
    "    CMP.B   0(A0,D7.L),D0\n"
    "    BEQ.S   .after_scan\n"
    "\n"
    "    MOVE.B  0(A0,D7.L),-11(A5,D7.L)\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .scan_input_loop\n"
    "\n"
    ".after_scan:\n"
    "    CLR.B   -11(A5,D7.L)\n"
    "    MOVE.L  (A3),-(A7)\n"
    "    PEA     -11(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,(A3)\n"
    "    LEA     CLOCK_STR_TOKEN_OUTPUT_TEMPLATE,A0\n"
    "    LEA     -11(A5),A1\n"
    "\n"
    ".copy_suffix_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_suffix_loop\n"
    "\n"
    "    ADDQ.L  #1,-26(A5)\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".token_loop:\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.W   .commit_output\n"
    "\n"
    "    MOVEA.L -26(A5),A0\n"
    "    TST.B   0(A0,D7.L)\n"
    "    BEQ.W   .commit_output\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    CMPI.L  #$9,D0\n"
    "    BCC.W   .next_token\n"
    "\n"
    "    ADD.W   D0,D0\n"
    "    MOVE.W  .token_table(PC,D0.W),D0\n"
    "    JMP     .token_table+2(PC,D0.W)\n"
    "\n"
    "\n"
    ".token_table:\n"
    "	DC.W    .case_alpha_or_copy-.token_table-2\n"
    "    DC.W    .case_alpha_or_copy-.token_table-2\n"
    "	DC.W    .case_alpha_or_copy-.token_table-2\n"
    "    DC.W    .case_alpha_or_copy-.token_table-2\n"
    "	DC.W    .case_alpha_or_copy-.token_table-2\n"
    "    DC.W    .case_alpha_or_copy-.token_table-2\n"
    "	DC.W    .case_flag7_check-.token_table-2\n"
    "    DC.W    .case_flag7_check-.token_table-2\n"
    "    DC.W    .case_pair_check-.token_table-2\n"
    "\n"
    ".case_alpha_or_copy:\n"
    "    MOVEA.L -26(A5),A0\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     CLOCK_STR_BOOL_CHARS_YyNn\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .use_default_char\n"
    "\n"
    "    MOVEA.L -26(A5),A0\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #1,(A1)\n"
    "    BEQ.S   .copy_raw_char\n"
    "\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .store_token_char\n"
    "\n"
    ".copy_raw_char:\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".store_token_char:\n"
    "    MOVE.B  D0,-11(A5,D7.L)\n"
    "    BRA.W   .next_token\n"
    "\n"
    ".use_default_char:\n"
    "    MOVE.B  -22(A5,D7.L),-11(A5,D7.L)\n"
    "    BRA.W   .next_token\n"
    "\n"
    ".case_flag7_check:\n"
    "    MOVEA.L -26(A5),A0\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    BTST    #7,(A0)\n"
    "    BEQ.S   .use_default_char_flag7\n"
    "\n"
    "    MOVEA.L -26(A5),A0\n"
    "    MOVE.B  0(A0,D7.L),-11(A5,D7.L)\n"
    "    BRA.W   .next_token\n"
    "\n"
    ".use_default_char_flag7:\n"
    "    MOVE.B  -22(A5,D7.L),-11(A5,D7.L)\n"
    "    BRA.W   .next_token\n"
    "\n"
    ".case_pair_check:\n"
    "    MOVEA.L -26(A5),A0\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A6\n"
    "    ADDA.L  D0,A6\n"
    "    MOVEQ   #7,D0\n"
    "    AND.B   (A6),D0\n"
    "    TST.B   D0\n"
    "    BEQ.S   .copy_default_pair\n"
    "\n"
    "    MOVE.B  1(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A1,A6\n"
    "    ADDA.L  D0,A6\n"
    "    MOVEQ   #7,D0\n"
    "    AND.B   (A6),D0\n"
    "    TST.B   D0\n"
    "    BEQ.S   .copy_default_pair\n"
    "\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A1,A6\n"
    "    ADDA.L  D0,A6\n"
    "    BTST    #1,(A6)\n"
    "    BEQ.S   .copy_pair_char1\n"
    "\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .store_pair_char1\n"
    "\n"
    ".copy_pair_char1:\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".store_pair_char1:\n"
    "    MOVE.B  D0,-11(A5,D7.L)\n"
    "    ADDQ.L  #1,D7\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #1,(A1)\n"
    "    BEQ.S   .copy_pair_char2\n"
    "\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .store_pair_char2\n"
    "\n"
    ".copy_pair_char2:\n"
    "    MOVE.B  0(A0,D7.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".store_pair_char2:\n"
    "    MOVE.B  D0,-11(A5,D7.L)\n"
    "    BRA.S   .next_token\n"
    "\n"
    ".copy_default_pair:\n"
    "    LEA     -11(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D7,A1\n"
    "    MOVEA.L D7,A6\n"
    "    ADDQ.L  #1,D7\n"
    "    MOVE.L  A6,D0\n"
    "    MOVE.B  -22(A5,D0.L),(A1)\n"
    "    MOVE.B  -22(A5,D7.L),-11(A5,D7.L)\n"
    "\n"
    ".next_token:\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.W   .token_loop\n"
    "\n"
    ".commit_output:\n"
    "    MOVE.L  (A2),-(A7)\n"
    "    PEA     -11(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,(A2)\n"
    "    BRA.S   .done\n"
    "\n"
    ".empty_input:\n"
    "    MOVE.L  (A3),-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,(A3)\n"
    "    MOVE.L  (A2),(A7)\n"
    "    PEA     CLOCK_STR_EMPTY_TOKEN_TEMPLATE\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,(A2)\n"
    "\n"
    ".done:\n"
    "    MOVEM.L (A7)+,D7/A2-A3/A6\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
