__asm__(
    ".globl _CLEANUP_UpdateEntryFlagBytes\n"
    "_CLEANUP_UpdateEntryFlagBytes:\n"
    "    LINK.W  A5,#-16\n"
    "    MOVEM.L D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     7.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    TST.L   D0\n"
    "    BNE.S   .entry_ok\n"
    "\n"
    "    LEA     CLOCK_STR_FALLBACK_ENTRY_FLAGS_PRIMARY,A0\n"
    "    LEA     -15(A5),A1\n"
    "\n"
    ".copy_default_entry_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_default_entry_loop\n"
    "\n"
    "    LEA     -15(A5),A0\n"
    "    MOVE.L  A0,-4(A5)\n"
    "\n"
    ".entry_ok:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #7,(A1)\n"
    "    BEQ.S   .entry_flag6_not_set\n"
    "\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_LADFUNC_ParseHexDigit(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    BRA.S   .store_flag6\n"
    "\n"
    ".entry_flag6_not_set:\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "\n"
    ".store_flag6:\n"
    "    MOVE.B  D1,DISPTEXT_InsetNibblePrimary\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #7,(A1)\n"
    "    BEQ.S   .entry_flag7_not_set\n"
    "\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_LADFUNC_ParseHexDigit(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    BRA.S   .store_flag7\n"
    "\n"
    ".entry_flag7_not_set:\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "\n"
    ".store_flag7:\n"
    "    MOVE.B  D1,DISPTEXT_InsetNibbleSecondary\n"
    "    MOVEM.L (A7)+,D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
