__asm__(
    ".globl _CLEANUP_ShutdownSystem\n"
    "_CLEANUP_ShutdownSystem:\n"
    "    MOVEM.L D6-D7,-(A7)\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    PEA     LOCAVAIL_PrimaryFilterState\n"
    "    JSR     GROUP_AB_JMPTBL_LOCAVAIL_FreeResourceChain(PC)\n"
    "\n"
    "    PEA     LOCAVAIL_SecondaryFilterState\n"
    "    JSR     GROUP_AB_JMPTBL_LOCAVAIL_FreeResourceChain(PC)\n"
    "\n"
    "    CLR.L   (A7)\n"
    "    PEA     ESQIFF_BrushIniListHead\n"
    "    JSR     BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    CLR.L   (A7)\n"
    "    PEA     ESQIFF_GAdsBrushListHead\n"
    "    JSR     BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    CLR.L   (A7)\n"
    "    PEA     ESQIFF_LogoBrushListHead\n"
    "    JSR     BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    CLR.L   (A7)\n"
    "    PEA     ESQFUNC_PwBrushListHead\n"
    "    JSR     BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    BSR.W   CLEANUP_ClearVertbInterruptServer\n"
    "\n"
    "    BSR.W   CLEANUP_ClearAud1InterruptVector\n"
    "\n"
    "    BSR.W   CLEANUP_ClearRbfInterruptAndSerial\n"
    "\n"
    "    PEA     9000.W\n"
    "    MOVE.L  ESQIFF_RecordBufferPtr,-(A7)\n"
    "    PEA     260.W\n"
    "    PEA     Global_STR_CLEANUP_C_13\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    BSR.W   CLEANUP_ShutdownInputDevices\n"
    "\n"
    "    BSR.W   CLEANUP_ReleaseDisplayResources\n"
    "\n"
    "    JSR     GROUP_AB_JMPTBL_LADFUNC_FreeBannerRectEntries(PC)\n"
    "\n"
    "    JSR     GROUP_AH_JMPTBL_ESQPARS_ClearAliasStringPointers(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    JSR     GROUP_AB_JMPTBL_ESQIFF2_ClearLineHeadTailByMode(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    JSR     GROUP_AB_JMPTBL_ESQIFF2_ClearLineHeadTailByMode(PC)\n"
    "\n"
    "    JSR     GROUP_AB_JMPTBL_ESQIFF_DeallocateAdsAndLogoLstData(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    JSR     GROUP_AB_JMPTBL_ESQPARS_RemoveGroupEntryAndReleaseStrings(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    JSR     GROUP_AB_JMPTBL_ESQPARS_RemoveGroupEntryAndReleaseStrings(PC)\n"
    "\n"
    "    JSR     GROUP_AB_JMPTBL_ESQFUNC_FreeLineTextBuffers(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A0\n"
    "    MOVE.L  38(A0),COP1LCH\n"
    "    JSR     GROUP_AB_JMPTBL_NEWGRID_ShutdownGridResources(PC)\n"
    "\n"
    "    PEA     34.W\n"
    "    MOVE.L  ESQ_HighlightMsgPort,-(A7)\n"
    "    PEA     318.W\n"
    "    PEA     Global_STR_CLEANUP_C_14\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     72(A7),A7\n"
    "\n"
    "    PEA     34.W\n"
    "    MOVE.L  ESQ_HighlightReplyPort,-(A7)\n"
    "    PEA     319.W\n"
    "    PEA     Global_STR_CLEANUP_C_15\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".freeRaster_rows_loop:\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.S   .after_raster_table\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".freeRaster_cols_loop:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .next_raster_row\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEQ   #40,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    LEA     ESQDISP_HighlightBitmapTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  WDISP_HighlightRasterHeightPx,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     696.W\n"
    "    MOVE.L  8(A0),-(A7)\n"
    "    PEA     329.W\n"
    "    PEA     Global_STR_CLEANUP_C_16\n"
    "    JSR     GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .freeRaster_cols_loop\n"
    "\n"
    ".next_raster_row:\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.S   .freeRaster_rows_loop\n"
    "\n"
    ".after_raster_table:\n"
    "    MOVE.L  WDISP_WeatherStatusTextPtr,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,WDISP_WeatherStatusTextPtr\n"
    "    MOVE.L  WDISP_WeatherStatusOverlayTextPtr,(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_WeatherStatusOverlayTextPtr\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    MOVEA.L Global_REF_BACKED_UP_INTUITION_AUTOREQUEST,A0\n"
    "    MOVE.L  A0,D0\n"
    "    MOVEA.L Global_REF_INTUITION_LIBRARY,A1\n"
    "    MOVEA.W #_LVOAutoRequest,A0\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOSetFunction(A6)\n"
    "\n"
    "\n"
    "\n"
    "    MOVEA.L Global_REF_BACKED_UP_INTUITION_DISPLAYALERT,A0\n"
    "    MOVE.L  A0,D0\n"
    "    MOVEA.L Global_REF_INTUITION_LIBRARY,A1\n"
    "    MOVEA.W #_LVODisplayAlert,A0\n"
    "    JSR     _LVOSetFunction(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_INTUITION_LIBRARY,A6\n"
    "    JSR     _LVOVBeamPos(A6)\n"
    "\n"
    "    TST.L   ESQ_ProcessWindowPtrBackup\n"
    "    BEQ.S   .after_optional_restore\n"
    "\n"
    "    MOVEA.L WDISP_ExecBaseHookPtr,A0\n"
    "    MOVE.L  ESQ_ProcessWindowPtrBackup,184(A0)\n"
    "\n"
    ".after_optional_restore:\n"
    "    JSR     GROUP_AB_JMPTBL_UNKNOWN2A_Stub0(PC)\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    MOVEM.L (A7)+,D6-D7\n"
    "    RTS\n"
    "\n"
);
