__asm__(
    ".globl _CLEANUP_ReleaseDisplayResources\n"
    "_CLEANUP_ReleaseDisplayResources:\n"
    "    MOVE.L  D7,-(A7)\n"
    "\n"
    "    PEA     96.W\n"
    "    MOVE.L  Global_REF_96_BYTES_ALLOCATED,-(A7)\n"
    "    PEA     148.W\n"
    "    PEA     Global_STR_CLEANUP_C_6\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    PEA     100.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    PEA     152.W\n"
    "    PEA     Global_STR_CLEANUP_C_7\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".freeRaster_set1_loop:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .after_raster_set1\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     WDISP_LivePlaneRasterTable0,A0\n"
    "    ADDA.L  D0,A0\n"
    "    PEA     2.W\n"
    "    PEA     696.W\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     160.W\n"
    "    PEA     Global_STR_CLEANUP_C_8\n"
    "    JSR     GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .freeRaster_set1_loop\n"
    "\n"
    ".after_raster_set1:\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".freeRaster_set2_loop:\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .after_raster_set2\n"
    "\n"
    "    MOVE.L  D7,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     WDISP_352x240RasterPtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    PEA     240.W\n"
    "    PEA     352.W\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     169.W\n"
    "    PEA     Global_STR_CLEANUP_C_9\n"
    "    JSR     GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .freeRaster_set2_loop\n"
    "\n"
    ".after_raster_set2:\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".freeRaster_set3_loop:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .after_raster_set3\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     WDISP_BannerRowScratchRasterTable0,A0\n"
    "    ADDA.L  D0,A0\n"
    "    PEA     509.W\n"
    "    PEA     696.W\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     178.W\n"
    "    PEA     Global_STR_CLEANUP_C_10\n"
    "    JSR     GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .freeRaster_set3_loop\n"
    "\n"
    ".after_raster_set3:\n"
    "    MOVEQ   #3,D7\n"
    "\n"
    ".freeRaster_set4_loop:\n"
    "    MOVEQ   #5,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .after_raster_set4\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     WDISP_DisplayContextPlanePointer0,A0\n"
    "    ADDA.L  D0,A0\n"
    "    PEA     241.W\n"
    "    PEA     696.W\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     187.W\n"
    "    PEA     Global_STR_CLEANUP_C_11\n"
    "    JSR     GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .freeRaster_set4_loop\n"
    "\n"
    ".after_raster_set4:\n"
    "    PEA     15.W\n"
    "    PEA     696.W\n"
    "    MOVE.L  WDISP_BannerWorkRasterPtr,-(A7)\n"
    "    PEA     200.W\n"
    "    PEA     Global_STR_CLEANUP_C_12\n"
    "    JSR     GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "\n"
    "    TST.L   Global_HANDLE_PREVUE_FONT\n"
    "    BEQ.S   .closeTopazFont\n"
    "\n"
    "    MOVEA.L Global_HANDLE_PREVUE_FONT,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOCloseFont(A6)\n"
    "\n"
    ".closeTopazFont:\n"
    "    TST.L   Global_HANDLE_TOPAZ_FONT\n"
    "    BEQ.S   .closeH26fFont\n"
    "\n"
    "    MOVEA.L Global_HANDLE_TOPAZ_FONT,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOCloseFont(A6)\n"
    "\n"
    ".closeH26fFont:\n"
    "    TST.L   Global_HANDLE_H26F_FONT\n"
    "    BEQ.S   .closePrevueCFont\n"
    "\n"
    "    MOVEA.L Global_HANDLE_H26F_FONT,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOCloseFont(A6)\n"
    "\n"
    ".closePrevueCFont:\n"
    "    TST.L   Global_HANDLE_PREVUEC_FONT\n"
    "    BEQ.S   .closeUtilityLibrary\n"
    "\n"
    "    MOVEA.L Global_HANDLE_PREVUEC_FONT,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOCloseFont(A6)\n"
    "\n"
    ".closeUtilityLibrary:\n"
    "    TST.L   Global_REF_UTILITY_LIBRARY\n"
    "    BEQ.S   .closeDiskfontLibrary\n"
    "\n"
    "    MOVEA.L Global_REF_UTILITY_LIBRARY,A1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOCloseLibrary(A6)\n"
    "\n"
    ".closeDiskfontLibrary:\n"
    "    MOVEA.L Global_REF_DISKFONT_LIBRARY,A1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOCloseLibrary(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY,A1\n"
    "    JSR     _LVOCloseLibrary(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_INTUITION_LIBRARY,A1\n"
    "    JSR     _LVOCloseLibrary(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A1\n"
    "    JSR     _LVOCloseLibrary(A6)\n"
    "\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
    "\n"
);
