__asm__(
    ".globl _CLEANUP_DrawInsetRectFrame\n"
    "_CLEANUP_DrawInsetRectFrame:\n"
    "    LINK.W  A5,#-24\n"
    "    MOVEM.L D2-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.B  15(A5),D7\n"
    "    MOVE.W  18(A5),D6\n"
    "    MOVE.W  22(A5),D5\n"
    "    MOVE.B  25(A3),D4\n"
    "    EXT.W   D4\n"
    "    EXT.L   D4\n"
    "    MOVE.W  36(A3),D0\n"
    "    MOVE.W  38(A3),D1\n"
    "    ADDQ.W  #2,D1\n"
    "    MOVE.W  D0,-6(A5)\n"
    "    SUBQ.W  #2,D0\n"
    "    MOVE.W  D1,-8(A5)\n"
    "    SUB.W   62(A3),D1\n"
    "    SUBQ.W  #1,D1\n"
    "    ADDQ.W  #2,D6\n"
    "    MOVE.L  D7,D2\n"
    "    EXT.W   D2\n"
    "    EXT.L   D2\n"
    "    MOVE.W  D0,-10(A5)\n"
    "    MOVE.W  D1,-12(A5)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D2,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  -10(A5),D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D6,D3\n"
    "    EXT.L   D3\n"
    "    ADD.L   D3,D2\n"
    "    MOVE.W  -12(A5),D3\n"
    "    EXT.L   D3\n"
    "    MOVE.L  D2,36(A7)\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D3\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  36(A7),D2\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEQ   #1,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #2,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D1\n"
    "    ADDQ.L  #2,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #2,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    SUBQ.L  #2,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    ADDQ.L  #2,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    SUBQ.L  #2,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D1\n"
    "    ADDQ.L  #1,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    SUBQ.L  #1,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    SUBQ.L  #1,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEQ   #2,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    ADDQ.L  #2,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    SUBQ.L  #1,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    ADDQ.L  #2,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D1\n"
    "    ADDQ.L  #2,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D1\n"
    "    ADDQ.L  #2,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D1\n"
    "    ADDQ.L  #1,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -10(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  -12(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D1\n"
    "    ADDQ.L  #1,D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVODraw(A6)\n"
    "\n"
    "    MOVE.W  -6(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  -8(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVEA.L A3,A1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D4,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEM.L (A7)+,D2-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
