__asm__(
    ".globl _CLEANUP_DrawClockFormatFrame\n"
    "_CLEANUP_DrawClockFormatFrame:\n"
    "    MOVEM.L D2-D3,-(A7)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVE.L  D0,D1\n"
    "    MOVEQ   #36,D2\n"
    "    ADD.L   D2,D1\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.W  D0,D3\n"
    "    ADD.L   D2,D3\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D0,D2\n"
    "    MOVE.L  #660,D0\n"
    "    SUB.L   D2,D0\n"
    "    PEA     192.W\n"
    "    MOVEQ   #34,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  NEWGRID_MainRastPortPtr,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A0\n"
    "    MOVE.L  4(A0),-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_GRAPHICS_BltBitMapRastPort(PC)\n"
    "    LEA     36(A7),A7\n"
    "    MOVEM.L (A7)+,D2-D3\n"
    "    RTS\n"
);
