__asm__(
    ".globl _CLEANUP_ClearRbfInterruptAndSerial\n"
    "_CLEANUP_ClearRbfInterruptAndSerial:\n"
    "    move.w  #0x800,_INTENA\n"
    "    movea.l _WDISP_SerialIoRequestPtr,%a1\n"
    "    movea.l _AbsExecBase,%a6\n"
    "    jsr     _LVOCloseDevice(%a6)\n"
    "    move.l  _WDISP_SerialMessagePortPtr,-(%sp)\n"
    "    jsr     _GROUP_AG_JMPTBL_IOSTDREQ_CleanupSignalAndMsgport\n"
    "    move.l  _WDISP_SerialIoRequestPtr,(%sp)\n"
    "    jsr     _GROUP_AG_JMPTBL_STRUCT_FreeWithSizeField\n"
    "    moveq   #11,%d0\n"
    "    movea.l _Global_REF_INTB_RBF_INTERRUPT,%a1\n"
    "    movea.l _AbsExecBase,%a6\n"
    "    jsr     _LVOSetIntVector(%a6)\n"
    "    move.l  #64000,(%sp)\n"
    "    move.l  _Global_REF_INTB_RBF_64K_BUFFER,-(%sp)\n"
    "    pea     113.w\n"
    "    pea     _Global_STR_CLEANUP_C_3\n"
    "    jsr     _GROUP_AG_JMPTBL_MEMORY_DeallocateMemory\n"
    "    pea     22.w\n"
    "    move.l  _Global_REF_INTERRUPT_STRUCT_INTB_RBF,-(%sp)\n"
    "    pea     118.w\n"
    "    pea     _Global_STR_CLEANUP_C_4\n"
    "    jsr     _GROUP_AG_JMPTBL_MEMORY_DeallocateMemory\n"
    "    lea     32(%sp),%sp\n"
    "    rts\n");
