__asm__(
    ".globl _CLEANUP_DrawDateBannerSegment\n"
    "_CLEANUP_DrawDateBannerSegment:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D2-D3,-(A7)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  Struct_RastPort__BitMap(A0),-4(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,Struct_RastPort__BitMap(A0)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #7,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  Struct_RastPort__Flags(A0),D0\n"
    "    ANDI.W  #$fff7,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  D0,Struct_RastPort__Flags(A0)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #40,D0\n"
    "    MOVEQ   #34,D1\n"
    "    MOVEQ   #0,D2\n"
    "    NOT.B   D2\n"
    "    MOVEQ   #67,D3\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVORectFill(A6)\n"
    "    BSR.W   RENDER_SHORT_MONTH_SHORT_DAY_OF_WEEK_DAY\n"
    "    PEA     67.W\n"
    "    PEA     255.W\n"
    "    PEA     34.W\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     BEVEL_DrawBevelFrameWithTopRight(PC)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -4(A5),Struct_RastPort__BitMap(A0)\n"
    "    MOVEM.L -12(A5),D2-D3\n"
    "    UNLK    A5\n"
    "    RTS\n");
