__asm__(
    ".globl _CLEANUP_ShutdownInputDevices\n"
    "_CLEANUP_ShutdownInputDevices:\n"
    "    movea.l _Global_REF_IOSTDREQ_STRUCT_INPUT_DEVICE,%a0\n"
    "    move.w  #10,28(%a0)\n"
    "    movea.l _Global_REF_IOSTDREQ_STRUCT_INPUT_DEVICE,%a0\n"
    "    move.l  _Global_REF_DATA_INPUT_BUFFER,40(%a0)\n"
    "    movea.l _Global_REF_IOSTDREQ_STRUCT_INPUT_DEVICE,%a1\n"
    "    movea.l _AbsExecBase,%a6\n"
    "    jsr     _LVODoIO(%a6)\n"
    "    pea     22.w\n"
    "    move.l  _Global_REF_DATA_INPUT_BUFFER,-(%sp)\n"
    "    pea     127.w\n"
    "    pea     _Global_STR_CLEANUP_C_5\n"
    "    jsr     _GROUP_AG_JMPTBL_MEMORY_DeallocateMemory\n"
    "    movea.l _Global_REF_IOSTDREQ_STRUCT_INPUT_DEVICE,%a1\n"
    "    movea.l _AbsExecBase,%a6\n"
    "    jsr     _LVOCloseDevice(%a6)\n"
    "    movea.l _Global_REF_IOSTDREQ_STRUCT_CONSOLE_DEVICE,%a1\n"
    "    jsr     _LVOCloseDevice(%a6)\n"
    "    move.l  _Global_REF_INPUTDEVICE_MSGPORT,(%sp)\n"
    "    jsr     _GROUP_AG_JMPTBL_IOSTDREQ_CleanupSignalAndMsgport\n"
    "    move.l  _Global_REF_CONSOLEDEVICE_MSGPORT,(%sp)\n"
    "    jsr     _GROUP_AG_JMPTBL_IOSTDREQ_CleanupSignalAndMsgport\n"
    "    move.l  _Global_REF_IOSTDREQ_STRUCT_INPUT_DEVICE,(%sp)\n"
    "    jsr     _GROUP_AB_JMPTBL_IOSTDREQ_Free\n"
    "    move.l  _Global_REF_IOSTDREQ_STRUCT_CONSOLE_DEVICE,(%sp)\n"
    "    jsr     _GROUP_AB_JMPTBL_IOSTDREQ_Free\n"
    "    lea     16(%sp),%sp\n"
    "    rts\n");
