__asm__(
    ".globl _CLEANUP_BuildAlignedStatusLine\n"
    "_CLEANUP_BuildAlignedStatusLine:\n"
    "    LINK.W  A5,#-32\n"
    "    MOVEM.L D5-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVE.W  18(A5),D6\n"
    "    MOVE.W  22(A5),D5\n"
    "    CLR.L   -28(A5)\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    TST.W   D7\n"
    "    BEQ.S   .use_format_b\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    BRA.S   .format_selected\n"
    "\n"
    ".use_format_b:\n"
    "    MOVEQ   #2,D1\n"
    "\n"
    ".format_selected:\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQDISP_GetEntryPointerByMode(PC)\n"
    "\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  24(A5),(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    BSR.W   CLEANUP_TestEntryFlagYAndBit1\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .skip_entry_text\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    PEA     6.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,-28(A5)\n"
    "\n"
    ".skip_entry_text:\n"
    "    TST.L   -28(A5)\n"
    "    BEQ.W   .clear_status_flag\n"
    "\n"
    "    PEA     20.W\n"
    "    MOVE.L  -28(A5),-(A7)\n"
    "    PEA     19.W\n"
    "    PEA     CLOCK_FMT_WRAP_CHAR_STRING_CHAR\n"
    "    PEA     -12(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    TST.L   28(A5)\n"
    "    BEQ.S   .append_default_prefix\n"
    "\n"
    "    PEA     TEXTDISP_CenterAlignToken\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .append_entry_text\n"
    "\n"
    ".append_default_prefix:\n"
    "    PEA     CLOCK_STR_DOUBLE_SPACE\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".append_entry_text:\n"
    "    PEA     -12(A5)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    PEA     7.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVE.L  D0,-32(A5)\n"
    "    TST.L   D0\n"
    "    BNE.S   .entry2_ok\n"
    "\n"
    "    LEA     CLOCK_STR_FALLBACK_ENTRY_FLAGS_SECONDARY,A0\n"
    "    LEA     -23(A5),A1\n"
    "\n"
    ".copy_default_entry2_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_default_entry2_loop\n"
    "\n"
    "    LEA     -23(A5),A0\n"
    "    MOVE.L  A0,-32(A5)\n"
    "\n"
    ".entry2_ok:\n"
    "    MOVEA.L -32(A5),A0\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #7,(A1)\n"
    "    BEQ.S   .entry2_flag6_not_set\n"
    "\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_LADFUNC_ParseHexDigit(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    BRA.S   .store_entry2_flag6\n"
    "\n"
    ".entry2_flag6_not_set:\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "\n"
    ".store_entry2_flag6:\n"
    "    MOVE.B  D1,CLEANUP_AlignedInsetNibblePrimary\n"
    "    MOVEA.L -32(A5),A0\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #7,(A1)\n"
    "    BEQ.S   .entry2_flag7_not_set\n"
    "\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_LADFUNC_ParseHexDigit(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    BRA.S   .store_entry2_flag7\n"
    "\n"
    ".entry2_flag7_not_set:\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "\n"
    ".store_entry2_flag7:\n"
    "    MOVE.B  D1,CLEANUP_AlignedInsetNibbleSecondary\n"
    "    MOVE.B  #$1,CLOCK_AlignedInsetRenderGateFlag\n"
    "    BRA.S   .done\n"
    "\n"
    ".clear_status_flag:\n"
    "    CLR.B   CLOCK_AlignedInsetRenderGateFlag\n"
    "\n"
    ".done:\n"
    "    MOVEM.L (A7)+,D5-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
