__asm__(
    ".globl _CLEANUP_BuildAndRenderAlignedStatusBanner\n"
    "_CLEANUP_BuildAndRenderAlignedStatusBanner:\n"
    "CLEANUP_RenderAlignedStatusScreen:\n"
    "    LINK.W  A5,#-840\n"
    "    MOVEM.L D2-D7/A2,-(A7)\n"
    "\n"
    "    MOVE.W  10(A5),D7\n"
    "    MOVE.W  14(A5),D6\n"
    "    MOVE.W  18(A5),D5\n"
    "    MOVE.W  D7,TEXTDISP_ChannelSourceMode\n"
    "    CLR.B   -554(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,WDISP_AccumulatorFlushPending\n"
    "    MOVE.W  D0,-40(A5)\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .use_secondary_template\n"
    "\n"
    "    LEA     TEXTDISP_PrimarySearchText,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_template_primary_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_template_primary_loop\n"
    "\n"
    "    MOVE.W  TEXTDISP_PrimaryChannelCode,-38(A5)\n"
    "    BRA.S   .backup_template_text\n"
    "\n"
    ".use_secondary_template:\n"
    "    LEA     TEXTDISP_SecondarySearchText,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_template_secondary_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_template_secondary_loop\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryChannelCode,-38(A5)\n"
    "\n"
    ".backup_template_text:\n"
    "    LEA     -554(A5),A0\n"
    "    LEA     -754(A5),A1\n"
    "\n"
    ".copy_template_backup_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_template_backup_loop\n"
    "\n"
    "    TST.W   -38(A5)\n"
    "    BNE.S   .normalize_template_code\n"
    "\n"
    "    MOVEQ   #48,D0\n"
    "    MOVE.W  D0,-38(A5)\n"
    "\n"
    ".normalize_template_code:\n"
    "    MOVE.W  -38(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     CLOCK_STR_TEMPLATE_CODE_SET_FGN\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .maybe_format_alt_time_text\n"
    "\n"
    "    CLR.B   CLEANUP_AlignedStatusClockEntryBuffer\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  CLEANUP_AlignedStatusClockEntryIndex,D1\n"
    "    EXT.L   D1\n"
    "    CLR.L   -(A7)\n"
    "    PEA     CLEANUP_AlignedStatusClockEntryBuffer\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA1_BuildClockFormatEntryIfVisible(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    BRA.S   .dispatch_template_code\n"
    "\n"
    ".maybe_format_alt_time_text:\n"
    "    MOVEQ   #79,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.S   .dispatch_template_code\n"
    "\n"
    "    CLR.B   CLEANUP_AlignedStatusAltTimeBuffer\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  CLEANUP_AlignedStatusClockEntryIndex,D1\n"
    "    EXT.L   D1\n"
    "    PEA     1.W\n"
    "    PEA     CLEANUP_AlignedStatusAltTimeBuffer\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA1_BuildClockFormatEntryIfVisible(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".dispatch_template_code:\n"
    "    MOVEQ   #69,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.W   .check_code_F\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-8(A5)\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     CLEANUP_AlignedStatusEntryCycleTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.W  (A0),-42(A5)\n"
    "    CLR.W   -36(A5)\n"
    "\n"
    ".scan_entry_loop:\n"
    "    ADDQ.W  #1,-42(A5)\n"
    "    MOVE.W  -42(A5),D0\n"
    "    EXT.L   D0\n"
    "    PEA     48.W\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     DISPLIB_NormalizeValueByStep(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    LEA     CLEANUP_AlignedStatusEntryCycleTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.W  D0,-42(A5)\n"
    "    CMP.W   (A0),D0\n"
    "    BEQ.S   .apply_entry_selection\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    MOVEA.L -8(A5),A0\n"
    "    TST.L   56(A0,D1.L)\n"
    "    BNE.S   .apply_entry_selection\n"
    "\n"
    "    MOVE.W  -36(A5),D0\n"
    "    MOVEQ   #60,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .apply_entry_selection\n"
    "\n"
    "    ADDQ.W  #1,-36(A5)\n"
    "    BRA.S   .scan_entry_loop\n"
    "\n"
    ".apply_entry_selection:\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     CLEANUP_AlignedStatusEntryCycleTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVE.W  -42(A5),D0\n"
    "    MOVE.W  (A1),D1\n"
    "    CMP.W   D0,D1\n"
    "    BNE.S   .store_entry_selection\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndexSaved,D1\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    CMP.W   D2,D1\n"
    "    BEQ.W   .done\n"
    "\n"
    ".store_entry_selection:\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    MOVE.W  D0,(A1)\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.W  (A0),D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L 56(A0,D0.L),A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_entry_title_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_entry_title_loop\n"
    "\n"
    "    MOVE.W  #2,-40(A5)\n"
    "    BRA.W   .finalize_title_state\n"
    "\n"
    ".check_code_F:\n"
    "    MOVEQ   #70,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.S   .check_code_G\n"
    "\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BEQ.S   .fallback_title_buffer\n"
    "\n"
    "    MOVE.B  CLEANUP_AlignedStatusClockEntryBuffer,D0\n"
    "    TST.B   D0\n"
    "    BEQ.S   .fallback_title_buffer\n"
    "\n"
    "    LEA     CLEANUP_AlignedStatusClockEntryBuffer,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_buffer_title_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_buffer_title_loop\n"
    "\n"
    "    BRA.S   .set_title_ready\n"
    "\n"
    ".fallback_title_buffer:\n"
    "    TST.L   ESQIFF_PrimaryLineHeadPtr\n"
    "    BEQ.W   .done\n"
    "\n"
    "    MOVEA.L ESQIFF_PrimaryLineHeadPtr,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_fallback_title_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_fallback_title_loop\n"
    "\n"
    ".set_title_ready:\n"
    "    MOVE.W  #2,-40(A5)\n"
    "    BRA.W   .finalize_title_state\n"
    "\n"
    ".check_code_G:\n"
    "    MOVEQ   #71,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.S   .check_code_N\n"
    "\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BEQ.S   .fallback_title_buffer_g\n"
    "\n"
    "    MOVE.B  CLEANUP_AlignedStatusClockEntryBuffer,D0\n"
    "    TST.B   D0\n"
    "    BEQ.S   .fallback_title_buffer_g\n"
    "\n"
    "    LEA     CLEANUP_AlignedStatusClockEntryBuffer,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_buffer_title_loop_g:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_buffer_title_loop_g\n"
    "\n"
    "    BRA.S   .set_title_ready_g\n"
    "\n"
    ".fallback_title_buffer_g:\n"
    "    TST.L   ESQIFF_PrimaryLineTailPtr\n"
    "    BEQ.W   .done\n"
    "\n"
    "    MOVEA.L ESQIFF_PrimaryLineTailPtr,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_fallback_title_loop_g:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_fallback_title_loop_g\n"
    "\n"
    ".set_title_ready_g:\n"
    "    MOVE.W  #2,-40(A5)\n"
    "    BRA.S   .finalize_title_state\n"
    "\n"
    ".check_code_N:\n"
    "    MOVEQ   #78,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.S   .check_code_O\n"
    "\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BEQ.W   .done\n"
    "\n"
    "    MOVE.B  CLEANUP_AlignedStatusClockEntryBuffer,D0\n"
    "    TST.B   D0\n"
    "    BEQ.W   .done\n"
    "\n"
    "    LEA     CLEANUP_AlignedStatusClockEntryBuffer,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_buffer_title_loop_n:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_buffer_title_loop_n\n"
    "\n"
    "    MOVE.W  #2,-40(A5)\n"
    "    BRA.S   .finalize_title_state\n"
    "\n"
    ".check_code_O:\n"
    "    MOVEQ   #79,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.S   .finalize_title_state\n"
    "\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BEQ.W   .done\n"
    "\n"
    "    MOVE.B  CLEANUP_AlignedStatusAltTimeBuffer,D0\n"
    "    TST.B   D0\n"
    "    BEQ.W   .done\n"
    "\n"
    "    LEA     CLEANUP_AlignedStatusAltTimeBuffer,A0\n"
    "    LEA     -554(A5),A1\n"
    "\n"
    ".copy_alt_title_loop_o:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_alt_title_loop_o\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    MOVE.W  D0,-40(A5)\n"
    "\n"
    ".finalize_title_state:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   -40(A5),D0\n"
    "    BEQ.S   .sync_time_defaults\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    MOVE.W  D0,CLEANUP_AlignedStatusMatchIndex\n"
    "    MOVE.W  D0,CLEANUP_AlignedStatusClockEntryIndex\n"
    "\n"
    ".sync_time_defaults:\n"
    "    MOVEQ   #53,D0\n"
    "    CMP.W   D0,D6\n"
    "    BNE.S   .maybe_refresh_display\n"
    "\n"
    "    JSR     ESQ_SetCopperEffect_OffDisableHighlight(PC)\n"
    "\n"
    ".maybe_refresh_display:\n"
    "    JSR     GROUP_AD_JMPTBL_ESQIFF_RunCopperDropTransition(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A0\n"
    "    ADDQ.W  #2,A0\n"
    "    MOVEA.L WDISP_DisplayContextBase,A2\n"
    "    MOVEA.L 14(A2),A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  5(A1),D0\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.L  D1,D2\n"
    "    ASL.L   D0,D2\n"
    "    SUBQ.L  #1,D2\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  D2,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    "    TST.W   D7\n"
    "    BNE.S   .alloc_rastport_primary\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    BRA.S   .primary_rastport_ready\n"
    "\n"
    ".alloc_rastport_primary:\n"
    "    PEA     1.W\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "\n"
    ".primary_rastport_ready:\n"
    "    TST.W   D5\n"
    "    BNE.S   .maybe_notify_timing\n"
    "\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_ESQFUNC_SelectAndApplyBrushForCurrentEntry(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".maybe_notify_timing:\n"
    "    TST.W   D7\n"
    "    BNE.S   .alloc_rastport_secondary\n"
    "\n"
    "    PEA     4.W\n"
    "    CLR.L   -(A7)\n"
    "    PEA     1.W\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    PEA     2.W\n"
    "    JSR     GROUP_AD_JMPTBL_SCRIPT_UpdateSerialShadowFromCtrlByte(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    BRA.S   .after_secondary_alloc\n"
    "\n"
    ".alloc_rastport_secondary:\n"
    "    PEA     4.W\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    PEA     1.W\n"
    "    JSR     GROUP_AD_JMPTBL_SCRIPT_UpdateSerialShadowFromCtrlByte(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".after_secondary_alloc:\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D5\n"
    "    BNE.S   .maybe_clear_rastport_secondary\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    ".maybe_clear_rastport_secondary:\n"
    "    JSR     ESQ_NoOp(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,TEXTDISP_CurrentMatchIndexSaved\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   -38(A5),D0\n"
    "    BNE.S   .handle_empty_template\n"
    "\n"
    "    MOVE.B  -554(A5),D0\n"
    "    TST.B   D0\n"
    "    BNE.S   .handle_empty_template\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     3.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_DrawChannelBanner(PC)\n"
    "\n"
    "    JSR     ESQ_SetCopperEffect_OnEnableHighlight(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,CLEANUP_AlignedStatusSuffixBuffer\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D1\n"
    "    MOVE.W  D1,CLEANUP_AlignedStatusMatchIndex\n"
    "    MOVEQ   #-1,D1\n"
    "    MOVE.W  D1,CLEANUP_AlignedStatusClockEntryIndex\n"
    "    BRA.W   .done\n"
    "\n"
    ".handle_empty_template:\n"
    "    MOVE.B  TEXTDISP_BannerCharSelected,D0\n"
    "    MOVEQ   #100,D1\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.S   .select_aligned_index\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    MOVE.W  D1,-36(A5)\n"
    "    BRA.S   .check_aligned_index_valid\n"
    "\n"
    ".select_aligned_index:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerCharFallback,D0\n"
    "    MOVE.W  D0,-36(A5)\n"
    "\n"
    ".check_aligned_index_valid:\n"
    "    MOVE.W  -36(A5),D0\n"
    "    MOVEQ   #49,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .reset_alignment_state\n"
    "\n"
    "    MOVE.B  -554(A5),D1\n"
    "    TST.B   D1\n"
    "    BEQ.S   .reset_alignment_state\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    MOVE.W  D2,CLEANUP_AlignedStatusMatchIndex\n"
    "    MOVE.W  D0,CLEANUP_AlignedStatusClockEntryIndex\n"
    "    MOVE.W  D1,-40(A5)\n"
    "    BRA.S   .prepare_channel_line\n"
    "\n"
    ".reset_alignment_state:\n"
    "    MOVE.W  -40(A5),D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BEQ.S   .prepare_channel_line\n"
    "\n"
    "    CLR.B   CLEANUP_AlignedStatusSuffixBuffer\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    MOVE.W  D2,CLEANUP_AlignedStatusMatchIndex\n"
    "    MOVE.W  #(-1),CLEANUP_AlignedStatusClockEntryIndex\n"
    "\n"
    ".prepare_channel_line:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   -40(A5),D0\n"
    "    BEQ.S   .clear_channel_string\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_channel_format\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    BRA.S   .format_channel_string\n"
    "\n"
    ".select_channel_format:\n"
    "    MOVEQ   #2,D1\n"
    "\n"
    ".format_channel_string:\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQDISP_GetEntryPointerByMode(PC)\n"
    "\n"
    "    PEA     TEXTDISP_EntryShortNameScratch\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_BuildEntryShortName(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    LEA     TEXTDISP_EntryShortNameScratch,A0\n"
    "    LEA     TEXTDISP_ChannelLabelBuffer,A1\n"
    "\n"
    ".copy_channel_string_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_channel_string_loop\n"
    "\n"
    "    BRA.S   .append_optional_prefix\n"
    "\n"
    ".clear_channel_string:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,TEXTDISP_ChannelLabelBuffer\n"
    "\n"
    ".append_optional_prefix:\n"
    "    MOVE.B  -554(A5),D0\n"
    "    TST.B   D0\n"
    "    BEQ.S   .append_template_text\n"
    "\n"
    "    PEA     TEXTDISP_LeftAlignToken\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".append_template_text:\n"
    "    PEA     -554(A5)\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   -40(A5),D0\n"
    "    BNE.W   .maybe_append_centered_schedule_label\n"
    "\n"
    "    MOVE.B  TEXTDISP_BannerCharSelected,D0\n"
    "    MOVEQ   #100,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .select_now_showing_index\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerFallbackIsSpecialFlag,D0\n"
    "    BRA.S   .after_now_showing_index\n"
    "\n"
    ".select_now_showing_index:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerSelectedIsSpecialFlag,D0\n"
    "\n"
    ".after_now_showing_index:\n"
    "    TST.L   D0\n"
    "    BEQ.S   .build_time_phrase\n"
    "\n"
    "    LEA     Global_STR_ALIGNED_NOW_SHOWING,A0\n"
    "    LEA     CLEANUP_AlignedStatusSuffixBuffer,A1\n"
    "\n"
    ".copy_now_showing_label_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_now_showing_label_loop\n"
    "\n"
    "    MOVE.B  TEXTDISP_BannerCharSelected,D0\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .select_next_showing_index\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerFallbackValidFlag,D0\n"
    "    BRA.S   .after_next_showing_index\n"
    "\n"
    ".select_next_showing_index:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerSelectedValidFlag,D0\n"
    "\n"
    ".after_next_showing_index:\n"
    "    TST.L   D0\n"
    "    BEQ.W   .append_alignment_text\n"
    "\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     Global_STR_ALIGNED_NEXT_SHOWING,A0\n"
    "    LEA     CLEANUP_AlignedStatusSuffixBuffer,A1\n"
    "\n"
    ".copy_next_showing_label_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_next_showing_label_loop\n"
    "\n"
    "    MOVE.W  -36(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    PEA     -834(A5)\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_FormatEntryTime(PC)\n"
    "\n"
    "    PEA     -834(A5)\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    BRA.W   .append_alignment_text\n"
    "\n"
    ".build_time_phrase:\n"
    "    MOVE.W  -36(A5),D0\n"
    "    EXT.L   D0\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_time_table\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D1\n"
    "    BRA.S   .format_time_components\n"
    "\n"
    ".select_time_table:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "\n"
    ".format_time_components:\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.B  D1,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -34(A5)\n"
    "    JSR     GROUP_AD_JMPTBL_DST_ComputeBannerIndex(PC)\n"
    "\n"
    "    PEA     -34(A5)\n"
    "    JSR     GROUP_AD_JMPTBL_DATETIME_AdjustMonthIndex(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.W  -18(A5),D0\n"
    "    MOVE.W  CLOCK_CurrentDayOfYear,D1\n"
    "    CMP.W   D1,D0\n"
    "    BEQ.S   .check_today_vs_tonight\n"
    "\n"
    "    LEA     Global_STR_ALIGNED_TOMORROW_AT,A0\n"
    "    LEA     CLEANUP_AlignedStatusSuffixBuffer,A1\n"
    "\n"
    ".copy_tomorrow_label_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_tomorrow_label_loop\n"
    "\n"
    "    BRA.S   .append_time_string\n"
    "\n"
    ".check_today_vs_tonight:\n"
    "    MOVE.W  -26(A5),D0\n"
    "    MOVEQ   #17,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLT.S   .copy_today_label\n"
    "\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .copy_tonight_label\n"
    "\n"
    "    MOVE.W  -24(A5),D0\n"
    "    MOVEQ   #30,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .copy_tonight_label\n"
    "\n"
    ".copy_today_label:\n"
    "    LEA     Global_STR_ALIGNED_TODAY_AT,A0\n"
    "    LEA     CLEANUP_AlignedStatusSuffixBuffer,A1\n"
    "\n"
    ".copy_today_label_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_today_label_loop\n"
    "\n"
    "    BRA.S   .append_time_string\n"
    "\n"
    ".copy_tonight_label:\n"
    "    LEA     Global_STR_ALIGNED_TONIGHT_AT,A0\n"
    "    LEA     CLEANUP_AlignedStatusSuffixBuffer,A1\n"
    "\n"
    ".copy_tonight_label_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_tonight_label_loop\n"
    "\n"
    ".append_time_string:\n"
    "    PEA     -34(A5)\n"
    "    JSR     GROUP_AD_JMPTBL_DATETIME_NormalizeMonthRange(PC)\n"
    "\n"
    "    MOVE.W  -36(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    PEA     -834(A5)\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_FormatEntryTime(PC)\n"
    "\n"
    "    PEA     -834(A5)\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".append_alignment_text:\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .maybe_rebuild_output_record\n"
    "\n"
    ".maybe_append_centered_schedule_label:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   -40(A5),D0\n"
    "    BEQ.S   .maybe_rebuild_output_record\n"
    "\n"
    "    MOVE.W  -38(A5),D0\n"
    "    MOVEQ   #48,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLE.S   .check_upper_fallback_schedule_range\n"
    "\n"
    "    MOVEQ   #67,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLE.S   .prepend_center_align_and_schedule_suffix\n"
    "\n"
    ".check_upper_fallback_schedule_range:\n"
    "    MOVEQ   #72,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLT.S   .maybe_rebuild_output_record\n"
    "\n"
    "    MOVEQ   #77,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGT.S   .maybe_rebuild_output_record\n"
    "\n"
    ".prepend_center_align_and_schedule_suffix:\n"
    "    LEA     TEXTDISP_CenterAlignToken,A0\n"
    "    LEA     CLEANUP_AlignedStatusSuffixBuffer,A1\n"
    "\n"
    ".copy_center_align_control_bytes_loop:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_center_align_control_bytes_loop\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    MOVE.W  -38(A5),D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     (SCRIPT_StrChannelLabel_TuesdaysFridays+2),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".maybe_rebuild_output_record:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   -40(A5),D0\n"
    "    BNE.S   .rebuild_output_record\n"
    "\n"
    "    MOVE.W  -38(A5),D0\n"
    "    MOVEQ   #70,D1\n"
    "    CMP.W   D1,D0\n"
    "    BEQ.S   .rebuild_output_record\n"
    "\n"
    "    MOVEQ   #71,D1\n"
    "    CMP.W   D1,D0\n"
    "    BEQ.S   .rebuild_output_record\n"
    "\n"
    "    MOVEQ   #78,D1\n"
    "    CMP.W   D1,D0\n"
    "    BEQ.S   .rebuild_output_record\n"
    "\n"
    "    MOVEQ   #79,D1\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .render_output_text\n"
    "\n"
    ".rebuild_output_record:\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_BuildChannelLabel(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  CLEANUP_AlignedStatusMatchIndex,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  CLEANUP_AlignedStatusClockEntryIndex,D2\n"
    "    EXT.L   D2\n"
    "    MOVEQ   #2,D3\n"
    "    CMP.W   -40(A5),D3\n"
    "    BNE.S   .select_output_mode\n"
    "\n"
    "    MOVEQ   #1,D3\n"
    "    BRA.S   .submit_output_record\n"
    "\n"
    ".select_output_mode:\n"
    "    MOVEQ   #0,D3\n"
    "\n"
    ".submit_output_record:\n"
    "    TST.L   TEXTDISP_ChannelLabelReadyFlag\n"
    "    SEQ     D4\n"
    "    NEG.B   D4\n"
    "    EXT.W   D4\n"
    "    EXT.L   D4\n"
    "    MOVE.L  D4,-(A7)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     CLEANUP_BuildAlignedStatusLine(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   -40(A5),D0\n"
    "    BNE.S   .render_output_text\n"
    "\n"
    "    PEA     CLEANUP_AlignedStatusSuffixBuffer\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".render_output_text:\n"
    "    MOVE.B  #$64,TEXTDISP_BannerCharSelected\n"
    "    MOVE.B  #$31,TEXTDISP_BannerCharFallback\n"
    "    CLR.W   TEXTDISP_LinePenOverrideStateWord\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVE.W  #1,TEXTDISP_LinePenOverrideEnabledFlag\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    MOVE.W  2(A0),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_TrimTextToPixelWidth(PC)\n"
    "\n"
    "    PEA     3.W\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     GROUP_AD_JMPTBL_TEXTDISP_DrawInsetRectFrame(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    PEA     2.W\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_GetViewModeRastPort(PC)\n"
    "\n"
    "    MOVE.L  D0,-4(A5)\n"
    "\n"
    "    MOVEA.L D0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    PEA     2.W\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_GetViewModeHeight(PC)\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .center_output_rect\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".center_output_rect:\n"
    "    ASR.L   #1,D1\n"
    "    PEA     2.W\n"
    "    MOVE.L  D1,56(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_TLIBA3_GetViewModeHeight(PC)\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    SUBQ.L  #1,D1\n"
    "\n"
    "    MOVE.L  D1,D3\n"
    "    MOVEA.L -4(A5),A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  56(A7),D1\n"
    "    MOVE.L  #703,D2\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    JSR     ESQ_SetCopperEffect_OnEnableHighlight(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A0\n"
    "    ADDQ.W  #2,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L WDISP_DisplayContextBase,A1\n"
    "    MOVE.W  2(A1),D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  4(A1),D1\n"
    "    SUBQ.L  #1,D1\n"
    "    PEA     192.W\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    PEA     Global_REF_320_240_BITMAP\n"
    "    JSR     GROUP_AD_JMPTBL_GRAPHICS_BltBitMapRastPort(PC)\n"
    "\n"
    "    JSR     GROUP_AD_JMPTBL_ESQIFF_RunCopperRiseTransition(PC)\n"
    "\n"
    ".done:\n"
    "    MOVEM.L -868(A5),D2-D7/A2\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
