__asm__(
    ".globl _CLEANUP_FormatClockFormatEntry\n"
    "_CLEANUP_FormatClockFormatEntry:\n"
    "    MOVEM.L D6-D7/A2-A3,-(A7)\n"
    "    MOVE.L  20(A7),D7\n"
    "    MOVEA.L 24(A7),A3\n"
    ".wrap_slot_index_loop:\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.L   D0,D7\n"
    "    BLE.S   .slot_index_ready\n"
    "    SUB.L   D0,D7\n"
    "    BRA.S   .wrap_slot_index_loop\n"
    ".slot_index_ready:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  CLOCK_FormatVariantCode,D0\n"
    "    MOVEQ   #30,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "    MOVE.L  D1,D6\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L Global_REF_STR_CLOCK_FORMAT,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVEA.L A3,A2\n"
    ".copy_format_loop:\n"
    "    MOVE.B  (A1)+,(A2)+\n"
    "    BNE.S   .copy_format_loop\n"
    "    TST.L   D6\n"
    "    BLE.S   .done\n"
    "    MOVE.B  3(A3),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "    ADD.L   D0,D6\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "    MOVEQ   #48,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.B  D0,3(A3)\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "    MOVEQ   #48,D0\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.B  D1,4(A3)\n"
    ".done:\n"
    "    MOVEM.L (A7)+,D6-D7/A2-A3\n"
    "    RTS\n"
);
