__asm__(
    ".globl _CLEANUP_DrawDateTimeBannerRow\n"
    "_CLEANUP_DrawDateTimeBannerRow:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D2-D3,-(A7)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  4(A0),-4(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #7,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  32(A0),D0\n"
    "    ANDI.W  #$fff7,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  D0,32(A0)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEQ   #34,D1\n"
    "    MOVE.L  #695,D2\n"
    "    MOVEQ   #67,D3\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVORectFill(A6)\n"
    "    BSR.W   CLEANUP_DrawDateBannerSegment\n"
    "    BSR.W   CLEANUP_DrawBannerSpacerSegment\n"
    "    BSR.W   CLEANUP_DrawTimeBannerSegment\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -4(A5),4(A0)\n"
    "    MOVEM.L (A7)+,D2-D3\n"
    "    UNLK    A5\n"
    "    RTS\n");
