__asm__(
    ".globl _CLEANUP_ProcessAlerts\n"
    "_CLEANUP_ProcessAlerts:\n"
    "    MOVEM.L D2/D7,-(A7)\n"
    "    TST.W   CLEANUP_PendingAlertFlag\n"
    "    BEQ.W   .return_status\n"
    "\n"
    "    TST.L   CLEANUP_AlertProcessingFlag\n"
    "    BNE.W   .return_status\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,CLEANUP_AlertProcessingFlag\n"
    "    TST.B   CLEANUP_DiagOverlayAutoRefreshFlag\n"
    "    BEQ.S   .update_alert_state\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .update_alert_state\n"
    "\n"
    "    SUBQ.L  #1,CLEANUP_AlertCooldownTicks\n"
    "    BGT.S   .update_alert_state\n"
    "\n"
    "    JSR     GROUP_AC_JMPTBL_ESQFUNC_DrawDiagnosticsScreen(PC)\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,CLEANUP_AlertCooldownTicks\n"
    "\n"
    ".update_alert_state:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   LOCAVAIL_FilterStep,D0\n"
    "    BNE.S   .check_state_three\n"
    "\n"
    "    MOVE.W  LOCAVAIL_FilterCooldownTicks,D0\n"
    "    BGT.S   .after_state_update\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    ADDI.W  #10,D1\n"
    "    MOVE.W  D1,LOCAVAIL_FilterCooldownTicks\n"
    "    MOVEQ   #3,D0\n"
    "    MOVE.L  D0,LOCAVAIL_FilterStep\n"
    "    BRA.S   .after_state_update\n"
    "\n"
    ".check_state_three:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   LOCAVAIL_FilterStep,D0\n"
    "    BNE.S   .after_state_update\n"
    "\n"
    "    MOVE.W  LOCAVAIL_FilterCooldownTicks,D0\n"
    "    BGT.S   .after_state_update\n"
    "\n"
    "    MOVEQ   #4,D0\n"
    "    MOVE.L  D0,LOCAVAIL_FilterStep\n"
    "    JSR     GROUP_AG_JMPTBL_TEXTDISP_ResetSelectionAndRefresh(PC)\n"
    "\n"
    ".after_state_update:\n"
    "    CLR.W   CLEANUP_PendingAlertFlag\n"
    "    PEA     CLOCK_DaySlotIndex\n"
    "    JSR     ESQ_TickClockAndFlagEvents(PC)\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "    EXT.L   D7\n"
    "    PEA     CLOCK_CurrentDayOfWeekIndex\n"
    "    JSR     ESQ_TickClockAndFlagEvents(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.W  TEXTDISP_DeferredActionDelayTicks,D0\n"
    "    BLT.S   .update_banner_queue\n"
    "\n"
    "    MOVEQ   #11,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .update_banner_queue\n"
    "\n"
    "    JSR     GROUP_AC_JMPTBL_SCRIPT_ClearCtrlLineIfEnabled(PC)\n"
    "\n"
    "    MOVE.W  TEXTDISP_DeferredActionDelayTicks,D0\n"
    "    BNE.S   .update_banner_queue\n"
    "\n"
    "    MOVE.W  #(-1),TEXTDISP_DeferredActionDelayTicks\n"
    "\n"
    ".update_banner_queue:\n"
    "    JSR     GROUP_AC_JMPTBL_SCRIPT_UpdateCtrlLineTimeout(PC)\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   BRUSH_PendingAlertCode,D0\n"
    "    BNE.S   .handle_brush_alert_code1\n"
    "\n"
    "    PEA     3.W\n"
    "    JSR     GROUP_AH_JMPTBL_ESQIFF2_ShowAttentionOverlay(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #4,D0\n"
    "    MOVE.L  D0,BRUSH_PendingAlertCode\n"
    "\n"
    ".handle_brush_alert_code1:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   BRUSH_PendingAlertCode,D0\n"
    "    BNE.S   .handle_brush_alert_code2\n"
    "\n"
    "    PEA     4.W\n"
    "    JSR     GROUP_AH_JMPTBL_ESQIFF2_ShowAttentionOverlay(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #4,D0\n"
    "    MOVE.L  D0,BRUSH_PendingAlertCode\n"
    "\n"
    ".handle_brush_alert_code2:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   BRUSH_PendingAlertCode,D0\n"
    "    BNE.S   .handle_brush_alert_code3\n"
    "\n"
    "    PEA     5.W\n"
    "    JSR     GROUP_AH_JMPTBL_ESQIFF2_ShowAttentionOverlay(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #4,D0\n"
    "    MOVE.L  D0,BRUSH_PendingAlertCode\n"
    "\n"
    ".handle_brush_alert_code3:\n"
    "    TST.L   D7\n"
    "    BEQ.S   .after_banner_poll\n"
    "\n"
    "    MOVE.B  WDISP_WeatherStatusCountdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.B   D1,D0\n"
    "    BLS.S   .decrement_banner_counter\n"
    "\n"
    "    SUBQ.B  #1,D0\n"
    "    MOVE.B  D0,WDISP_WeatherStatusCountdown\n"
    "\n"
    ".decrement_banner_counter:\n"
    "    SUBQ.L  #1,CLEANUP_BannerTickCounter\n"
    "    BNE.S   .poll_banner_event\n"
    "\n"
    "    MOVEQ   #60,D0\n"
    "    MOVE.L  D0,CLEANUP_BannerTickCounter\n"
    "    MOVE.B  TLIBA1_DayEntryModeCounter,D0\n"
    "    CMP.B   D1,D0\n"
    "    BLS.S   .poll_banner_event\n"
    "\n"
    "    SUBQ.B  #1,D0\n"
    "    MOVE.B  D0,TLIBA1_DayEntryModeCounter\n"
    "\n"
    ".poll_banner_event:\n"
    "    PEA     DST_BannerWindowPrimary\n"
    "    JSR     GROUP_AC_JMPTBL_DST_UpdateBannerQueue(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .after_banner_poll\n"
    "\n"
    "    PEA     1.W\n"
    "    JSR     GROUP_AC_JMPTBL_ESQDISP_DrawStatusBanner(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".after_banner_poll:\n"
    "    MOVE.B  ESQ_AlertType235ModeFlagChar,D0\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .handle_alert_type2\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .handle_alert_type2\n"
    "\n"
    "    CLR.W   ESQDISP_StatusBannerClampGateFlag\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AC_JMPTBL_ESQDISP_DrawStatusBanner(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.W  #1,ESQDISP_StatusBannerClampGateFlag\n"
    "\n"
    ".handle_alert_type2:\n"
    "    MOVE.B  ESQ_AlertType235ModeFlagChar,D0\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .check_alert_type5_or_type2\n"
    "\n"
    "    MOVEQ   #5,D2\n"
    "    CMP.L   D2,D7\n"
    "    BEQ.S   .handle_alert_type5_or_type2\n"
    "\n"
    ".check_alert_type5_or_type2:\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.S   .init_alert_counters\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .init_alert_counters\n"
    "\n"
    ".handle_alert_type5_or_type2:\n"
    "    JSR     GROUP_AC_JMPTBL_PARSEINI_UpdateClockFromRtc(PC)\n"
    "\n"
    "    JSR     GROUP_AC_JMPTBL_DST_RefreshBannerBuffer(PC)\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AC_JMPTBL_ESQDISP_DrawStatusBanner(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".init_alert_counters:\n"
    "    MOVE.B  ESQ_AlertType235ModeFlagChar,D0\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .advance_alert_counters\n"
    "\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .advance_alert_counters\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.W  D0,BANNER_ResetPendingFlag\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D1\n"
    "    ADDQ.W  #1,D1\n"
    "    EXT.L   D1\n"
    "    PEA     48.W\n"
    "    PEA     1.W\n"
    "    MOVE.L  D1,-(A7)\n"
    "    JSR     DISPLIB_NormalizeValueByStep(PC)\n"
    "\n"
    "    MOVE.W  D0,WDISP_BannerCharRangeStart\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    ADDQ.W  #2,D0\n"
    "    EXT.L   D0\n"
    "    PEA     48.W\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     DISPLIB_NormalizeValueByStep(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    MOVE.W  D0,WDISP_BannerCharRangeEnd\n"
    "\n"
    ".advance_alert_counters:\n"
    "    MOVE.B  ESQ_AlertType4ModeFlagChar,D0\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .draw_banner\n"
    "\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .draw_banner\n"
    "\n"
    "    MOVE.W  WDISP_BannerCharRangeStart,D0\n"
    "    MOVE.L  D0,D1\n"
    "    ADDQ.W  #1,D1\n"
    "    MOVE.W  D1,WDISP_BannerCharRangeStart\n"
    "    EXT.L   D1\n"
    "    PEA     48.W\n"
    "    PEA     1.W\n"
    "    MOVE.L  D1,-(A7)\n"
    "    JSR     DISPLIB_NormalizeValueByStep(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,WDISP_BannerCharRangeStart\n"
    "    MOVE.W  WDISP_BannerCharRangeEnd,D0\n"
    "    MOVE.L  D0,D1\n"
    "    ADDQ.W  #1,D1\n"
    "    MOVE.W  D1,WDISP_BannerCharRangeEnd\n"
    "    EXT.L   D1\n"
    "    PEA     48.W\n"
    "    PEA     1.W\n"
    "    MOVE.L  D1,-(A7)\n"
    "    JSR     DISPLIB_NormalizeValueByStep(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,WDISP_BannerCharRangeEnd\n"
    "\n"
    ".draw_banner:\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BEQ.S   .draw_clock_banner\n"
    "\n"
    "    BSR.W   CLEANUP_DrawGridTimeBanner\n"
    "\n"
    "    BRA.S   .after_banner_draw\n"
    "\n"
    ".draw_clock_banner:\n"
    "    BSR.W   CLEANUP_DrawClockBanner\n"
    "\n"
    ".after_banner_draw:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .update_grid_flash\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D1\n"
    "    MOVE.L  D1,D0\n"
    "    MOVEQ   #2,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    SUBQ.L  #1,D1\n"
    "    BNE.S   .maybe_clear_brush_alert\n"
    "\n"
    "    CLR.L   BRUSH_PendingAlertCode\n"
    "\n"
    ".maybe_clear_brush_alert:\n"
    "    MOVE.W  WDISP_BannerCharRangeStart,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AC_JMPTBL_ESQFUNC_FreeExtraTitleTextPointers(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".update_grid_flash:\n"
    "    JSR     GROUP_AC_JMPTBL_SCRIPT_UpdateCtrlStateMachine(PC)\n"
    "\n"
    "    MOVE.B  ED_MenuStateId,D0\n"
    "    SUBQ.B  #8,D0\n"
    "    BNE.S   .check_grid_flash_alt\n"
    "\n"
    "    JSR     GROUP_AC_JMPTBL_ESQFUNC_DrawEscMenuVersion(PC)\n"
    "\n"
    "    BRA.S   .finish\n"
    "\n"
    ".check_grid_flash_alt:\n"
    "    MOVE.B  ED_MenuStateId,D0\n"
    "    SUBQ.B  #7,D0\n"
    "    BNE.S   .finish\n"
    "\n"
    "    JSR     GROUP_AC_JMPTBL_ESQFUNC_DrawMemoryStatusScreen(PC)\n"
    "\n"
    ".finish:\n"
    "    CLR.L   CLEANUP_AlertProcessingFlag\n"
    "\n"
    ".return_status:\n"
    "    MOVEM.L (A7)+,D2/D7\n"
    "    RTS\n"
    "\n"
);
