__asm__(
    ".globl _CLEANUP_DrawClockFormatList\n"
    "_CLEANUP_DrawClockFormatList:\n"
    "    LINK.W  A5,#-100\n"
    "    MOVEM.L D2-D3/D5-D7,-(A7)\n"
    "    MOVE.L  8(A5),D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     6.W\n"
    "    PEA     5.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AC_JMPTBL_GCOMMAND_UpdateBannerBounds(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEQ   #7,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVEQ   #36,D1\n"
    "\n"
    "    ADD.L   D1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.L  #695,D2\n"
    "    MOVEQ   #33,D3\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".row_loop:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.W   .final_row\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ADD.L   D6,D0\n"
    "    MOVEQ   #48,D1\n"
    "    CMP.L   D1,D0\n"
    "    BLE.S   .row_index_no_wrap\n"
    "\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .row_index_ready\n"
    "\n"
    ".row_index_no_wrap:\n"
    "    MOVE.L  D7,D0\n"
    "    ADD.L   D6,D0\n"
    "\n"
    ".row_index_ready:\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D1\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #36,D0\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D2\n"
    "    MOVE.L  D0,24(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    MOVE.L  D1,20(A7)\n"
    "    MOVE.L  D2,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  24(A7),D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D2,D0\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #35,D0\n"
    "    ADD.L   D0,D1\n"
    "    PEA     33.W\n"
    "    MOVE.L  D1,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  32(A7),-(A7)\n"
    "    MOVE.L  NEWGRID_MainRastPortPtr,-(A7)\n"
    "    JSR     BEVEL_DrawBevelFrameWithTopRight(PC)\n"
    "\n"
    "    PEA     -89(A5)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    BSR.W   CLEANUP_FormatClockFormatEntry\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D1\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D0\n"
    "    LEA     -89(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_row_text_loop:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_row_text_loop\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  D0,24(A7)\n"
    "    MOVE.L  D1,20(A7)\n"
    "    MOVE.L  A1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  24(A7),D1\n"
    "    SUB.L   D0,D1\n"
    "    SUBQ.L  #8,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .center_row_text_x\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".center_row_text_x:\n"
    "    ASR.L   #1,D1\n"
    "    MOVE.L  20(A7),D0\n"
    "    ADD.L   D1,D0\n"
    "    MOVEQ   #42,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEA.L 52(A1),A0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  26(A0),D1\n"
    "    MOVEQ   #34,D2\n"
    "    SUB.L   D1,D2\n"
    "    TST.L   D2\n"
    "    BPL.S   .center_row_text_y\n"
    "\n"
    "    ADDQ.L  #1,D2\n"
    "\n"
    ".center_row_text_y:\n"
    "    ASR.L   #1,D2\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  26(A0),D1\n"
    "    ADD.L   D1,D2\n"
    "    SUBQ.L  #1,D2\n"
    "    MOVE.L  D2,D1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEQ   #3,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    LEA     -89(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".draw_row_text_loop:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .draw_row_text_loop\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.W   .row_loop\n"
    "\n"
    ".final_row:\n"
    "    MOVEQ   #2,D6\n"
    "    MOVE.L  D7,D0\n"
    "    ADD.L   D6,D0\n"
    "    MOVEQ   #48,D1\n"
    "    CMP.L   D1,D0\n"
    "    BLE.S   .final_index_no_wrap\n"
    "\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .final_index_ready\n"
    "\n"
    ".final_index_no_wrap:\n"
    "    MOVE.L  D7,D0\n"
    "    ADD.L   D6,D0\n"
    "\n"
    ".final_index_ready:\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D1\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #36,D0\n"
    "    ADD.L   D0,D1\n"
    "    PEA     33.W\n"
    "    PEA     695.W\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  NEWGRID_MainRastPortPtr,-(A7)\n"
    "    JSR     BEVEL_DrawBevelFrameWithTopRight(PC)\n"
    "\n"
    "    PEA     -89(A5)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    BSR.W   CLEANUP_FormatClockFormatEntry\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnStartXPx,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D1\n"
    "    MOVE.L  D0,48(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  48(A7),D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  NEWGRID_ColumnWidthPx,D0\n"
    "    LEA     -89(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_final_text_loop:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_final_text_loop\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  D0,52(A7)\n"
    "    MOVE.L  D1,48(A7)\n"
    "    MOVE.L  A1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  52(A7),D1\n"
    "    SUB.L   D0,D1\n"
    "    SUBQ.L  #8,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .center_final_text_x\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".center_final_text_x:\n"
    "    ASR.L   #1,D1\n"
    "    MOVE.L  48(A7),D0\n"
    "    ADD.L   D1,D0\n"
    "    MOVEQ   #42,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEA.L 52(A1),A0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  26(A0),D1\n"
    "    MOVEQ   #34,D2\n"
    "    SUB.L   D1,D2\n"
    "    TST.L   D2\n"
    "    BPL.S   .center_final_text_y\n"
    "\n"
    "    ADDQ.L  #1,D2\n"
    "\n"
    ".center_final_text_y:\n"
    "    ASR.L   #1,D2\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  26(A0),D1\n"
    "    ADD.L   D1,D2\n"
    "    SUBQ.L  #1,D2\n"
    "    MOVE.L  D2,D1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    MOVEQ   #3,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    LEA     -89(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".draw_final_text_loop:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .draw_final_text_loop\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D0\n"
    "    MOVEA.L NEWGRID_MainRastPortPtr,A1\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    "    MOVEM.L -120(A5),D2-D3/D5-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
