__asm__(
    ".globl _COI_ClearAnimObjectStrings\n"
    "_COI_ClearAnimObjectStrings:\n"
    "COI_ClearAnimObjectStrings:\n"
    "    MOVEM.L A2-A3,-(A7)\n"
    "    MOVEA.L 12(A7),A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   .lab_02D2\n"
    "\n"
    "    MOVEA.L 48(A3),A0\n"
    "    BRA.S   .lab_02D3\n"
    "\n"
    ".lab_02D2:\n"
    "    SUBA.L  A0,A0\n"
    "\n"
    ".lab_02D3:\n"
    "    MOVEA.L A0,A2\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.W   COI_ClearAnimObjectStrings_Return\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,(A2)\n"
    "    MOVE.B  D0,1(A2)\n"
    "    MOVE.B  D0,2(A2)\n"
    "    MOVE.B  D0,3(A2)\n"
    "    MOVE.L  4(A2),-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,4(A2)\n"
    "    MOVE.L  8(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,8(A2)\n"
    "    MOVE.L  12(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,12(A2)\n"
    "    MOVE.L  16(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,16(A2)\n"
    "    MOVE.L  20(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,20(A2)\n"
    "    MOVE.L  24(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,24(A2)\n"
    "    MOVE.L  28(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    MOVE.L  D0,28(A2)\n"
    "    CLR.L   32(A2)\n"
    "    BRA.W   COI_ClearAnimObjectStrings_Return\n"
);
