__asm__(
    ".globl _COI_WriteOiDataFile\n"
    "_COI_WriteOiDataFile:\n"
    "COI_WriteOiDataFile:\n"
    "    LINK.W  A5,#-152\n"
    "    MOVEM.L D5-D7/A2-A3/A6,-(A7)\n"
    "    MOVE.B  11(A5),D7\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    CMPI.W  #$c8,D0\n"
    "    BLS.S   .check_primary_header\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".check_primary_header:\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D7,D0\n"
    "    BNE.S   .check_secondary_header\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D0\n"
    "    SUBQ.B  #1,D0\n"
    "    BNE.S   .check_secondary_header\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.B  D0,CTASKS_SecondaryOiWritePendingFlag\n"
    "    MOVE.B  D7,CTASKS_PendingSecondaryOiDiskId\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D1\n"
    "    MOVE.W  D1,-32(A5)\n"
    "    BRA.S   .format_filename\n"
    "\n"
    ".check_secondary_header:\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    CMP.B   D7,D0\n"
    "    BNE.S   .invalid_disk_id\n"
    "\n"
    "    MOVE.B  #$1,CTASKS_PrimaryOiWritePendingFlag\n"
    "    MOVE.B  D7,CTASKS_PendingPrimaryOiDiskId\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    MOVE.W  D0,-32(A5)\n"
    "    BRA.S   .format_filename\n"
    "\n"
    ".invalid_disk_id:\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".format_filename:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D7,D0\n"
    "    MOVEQ   #2,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.W  D1,-30(A5)\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    PEA     Global_STR_DF0_OI_PERCENT_2_LX_DAT_1\n"
    "    PEA     -112(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     MODE_NEWFILE.W\n"
    "    PEA     -112(A5)\n"
    "    JSR     DISKIO_OpenFileWithBuffer(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    TST.L   D5\n"
    "    BNE.S   .write_header_disk_id\n"
    "\n"
    "    MOVEQ   #-3,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".write_header_disk_id:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D7,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     COI_FMT_LONG_DEC_A\n"
    "    PEA     -152(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -152(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_header_disk_id:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_header_disk_id\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    PEA     COI_FMT_DEC_A\n"
    "    PEA     -152(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -152(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_header_second_field:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_header_second_field\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    PEA     COI_RecordTerminatorCrLf\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     64(A7),A7\n"
    "    CLR.W   -26(A5)\n"
    "\n"
    ".entry_loop:\n"
    "    MOVE.W  -26(A5),D0\n"
    "    CMP.W   -32(A5),D0\n"
    "    BGE.W   .write_eof\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    CMP.B   D1,D7\n"
    "    BNE.S   .select_default_table\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    SUBQ.B  #1,D1\n"
    "    BNE.S   .select_default_table\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEA.L (A0),A3\n"
    "    BRA.S   .entry_selected\n"
    "\n"
    ".select_default_table:\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEA.L (A0),A3\n"
    "\n"
    ".entry_selected:\n"
    "    CLR.W   -28(A5)\n"
    "    MOVE.W  -28(A5),D6\n"
    "    EXT.L   D6\n"
    "\n"
    ".find_duplicate_entry:\n"
    "    MOVE.W  -28(A5),D0\n"
    "    CMP.W   -26(A5),D0\n"
    "    BGE.S   .entry_ready\n"
    "\n"
    "    TST.L   D6\n"
    "    BNE.S   .entry_ready\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    CMP.B   D1,D7\n"
    "    BNE.S   .select_compare_table\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    SUBQ.B  #1,D1\n"
    "    BNE.S   .select_compare_table\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    BRA.S   .compare_entry_names\n"
    "\n"
    ".select_compare_table:\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEA.L (A0),A1\n"
    "\n"
    ".compare_entry_names:\n"
    "    LEA     12(A3),A0\n"
    "    LEA     12(A1),A6\n"
    "    MOVE.L  A6,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A1,-16(A5)\n"
    "    JSR     ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    SEQ     D1\n"
    "    NEG.B   D1\n"
    "    EXT.W   D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,D6\n"
    "    ADDQ.W  #1,-28(A5)\n"
    "    BRA.S   .find_duplicate_entry\n"
    "\n"
    ".entry_ready:\n"
    "    TST.L   D6\n"
    "    BNE.W   .next_entry_group\n"
    "\n"
    "    MOVEA.L 48(A3),A2\n"
    "    LEA     12(A3),A0\n"
    "    MOVE.L  A0,D0\n"
    "    BEQ.S   .write_field24\n"
    "\n"
    "    LEA     12(A3),A0\n"
    "    LEA     12(A3),A1\n"
    "    MOVEA.L A1,A6\n"
    "\n"
    ".measure_entry_name:\n"
    "    TST.B   (A6)+\n"
    "    BNE.S   .measure_entry_name\n"
    "\n"
    "    SUBQ.L  #1,A6\n"
    "    SUBA.L  A1,A6\n"
    "    MOVE.L  A6,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field24:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   24(A2)\n"
    "    BEQ.S   .write_field28\n"
    "\n"
    "    MOVEA.L 24(A2),A0\n"
    "\n"
    ".measure_field24:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field24\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  24(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  24(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field28:\n"
    "    PEA     1.W\n"
    "    PEA     COI_STR_COLON_A\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   28(A2)\n"
    "    BEQ.S   .write_field32\n"
    "\n"
    "    MOVEA.L 28(A2),A0\n"
    "\n"
    ".measure_field28:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field28\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  28(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  28(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field32:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    MOVE.L  32(A2),(A7)\n"
    "    PEA     COI_FMT_LONG_DEC_B\n"
    "    PEA     -152(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -152(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_field32:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_field32\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     40(A7),A7\n"
    "    TST.L   4(A2)\n"
    "    BEQ.S   .write_field0\n"
    "\n"
    "    MOVEA.L 4(A2),A0\n"
    "\n"
    ".measure_field4:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field4\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  4(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  4(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field0:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    MOVEA.L A2,A0\n"
    "\n"
    ".measure_field0:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field0\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  A2,A0\n"
    "    MOVE.L  A0,(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    TST.L   12(A2)\n"
    "    BEQ.S   .write_field16\n"
    "\n"
    "    MOVEA.L 12(A2),A0\n"
    "\n"
    ".measure_field12:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field12\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  12(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  12(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field16:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   16(A2)\n"
    "    BEQ.S   .write_field20\n"
    "\n"
    "    MOVEA.L 16(A2),A0\n"
    "\n"
    ".measure_field16:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field16\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  16(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  16(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field20:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   20(A2)\n"
    "    BEQ.S   .write_field8\n"
    "\n"
    "    MOVEA.L 20(A2),A0\n"
    "\n"
    ".measure_field20:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field20\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  20(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  20(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_field8:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   8(A2)\n"
    "    BEQ.S   .write_entry_count\n"
    "\n"
    "    MOVEA.L 8(A2),A0\n"
    "\n"
    ".measure_field8:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_field8\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  8(A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  8(A2),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_entry_count:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    MOVE.W  36(A2),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    PEA     COI_FMT_LONG_DEC_C\n"
    "    PEA     -152(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -152(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_entry_count:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_entry_count\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    PEA     COI_RecordTerminatorCrLf\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     40(A7),A7\n"
    "    CLR.W   -28(A5)\n"
    "\n"
    ".subentry_loop:\n"
    "    MOVE.W  -28(A5),D0\n"
    "    CMP.W   36(A2),D0\n"
    "    BGE.W   .next_entry_group\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    MOVEA.L 38(A2),A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  (A0),-12(A5)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.W  (A0),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     COI_FMT_LONG_DEC_PAD2\n"
    "    PEA     -152(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -152(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_subentry_id:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_subentry_id\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    TST.L   18(A0)\n"
    "    BEQ.S   .write_subentry_field22\n"
    "\n"
    "    MOVEA.L 18(A0),A1\n"
    "\n"
    ".measure_subentry_field18:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_subentry_field18\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  18(A0),A1\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  18(A0),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_subentry_field22:\n"
    "    PEA     1.W\n"
    "    PEA     COI_STR_COLON_B\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    TST.L   22(A0)\n"
    "    BEQ.S   .write_subentry_field26\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 22(A1),A0\n"
    "\n"
    ".measure_subentry_field22:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_subentry_field22\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  22(A1),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  22(A1),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_subentry_field26:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  26(A0),(A7)\n"
    "    PEA     COI_FMT_DEC_B\n"
    "    PEA     -152(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -152(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_subentry_field26:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_subentry_field26\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     40(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    TST.L   6(A0)\n"
    "    BEQ.S   .write_subentry_field10\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 6(A1),A0\n"
    "\n"
    ".measure_subentry_field6:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_subentry_field6\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  6(A1),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  6(A1),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_subentry_field10:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    TST.L   10(A0)\n"
    "    BEQ.S   .write_subentry_field14\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 10(A1),A0\n"
    "\n"
    ".measure_subentry_field10:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_subentry_field10\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  10(A1),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  10(A1),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_subentry_field14:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    TST.L   14(A0)\n"
    "    BEQ.S   .write_subentry_field2\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 14(A1),A0\n"
    "\n"
    ".measure_subentry_field14:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_subentry_field14\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  14(A1),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  14(A1),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".write_subentry_field2:\n"
    "    PEA     1.W\n"
    "    PEA     COI_FieldDelimiterTab\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    TST.L   2(A0)\n"
    "    BEQ.S   .next_subentry\n"
    "\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVEA.L 2(A1),A0\n"
    "\n"
    ".measure_subentry_field2:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_subentry_field2\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  2(A1),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  2(A1),-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".next_subentry:\n"
    "    PEA     2.W\n"
    "    PEA     COI_RecordTerminatorCrLf\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    ADDQ.W  #1,-28(A5)\n"
    "    BRA.W   .subentry_loop\n"
    "\n"
    ".next_entry_group:\n"
    "    ADDQ.W  #1,-26(A5)\n"
    "    BRA.W   .entry_loop\n"
    "\n"
    ".write_eof:\n"
    "    PEA     1.W\n"
    "    PEA     CLOCK_FileEofMarkerCtrlZ\n"
    "    MOVE.L  D5,-(A7)\n"
    "    JSR     DISKIO_WriteBufferedBytes(PC)\n"
    "\n"
    "    MOVE.L  D5,(A7)\n"
    "    JSR     DISKIO_CloseBufferedFileAndFlush(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".return_status:\n"
    "    MOVEM.L -176(A5),D5-D7/A2-A3/A6\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
