__asm__(
    ".globl _COI_FreeSubEntryTableEntries\n"
    "_COI_FreeSubEntryTableEntries:\n"
    "COI_FreeSubEntryTableEntries:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D7/A2-A3,-(A7)\n"
    "    TST.L   8(A5)\n"
    "    BEQ.S   .lab_02D6\n"
    "\n"
    "    MOVEA.L 8(A5),A1\n"
    "    MOVEA.L 48(A1),A0\n"
    "    BRA.S   .lab_02D7\n"
    "\n"
    ".lab_02D6:\n"
    "    SUBA.L  A0,A0\n"
    "\n"
    ".lab_02D7:\n"
    "    MOVEA.L A0,A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.W   COI_FreeSubEntryTableEntries_Return\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".lab_02D8:\n"
    "    CMP.W   36(A3),D7\n"
    "    BGE.S   .lab_02D9\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L 38(A3),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "    CLR.W   (A2)\n"
    "    MOVE.L  2(A2),-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,2(A2)\n"
    "    MOVE.L  6(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,6(A2)\n"
    "    MOVE.L  10(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,10(A2)\n"
    "    MOVE.L  14(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,14(A2)\n"
    "    MOVE.L  18(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,18(A2)\n"
    "    MOVE.L  22(A2),(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVE.L  D0,22(A2)\n"
    "    CLR.L   26(A2)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .lab_02D8\n"
    "\n"
    ".lab_02D9:\n"
    "    TST.W   36(A3)\n"
    "    BEQ.S   .lab_02DA\n"
    "\n"
    "    MOVE.W  36(A3),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     30.W\n"
    "    MOVE.L  38(A3),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_DeallocateBufferArray(PC)\n"
    "\n"
    "    MOVE.W  36(A3),D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  38(A3),-(A7)\n"
    "    PEA     876.W\n"
    "    PEA     Global_STR_COI_C_4\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "\n"
    ".lab_02DA:\n"
    "    CLR.W   36(A3)\n"
    "    CLR.L   38(A3)\n"
    "    BRA.W   COI_FreeSubEntryTableEntries_Return\n"
);
