__asm__(
    ".globl _COI_LoadOiDataFile\n"
    "_COI_LoadOiDataFile:\n"
    "COI_LoadOiDataFile:\n"
    "    LINK.W  A5,#-648\n"
    "    MOVEM.L D2-D3/D5-D7/A2-A3,-(A7)\n"
    "    MOVE.B  11(A5),D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEQ   #9,D1\n"
    "    MOVE.B  D1,-615(A5)\n"
    "    MOVE.B  D1,-614(A5)\n"
    "    MOVE.B  D1,-613(A5)\n"
    "    MOVE.B  D1,-612(A5)\n"
    "    MOVE.B  D1,-611(A5)\n"
    "    MOVE.B  D1,-610(A5)\n"
    "    MOVE.B  D1,-609(A5)\n"
    "    MOVE.B  D1,-608(A5)\n"
    "    MOVE.B  D1,-607(A5)\n"
    "    MOVEQ   #13,D2\n"
    "    MOVE.B  D2,-606(A5)\n"
    "    MOVEQ   #10,D3\n"
    "    MOVE.B  D3,-605(A5)\n"
    "    MOVE.B  D1,-640(A5)\n"
    "    MOVE.B  D1,-639(A5)\n"
    "    MOVE.B  D1,-638(A5)\n"
    "    MOVE.B  D1,-637(A5)\n"
    "    MOVE.B  D1,-636(A5)\n"
    "    MOVE.B  D1,-635(A5)\n"
    "    MOVE.B  D2,-634(A5)\n"
    "    MOVE.B  D3,-633(A5)\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D7,D1\n"
    "    MOVE.L  D0,-582(A5)\n"
    "    MOVE.L  D0,-578(A5)\n"
    "    MOVE.L  D1,D0\n"
    "    MOVEQ   #2,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.W  D1,-334(A5)\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    PEA     Global_STR_DF0_OI_PERCENT_2_LX_DAT_2\n"
    "    PEA     -566(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -566(A5)\n"
    "    JSR     DISKIO_LoadFileToWorkBuffer(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    ADDQ.L  #1,D0\n"
    "    BNE.S   .file_loaded\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".file_loaded:\n"
    "    MOVE.L  Global_REF_LONG_FILE_SCRATCH,D0\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    MOVE.L  D0,-574(A5)\n"
    "    MOVE.L  A0,-570(A5)\n"
    "    CMP.B   D7,D1\n"
    "    BNE.S   .check_alt_header\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D0\n"
    "    SUBQ.B  #1,D0\n"
    "    BNE.S   .check_alt_header\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    MOVE.W  D0,-336(A5)\n"
    "    BRA.S   .init_parse_state\n"
    "\n"
    ".check_alt_header:\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .invalid_header\n"
    "\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    MOVE.W  D0,-336(A5)\n"
    "    BRA.S   .init_parse_state\n"
    "\n"
    ".invalid_header:\n"
    "    MOVE.L  -574(A5),D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    PEA     1198.W\n"
    "    PEA     Global_STR_COI_C_6\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".init_parse_state:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-578(A5)\n"
    "    MOVE.L  D0,-582(A5)\n"
    "\n"
    ".copy_header_line:\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    ADDA.L  -582(A5),A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A0),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     COI_STR_LINEFEED_CR_1\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .finish_header_line\n"
    "\n"
    "    LEA     -486(A5),A0\n"
    "    MOVE.L  -582(A5),D0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVE.B  (A1),(A0)\n"
    "    ADDQ.L  #1,-582(A5)\n"
    "    BRA.S   .copy_header_line\n"
    "\n"
    ".finish_header_line:\n"
    "    LEA     -486(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  -582(A5),A1\n"
    "    CLR.B   (A1)\n"
    "    PEA     9.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,-648(A5)\n"
    "    TST.L   D0\n"
    "    BEQ.S   .no_header_tab\n"
    "\n"
    "    MOVEA.L D0,A0\n"
    "    CLR.B   (A0)+\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A0,-648(A5)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,-644(A5)\n"
    "    BRA.S   .validate_disk_id\n"
    "\n"
    ".no_header_tab:\n"
    "    CLR.L   -644(A5)\n"
    "\n"
    ".validate_disk_id:\n"
    "    PEA     -486(A5)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D7,D1\n"
    "    CMP.L   D0,D1\n"
    "    BEQ.S   .strip_line_terminators\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    BRA.W   .return_status\n"
    "\n"
    ".strip_line_terminators:\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    ADDA.L  -582(A5),A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A0),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     COI_STR_LINEFEED_CR_2\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .clear_seen_flags\n"
    "\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    MOVE.L  -582(A5),D0\n"
    "    ADDA.L  D0,A0\n"
    "    CLR.B   (A0)\n"
    "    ADDQ.L  #1,-582(A5)\n"
    "    BRA.S   .strip_line_terminators\n"
    "\n"
    ".clear_seen_flags:\n"
    "    MOVE.W  #$12d,D0\n"
    "    MOVEQ   #0,D1\n"
    "    LEA     -326(A5),A0\n"
    "\n"
    ".zero_seen_flags:\n"
    "    MOVE.B  D1,(A0)+\n"
    "    DBF     D0,.zero_seen_flags\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".record_loop:\n"
    "    CMP.W   -336(A5),D6\n"
    "    BGE.W   .cleanup_and_return\n"
    "\n"
    "    MOVE.L  -582(A5),D0\n"
    "    ADD.L   D0,-578(A5)\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   -644(A5),D0\n"
    "    BNE.S   .parse_record_legacy\n"
    "\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    MOVE.L  -574(A5),D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    PEA     26.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -615(A5)\n"
    "    PEA     11.W\n"
    "    PEA     -604(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    BRA.S   .init_entry_loop\n"
    "\n"
    ".parse_record_legacy:\n"
    "    MOVEQ   #21,D0\n"
    "    MOVEQ   #0,D1\n"
    "    LEA     -604(A5),A0\n"
    "\n"
    ".clear_record_fields:\n"
    "    MOVE.B  D1,(A0)+\n"
    "    DBF     D0,.clear_record_fields\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    MOVE.L  -574(A5),D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    PEA     26.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -613(A5)\n"
    "    PEA     11.W\n"
    "    PEA     -600(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "\n"
    ".init_entry_loop:\n"
    "    MOVE.W  -584(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #0,D5\n"
    "    MOVE.L  D0,-582(A5)\n"
    "\n"
    ".entry_loop:\n"
    "    CMP.W   -336(A5),D5\n"
    "    BGE.W   .advance_entry\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .select_default_table\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D0\n"
    "    SUBQ.B  #1,D0\n"
    "    BNE.S   .select_default_table\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    BRA.S   .match_entry_pattern\n"
    "\n"
    ".select_default_table:\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "\n"
    ".match_entry_pattern:\n"
    "    LEA     12(A1),A0\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A2\n"
    "    ADDA.L  -578(A5),A2\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A1,-4(A5)\n"
    "    JSR     ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.W   .next_entry\n"
    "\n"
    "    LEA     -326(A5),A0\n"
    "    ADDA.W  D5,A0\n"
    "    TST.B   (A0)\n"
    "    BNE.W   .alloc_subentries\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  48(A0),-8(A5)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    ADDA.W  -600(A5),A0\n"
    "    MOVEA.L -8(A5),A1\n"
    "    MOVE.L  4(A1),-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,4(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    MOVEA.W -598(A5),A2\n"
    "    MOVE.L  A2,D0\n"
    "    MOVE.B  0(A1,D0.W),(A0)\n"
    "    MOVE.B  1(A1,D0.W),1(A0)\n"
    "    MOVE.B  2(A1,D0.W),2(A0)\n"
    "    CLR.B   3(A0)\n"
    "    ADDA.W  -596(A5),A1\n"
    "    MOVE.L  12(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,12(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -594(A5),A1\n"
    "    MOVE.L  16(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,16(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -592(A5),A1\n"
    "    MOVE.L  20(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,20(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -590(A5),A1\n"
    "    MOVE.L  8(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,8(A0)\n"
    "    MOVE.W  -604(A5),D0\n"
    "    BLE.S   .default_field24\n"
    "\n"
    "    MOVE.L  -578(A5),D1\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D1,A2\n"
    "    ADDA.W  D0,A2\n"
    "    MOVE.L  A2,D2\n"
    "    BEQ.S   .default_field24\n"
    "\n"
    "    LEA     24(A0),A2\n"
    "    LEA     28(A0),A3\n"
    "    ADDA.L  D1,A1\n"
    "    ADDA.W  D0,A1\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    BSR.W   CLEANUP_FormatEntryStringTokens\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .after_field24\n"
    "\n"
    ".default_field24:\n"
    "    MOVE.L  24(A0),-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,24(A0)\n"
    "    MOVE.L  28(A0),(A7)\n"
    "    PEA     COI_STR_DEFAULT_TOKEN_TEMPLATE_A\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,28(A0)\n"
    "\n"
    ".after_field24:\n"
    "    MOVE.W  -602(A5),D0\n"
    "    BEQ.S   .missing_field32\n"
    "\n"
    "    MOVE.L  -578(A5),D1\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    ADDA.W  D0,A1\n"
    "    MOVE.L  A1,D2\n"
    "    BEQ.S   .missing_field32\n"
    "\n"
    "    ADDA.L  D1,A0\n"
    "    ADDA.W  D0,A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,32(A0)\n"
    "    BRA.S   .store_field36\n"
    "\n"
    ".missing_field32:\n"
    "    MOVEQ   #-1,D0\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  D0,32(A0)\n"
    "\n"
    ".store_field36:\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    ADDA.W  -588(A5),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    PEA     Global_STR_PERCENT_S_1\n"
    "    PEA     -486(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -486(A5)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.W  D0,36(A0)\n"
    "\n"
    ".alloc_subentries:\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    BSR.W   COI_AllocSubEntryTable\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    CLR.W   -332(A5)\n"
    "\n"
    ".subentry_loop:\n"
    "    MOVE.W  -332(A5),D0\n"
    "    MOVEA.L -8(A5),A0\n"
    "    CMP.W   36(A0),D0\n"
    "    BGE.W   .mark_entry_seen\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    MOVEA.L -8(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  (A0),-12(A5)\n"
    "    MOVE.L  -582(A5),D0\n"
    "    ADD.L   D0,-578(A5)\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   -644(A5),D0\n"
    "    BNE.S   .parse_subentry_legacy\n"
    "\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    MOVE.L  -574(A5),D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    PEA     26.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -640(A5)\n"
    "    PEA     8.W\n"
    "    PEA     -632(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    BRA.S   .process_subentry\n"
    "\n"
    ".parse_subentry_legacy:\n"
    "    MOVEQ   #15,D0\n"
    "    MOVEQ   #0,D1\n"
    "    LEA     -632(A5),A0\n"
    "\n"
    ".clear_subentry_fields:\n"
    "    MOVE.B  D1,(A0)+\n"
    "    DBF     D0,.clear_subentry_fields\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    MOVE.L  -574(A5),D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    PEA     26.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -638(A5)\n"
    "    PEA     6.W\n"
    "    PEA     -628(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "\n"
    ".process_subentry:\n"
    "    LEA     -326(A5),A0\n"
    "    ADDA.W  D5,A0\n"
    "    TST.B   (A0)\n"
    "    BNE.W   .advance_subentry\n"
    "\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    ADDA.L  -578(A5),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.W  D0,(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -628(A5),A1\n"
    "    MOVE.L  6(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,6(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -626(A5),A1\n"
    "    MOVE.L  10(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,10(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -624(A5),A1\n"
    "    MOVE.L  14(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,14(A0)\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    ADDA.L  -578(A5),A1\n"
    "    ADDA.W  -622(A5),A1\n"
    "    MOVE.L  2(A0),(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,2(A0)\n"
    "    MOVE.W  -632(A5),D0\n"
    "    BLE.S   .default_subentry_field18\n"
    "\n"
    "    MOVE.L  -578(A5),D1\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D1,A2\n"
    "    ADDA.W  D0,A2\n"
    "    MOVE.L  A2,D2\n"
    "    BEQ.S   .default_subentry_field18\n"
    "\n"
    "    LEA     18(A0),A2\n"
    "    LEA     22(A0),A3\n"
    "    ADDA.L  D1,A1\n"
    "    ADDA.W  D0,A1\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    BSR.W   CLEANUP_FormatEntryStringTokens\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .after_subentry_field18\n"
    "\n"
    ".default_subentry_field18:\n"
    "    MOVE.L  18(A0),-(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  24(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,18(A0)\n"
    "    MOVE.L  22(A0),(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  28(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,22(A0)\n"
    "\n"
    ".after_subentry_field18:\n"
    "    MOVE.W  -630(A5),D0\n"
    "    BLE.S   .inherit_subentry_field26\n"
    "\n"
    "    MOVE.L  -578(A5),D1\n"
    "    MOVEA.L Global_PTR_WORK_BUFFER,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    ADDA.W  D0,A1\n"
    "    MOVE.L  A1,D2\n"
    "    BEQ.S   .inherit_subentry_field26\n"
    "\n"
    "    ADDA.L  D1,A0\n"
    "    ADDA.W  D0,A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  D0,26(A0)\n"
    "    BRA.S   .advance_subentry\n"
    "\n"
    ".inherit_subentry_field26:\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L -12(A5),A1\n"
    "    MOVE.L  32(A0),26(A1)\n"
    "\n"
    ".advance_subentry:\n"
    "    MOVE.W  -618(A5),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-582(A5)\n"
    "    ADDQ.W  #1,-332(A5)\n"
    "    BRA.W   .subentry_loop\n"
    "\n"
    ".mark_entry_seen:\n"
    "    LEA     -326(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.W  D5,A1\n"
    "    TST.B   (A1)\n"
    "    BNE.S   .advance_entry\n"
    "\n"
    "    ADDA.W  D5,A0\n"
    "    MOVE.B  #$1,(A0)\n"
    "    BRA.S   .advance_entry\n"
    "\n"
    ".next_entry:\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.W   .entry_loop\n"
    "\n"
    ".advance_entry:\n"
    "    ADDQ.W  #1,D5\n"
    "\n"
    ".second_pass_loop:\n"
    "    CMP.W   -336(A5),D5\n"
    "    BGE.W   .next_record\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .select_table_second_pass\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D0\n"
    "    SUBQ.B  #1,D0\n"
    "    BNE.S   .select_table_second_pass\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    BRA.S   .match_entry_second_pass\n"
    "\n"
    ".select_table_second_pass:\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "\n"
    ".match_entry_second_pass:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    ADDA.W  #12,A0\n"
    "    LEA     12(A1),A2\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A1,-16(A5)\n"
    "    JSR     ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.W   .next_second_pass_entry\n"
    "\n"
    "    LEA     -326(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.W  D5,A1\n"
    "    TST.B   (A1)\n"
    "    BNE.W   .next_second_pass_entry\n"
    "\n"
    "    ADDA.W  D5,A0\n"
    "    MOVE.B  #$1,(A0)\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  48(A0),-20(A5)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  4(A0),-(A7)\n"
    "    MOVEA.L -8(A5),A1\n"
    "    MOVE.L  4(A1),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,4(A0)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L -20(A5),A1\n"
    "    MOVE.B  (A0),(A1)\n"
    "    MOVE.B  1(A0),1(A1)\n"
    "    MOVE.B  2(A0),2(A1)\n"
    "    MOVE.B  3(A0),3(A1)\n"
    "    MOVE.L  12(A1),(A7)\n"
    "    MOVE.L  12(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,12(A0)\n"
    "    MOVE.L  16(A0),(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  16(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,16(A0)\n"
    "    MOVE.L  20(A0),(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  20(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,20(A0)\n"
    "    MOVE.L  8(A0),(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  8(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,8(A0)\n"
    "    MOVE.L  24(A0),(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  24(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,24(A0)\n"
    "    MOVE.L  28(A0),(A7)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  28(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  D0,28(A0)\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L -20(A5),A1\n"
    "    MOVE.L  32(A0),32(A1)\n"
    "    MOVE.W  36(A0),36(A1)\n"
    "    MOVE.L  -16(A5),(A7)\n"
    "    BSR.W   COI_AllocSubEntryTable\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    CLR.W   -332(A5)\n"
    "\n"
    ".copy_subentries:\n"
    "    MOVE.W  -332(A5),D0\n"
    "    MOVEA.L -20(A5),A0\n"
    "    CMP.W   36(A0),D0\n"
    "    BGE.W   .next_second_pass_entry\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    MOVEA.L -20(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  (A0),-24(A5)\n"
    "    MOVEA.L -8(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  (A0),-12(A5)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVEA.L -24(A5),A1\n"
    "    MOVE.W  (A0),(A1)\n"
    "    MOVE.L  6(A1),-(A7)\n"
    "    MOVE.L  6(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,6(A0)\n"
    "    MOVE.L  10(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  10(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,10(A0)\n"
    "    MOVE.L  14(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  14(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,14(A0)\n"
    "    MOVE.L  2(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  2(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,2(A0)\n"
    "    MOVE.L  18(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  18(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,18(A0)\n"
    "    MOVE.L  22(A0),(A7)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVE.L  22(A0),-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.L  D0,22(A0)\n"
    "    MOVEA.L -12(A5),A0\n"
    "    MOVEA.L -24(A5),A1\n"
    "    MOVE.L  26(A0),26(A1)\n"
    "    ADDQ.W  #1,-332(A5)\n"
    "    BRA.W   .copy_subentries\n"
    "\n"
    ".next_second_pass_entry:\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.W   .second_pass_loop\n"
    "\n"
    ".next_record:\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.W   .record_loop\n"
    "\n"
    ".cleanup_and_return:\n"
    "    MOVE.L  -574(A5),D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  -570(A5),-(A7)\n"
    "    PEA     1443.W\n"
    "    PEA     Global_STR_COI_C_1\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".return_status:\n"
    "    MOVEM.L -676(A5),D2-D3/D5-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
