__asm__(
    ".globl _COI_ComputeEntryTimeDeltaMinutes\n"
    "_COI_ComputeEntryTimeDeltaMinutes:\n"
    "COI_ComputeEntryTimeDeltaMinutes:\n"
    "    MOVEM.L D5-D7/A3,-(A7)\n"
    "    MOVEA.L 20(A7),A3\n"
    "    MOVE.W  26(A7),D7\n"
    "    MOVEQ   #49,D6\n"
    "    MOVEQ   #-1,D5\n"
    "    TST.W   D7\n"
    "    BLE.W   COI_ComputeEntryTimeDeltaMinutes_Return\n"
    "\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.W   COI_ComputeEntryTimeDeltaMinutes_Return\n"
    "\n"
    "    MOVE.L  D7,D6\n"
    "    ADDQ.W  #1,D6\n"
    "\n"
    ".lab_0365:\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGE.S   .lab_0366\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    TST.L   56(A3,D0.L)\n"
    "    BNE.S   .lab_0366\n"
    "\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .lab_0365\n"
    "\n"
    ".lab_0366:\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .lab_0369\n"
    "\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    MOVE.B  498(A3),D1\n"
    "    CMP.B   D0,D1\n"
    "    BNE.S   .lab_0369\n"
    "\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_TLIBA_FindFirstWildcardMatchIndex(PC)\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    PEA     2.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQDISP_GetEntryAuxPointerByMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L D0,A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   .lab_0368\n"
    "\n"
    "    MOVEQ   #1,D6\n"
    "\n"
    ".lab_0367:\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGE.S   .lab_0369\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    TST.L   56(A3,D0.L)\n"
    "    BNE.S   .lab_0369\n"
    "\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .lab_0367\n"
    "\n"
    ".lab_0368:\n"
    "    MOVEQ   #49,D6\n"
    "\n"
    ".lab_0369:\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .lab_036A\n"
    "\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    MULU    #30,D0\n"
    "    MOVE.L  #2880,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D5\n"
    "    BRA.W   COI_ComputeEntryTimeDeltaMinutes_Return\n"
    "\n"
    ".lab_036A:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  498(A3),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_TEXTDISP_ComputeTimeOffset(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    BRA.W   COI_ComputeEntryTimeDeltaMinutes_Return\n"
);
