__asm__(
    ".globl _COI_EnsureAnimObjectAllocated\n"
    "_COI_EnsureAnimObjectAllocated:\n"
    "COI_EnsureAnimObjectAllocated:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   .return\n"
    "\n"
    "    MOVEA.L 48(A3),A0\n"
    "    MOVE.L  A0,-4(A5)\n"
    "    BNE.S   .return\n"
    "\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    PEA     Struct_AnimOb_Size.W\n"
    "    PEA     1458.W\n"
    "    PEA     Global_STR_COI_C_2\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    MOVE.L  D0,48(A3)\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.L  28(A0),(A7)\n"
    "    PEA     COI_STR_DEFAULT_TOKEN_TEMPLATE_B\n"
    "    MOVE.L  D0,24(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVEA.L 4(A7),A0\n"
    "    MOVE.L  D0,28(A0)\n"
    "    MOVEA.L 48(A3),A0\n"
    "    MOVEQ   #-1,D0\n"
    "    MOVE.L  D0,32(A0)\n"
    "\n"
    ".return:\n"
    "    MOVEA.L (A7)+,A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
