__asm__(
    ".globl _COI_FormatEntryDisplayText\n"
    "_COI_FormatEntryDisplayText:\n"
    "COI_FormatEntryDisplayText:\n"
    "    LINK.W  A5,#-44\n"
    "    MOVEM.L D2/D5-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    MOVE.L  16(A5),D7\n"
    "    MOVE.L  24(A5),D6\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   .lab_0359\n"
    "\n"
    "    MOVE.L  GCOMMAND_PpvSelectionWindowMinutes,D1\n"
    "    BRA.S   .lab_035A\n"
    "\n"
    ".lab_0359:\n"
    "    MOVE.L  #1440,D1\n"
    "\n"
    ".lab_035A:\n"
    "    MOVE.L  D1,-28(A5)\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   .lab_035B\n"
    "\n"
    "    MOVE.L  GCOMMAND_PpvSelectionToleranceMinutes,D0\n"
    "    BRA.S   .lab_035C\n"
    "\n"
    ".lab_035B:\n"
    "    MOVE.L  CONFIG_TimeWindowMinutes,D0\n"
    "\n"
    ".lab_035C:\n"
    "    MOVE.L  D7,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  D0,-32(A5)\n"
    "    BSR.W   COI_TestEntryWithinTimeWindow\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    TST.L   D0\n"
    "    BEQ.W   COI_FormatEntryDisplayText_Return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,-20(A5)\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   .lab_035D\n"
    "\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,-16(A5)\n"
    "    MOVE.L  A0,-12(A5)\n"
    "    MOVE.L  A0,-8(A5)\n"
    "    MOVEQ   #3,D6\n"
    "    BRA.S   .lab_035E\n"
    "\n"
    ".lab_035D:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     3.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    MOVE.L  D0,-16(A5)\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     4.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     2.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    LEA     36(A7),A7\n"
    "    MOVE.L  D0,-8(A5)\n"
    "\n"
    ".lab_035E:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   CLEANUP_TestEntryFlagYAndBit1\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .lab_035F\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    PEA     6.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_GetAnimFieldPointerByMode\n"
    "\n"
    "    PEA     20.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     19.W\n"
    "    PEA     COI_FMT_WRAP_CHAR_STRING_CHAR\n"
    "    PEA     -44(A5)\n"
    "    MOVE.L  D0,-36(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     -44(A5),A0\n"
    "    MOVE.L  A0,-4(A5)\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   CLEANUP_UpdateEntryFlagBytes\n"
    "\n"
    "    LEA     36(A7),A7\n"
    "    BRA.S   .lab_0360\n"
    "\n"
    ".lab_035F:\n"
    "    CLR.L   -4(A5)\n"
    "\n"
    ".lab_0360:\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".lab_0361:\n"
    "    MOVEQ   #5,D0\n"
    "    CMP.L   D0,D5\n"
    "    BGE.W   COI_FormatEntryDisplayText_Return\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    ASL.L   #2,D0\n"
    "    TST.L   -20(A5,D0.L)\n"
    "    BEQ.S   .lab_0362\n"
    "\n"
    "    MOVEA.L -20(A5,D0.L),A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.S   .lab_0362\n"
    "\n"
    "    PEA     COI_STR_SINGLE_SPACE\n"
    "    MOVE.L  20(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVE.L  -20(A5,D0.L),(A7)\n"
    "    MOVE.L  20(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".lab_0362:\n"
    "    ADDQ.L  #1,D5\n"
    "    BRA.S   .lab_0361\n"
);
