__asm__(
    ".globl _COI_CountEscape14BeforeNull\n"
    "_COI_CountEscape14BeforeNull:\n"
    "COI_CountEscape14BeforeNull:\n"
    "    MOVEM.L D4-D7/A3,-(A7)\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVE.L  28(A7),D7\n"
    "    MOVEQ   #0,D5\n"
    "    MOVEQ   #0,D6\n"
    "    MOVE.L  D6,D4\n"
    "\n"
    ".scan_loop:\n"
    "    TST.W   D5\n"
    "    BNE.S   .done\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    CMP.L   D7,D0\n"
    "    BGE.S   .done\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  0(A3,D6.W),D0\n"
    "    TST.W   D0\n"
    "    BEQ.S   .found_null\n"
    "\n"
    "    SUBI.W  #20,D0\n"
    "    BEQ.S   .found_escape\n"
    "\n"
    "    BRA.S   .advance\n"
    "\n"
    ".found_null:\n"
    "    MOVEQ   #1,D5\n"
    "    BRA.S   .advance\n"
    "\n"
    ".found_escape:\n"
    "    ADDQ.W  #1,D4\n"
    "    ADDQ.W  #1,D6\n"
    "\n"
    ".advance:\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .scan_loop\n"
    "\n"
    ".done:\n"
    "    MOVE.L  D4,D0\n"
    "    MOVEM.L (A7)+,D4-D7/A3\n"
    "    RTS\n"
);
