__asm__(
    ".globl _COI_TestEntryWithinTimeWindow\n"
    "_COI_TestEntryWithinTimeWindow:\n"
    "COI_TestEntryWithinTimeWindow:\n"
    "    LINK.W  A5,#-24\n"
    "    MOVEM.L D5-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    MOVE.W  18(A5),D7\n"
    "    MOVE.L  20(A5),D6\n"
    "    MOVE.L  24(A5),D5\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    MOVE.L  D0,-8(A5)\n"
    "    MOVE.L  A0,-20(A5)\n"
    "    MOVE.L  A0,-16(A5)\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.W   .lab_0378\n"
    "\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.W   .lab_0378\n"
    "\n"
    "    TST.W   D7\n"
    "    BLE.W   .lab_0378\n"
    "\n"
    "    TST.W   D7\n"
    "    BLE.S   .lab_036D\n"
    "\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .lab_036D\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A3),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_TEXTDISP_ComputeTimeOffset(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,-8(A5)\n"
    "    BRA.S   .lab_036E\n"
    "\n"
    ".lab_036D:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVEQ   #30,D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  D0,-8(A5)\n"
    "\n"
    ".lab_036E:\n"
    "    BTST    #4,27(A3)\n"
    "    BEQ.S   .lab_0375\n"
    "\n"
    "    MOVEA.L 48(A3),A0\n"
    "    MOVE.L  A0,-16(A5)\n"
    "    BEQ.S   .lab_0374\n"
    "\n"
    "    CLR.L   -24(A5)\n"
    "\n"
    ".lab_036F:\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.W  36(A0),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  -24(A5),D1\n"
    "    CMP.L   D0,D1\n"
    "    BGE.S   .lab_0371\n"
    "\n"
    "    ASL.L   #2,D1\n"
    "    MOVEA.L -16(A5),A1\n"
    "    MOVEA.L 38(A1),A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  (A0),-20(A5)\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.W  (A0),D0\n"
    "    CMP.W   D7,D0\n"
    "    BNE.S   .lab_0370\n"
    "\n"
    "    BRA.S   .lab_0371\n"
    "\n"
    ".lab_0370:\n"
    "    CLR.L   -20(A5)\n"
    "    ADDQ.L  #1,-24(A5)\n"
    "    BRA.S   .lab_036F\n"
    "\n"
    ".lab_0371:\n"
    "    TST.L   -20(A5)\n"
    "    BEQ.S   .lab_0372\n"
    "\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  26(A0),-12(A5)\n"
    "    BRA.S   .lab_0373\n"
    "\n"
    ".lab_0372:\n"
    "    MOVEA.L -16(A5),A0\n"
    "    MOVE.L  32(A0),D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "\n"
    ".lab_0373:\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   -12(A5),D0\n"
    "    BNE.S   .lab_0376\n"
    "\n"
    "    MOVE.L  D5,-12(A5)\n"
    "    BRA.S   .lab_0376\n"
    "\n"
    ".lab_0374:\n"
    "    MOVE.L  D5,-12(A5)\n"
    "    BRA.S   .lab_0376\n"
    "\n"
    ".lab_0375:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    BSR.W   COI_ComputeEntryTimeDeltaMinutes\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  -8(A5),D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "\n"
    ".lab_0376:\n"
    "    MOVE.L  -12(A5),D0\n"
    "    TST.L   D0\n"
    "    BMI.S   .lab_0377\n"
    "\n"
    "    MOVE.L  -8(A5),D1\n"
    "    CMP.L   D6,D1\n"
    "    BGT.S   .lab_0377\n"
    "\n"
    "    NEG.L   D0\n"
    "    CMP.L   D0,D1\n"
    "    BGE.W   COI_TestEntryWithinTimeWindow_Return\n"
    "\n"
    ".lab_0377:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    BRA.W   COI_TestEntryWithinTimeWindow_Return\n"
    "\n"
    ".lab_0378:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    BRA.W   COI_TestEntryWithinTimeWindow_Return\n"
);
