__asm__(
    ".globl _COI_AllocSubEntryTable\n"
    "_COI_AllocSubEntryTable:\n"
    "COI_AllocSubEntryTable:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVE.L  A3,-(A7)\n"
    "\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   .null_parent\n"
    "\n"
    "    MOVEA.L 48(A3),A0\n"
    "    BRA.S   .have_anim_ptr\n"
    "\n"
    ".null_parent:\n"
    "    SUBA.L  A0,A0\n"
    "\n"
    ".have_anim_ptr:\n"
    "    MOVE.L  A0,-4(A5)\n"
    "    MOVE.L  A0,D0\n"
    "    BEQ.S   .return_status\n"
    "\n"
    "    MOVE.W  36(A0),D0\n"
    "    TST.W   D0\n"
    "    BLE.S   .return_status\n"
    "\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     1123.W\n"
    "    PEA     Global_STR_COI_C_5\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  D0,38(A0)\n"
    "    MOVE.W  36(A0),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,(A7)\n"
    "    PEA     30.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_SCRIPT_AllocateBufferArray(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "\n"
    ".return_status:\n"
    "    MOVEA.L (A7)+,A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
