__asm__(
    ".globl _COI_FreeEntryResources\n"
    "_COI_FreeEntryResources:\n"
    "COI_FreeEntryResources:\n"
    "    MOVEM.L A2-A3,-(A7)\n"
    "    MOVEA.L 12(A7),A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.W   COI_FreeEntryResources_Return\n"
    "\n"
    "    MOVEA.L 48(A3),A2\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   COI_FreeSubEntryTableEntries\n"
    "\n"
    "    MOVE.L  A3,(A7)\n"
    "    BSR.W   COI_ClearAnimObjectStrings\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.S   .lab_02CF\n"
    "\n"
    "    PEA     42.W\n"
    "    MOVE.L  A2,-(A7)\n"
    "    PEA     815.W\n"
    "    PEA     Global_STR_COI_C_3\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".lab_02CF:\n"
    "    CLR.L   48(A3)\n"
    "    BRA.W   COI_FreeEntryResources_Return\n"
);
