__asm__(
    ".globl _CTASKS_IFFTaskCleanup\n"
    "_CTASKS_IFFTaskCleanup:\n"
    "CTASKS_IFFTaskCleanup:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVE.L  A4,-(A7)\n"
    "    LEA     Global_REF_LONG_FILE_SCRATCH,A4\n"
    "    MOVE.W  CTASKS_IffTaskState,D0                  \n"
    "    SUBQ.W  #4,D0\n"
    "    BNE.S   .check_state_5\n"
    "\n"
    "    MOVE.L  CTASKS_PendingLogoBrushDescriptor,-4(A5)\n"
    "    BRA.S   .wait_for_brush\n"
    "\n"
    ".check_state_5:\n"
    "    MOVE.W  CTASKS_IffTaskState,D0\n"
    "    SUBQ.W  #5,D0\n"
    "    BNE.S   .check_state_6_or_11\n"
    "\n"
    "    MOVE.L  CTASKS_PendingGAdsBrushDescriptor,-4(A5)\n"
    "    BRA.S   .wait_for_brush\n"
    "\n"
    ".check_state_6_or_11:\n"
    "    MOVE.W  CTASKS_IffTaskState,D0\n"
    "    SUBQ.W  #6,D0\n"
    "    BEQ.S   .state_6_or_11\n"
    "\n"
    "    MOVE.W  CTASKS_IffTaskState,D0\n"
    "    MOVEQ   #11,D1\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .wait_for_brush\n"
    "\n"
    ".state_6_or_11:\n"
    "    MOVE.L  CTASKS_PendingIffBrushDescriptor,-4(A5)\n"
    "\n"
    ".wait_for_brush:\n"
    "    TST.L   BRUSH_LoadInProgressFlag      \n"
    "    BNE.S   .wait_for_brush\n"
    "\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    JSR     GROUP_AF_JMPTBL_GCOMMAND_SaveBrushResult(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.W  CTASKS_IffTaskState,D0\n"
    "    SUBQ.W  #4,D0\n"
    "    BNE.S   .clear_state5\n"
    "\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,CTASKS_PendingLogoBrushDescriptor\n"
    "    BRA.S   .finish_reset\n"
    "\n"
    ".clear_state5:\n"
    "    MOVE.W  CTASKS_IffTaskState,D0\n"
    "    SUBQ.W  #5,D0\n"
    "    BNE.S   .clear_state6\n"
    "\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,CTASKS_PendingGAdsBrushDescriptor\n"
    "    BRA.S   .finish_reset\n"
    "\n"
    ".clear_state6:\n"
    "    MOVE.W  CTASKS_IffTaskState,D0\n"
    "    SUBQ.W  #6,D0\n"
    "    BNE.S   .finish_reset\n"
    "\n"
    "    CLR.L   CTASKS_PendingIffBrushDescriptor\n"
    "\n"
    ".finish_reset:\n"
    "    MOVEA.L AbsExecBase,A6               \n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    MOVE.W  #1,CTASKS_IffTaskDoneFlag\n"
    "    CLR.W   CTASKS_IffTaskState\n"
    "    PEA     14.W\n"
    "    MOVE.L  Global_REF_LIST_IFF_TASK_PROC,-(A7)\n"
    "    PEA     127.W\n"
    "    PEA     Global_STR_CTASKS_C_1\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    MOVEA.L -8(A5),A4\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
