__asm__(
    ".globl _CTASKS_CloseTaskTeardown\n"
    "_CTASKS_CloseTaskTeardown:\n"
    "CTASKS_CloseTaskTeardown:\n"
    "    MOVE.L  A4,-(A7)\n"
    "\n"
    "    LEA     Global_REF_LONG_FILE_SCRATCH,A4\n"
    "    TST.L   CTASKS_CloseTaskFileHandle\n"
    "    BEQ.S   .skip_close_handle\n"
    "\n"
    "    MOVE.L  CTASKS_CloseTaskFileHandle,D1\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOClose(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,CTASKS_CloseTaskFileHandle\n"
    "\n"
    ".skip_close_handle:\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    PEA     14.W\n"
    "    MOVE.L  Global_REF_LIST_CLOSE_TASK_PROC,-(A7)\n"
    "    PEA     194.W\n"
    "    PEA     Global_STR_CTASKS_C_3\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.W  #1,CTASKS_CloseTaskCompletionFlag\n"
    "\n"
    "    MOVEA.L (A7)+,A4\n"
    "    RTS\n"
);
