__asm__(
    ".globl _CTASKS_StartCloseTaskProcess\n"
    "_CTASKS_StartCloseTaskProcess:\n"
    "CTASKS_StartCloseTaskProcess:\n"
    "    MOVEM.L D2-D4/D7,-(A7)\n"
    "\n"
    "    MOVE.L  20(A7),D7\n"
    "\n"
    "    CLR.W   CTASKS_CloseTaskCompletionFlag\n"
    "    MOVE.L  D7,CTASKS_CloseTaskFileHandle\n"
    "\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    PEA     (Struct_List_Size).W\n"
    "    PEA     203.W\n"
    "    PEA     Global_STR_CTASKS_C_4\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    "    MOVE.L  D0,Global_REF_LIST_CLOSE_TASK_PROC\n"
    "    MOVEQ   #(Struct_List_Size),D1\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.L  D1,(A0)\n"
    "    LEA     CTASKS_CloseTaskTeardown(PC),A0\n"
    "    MOVEA.L Global_REF_LIST_CLOSE_TASK_PROC,A1\n"
    "    MOVE.L  A0,10(A1)\n"
    "    MOVE.W  #20217,8(A1)\n"
    "    MOVEA.L Global_REF_LIST_CLOSE_TASK_PROC,A0\n"
    "    ADDQ.L  #4,A0\n"
    "    MOVE.L  A0,D0\n"
    "    LSR.L   #2,D0\n"
    "    MOVE.L  D0,CTASKS_CloseTaskSegListBPTR\n"
    "    MOVE.L  D0,D3\n"
    "\n"
    "    LEA     Global_STR_CLOSE_TASK,A0\n"
    "    MOVE.L  A0,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  #8192,D4\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOCreateProc(A6)\n"
    "\n"
    "    MOVE.L  D0,CTASKS_CloseTaskProcPtr\n"
    "    MOVEM.L (A7)+,D2-D4/D7\n"
    "    RTS\n"
);
