__asm__(
    ".globl _CTASKS_StartIffTaskProcess\n"
    "_CTASKS_StartIffTaskProcess:\n"
    "CTASKS_StartIffTaskProcess:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D2-D4,-(A7)\n"
    "\n"
    "CTASKS_StartIffTaskProcess_wait_for_prior_iff_task:\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    LEA     Global_STR_IFF_TASK_1,A1\n"
    "    JSR     _LVOFindTask(A6)\n"
    "\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    TST.L   -4(A5)\n"
    "    BNE.S   CTASKS_StartIffTaskProcess_wait_for_prior_iff_task\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,CTASKS_IffTaskDoneFlag\n"
    "    MOVE.W  CTASKS_IffTaskState,D1\n"
    "    SUBQ.W  #6,D1\n"
    "    BEQ.S   CTASKS_StartIffTaskProcess_alloc_list_and_spawn\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D1\n"
    "    BEQ.S   CTASKS_StartIffTaskProcess_set_state_to_5\n"
    "\n"
    "    MOVE.W  #4,CTASKS_IffTaskState\n"
    "    BRA.S   CTASKS_StartIffTaskProcess_alloc_list_and_spawn\n"
    "\n"
    "CTASKS_StartIffTaskProcess_set_state_to_5:\n"
    "    MOVE.W  #5,CTASKS_IffTaskState\n"
    "\n"
    "CTASKS_StartIffTaskProcess_alloc_list_and_spawn:\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    PEA     (Struct_List_Size).W\n"
    "    PEA     159.W\n"
    "    PEA     Global_STR_CTASKS_C_2\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    MOVE.L  D0,Global_REF_LIST_IFF_TASK_PROC\n"
    "    MOVEQ   #(Struct_List_Size),D1\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.L  D1,(A0)\n"
    "    LEA     CTASKS_IFFTaskCleanup(PC),A0\n"
    "    MOVEA.L Global_REF_LIST_IFF_TASK_PROC,A1\n"
    "    MOVE.L  A0,10(A1)\n"
    "    MOVE.W  #20217,8(A1)\n"
    "\n"
    "    MOVEA.L Global_REF_LIST_IFF_TASK_PROC,A0\n"
    "    ADDQ.L  #4,A0\n"
    "    MOVE.L  A0,D0\n"
    "    LSR.L   #2,D0\n"
    "    MOVE.L  D0,CTASKS_IffTaskSegListBPTR\n"
    "    MOVE.L  D0,D3\n"
    "    LEA     Global_STR_IFF_TASK_2,A0\n"
    "    MOVE.L  A0,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  #8192,D4\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOCreateProc(A6)\n"
    "\n"
    "    MOVE.L  D0,CTASKS_IffTaskProcPtr\n"
    "    MOVEM.L -16(A5),D2-D4\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
