__asm__(
    ".globl _DISKIO_WriteBytesToOutputHandleGuarded\n"
    "_DISKIO_WriteBytesToOutputHandleGuarded:\n"
    "DISKIO_WriteBytesToOutputHandleGuarded:\n"
    "    MOVEM.L D2-D3/D6-D7/A3,-(A7)\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVE.W  30(A7),D7\n"
    "    MOVE.W  ESQPARS2_ReadModeFlags,DISKIO_SavedReadModeFlags\n"
    "    MOVE.W  #$100,ESQPARS2_ReadModeFlags\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  A3,D2\n"
    "    MOVE.L  D0,D3\n"
    "    MOVE.L  DISKIO_WriteFileHandle,D1\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOWrite(A6)\n"
    "    MOVE.L  D0,D6\n"
    "    CMP.W   D7,D6\n"
    "    MOVE.W  DISKIO_SavedReadModeFlags,ESQPARS2_ReadModeFlags\n"
    "    CMP.W   D7,D6\n"
    "    BEQ.S   1f\n"
    "    MOVEQ   #-1,D0\n"
    "    BRA.S   2f\n"
    "1:\n"
    "    MOVEQ   #0,D0\n"
    "2:\n"
    "    MOVEM.L (A7)+,D2-D3/D6-D7/A3\n"
    "    RTS\n"
);
