__asm__(
    ".globl _DISKIO_EnsurePc1MountedAndGfxAssigned\n"
    "_DISKIO_EnsurePc1MountedAndGfxAssigned:\n"
    "DISKIO_EnsurePc1MountedAndGfxAssigned:\n"
    "    MOVEM.L D2-D3,-(A7)\n"
    "    TST.W   DISKIO_Pc1MountAssignFlag\n"
    "    BNE.S   DISKIO_EnsurePc1MountedAndGfxAssigned_Return\n"
    "    MOVE.W  #1,DISKIO_Pc1MountAssignFlag\n"
    "    LEA     DISKIO_CMD_MOUNT_PC1,A0\n"
    "    MOVE.L  A0,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  D2,D3\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOExecute(A6)\n"
    "    MOVE.L  D2,D3\n"
    "    LEA     DISKIO_CMD_ASSIGN_GFX_PC1_EXPLICIT,A0\n"
    "    MOVE.L  A0,D1\n"
    "    JSR     _LVOExecute(A6)\n"
    "    MOVEM.L (A7)+,D2-D3\n"
    "    RTS\n"
);
