__asm__(
    ".globl _DISKIO_ResetCtrlInputStateIfIdle\n"
    "_DISKIO_ResetCtrlInputStateIfIdle:\n"
    "DISKIO_ResetCtrlInputStateIfIdle:\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   1f\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVODisable(A6)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,CTRL_BufferedByteCount\n"
    "    MOVE.W  D0,CTRL_HPreviousSample\n"
    "    MOVE.W  D0,CTRL_H\n"
    "    JSR     _LVOEnable(A6)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,Global_RefreshTickCounter\n"
    "    MOVE.W  D0,ESQPARS2_ReadModeFlags\n"
    "1:\n"
    "    RTS\n"
);
