__asm__(
    ".globl _DISKIO_QueryVolumeSoftErrorCount\n"
    "_DISKIO_QueryVolumeSoftErrorCount:\n"
    "DISKIO_QueryVolumeSoftErrorCount:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D2/D6-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEQ   #0,D7\n"
    "    MOVE.L  A3,D1\n"
    "    MOVEQ   #-2,D2\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOLock(A6)\n"
    "    MOVE.L  D0,D6\n"
    "    TST.L   D6\n"
    "    BEQ.S   .return\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    PEA     Struct_InfoData_Size\n"
    "    PEA     593.W\n"
    "    PEA     Global_STR_DISKIO_C_7\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,-8(A5)\n"
    "    TST.L   D0\n"
    "    BEQ.S   .lab_03C6\n"
    "    MOVE.L  D6,D1\n"
    "    MOVE.L  D0,D2\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOInfo(A6)\n"
    "    TST.L   D0\n"
    "    BEQ.S   .lab_03C5\n"
    "    MOVEA.L D2,A0\n"
    "    MOVE.L  (A0),D7\n"
    ".lab_03C5:\n"
    "    PEA     Struct_InfoData_Size\n"
    "    MOVE.L  D2,-(A7)\n"
    "    PEA     599.W\n"
    "    PEA     Global_STR_DISKIO_C_8\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "    LEA     16(A7),A7\n"
    ".lab_03C6:\n"
    "    MOVE.L  D6,D1\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOUnLock(A6)\n"
    ".return:\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEM.L (A7)+,D2/D6-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
