__asm__(
    ".globl _DISKIO_GetFilesizeFromHandle\n"
    "_DISKIO_GetFilesizeFromHandle:\n"
    "DISKIO_GetFilesizeFromHandle:\n"
    "    MOVEM.L D2-D3/D6-D7,-(A7)\n"
    "    MOVE.L  D7,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVEQ   #1,D3\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOSeek(A6)\n"
    "    MOVE.L  D7,D1\n"
    "    MOVE.L  D2,D3\n"
    "    JSR     _LVOSeek(A6)\n"
    "    MOVE.L  D0,D6\n"
    "    MOVE.L  D7,D1\n"
    "    MOVEQ   #0,D3\n"
    "    JSR     _LVOSeek(A6)\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEM.L (A7)+,D2-D3/D6-D7\n"
    "    RTS\n"
);
