__asm__(
    ".globl _DISKIO_DrawTransferErrorMessageIfDiagnostics\n"
    "_DISKIO_DrawTransferErrorMessageIfDiagnostics:\n"
    "DISKIO_DrawTransferErrorMessageIfDiagnostics:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  8(A7),D7\n"
    "    TST.W   ED_DiagnosticsScreenActive\n"
    "    BEQ.S   1f\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #4,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     (CTASKS_TerminationReasonPtrTable-4),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     240.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     DISPLIB_DisplayTextAtPosition\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "1:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
