__asm__(
    ".globl _DISKIO_WriteDecimalField\n"
    "_DISKIO_WriteDecimalField:\n"
    "DISKIO_WriteDecimalField:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D6-D7,-(A7)\n"
    "    MOVE.L  8(A5),D7\n"
    "    MOVE.L  12(A5),D6\n"
    "    MOVE.L  D6,-(A7)\n"
    "    PEA     Global_STR_PERCENT_LD\n"
    "    PEA     -10(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "    LEA     -10(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    ".lab_03AA:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .lab_03AA\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D7,-(A7)\n"
    "    BSR.W   DISKIO_WriteBufferedBytes\n"
    "    MOVEM.L -20(A5),D6-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
