__asm__(
    ".globl _DISPTEXT_AppendToBuffer\n"
    "_DISPTEXT_AppendToBuffer:\n"
    "DISPTEXT_AppendToBuffer:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    CLR.L   -8(A5)\n"
    "    TST.L   DISPTEXT_TextBufferPtr\n"
    "    BEQ.W   DISPTEXT_AppendToBuffer_alloc_new_buffer\n"
    "\n"
    "    MOVEA.L DISPTEXT_TextBufferPtr,A0\n"
    "\n"
    "DISPTEXT_AppendToBuffer_find_end_dst:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   DISPTEXT_AppendToBuffer_find_end_dst\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  DISPTEXT_TextBufferPtr,A0\n"
    "    MOVEA.L A3,A1\n"
    "\n"
    "DISPTEXT_AppendToBuffer_find_end_src:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   DISPTEXT_AppendToBuffer_find_end_src\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A3,A1\n"
    "    MOVE.L  A0,D0\n"
    "    MOVE.L  A1,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.L  D0,D7\n"
    "    ADDQ.L  #1,D7\n"
    "    MOVEQ   #1,D1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    CMPI.L  #$2710,D0\n"
    "    BLE.S   DISPTEXT_AppendToBuffer_realloc_buffer\n"
    "\n"
    "    PEA     (MEMF_PUBLIC).W\n"
    "    MOVE.L  D7,-(A7)\n"
    "    PEA     127.W\n"
    "    PEA     Global_STR_DISPTEXT_C_1\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,-8(A5)\n"
    "\n"
    "DISPTEXT_AppendToBuffer_realloc_buffer:\n"
    "    TST.L   -8(A5)\n"
    "    BEQ.S   DISPTEXT_AppendToBuffer_return_status\n"
    "\n"
    "    MOVEA.L DISPTEXT_TextBufferPtr,A0\n"
    "    MOVEA.L -8(A5),A1\n"
    "\n"
    "DISPTEXT_AppendToBuffer_copy_old_buffer:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   DISPTEXT_AppendToBuffer_copy_old_buffer\n"
    "\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  -8(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    MOVE.L  DISPTEXT_TextBufferPtr,(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  A0,DISPTEXT_TextBufferPtr\n"
    "    BRA.S   DISPTEXT_AppendToBuffer_return_status\n"
    "\n"
    "DISPTEXT_AppendToBuffer_alloc_new_buffer:\n"
    "    MOVE.L  DISPTEXT_TextBufferPtr,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,DISPTEXT_TextBufferPtr\n"
    "\n"
    "DISPTEXT_AppendToBuffer_return_status:\n"
    "    TST.L   DISPTEXT_TextBufferPtr\n"
    "    SNE     D0\n"
    "    NEG.B   D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEM.L (A7)+,D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
