__asm__(
    ".globl _DISPTEXT_LayoutSourceToLines\n"
    "_DISPTEXT_LayoutSourceToLines:\n"
    "DISPTEXT_LayoutSourceToLines:\n"
    "    LINK.W  A5,#-276\n"
    "    MOVEM.L D2/D5-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    MOVEQ   #0,D7\n"
    "    TST.L   DISPTEXT_LineTableLockFlag\n"
    "    BNE.W   DISPTEXT_LayoutSourceToLines_return_status\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.W   DISPTEXT_LayoutSourceToLines_return_status\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ADD.L   D1,D1\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    TST.W   (A1)\n"
    "    BEQ.S   DISPTEXT_LayoutSourceToLines_no_prefix_line\n"
    "\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D0,D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     DISPTEXT_LinePtrTable,A1\n"
    "    ADDA.L  D2,A1\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  (A0),D0\n"
    "    MOVE.L  A1,28(A7)\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEA.L 28(A7),A0\n"
    "    MOVEA.L (A0),A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D1\n"
    "    MOVE.L  D1,D2\n"
    "    SUB.L   D0,D2\n"
    "    MOVE.L  D2,D6\n"
    "    BRA.S   DISPTEXT_LayoutSourceToLines_adjust_for_prefix\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_no_prefix_line:\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D6\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_adjust_for_prefix:\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   DISPTEXT_LayoutSourceToLines_maybe_subtract_markers\n"
    "\n"
    "    SUB.L   DISPTEXT_ControlMarkerWidthPx,D6\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_maybe_subtract_markers:\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D0,D2\n"
    "    ADD.L   D2,D2\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    TST.W   (A0)\n"
    "    BEQ.S   DISPTEXT_LayoutSourceToLines_try_build_line\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    LEA     DISPTEXT_STR_SINGLE_SPACE_PREFIX_1,A0\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "    CMP.L   D5,D6\n"
    "    BLE.S   DISPTEXT_LayoutSourceToLines_reset_width_for_next\n"
    "\n"
    "    SUB.L   D5,D6\n"
    "    BRA.S   DISPTEXT_LayoutSourceToLines_try_build_line\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_reset_width_for_next:\n"
    "    ADDQ.L  #1,D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D7,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.L   D1,D0\n"
    "    BGE.S   DISPTEXT_LayoutSourceToLines_try_build_line\n"
    "\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D6\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_try_build_line:\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.S   DISPTEXT_LayoutSourceToLines_return_status\n"
    "\n"
    "    TST.B   (A2)\n"
    "    BEQ.S   DISPTEXT_LayoutSourceToLines_return_status\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D7,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.L   D1,D0\n"
    "    BGE.S   DISPTEXT_LayoutSourceToLines_return_status\n"
    "\n"
    "    MOVE.L  D6,-(A7)\n"
    "    PEA     -268(A5)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   DISPTEXT_BuildLineWithWidth\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L D0,A2\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D6\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   DISPTEXT_LayoutSourceToLines_after_build_line\n"
    "\n"
    "    SUB.L   DISPTEXT_ControlMarkerWidthPx,D6\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_after_build_line:\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.S   DISPTEXT_LayoutSourceToLines_try_build_line\n"
    "\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   DISPTEXT_LayoutSourceToLines_try_build_line\n"
    "\n"
    "DISPTEXT_LayoutSourceToLines_return_status:\n"
    "    MOVE.L  A2,D1\n"
    "    SEQ     D0\n"
    "    NEG.B   D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEM.L (A7)+,D2/D5-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
