__asm__(
    ".globl _DISPTEXT_BuildLayoutForSource\n"
    "_DISPTEXT_BuildLayoutForSource:\n"
    "DISPTEXT_BuildLayoutForSource:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEQ   #0,D7\n"
    "    TST.L   DISPTEXT_LineTableLockFlag\n"
    "    BNE.S   DISPTEXT_BuildLayoutForSource_return_status\n"
    "\n"
    "    LEA     16(A5),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  12(A5),-(A7)\n"
    "    MOVE.L  Global_REF_1000_BYTES_ALLOCATED_1,-(A7)\n"
    "    MOVE.L  A0,-8(A5)\n"
    "    JSR     GROUP_AI_JMPTBL_FORMAT_FormatToBuffer2(PC)\n"
    "\n"
    "    MOVE.L  Global_REF_1000_BYTES_ALLOCATED_1,(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   DISPTEXT_LayoutAndAppendToBuffer\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,D7\n"
    "\n"
    "DISPTEXT_BuildLayoutForSource_return_status:\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEM.L (A7)+,D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
