__asm__(
    ".globl _DISPLIB_ApplyInlineAlignmentPadding\n"
    ".globl _DISPLIB_ApplyInlineAlignmentPadding_Return\n"
    "_DISPLIB_ApplyInlineAlignmentPadding:\n"
    "DISPLIB_ApplyInlineAlignmentPadding:\n"
    "    LINK.W  A5,#-28\n"
    "    MOVEM.L D4-D7/A3,-(A7)\n"
    "\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.B  15(A5),D7\n"
    "    MOVEA.L A3,A0\n"
    "\n"
    ".lab_0553:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .lab_0553\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  A3,A0\n"
    "    MOVE.L  A0,D5\n"
    "    MOVEA.L A3,A0\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  #624,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D6\n"
    "    TST.L   D6\n"
    "    BLE.W   DISPLIB_ApplyInlineAlignmentPadding_Return\n"
    "\n"
    "    MOVEQ   #24,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .lab_0555\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    LEA     DISPLIB_STR_InlineAlignPadCharCenter,A0\n"
    "    MOVEQ   #1,D0\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    MOVE.L  20(A7),D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    TST.L   D0\n"
    "    BPL.S   .lab_0554\n"
    "\n"
    "    ADDQ.L  #1,D0\n"
    "\n"
    ".lab_0554:\n"
    "    ASR.L   #1,D0\n"
    "    MOVE.L  D0,D4\n"
    "    BRA.S   .lab_0557\n"
    "\n"
    ".lab_0555:\n"
    "    MOVEQ   #26,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .branch\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    LEA     DISPLIB_STR_InlineAlignPadCharRight,A0\n"
    "    MOVEQ   #1,D0\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    MOVE.L  20(A7),D1\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.L  D0,D4\n"
    "    BRA.S   .lab_0557\n"
    "\n"
    ".branch:\n"
    "    MOVEQ   #0,D4\n"
    "\n"
    ".lab_0557:\n"
    "    TST.L   D4\n"
    "    BEQ.S   DISPLIB_ApplyInlineAlignmentPadding_Return\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    PEA     (MEMF_PUBLIC).W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     194.W\n"
    "    PEA     Global_STR_DISPLIB_C_1\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    TST.L   D0\n"
    "    BEQ.S   DISPLIB_ApplyInlineAlignmentPadding_Return\n"
    "\n"
    "    MOVEA.L A3,A0\n"
    "    MOVEA.L D0,A1\n"
    "\n"
    ".branch_1:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .branch_1\n"
    "\n"
    "    MOVE.L  A3,-8(A5)\n"
    "    CLR.L   -24(A5)\n"
    "\n"
    ".branch_2:\n"
    "    MOVE.L  -24(A5),D0\n"
    "    CMP.L   D4,D0\n"
    "    BGE.S   .branch_3\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.B  #$20,(A0)+\n"
    "    MOVE.L  A0,-8(A5)\n"
    "    ADDQ.L  #1,-24(A5)\n"
    "    BRA.S   .branch_2\n"
    "\n"
    ".branch_3:\n"
    "    MOVEA.L -8(A5),A0\n"
    "    CLR.B   (A0)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    PEA     204.W\n"
    "    PEA     Global_STR_DISPLIB_C_2\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "\n"
    "_DISPLIB_ApplyInlineAlignmentPadding_Return:\n"
    "DISPLIB_ApplyInlineAlignmentPadding_Return:\n"
    "    MOVEM.L (A7)+,D4-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
