__asm__(
    ".globl _DISPTEXT_HasMultipleLines\n"
    "_DISPTEXT_HasMultipleLines:\n"
    "DISPTEXT_HasMultipleLines:\n"
    "    BSR.W   DISPTEXT_FinalizeLineTable\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    BNE.S   DISPTEXT_HasMultipleLines_return_false\n"
    "\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.S   DISPTEXT_HasMultipleLines_return_false\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   DISPTEXT_HasMultipleLines_return\n"
    "\n"
    "DISPTEXT_HasMultipleLines_return_false:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "DISPTEXT_HasMultipleLines_return:\n"
    "    RTS\n"
);
