__asm__(
    ".globl _DISPTEXT_BuildLinePointerTable\n"
    "_DISPTEXT_BuildLinePointerTable:\n"
    "DISPTEXT_BuildLinePointerTable:\n"
    "    MOVEM.L D5-D7/A2-A3,-(A7)\n"
    "    MOVE.L  24(A7),D7\n"
    "    TST.L   DISPTEXT_LineTableLockFlag\n"
    "    BNE.S   DISPTEXT_BuildLinePointerTable_return\n"
    "\n"
    "    MOVE.L  DISPTEXT_TextBufferPtr,DISPTEXT_LinePtrTable\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    TST.W   (A0)\n"
    "    BEQ.S   DISPTEXT_BuildLinePointerTable_has_header_line\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   DISPTEXT_BuildLinePointerTable_init_line_count\n"
    "\n"
    "DISPTEXT_BuildLinePointerTable_has_header_line:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "DISPTEXT_BuildLinePointerTable_init_line_count:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.L  D1,D5\n"
    "    MOVEQ   #1,D6\n"
    "\n"
    "DISPTEXT_BuildLinePointerTable_build_ptrs_loop:\n"
    "    CMP.L   D5,D6\n"
    "    BGE.S   DISPTEXT_BuildLinePointerTable_set_locked\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     DISPTEXT_LinePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     DISPTEXT_TextBufferPtr,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVE.L  D6,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_CurrentLineIndex,A2\n"
    "    ADDA.L  D0,A2\n"
    "    MOVEA.L (A1),A3\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  (A2),D0\n"
    "    ADDA.L  D0,A3\n"
    "    MOVE.L  A3,(A0)\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.S   DISPTEXT_BuildLinePointerTable_build_ptrs_loop\n"
    "\n"
    "DISPTEXT_BuildLinePointerTable_set_locked:\n"
    "    MOVE.L  D7,DISPTEXT_LineTableLockFlag\n"
    "\n"
    "DISPTEXT_BuildLinePointerTable_return:\n"
    "    MOVEM.L (A7)+,D5-D7/A2-A3\n"
    "    RTS\n"
);
