__asm__(
    ".globl _DISPLIB_DisplayTextAtPosition\n"
    "_DISPLIB_DisplayTextAtPosition:\n"
    "DISPLIB_DisplayTextAtPosition:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D6-D7/A2-A3,-(A7)\n"
    "\n"
    "    MOVEA.L 28(A7),A3\n"
    "    MOVE.L  32(A7),D7\n"
    "    MOVE.L  36(A7),D6\n"
    "    MOVEA.L 40(A7),A2\n"
    "\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.S   .return\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D7,D0\n"
    "    MOVE.L  D6,D1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVEA.L A2,A0\n"
    "\n"
    ".currentCharacterIsNotNull:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .currentCharacterIsNotNull\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  A2,A0\n"
    "    MOVE.L  A0,16(A7)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEA.L A2,A0\n"
    "    MOVE.L  16(A7),D0\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D6-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
