__asm__(
    ".globl _DISPTEXT_MeasureCurrentLineLength\n"
    "_DISPTEXT_MeasureCurrentLineLength:\n"
    "DISPTEXT_MeasureCurrentLineLength:\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVEA.L 8(A7),A3\n"
    "    BSR.W   DISPTEXT_FinalizeLineTable\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     DISPTEXT_LinePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_LineLengthTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  (A1),D0\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEA.L (A0),A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVEA.L (A7)+,A3\n"
    "    RTS\n"
);
