__asm__(
    ".globl _DISPLIB_ResetLineTables\n"
    "_DISPLIB_ResetLineTables:\n"
    "DISPLIB_ResetLineTables:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,DISPTEXT_TargetLineIndex\n"
    "    MOVE.W  D0,DISPTEXT_CurrentLineIndex\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.L  D1,DISPTEXT_LineWidthPx\n"
    "    MOVE.L  D1,DISPTEXT_ControlMarkerWidthPx\n"
    "    MOVE.L  D1,DISPTEXT_LineTableLockFlag\n"
    "    MOVE.W  D0,DISPTEXT_ControlMarkersEnabledFlag\n"
    "    MOVE.L  D1,D7\n"
    "\n"
    ".lab_0564:\n"
    "    MOVEQ   #20,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .lab_0565\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     DISPTEXT_LinePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    CLR.L   (A0)\n"
    "    MOVE.L  D7,D1\n"
    "    ADD.L   D1,D1\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    CLR.W   (A0)\n"
    "    LEA     DISPTEXT_LinePenTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,(A0)\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .lab_0564\n"
    "\n"
    ".lab_0565:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
