__asm__(
    ".globl _DISPTEXT_BuildLineWithWidth\n"
    "_DISPTEXT_BuildLineWithWidth:\n"
    "DISPTEXT_BuildLineWithWidth:\n"
    "    LINK.W  A5,#-76\n"
    "    MOVEM.L D2-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    MOVE.L  20(A5),D7\n"
    "    MOVEA.L A3,A1\n"
    "    LEA     DISPTEXT_STR_SINGLE_SPACE_MEASURE,A0\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVEA.L 16(A5),A0\n"
    "    CLR.B   (A0)\n"
    "    MOVE.L  D0,-16(A5)\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_line_loop:\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.W   DISPTEXT_BuildLineWithWidth_done\n"
    "\n"
    "    TST.B   (A2)\n"
    "    BEQ.W   DISPTEXT_BuildLineWithWidth_done\n"
    "\n"
    "    CMP.L   -16(A5),D7\n"
    "    BLE.W   DISPTEXT_BuildLineWithWidth_done\n"
    "\n"
    "    MOVEA.L 16(A5),A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.S   DISPTEXT_BuildLineWithWidth_append_separator\n"
    "\n"
    "    PEA     DISPTEXT_STR_SINGLE_SPACE_APPEND\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    SUB.L   -16(A5),D7\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_append_separator:\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_SkipClass3Chars(PC)\n"
    "\n"
    "    MOVEA.L D0,A2\n"
    "    MOVE.L  A2,-20(A5)\n"
    "    PEA     DISPTEXT_STR_SINGLE_SPACE_DELIM\n"
    "    PEA     50.W\n"
    "    PEA     -73(A5)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_CopyUntilAnyDelimN(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVEA.L D0,A2\n"
    "    LEA     -73(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_measure_word:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   DISPTEXT_BuildLineWithWidth_measure_word\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D6\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.B  (A0),D0\n"
    "    MOVEQ   #19,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   DISPTEXT_BuildLineWithWidth_measure_adjust\n"
    "\n"
    "    ADDQ.L  #8,D5\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_measure_adjust:\n"
    "    CMP.L   D7,D5\n"
    "    BLE.S   DISPTEXT_BuildLineWithWidth_append_word\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D2\n"
    "    MOVEQ   #2,D3\n"
    "    CMP.W   D3,D2\n"
    "    BCC.S   DISPTEXT_BuildLineWithWidth_set_separator_width\n"
    "\n"
    "    MOVE.L  DISPTEXT_ControlMarkerWidthPx,D2\n"
    "    BRA.S   DISPTEXT_BuildLineWithWidth_compute_remaining_width\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_set_separator_width:\n"
    "    MOVEQ   #0,D2\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_compute_remaining_width:\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D3\n"
    "    SUB.L   D2,D3\n"
    "    MOVE.L  D3,D4\n"
    "    CMP.L   D4,D5\n"
    "    BLE.S   DISPTEXT_BuildLineWithWidth_skip_word\n"
    "\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.W   DISPTEXT_BuildLineWithWidth_line_loop\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_shrink_word:\n"
    "    CMP.L   D7,D5\n"
    "    BLE.S   DISPTEXT_BuildLineWithWidth_emit_word\n"
    "\n"
    "    TST.L   D6\n"
    "    BLE.S   DISPTEXT_BuildLineWithWidth_emit_word\n"
    "\n"
    "    SUBQ.L  #1,D6\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D6,D0\n"
    "    LEA     -73(A5),A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "    BRA.S   DISPTEXT_BuildLineWithWidth_shrink_word\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_emit_word:\n"
    "    TST.L   D6\n"
    "    BLE.S   DISPTEXT_BuildLineWithWidth_advance_source\n"
    "\n"
    "    CLR.B   -73(A5,D6.L)\n"
    "    PEA     -73(A5)\n"
    "    MOVE.L  16(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_advance_source:\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D6,A1\n"
    "    MOVEA.L A1,A2\n"
    "    MOVEQ   #0,D7\n"
    "    BRA.W   DISPTEXT_BuildLineWithWidth_line_loop\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_skip_word:\n"
    "    MOVEA.L -20(A5),A2\n"
    "    MOVEQ   #0,D7\n"
    "    BRA.W   DISPTEXT_BuildLineWithWidth_line_loop\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_append_word:\n"
    "    PEA     -73(A5)\n"
    "    MOVE.L  16(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    SUB.L   D5,D7\n"
    "    MOVEQ   #19,D1\n"
    "    MOVEA.L -20(A5),A0\n"
    "    CMP.B   (A0),D1\n"
    "    SEQ     D0\n"
    "    NEG.B   D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  DISPTEXT_ControlMarkersEnabledFlag,D1\n"
    "    EXT.L   D1\n"
    "    OR.L    D0,D1\n"
    "    MOVE.W  D1,DISPTEXT_ControlMarkersEnabledFlag\n"
    "    BRA.W   DISPTEXT_BuildLineWithWidth_line_loop\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_done:\n"
    "    TST.B   (A2)\n"
    "    BNE.S   DISPTEXT_BuildLineWithWidth_null_out\n"
    "\n"
    "    SUBA.L  A2,A2\n"
    "\n"
    "DISPTEXT_BuildLineWithWidth_null_out:\n"
    "    MOVE.L  A2,D0\n"
    "    MOVEM.L (A7)+,D2-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
