__asm__(
    ".globl _DISPTEXT_FinalizeLineTable\n"
    "_DISPTEXT_FinalizeLineTable:\n"
    "DISPTEXT_FinalizeLineTable:\n"
    "    TST.L   DISPTEXT_LineTableLockFlag\n"
    "    BNE.S   DISPTEXT_FinalizeLineTable_return\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.W  D0,DISPTEXT_TargetLineIndex\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ADD.L   D1,D1\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    TST.W   (A0)\n"
    "    BEQ.S   DISPTEXT_FinalizeLineTable_check_extra_line\n"
    "\n"
    "    ADDQ.W  #1,D0\n"
    "    MOVE.W  D0,DISPTEXT_TargetLineIndex\n"
    "\n"
    "DISPTEXT_FinalizeLineTable_check_extra_line:\n"
    "    PEA     1.W\n"
    "    BSR.W   DISPTEXT_BuildLinePointerTable\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    CLR.W   DISPTEXT_CurrentLineIndex\n"
    "\n"
    "DISPTEXT_FinalizeLineTable_return:\n"
    "    RTS\n"
);
