__asm__(
    ".globl _DISPLIB_NormalizeValueByStep\n"
    "_DISPLIB_NormalizeValueByStep:\n"
    "DISPLIB_NormalizeValueByStep:\n"
    "    MOVEM.L D5-D7,-(A7)\n"
    "    MOVE.W  18(A7),D7\n"
    "    MOVE.W  22(A7),D6\n"
    "    MOVE.W  26(A7),D5\n"
    "\n"
    ".lab_0560:\n"
    "    CMP.W   D6,D7\n"
    "    BGE.S   .lab_0561\n"
    "\n"
    "    ADD.W   D5,D7\n"
    "    BRA.S   .lab_0560\n"
    "\n"
    ".lab_0561:\n"
    "    CMP.W   D5,D7\n"
    "    BLE.S   .return\n"
    "\n"
    "    SUB.W   D5,D7\n"
    "    BRA.S   .lab_0561\n"
    "\n"
    ".return:\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEM.L (A7)+,D5-D7\n"
    "    RTS\n"
);
