__asm__(
    ".globl _DISPTEXT_SetLayoutParams\n"
    "_DISPTEXT_SetLayoutParams:\n"
    "DISPTEXT_SetLayoutParams:\n"
    "    MOVEM.L D5-D7,-(A7)\n"
    "    MOVE.L  16(A7),D7\n"
    "    MOVE.L  20(A7),D6\n"
    "    MOVE.L  24(A7),D5\n"
    "    BSR.W   DISPLIB_ResetTextBufferAndLineTables\n"
    "\n"
    "    TST.L   D7\n"
    "    BMI.S   DISPTEXT_SetLayoutParams_clamp_width\n"
    "\n"
    "    CMPI.L  #624,D7\n"
    "    BGT.S   DISPTEXT_SetLayoutParams_clamp_width\n"
    "\n"
    "    MOVE.L  D7,DISPTEXT_LineWidthPx\n"
    "\n"
    "DISPTEXT_SetLayoutParams_clamp_width:\n"
    "    TST.L   D6\n"
    "    BLE.S   DISPTEXT_SetLayoutParams_clamp_lines\n"
    "\n"
    "    MOVEQ   #20,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGT.S   DISPTEXT_SetLayoutParams_clamp_lines\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    MOVE.W  D0,DISPTEXT_TargetLineIndex\n"
    "\n"
    "DISPTEXT_SetLayoutParams_clamp_lines:\n"
    "    MOVE.L  D5,-(A7)\n"
    "    BSR.W   DISPLIB_CommitCurrentLinePenAndAdvance\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D0\n"
    "    CMP.L   D7,D0\n"
    "    BNE.S   DISPTEXT_SetLayoutParams_mismatch\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D0\n"
    "    CMP.L   D6,D0\n"
    "    BNE.S   DISPTEXT_SetLayoutParams_mismatch\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   DISPTEXT_SetLayoutParams_done\n"
    "\n"
    "DISPTEXT_SetLayoutParams_mismatch:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "DISPTEXT_SetLayoutParams_done:\n"
    "    MOVEM.L (A7)+,D5-D7\n"
    "    RTS\n"
);
