__asm__(
    ".globl _DISPTEXT_IsLastLineSelected\n"
    "_DISPTEXT_IsLastLineSelected:\n"
    "DISPTEXT_IsLastLineSelected:\n"
    "    MOVE.L  D2,-(A7)\n"
    "    BSR.W   DISPTEXT_FinalizeLineTable\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D1\n"
    "    CMP.L   D0,D1\n"
    "    SEQ     D2\n"
    "    NEG.B   D2\n"
    "    EXT.W   D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D2,D0\n"
    "    MOVE.L  (A7)+,D2\n"
    "    RTS\n"
);
