__asm__(
    ".globl _DISPTEXT_InitBuffers\n"
    "_DISPTEXT_InitBuffers:\n"
    "DISPTEXT_InitBuffers:\n"
    "    TST.L   DISPTEXT_InitBuffersPending\n"
    "    BEQ.S   DISPTEXT_InitBuffers_return\n"
    "\n"
    "    CLR.L   DISPTEXT_TextBufferPtr\n"
    "    BSR.W   DISPLIB_ResetLineTables\n"
    "\n"
    "    CLR.L   DISPTEXT_InitBuffersPending\n"
    "\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    PEA     1000.W\n"
    "    PEA     320.W\n"
    "    PEA     Global_STR_DISPTEXT_C_2\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    MOVE.L  #65537,(A7)\n"
    "    PEA     1000.W\n"
    "    PEA     321.W\n"
    "    PEA     Global_STR_DISPTEXT_C_3\n"
    "    MOVE.L  D0,Global_REF_1000_BYTES_ALLOCATED_1\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVE.L  D0,Global_REF_1000_BYTES_ALLOCATED_2\n"
    "\n"
    "DISPTEXT_InitBuffers_return:\n"
    "    RTS\n"
);
