__asm__(
    ".globl _DISPTEXT_ComputeMarkerWidths\n"
    "_DISPTEXT_ComputeMarkerWidths:\n"
    "DISPTEXT_ComputeMarkerWidths:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D4-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.L  12(A5),D7\n"
    "    MOVE.L  16(A5),D6\n"
    "    PEA     -4(A5)\n"
    "    PEA     -3(A5)\n"
    "    PEA     -2(A5)\n"
    "    PEA     -1(A5)\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  D7,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_NEWGRID_SetSelectionMarkers(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    TST.B   -1(A5)\n"
    "    BEQ.S   DISPTEXT_ComputeMarkerWidths_no_prefix1\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    LEA     -1(A5),A0\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    BRA.S   DISPTEXT_ComputeMarkerWidths_check_prefix2\n"
    "\n"
    "DISPTEXT_ComputeMarkerWidths_no_prefix1:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "DISPTEXT_ComputeMarkerWidths_check_prefix2:\n"
    "    MOVE.L  D0,D5\n"
    "    TST.B   -3(A5)\n"
    "    BEQ.S   DISPTEXT_ComputeMarkerWidths_no_prefix2\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    LEA     -3(A5),A0\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    BRA.S   DISPTEXT_ComputeMarkerWidths_store_combined\n"
    "\n"
    "DISPTEXT_ComputeMarkerWidths_no_prefix2:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "DISPTEXT_ComputeMarkerWidths_store_combined:\n"
    "    MOVE.L  D0,D4\n"
    "    MOVE.L  D5,D0\n"
    "    ADD.L   D4,D0\n"
    "    MOVE.L  D0,DISPTEXT_ControlMarkerWidthPx\n"
    "    MOVEM.L (A7)+,D4-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
