__asm__(
    ".globl _DISPTEXT_SetCurrentLineIndex\n"
    "_DISPTEXT_SetCurrentLineIndex:\n"
    "DISPTEXT_SetCurrentLineIndex:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  8(A7),D7\n"
    "    TST.L   DISPTEXT_LineTableLockFlag\n"
    "    BNE.S   DISPTEXT_SetCurrentLineIndex_return\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BLT.S   DISPTEXT_SetCurrentLineIndex_return\n"
    "\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGT.S   DISPTEXT_SetCurrentLineIndex_return\n"
    "\n"
    "    MOVE.L  D7,-(A7)\n"
    "    BSR.W   DISPLIB_CommitCurrentLinePenAndAdvance\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    "DISPTEXT_SetCurrentLineIndex_return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
