__asm__(
    ".globl _DISPTEXT_ComputeVisibleLineCount\n"
    "_DISPTEXT_ComputeVisibleLineCount:\n"
    "DISPTEXT_ComputeVisibleLineCount:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D5-D7,-(A7)\n"
    "    MOVE.L  8(A5),D7\n"
    "    BSR.W   DISPTEXT_FinalizeLineTable\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D0\n"
    "    CMP.L   D7,D0\n"
    "    BGE.S   DISPTEXT_ComputeVisibleLineCount_line_index_ok\n"
    "\n"
    "    MOVE.L  D7,D1\n"
    "    BRA.S   DISPTEXT_ComputeVisibleLineCount_use_max_lines\n"
    "\n"
    "DISPTEXT_ComputeVisibleLineCount_line_index_ok:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "\n"
    "DISPTEXT_ComputeVisibleLineCount_use_max_lines:\n"
    "    MOVE.L  D1,D6\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  NEWGRID_RowHeightPx,D1\n"
    "    MOVE.L  D6,D0\n"
    "    JSR     GROUP_AG_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    TST.L   D0\n"
    "    BPL.S   DISPTEXT_ComputeVisibleLineCount_add_leading\n"
    "\n"
    "    ADDQ.L  #3,D0\n"
    "\n"
    "DISPTEXT_ComputeVisibleLineCount_add_leading:\n"
    "    ASR.L   #2,D0\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   DISPTEXT_ComputeVisibleLineCount_no_leading\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    BRA.S   DISPTEXT_ComputeVisibleLineCount_apply_leading\n"
    "\n"
    "DISPTEXT_ComputeVisibleLineCount_no_leading:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "DISPTEXT_ComputeVisibleLineCount_apply_leading:\n"
    "    ADD.L   D0,D5\n"
    "    TST.W   DISPTEXT_ControlMarkersEnabledFlag\n"
    "    BEQ.S   DISPTEXT_ComputeVisibleLineCount_return\n"
    "\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     DISPTEXT_TextBufferPtr,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVE.L  A1,-12(A5)\n"
    "    BEQ.S   DISPTEXT_ComputeVisibleLineCount_return\n"
    "\n"
    "    PEA     19.W\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   DISPTEXT_ComputeVisibleLineCount_return\n"
    "\n"
    "    PEA     20.W\n"
    "    MOVE.L  -12(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   DISPTEXT_ComputeVisibleLineCount_return\n"
    "\n"
    "    ADDQ.L  #2,D5\n"
    "\n"
    "DISPTEXT_ComputeVisibleLineCount_return:\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEM.L (A7)+,D5-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
