__asm__(
    ".globl _DISPLIB_FindPreviousValidEntryIndex\n"
    ".globl _DISPLIB_FindPreviousValidEntryIndex_Return\n"
    "_DISPLIB_FindPreviousValidEntryIndex:\n"
    "DISPLIB_FindPreviousValidEntryIndex:\n"
    "    MOVEM.L D5-D7/A2-A3,-(A7)\n"
    "\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVEA.L 28(A7),A2\n"
    "    MOVE.L  32(A7),D7\n"
    "\n"
    "    BTST    #5,27(A3)\n"
    "    BEQ.S   DISPLIB_FindPreviousValidEntryIndex_lab_054D\n"
    "\n"
    "    MOVEQ   #48,D5\n"
    "    BRA.S   DISPLIB_FindPreviousValidEntryIndex_lab_054E\n"
    "\n"
    "DISPLIB_FindPreviousValidEntryIndex_lab_054D:\n"
    "    MOVEQ   #7,D5\n"
    "\n"
    "DISPLIB_FindPreviousValidEntryIndex_lab_054E:\n"
    "    MOVE.L  D7,D6\n"
    "    SUB.L   D5,D6\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.S   DISPLIB_FindPreviousValidEntryIndex_branch\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "\n"
    "DISPLIB_FindPreviousValidEntryIndex_branch:\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    TST.L   56(A2,D0.L)\n"
    "    BNE.S   DISPLIB_FindPreviousValidEntryIndex_Return\n"
    "\n"
    "    SUBQ.L  #1,D7\n"
    "    CMP.L   D6,D7\n"
    "    BGE.S   DISPLIB_FindPreviousValidEntryIndex_branch_1\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "    CLR.W   DISPLIB_PreviousSearchWrappedFlag\n"
    "    BRA.S   DISPLIB_FindPreviousValidEntryIndex_Return\n"
    "\n"
    "DISPLIB_FindPreviousValidEntryIndex_branch_1:\n"
    "    BTST    #5,27(A3)\n"
    "    BNE.S   DISPLIB_FindPreviousValidEntryIndex_branch\n"
    "\n"
    "    MOVE.W  #1,DISPLIB_PreviousSearchWrappedFlag\n"
    "    BRA.S   DISPLIB_FindPreviousValidEntryIndex_branch\n"
    "\n"
    "_DISPLIB_FindPreviousValidEntryIndex_Return:\n"
    "DISPLIB_FindPreviousValidEntryIndex_Return:\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEM.L (A7)+,D5-D7/A2-A3\n"
    "    RTS\n"
);
