__asm__(
    ".globl _DISPTEXT_RenderCurrentLine\n"
    "_DISPTEXT_RenderCurrentLine:\n"
    "DISPTEXT_RenderCurrentLine:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D2-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.L  12(A5),D7\n"
    "    MOVE.L  16(A5),D6\n"
    "    BSR.W   DISPTEXT_FinalizeLineTable\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,DISPTEXT_ControlMarkerXOffsetPx\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D1\n"
    "    TST.L   D1\n"
    "    BLE.W   DISPTEXT_RenderCurrentLine_return\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D1\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D2\n"
    "    CMP.W   D2,D1\n"
    "    BCC.W   DISPTEXT_RenderCurrentLine_return\n"
    "\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D1,D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     DISPTEXT_LinePtrTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D2,A1\n"
    "    TST.L   (A1)\n"
    "    BEQ.W   DISPTEXT_RenderCurrentLine_return\n"
    "\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D1,D2\n"
    "    ASL.L   #2,D2\n"
    "    ADDA.L  D2,A0\n"
    "    MOVE.L  (A0),-6(A5)\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.W  D1,D3\n"
    "    ADD.L   D3,D3\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D3,A0\n"
    "    MOVEQ   #0,D4\n"
    "    MOVE.W  (A0),D4\n"
    "    TST.L   D4\n"
    "    BLE.W   DISPTEXT_RenderCurrentLine_return\n"
    "\n"
    "    LEA     DISPTEXT_LinePenTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  (A0),D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEQ   #0,D0\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVEA.L -6(A5),A0\n"
    "    MOVE.B  0(A0,D4.L),D5\n"
    "    CLR.B   0(A0,D4.L)\n"
    "    TST.W   DISPTEXT_ControlMarkersEnabledFlag\n"
    "    BEQ.S   DISPTEXT_RenderCurrentLine_draw_plain\n"
    "\n"
    "    PEA     19.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   DISPTEXT_RenderCurrentLine_draw_plain\n"
    "\n"
    "    PEA     20.W\n"
    "    MOVE.L  -6(A5),-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   DISPTEXT_RenderCurrentLine_draw_plain\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  DISPTEXT_InsetNibbleSecondary,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  DISPTEXT_InsetNibblePrimary,D1\n"
    "    MOVE.L  -6(A5),-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_TLIBA1_DrawTextWithInsetSegments(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    MOVEQ   #4,D0\n"
    "    MOVE.L  D0,DISPTEXT_ControlMarkerXOffsetPx\n"
    "    BRA.S   DISPTEXT_RenderCurrentLine_restore_char\n"
    "\n"
    "DISPTEXT_RenderCurrentLine_draw_plain:\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D7,D0\n"
    "    MOVE.L  D6,D1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVE.L  D4,D0\n"
    "    MOVEA.L -6(A5),A0\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    "DISPTEXT_RenderCurrentLine_restore_char:\n"
    "    MOVEA.L -6(A5),A0\n"
    "    MOVE.B  D5,0(A0,D4.L)\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADDQ.W  #1,D0\n"
    "    MOVE.W  D0,DISPTEXT_CurrentLineIndex\n"
    "\n"
    "DISPTEXT_RenderCurrentLine_return:\n"
    "    MOVEM.L (A7)+,D2-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
