__asm__(
    ".globl _DISPLIB_CommitCurrentLinePenAndAdvance\n"
    "_DISPLIB_CommitCurrentLinePenAndAdvance:\n"
    "DISPLIB_CommitCurrentLinePenAndAdvance:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  8(A7),D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    TST.W   (A0)\n"
    "    BEQ.S   .lab_0568\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.L  D0,D1\n"
    "    ADDQ.W  #1,D1\n"
    "    MOVE.W  D1,DISPTEXT_CurrentLineIndex\n"
    "\n"
    ".lab_0568:\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   .lab_0569\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     DISPTEXT_LinePenTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  D7,(A0)\n"
    "\n"
    ".lab_0569:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
