__asm__(
    ".globl _DISPTEXT_FreeBuffers\n"
    "_DISPTEXT_FreeBuffers:\n"
    "DISPTEXT_FreeBuffers:\n"
    "    BSR.W   DISPLIB_ResetTextBufferAndLineTables\n"
    "\n"
    "    TST.L   Global_REF_1000_BYTES_ALLOCATED_1\n"
    "    BEQ.S   DISPTEXT_FreeBuffers_freeSecondBlock\n"
    "\n"
    "    PEA     1000.W\n"
    "    MOVE.L  Global_REF_1000_BYTES_ALLOCATED_1,-(A7)\n"
    "    PEA     338.W\n"
    "    PEA     Global_STR_DISPTEXT_C_4\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    CLR.L   Global_REF_1000_BYTES_ALLOCATED_1\n"
    "\n"
    "DISPTEXT_FreeBuffers_freeSecondBlock:\n"
    "    TST.L   Global_REF_1000_BYTES_ALLOCATED_2\n"
    "    BEQ.S   DISPTEXT_FreeBuffers_return\n"
    "\n"
    "    PEA     1000.W\n"
    "    MOVE.L  Global_REF_1000_BYTES_ALLOCATED_2,-(A7)\n"
    "    PEA     343.W\n"
    "    PEA     Global_STR_DISPTEXT_C_5\n"
    "    JSR     GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    CLR.L   Global_REF_1000_BYTES_ALLOCATED_2\n"
    "\n"
    "DISPTEXT_FreeBuffers_return:\n"
    "    RTS\n"
);
