__asm__(
    ".globl _DISPTEXT_LayoutAndAppendToBuffer\n"
    "_DISPTEXT_LayoutAndAppendToBuffer:\n"
    "DISPTEXT_LayoutAndAppendToBuffer:\n"
    "    LINK.W  A5,#-276\n"
    "    MOVEM.L D2/D5-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    TST.L   DISPTEXT_LineTableLockFlag\n"
    "    BNE.W   DISPTEXT_LayoutAndAppendToBuffer_return_status\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.W   DISPTEXT_LayoutAndAppendToBuffer_return_status\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ADD.L   D1,D1\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    TST.W   (A1)\n"
    "    BEQ.S   DISPTEXT_LayoutAndAppendToBuffer_no_prefix_line\n"
    "\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D0,D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     DISPTEXT_LinePtrTable,A1\n"
    "    ADDA.L  D2,A1\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  (A0),D0\n"
    "    MOVE.L  A1,28(A7)\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEA.L 28(A7),A0\n"
    "    MOVEA.L (A0),A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D1\n"
    "    MOVE.L  D1,D2\n"
    "    SUB.L   D0,D2\n"
    "    MOVE.L  D2,D7\n"
    "    BRA.S   DISPTEXT_LayoutAndAppendToBuffer_adjust_for_prefix\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_no_prefix_line:\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D7\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_adjust_for_prefix:\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   DISPTEXT_LayoutAndAppendToBuffer_init_scratch\n"
    "\n"
    "    SUB.L   DISPTEXT_ControlMarkerWidthPx,D7\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_init_scratch:\n"
    "    MOVEA.L Global_REF_1000_BYTES_ALLOCATED_2,A0\n"
    "    CLR.B   (A0)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_LineLengthTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    TST.W   (A1)\n"
    "    BEQ.S   DISPTEXT_LayoutAndAppendToBuffer_line_loop\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    LEA     DISPTEXT_STR_SINGLE_SPACE_PREFIX_2,A0\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "    CMP.L   D6,D7\n"
    "    BLE.S   DISPTEXT_LayoutAndAppendToBuffer_fallback_layout\n"
    "\n"
    "    LEA     DISPTEXT_STR_SINGLE_SPACE_COPY_PREFIX,A0\n"
    "    MOVEA.L Global_REF_1000_BYTES_ALLOCATED_2,A1\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_copy_prefix:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   DISPTEXT_LayoutAndAppendToBuffer_copy_prefix\n"
    "\n"
    "    SUB.L   D6,D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    ADDQ.W  #1,(A0)\n"
    "    BRA.S   DISPTEXT_LayoutAndAppendToBuffer_line_loop\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_fallback_layout:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     DISPTEXT_LinePenTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    BSR.W   DISPLIB_CommitCurrentLinePenAndAdvance\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   DISPTEXT_LayoutAndAppendToBuffer_line_loop\n"
    "\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D7\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_line_loop:\n"
    "    MOVE.L  A2,D0\n"
    "    BEQ.W   DISPTEXT_LayoutAndAppendToBuffer_flush_remaining\n"
    "\n"
    "    TST.B   (A2)\n"
    "    BEQ.W   DISPTEXT_LayoutAndAppendToBuffer_flush_remaining\n"
    "\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVE.W  DISPTEXT_TargetLineIndex,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.W   DISPTEXT_LayoutAndAppendToBuffer_flush_remaining\n"
    "\n"
    "    MOVE.L  D7,-(A7)\n"
    "    PEA     -268(A5)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   DISPTEXT_BuildLineWithWidth\n"
    "\n"
    "    MOVEA.L D0,A2\n"
    "    LEA     -268(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_append_scratch:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   DISPTEXT_LayoutAndAppendToBuffer_append_scratch\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D5\n"
    "    MOVE.L  A0,(A7)\n"
    "    MOVE.L  Global_REF_1000_BYTES_ALLOCATED_2,-(A7)\n"
    "    JSR     GROUP_AI_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    ADD.L   D0,D0\n"
    "    LEA     DISPTEXT_LineLengthTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  (A0),D0\n"
    "    MOVE.L  D0,D1\n"
    "    ADD.L   D5,D1\n"
    "    MOVE.W  D1,(A0)\n"
    "    MOVE.L  DISPTEXT_LineWidthPx,D7\n"
    "    MOVE.W  DISPTEXT_CurrentLineIndex,D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   DISPTEXT_LayoutAndAppendToBuffer_after_append\n"
    "\n"
    "    SUB.L   DISPTEXT_ControlMarkerWidthPx,D7\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_after_append:\n"
    "    MOVE.L  A2,D1\n"
    "    BEQ.W   DISPTEXT_LayoutAndAppendToBuffer_line_loop\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     DISPTEXT_LinePenTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    BSR.W   DISPLIB_CommitCurrentLinePenAndAdvance\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    BRA.W   DISPTEXT_LayoutAndAppendToBuffer_line_loop\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_flush_remaining:\n"
    "    MOVEA.L Global_REF_1000_BYTES_ALLOCATED_2,A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.S   DISPTEXT_LayoutAndAppendToBuffer_return_status\n"
    "\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   DISPTEXT_AppendToBuffer\n"
    "\n"
    "    CLR.L   (A7)\n"
    "    BSR.W   DISPTEXT_BuildLinePointerTable\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    "DISPTEXT_LayoutAndAppendToBuffer_return_status:\n"
    "    MOVE.L  A2,D1\n"
    "    SEQ     D0\n"
    "    NEG.B   D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEM.L (A7)+,D2/D5-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
