__asm__(
    ".globl _ESQ_CaptureCtrlBit3Stream\n"
    "_ESQ_CaptureCtrlBit3Stream:\n"
    "    tst.w   _CTRL_Bit3CapturePhase\n"
    "    bne.s   .advance_state\n"
    "    jsr     _GET_BIT_3_OF_CIAB_PRA_INTO_D1\n"
    "    tst.b   %d1\n"
    "    bpl.w   .return\n"
    "    addq.w  #1,_CTRL_Bit3CapturePhase\n"
    "    move.w  #4,_CTRL_Bit3CaptureDelayCounter\n"
    "    move.w  #0,_CTRL_Bit3SampleSlotIndex\n"
    "    rts\n"
    ".advance_state:\n"
    "    move.w  _CTRL_Bit3CapturePhase,%d0\n"
    "    addq.w  #1,%d0\n"
    "    move.w  %d0,_CTRL_Bit3CapturePhase\n"
    "    move.w  _CTRL_Bit3CaptureDelayCounter,%d1\n"
    "    cmp.w   %d0,%d1\n"
    "    bgt.w   .return\n"
    "    moveq   #4,%d1\n"
    "    cmp.w   %d1,%d0\n"
    "    bgt.w   .collect_samples\n"
    "    jsr     _GET_BIT_3_OF_CIAB_PRA_INTO_D1\n"
    "    tst.b   %d1\n"
    "    bpl.s   .reset_state\n"
    "    move.w  #14,_CTRL_Bit3CaptureDelayCounter\n"
    "    moveq   #7,%d0\n"
    "    lea     _CTRL_Bit3SampleScratch,%a5\n"
    "    moveq   #0,%d1\n"
    ".clear_sample_buffer_loop:\n"
    "    move.b  %d1,(%a5)+\n"
    "    dbf     %d0,.clear_sample_buffer_loop\n"
    "    rts\n"
    ".reset_state:\n"
    "    moveq   #0,%d0\n"
    "    move.w  %d0,_CTRL_Bit3CaptureDelayCounter\n"
    "    move.w  %d0,_CTRL_Bit3SampleSlotIndex\n"
    "    move.w  %d0,_CTRL_Bit3CapturePhase\n"
    "    rts\n"
    ".collect_samples:\n"
    "    moveq   #94,%d1\n"
    "    cmp.w   %d1,%d0\n"
    "    bge.s   .assemble_and_store\n"
    "    jsr     _GET_BIT_3_OF_CIAB_PRA_INTO_D1\n"
    "    lea     _CTRL_Bit3SampleScratch,%a5\n"
    "    adda.w  _CTRL_Bit3SampleSlotIndex,%a5\n"
    "    move.b  %d1,(%a5)\n"
    "    addq.w  #1,_CTRL_Bit3SampleSlotIndex\n"
    "    addi.w  #10,_CTRL_Bit3CaptureDelayCounter\n"
    "    rts\n"
    ".assemble_and_store:\n"
    "    jsr     _GET_BIT_3_OF_CIAB_PRA_INTO_D1\n"
    "    tst.b   %d1\n"
    "    bmi.s   .reset_state_and_exit\n"
    "    lea     _CTRL_Bit3SampleScratch,%a5\n"
    "    adda.w  _CTRL_Bit3SampleSlotIndex,%a5\n"
    "    move.w  _CTRL_Bit3SampleSlotIndex,%d1\n"
    "    subq.w  #1,%d1\n"
    "    moveq   #0,%d0\n"
    ".build_byte_loop:\n"
    "    tst.b   -(%a5)\n"
    "    bmi.s   .clear_bit\n"
    "    bset    %d1,%d0\n"
    "    bra.s   .next_bit\n"
    ".clear_bit:\n"
    "    bclr    %d1,%d0\n"
    ".next_bit:\n"
    "    dbf     %d1,.build_byte_loop\n"
    "    lea     _CTRL_SampleEntryScratch,%a1\n"
    "    move.w  _CTRL_SampleEntryCount,%d1\n"
    "    adda.w  %d1,%a1\n"
    "    move.b  %d0,(%a1)\n"
    "    beq.s   .flush_on_zero\n"
    "    addq.w  #1,%d1\n"
    "    cmpi.w  #5,%d1\n"
    "    blt.s   .store_index\n"
    "    move.b  #0,(%a1)\n"
    ".flush_on_zero:\n"
    "    jsr     _ESQ_StoreCtrlSampleEntry\n"
    "    moveq   #0,%d1\n"
    ".store_index:\n"
    "    move.w  %d1,_CTRL_SampleEntryCount\n"
    ".reset_state_and_exit:\n"
    "    moveq   #0,%d0\n"
    "    move.w  %d0,_CTRL_Bit3CaptureDelayCounter\n"
    "    move.w  %d0,_CTRL_Bit3SampleSlotIndex\n"
    "    move.w  %d0,_CTRL_Bit3CapturePhase\n"
    ".return:\n"
    "    rts\n");
