__asm__(
    ".globl _ESQDISP_GetEntryAuxPointerByMode\n"
    "_ESQDISP_GetEntryAuxPointerByMode:\n"
    "ESQDISP_GetEntryAuxPointerByMode:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D6-D7,-(A7)\n"
    "    MOVE.L  8(A5),D7\n"
    "    MOVE.L  12(A5),D6\n"
    "    CLR.L   -4(A5)\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   ESQDISP_GetEntryAuxPointerByMode_lab_0927\n"
    "\n"
    "    TST.L   D7\n"
    "    BMI.S   ESQDISP_GetEntryAuxPointerByMode_return\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   ESQDISP_GetEntryAuxPointerByMode_return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    BRA.S   ESQDISP_GetEntryAuxPointerByMode_return\n"
    "\n"
    "ESQDISP_GetEntryAuxPointerByMode_lab_0927:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   ESQDISP_GetEntryAuxPointerByMode_return\n"
    "\n"
    "    TST.L   D7\n"
    "    BMI.S   ESQDISP_GetEntryAuxPointerByMode_return\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   ESQDISP_GetEntryAuxPointerByMode_return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVE.L  A1,-4(A5)\n"
    "\n"
    "ESQDISP_GetEntryAuxPointerByMode_return:\n"
    "    MOVE.L  -4(A5),D0\n"
    "    MOVEM.L (A7)+,D6-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
