__asm__(
    ".globl _ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty\n"
    ".globl _ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty_Return\n"
    "_ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty:\n"
    "ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D2-D3/D7/A2-A3/A6,-(A7)\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    BNE.W   .mark_no_mirror_needed\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_primary_entries_for_mirror:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.W   .set_mirror_performed_flag\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  27(A0),D1\n"
    "    LEA     12(A0),A1\n"
    "    LEA     1(A0),A2\n"
    "    LEA     28(A0),A3\n"
    "    LEA     19(A0),A6\n"
    "    MOVE.L  A6,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQSHARED_CreateGroupEntryAndTitle\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTablePreSlot,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  40(A0),D0\n"
    "    ANDI.W  #$ff7f,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  46(A0),D0\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.B  41(A0),D2\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.B  42(A0),D3\n"
    "    LEA     43(A0),A2\n"
    "    MOVE.L  A2,(A7)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A1,-8(A5)\n"
    "    BSR.W   ESQDISP_FillProgramInfoHeaderFields\n"
    "\n"
    "    LEA     44(A7),A7\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.W   .loop_primary_entries_for_mirror\n"
    "\n"
    ".set_mirror_performed_flag:\n"
    "    MOVE.W  #1,ESQDISP_PrimarySecondaryMirrorFlag\n"
    "    BRA.S   ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty_Return\n"
    "\n"
    ".mark_no_mirror_needed:\n"
    "    CLR.W   ESQDISP_PrimarySecondaryMirrorFlag\n"
    "\n"
    "_ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty_Return:\n"
    "ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty_Return:\n"
    "    MOVEM.L (A7)+,D2-D3/D7/A2-A3/A6\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
