__asm__(
    ".globl _ESQDISP_QueueHighlightDrawMessage\n"
    "_ESQDISP_QueueHighlightDrawMessage:\n"
    "ESQDISP_QueueHighlightDrawMessage:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "\n"
    "    MOVE.B  #$5,8(A3)\n"
    "    MOVE.W  #$a0,18(A3)\n"
    "    MOVE.L  ESQ_HighlightReplyPort,14(A3)\n"
    "    MOVE.L  8(A2),20(A3)\n"
    "    MOVE.L  12(A2),24(A3)\n"
    "    MOVE.L  16(A2),28(A3)\n"
    "    CLR.W   52(A3)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_NEWGRID_ValidateSelectionCode\n"
    "\n"
    "    CLR.L   32(A3)\n"
    "    MOVE.L  A3,(A7)\n"
    "    BSR.S   ESQDISP_InitHighlightMessagePattern\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    LEA     60(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOInitRastPort(A6)\n"
    "\n"
    "    MOVE.L  A2,64(A3)\n"
    "    LEA     60(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L Global_HANDLE_PREVUEC_FONT,A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetFont(A6)\n"
    "\n"
    "    LEA     60(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVE.L  112(A3),-4(A5)\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  #$1,55(A0)\n"
    "    BSET    #0,53(A0)\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEA.L ESQ_HighlightMsgPort,A0\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOPutMsg(A6)\n"
    "\n"
    "    MOVEM.L (A7)+,A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
