__asm__(
    ".globl _ESQDISP_ComputeScheduleOffsetForRow\n"
    "_ESQDISP_ComputeScheduleOffsetForRow:\n"
    "ESQDISP_ComputeScheduleOffsetForRow:\n"
    "    MOVEM.L D5-D7,-(A7)\n"
    "    MOVE.W  18(A7),D7\n"
    "    MOVE.B  23(A7),D6\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D6,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     DST_BuildBannerTimeWord(PC)\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.L  D0,D5\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    PEA     48.W\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     DISPLIB_NormalizeValueByStep(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEM.L (A7)+,D5-D7\n"
    "    RTS\n"
);
