__asm__(
    ".globl _ESQDISP_AllocateHighlightBitmaps\n"
    ".globl _ESQDISP_AllocateHighlightBitmaps_Return\n"
    "_ESQDISP_AllocateHighlightBitmaps:\n"
    "ESQDISP_AllocateHighlightBitmaps:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D2/D7/A3,-(A7)\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  WDISP_HighlightRasterHeightPx,D0\n"
    "    MOVEA.L A3,A0\n"
    "    MOVE.L  D0,D2\n"
    "    MOVEQ   #3,D0\n"
    "    MOVE.L  #696,D1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOInitBitMap(A6)\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".alloc_plane_loop:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   ESQDISP_AllocateHighlightBitmaps_Return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEQ   #0,D1\n"
    "\n"
    "    MOVE.W  WDISP_HighlightRasterHeightPx,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    PEA     696.W\n"
    "    PEA     79.W\n"
    "    PEA     Global_STR_ESQDISP_C\n"
    "    MOVE.L  D0,28(A7)\n"
    "    JSR     ESQDISP_JMPTBL_GRAPHICS_AllocRaster\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  12(A7),D1\n"
    "    MOVE.L  D0,8(A3,D1.L)\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVE.W  WDISP_HighlightRasterHeightPx,D1\n"
    "    MULU    #$58,D1\n"
    "    MOVE.L  D0,12(A7)\n"
    "    MOVE.L  D1,D0\n"
    "    MOVE.L  12(A7),D2\n"
    "    MOVEA.L 8(A3,D2.L),A1\n"
    "    MOVEQ   #0,D1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOBltClear(A6)\n"
    "\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .alloc_plane_loop\n"
    "\n"
    "_ESQDISP_AllocateHighlightBitmaps_Return:\n"
    "ESQDISP_AllocateHighlightBitmaps_Return:\n"
    "    MOVEM.L (A7)+,D2/D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
