__asm__(
    ".globl _ESQDISP_InitHighlightMessagePattern\n"
    ".globl _ESQDISP_InitHighlightMessagePattern_Return\n"
    "_ESQDISP_InitHighlightMessagePattern:\n"
    "ESQDISP_InitHighlightMessagePattern:\n"
    "    MOVEM.L D7/A3,-(A7)\n"
    "    MOVEA.L 12(A7),A3\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".init_pattern_loop:\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   ESQDISP_InitHighlightMessagePattern_Return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ADDQ.L  #4,D0\n"
    "    MOVE.B  D0,55(A3,D7.L)\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .init_pattern_loop\n"
    "\n"
    "_ESQDISP_InitHighlightMessagePattern_Return:\n"
    "ESQDISP_InitHighlightMessagePattern_Return:\n"
    "    MOVEM.L (A7)+,D7/A3\n"
    "    RTS\n"
);
