__asm__(
    ".globl _ESQDISP_PromoteSecondaryGroupToPrimary\n"
    "_ESQDISP_PromoteSecondaryGroupToPrimary:\n"
    "ESQDISP_PromoteSecondaryGroupToPrimary:\n"
    "    MOVEM.L D7/A2-A3,-(A7)\n"
    "    PEA     1.W\n"
    "    JSR     ESQPARS_RemoveGroupEntryAndReleaseStrings(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,NEWGRID_RefreshStateFlag\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,TEXTDISP_GroupMutationState\n"
    "    CLR.B   TEXTDISP_PrimaryGroupRecordChecksum\n"
    "    MOVE.W  D0,TEXTDISP_PrimaryGroupRecordLength\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    SUBQ.B  #1,D1\n"
    "    BNE.W   .sync_task_state_and_reindex\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "\n"
    ".loop_move_secondary_slots:\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .copy_secondary_group_metadata\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    MOVE.L  (A2),(A0)\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A2\n"
    "    MOVEA.L A2,A3\n"
    "    ADDA.L  D0,A3\n"
    "    MOVE.L  (A3),(A0)\n"
    "    ADDA.L  D0,A1\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,(A1)\n"
    "    ADDA.L  D0,A2\n"
    "    MOVE.L  A0,(A2)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .loop_move_secondary_slots\n"
    "\n"
    ".copy_secondary_group_metadata:\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,TEXTDISP_PrimaryGroupEntryCount\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupRecordChecksum,TEXTDISP_PrimaryGroupRecordChecksum\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupHeaderCode,TEXTDISP_PrimaryGroupHeaderCode\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupRecordLength,TEXTDISP_PrimaryGroupRecordLength\n"
    "    MOVE.B  #$1,TEXTDISP_PrimaryGroupPresentFlag\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,TEXTDISP_SecondaryGroupEntryCount\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D1,TEXTDISP_SecondaryGroupRecordChecksum\n"
    "    MOVE.W  D0,TEXTDISP_SecondaryGroupRecordLength\n"
    "    MOVE.B  D1,TEXTDISP_SecondaryGroupPresentFlag\n"
    "    MOVE.W  #3,TEXTDISP_GroupMutationState\n"
    "\n"
    ".sync_task_state_and_reindex:\n"
    "    MOVE.B  CTASKS_PendingSecondaryOiDiskId,CTASKS_PendingPrimaryOiDiskId\n"
    "    MOVE.B  CTASKS_SecondaryOiWritePendingFlag,CTASKS_PrimaryOiWritePendingFlag\n"
    "    MOVE.B  #$ff,CTASKS_PendingSecondaryOiDiskId\n"
    "    CLR.B   CTASKS_SecondaryOiWritePendingFlag\n"
    "    JSR     ESQPARS_JMPTBL_NEWGRID_RebuildIndexCache(PC)\n"
    "\n"
    "    MOVEM.L (A7)+,D7/A2-A3\n"
    "    RTS\n"
);
