__asm__(
    ".globl _ESQDISP_PollInputModeAndRefreshSelection\n"
    "_ESQDISP_PollInputModeAndRefreshSelection:\n"
    "ESQDISP_PollInputModeAndRefreshSelection:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.W  #(-1),Global_RefreshTickCounter\n"
    "    MOVE.L  #$bfd0ee,-6(A5)\n"
    "    MOVEQ   #4,D7\n"
    "    MOVEA.L -6(A5),A0\n"
    "    AND.B   (A0),D7\n"
    "    MOVE.B  ESQDISP_LatchedInputModeBit,D0\n"
    "    CMP.B   D7,D0\n"
    "    BEQ.S   .lab_092D\n"
    "\n"
    "    ADDQ.L  #1,ESQDISP_InputModeDebounceCount\n"
    "    BRA.S   .lab_092E\n"
    "\n"
    ".lab_092D:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,ESQDISP_InputModeDebounceCount\n"
    "\n"
    ".lab_092E:\n"
    "    CMPI.L  #$5,ESQDISP_InputModeDebounceCount\n"
    "    BLE.S   .return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    MOVE.B  D0,ESQDISP_LatchedInputModeBit\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.L  D1,ESQDISP_InputModeDebounceCount\n"
    "    TST.B   D0\n"
    "    BNE.S   .lab_092F\n"
    "\n"
    "    MOVE.L  D1,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TEXTDISP_SetRastForMode\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".lab_092F:\n"
    "    JSR     ESQFUNC_JMPTBL_TEXTDISP_ResetSelectionAndRefresh\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
