__asm__(
    ".globl _ESQDISP_TestEntryBits0And2\n"
    ".globl _ESQDISP_TestEntryBits0And2_Core\n"
    "_ESQDISP_TestEntryBits0And2:\n"
    "ESQDISP_TestEntryBits0And2:\n"
    "_ESQDISP_TestEntryBits0And2_Core:\n"
    "ESQDISP_TestEntryBits0And2_Core:\n"
    "    MOVEM.L D7/A3,-(A7)\n"
    "    MOVEA.L 12(A7),A3\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   ESQDISP_TestEntryBits0And2_return\n"
    "\n"
    "    BTST    #0,40(A3)\n"
    "    BEQ.S   ESQDISP_TestEntryBits0And2_bits_not_set\n"
    "\n"
    "    BTST    #2,40(A3)\n"
    "    BEQ.S   ESQDISP_TestEntryBits0And2_bits_not_set\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   ESQDISP_TestEntryBits0And2_store_result\n"
    "\n"
    "ESQDISP_TestEntryBits0And2_bits_not_set:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "ESQDISP_TestEntryBits0And2_store_result:\n"
    "    MOVE.L  D0,D7\n"
    "\n"
    "ESQDISP_TestEntryBits0And2_return:\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEM.L (A7)+,D7/A3\n"
    "    RTS\n"
);
