__asm__(
    ".globl _ESQDISP_ParseProgramInfoCommandRecord\n"
    ".globl _ESQDISP_ParseProgramInfoCommandRecord_Return\n"
    "_ESQDISP_ParseProgramInfoCommandRecord:\n"
    "ESQDISP_ParseProgramInfoCommandRecord:\n"
    "    LINK.W  A5,#-40\n"
    "    MOVEM.L D2-D3/D5-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEQ   #0,D6\n"
    "    MOVE.B  (A3)+,D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "    AND.L   D1,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    MOVE.L  D0,-16(A5)\n"
    "    CMP.L   D0,D1\n"
    "    BNE.S   .lab_08E5\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    SUBQ.B  #1,D1\n"
    "    BNE.S   .lab_08E5\n"
    "\n"
    "    MOVEQ   #0,D6\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D6\n"
    "    MOVE.L  #TEXTDISP_SecondaryEntryPtrTable,-40(A5)\n"
    "    BRA.S   .lab_08E6\n"
    "\n"
    ".lab_08E5:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .lab_08E6\n"
    "\n"
    "    MOVEQ   #0,D6\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D6\n"
    "    MOVE.L  #TEXTDISP_PrimaryEntryPtrTable,-40(A5)\n"
    "\n"
    ".lab_08E6:\n"
    "    MOVE.B  (A3),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #2,(A1)\n"
    "    BEQ.S   .lab_08E7\n"
    "\n"
    "    MOVE.B  (A3),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     ESQIFF_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    BRA.S   .lab_08E8\n"
    "\n"
    ".lab_08E7:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".lab_08E8:\n"
    "    MOVE.L  D0,D5\n"
    "    ADDQ.L  #1,A3\n"
    "    MOVE.B  (A3),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    ADDA.L  D0,A0\n"
    "    BTST    #2,(A0)\n"
    "    BEQ.S   .lab_08E9\n"
    "\n"
    "    MOVE.B  (A3),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .lab_08EA\n"
    "\n"
    ".lab_08E9:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".lab_08EA:\n"
    "    ADD.L   D0,D5\n"
    "    ADDQ.L  #1,A3\n"
    "    TST.L   D6\n"
    "    BLE.W   ESQDISP_ParseProgramInfoCommandRecord_Return\n"
    "\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLT.W   ESQDISP_ParseProgramInfoCommandRecord_Return\n"
    "\n"
    "    CLR.B   -25(A5)\n"
    "\n"
    ".lab_08EB:\n"
    "    MOVEQ   #18,D0\n"
    "    CMP.B   (A3),D0\n"
    "    BNE.W   ESQDISP_ParseProgramInfoCommandRecord_Return\n"
    "\n"
    "    ADDQ.L  #1,A3\n"
    "    MOVE.L  A3,-20(A5)\n"
    "    CLR.L   -24(A5)\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".lab_08EC:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.S   .lab_08EE\n"
    "\n"
    "    ADDQ.L  #1,A3\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.B   (A3),D0\n"
    "    BNE.S   .lab_08ED\n"
    "\n"
    "    CLR.B   (A3)+\n"
    "    MOVE.L  A3,-24(A5)\n"
    "    ADDA.L  D5,A3\n"
    "    BRA.S   .lab_08EE\n"
    "\n"
    ".lab_08ED:\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.S   .lab_08EC\n"
    "\n"
    ".lab_08EE:\n"
    "    TST.L   -24(A5)\n"
    "    BEQ.S   .lab_08EB\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".branch:\n"
    "    CMP.L   D6,D7\n"
    "    BGE.S   .lab_08EB\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -40(A5),A0\n"
    "    MOVEA.L 0(A0,D0.L),A0\n"
    "    LEA     12(A0),A1\n"
    "    MOVEA.L -20(A5),A0\n"
    "\n"
    ".lab_08F0:\n"
    "    MOVE.B  (A1)+,D0\n"
    "    CMP.B   (A0)+,D0\n"
    "    BNE.W   .lab_0918\n"
    "\n"
    "    TST.B   D0\n"
    "    BNE.S   .lab_08F0\n"
    "\n"
    "    BNE.W   .lab_0918\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -40(A5),A0\n"
    "    MOVE.L  0(A0,D0.L),-36(A5)\n"
    "    MOVEA.L -36(A5),A0\n"
    "    MOVE.B  40(A0),D0\n"
    "    MOVE.W  46(A0),-32(A5)\n"
    "    MOVE.B  D0,-28(A5)\n"
    "    TST.L   D5\n"
    "    BLE.S   .lab_08F4\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  (A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    BTST    #1,(A2)\n"
    "    BEQ.S   .lab_08F1\n"
    "\n"
    "    MOVE.B  (A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .lab_08F2\n"
    "\n"
    ".lab_08F1:\n"
    "    MOVE.B  (A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".lab_08F2:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .lab_08F3\n"
    "\n"
    "    BSET    #1,-28(A5)\n"
    "    BRA.S   .lab_08F4\n"
    "\n"
    ".lab_08F3:\n"
    "    BCLR    #1,-28(A5)\n"
    "\n"
    ".lab_08F4:\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .lab_08F8\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  1(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    BTST    #1,(A2)\n"
    "    BEQ.S   .lab_08F5\n"
    "\n"
    "    MOVE.B  1(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .lab_08F6\n"
    "\n"
    ".lab_08F5:\n"
    "    MOVE.B  1(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".lab_08F6:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .lab_08F7\n"
    "\n"
    "    BSET    #2,-28(A5)\n"
    "    BRA.S   .lab_08F8\n"
    "\n"
    ".lab_08F7:\n"
    "    BCLR    #2,-28(A5)\n"
    "\n"
    ".lab_08F8:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .lab_08F9\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  2(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #7,(A1)\n"
    "    BEQ.S   .lab_08F9\n"
    "\n"
    "    MOVE.B  2(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_LADFUNC_ParseHexDigit(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    BRA.S   .lab_08FA\n"
    "\n"
    ".lab_08F9:\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "\n"
    ".lab_08FA:\n"
    "    MOVE.B  D1,-29(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    CMP.B   D0,D1\n"
    "    BCS.S   .lab_08FB\n"
    "\n"
    "    MOVEQ   #15,D0\n"
    "    CMP.B   D0,D1\n"
    "    BLS.S   .lab_08FC\n"
    "\n"
    ".lab_08FB:\n"
    "    MOVE.B  #$ff,-29(A5)\n"
    "\n"
    ".lab_08FC:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .lab_08FD\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  3(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #7,(A1)\n"
    "    BEQ.S   .lab_08FD\n"
    "\n"
    "    MOVE.B  3(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_LADFUNC_ParseHexDigit(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    BRA.S   .lab_08FE\n"
    "\n"
    ".lab_08FD:\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "\n"
    ".lab_08FE:\n"
    "    MOVE.B  D1,-30(A5)\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.B   D0,D1\n"
    "    BCS.S   .lab_08FF\n"
    "\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.B   D0,D1\n"
    "    BLS.S   .branch_1\n"
    "\n"
    ".lab_08FF:\n"
    "    MOVE.B  #$ff,-30(A5)\n"
    "\n"
    ".branch_1:\n"
    "    MOVEQ   #5,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .branch_2\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    ADDQ.L  #4,A0\n"
    "    PEA     2.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    PEA     -27(A5)\n"
    "    JSR     ESQFUNC_JMPTBL_STRING_CopyPadNul(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .branch_4\n"
    "\n"
    ".branch_2:\n"
    "    LEA     ESQDISP_ProgramInfoZeroTag,A0\n"
    "    LEA     -27(A5),A1\n"
    "\n"
    ".branch_3:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .branch_3\n"
    "\n"
    ".branch_4:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .branch_8\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    BTST    #1,(A2)\n"
    "    BEQ.S   .branch_5\n"
    "\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .branch_6\n"
    "\n"
    ".branch_5:\n"
    "    MOVE.B  6(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".branch_6:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .branch_7\n"
    "\n"
    "    BSET    #0,-31(A5)\n"
    "    BRA.S   .branch_8\n"
    "\n"
    ".branch_7:\n"
    "    BCLR    #0,-31(A5)\n"
    "\n"
    ".branch_8:\n"
    "    MOVEQ   #7,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .branch_12\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    BTST    #1,(A2)\n"
    "    BEQ.S   .branch_9\n"
    "\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .branch_10\n"
    "\n"
    ".branch_9:\n"
    "    MOVE.B  7(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".branch_10:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .branch_11\n"
    "\n"
    "    BSET    #1,-31(A5)\n"
    "    BRA.S   .branch_12\n"
    "\n"
    ".branch_11:\n"
    "    BCLR    #1,-31(A5)\n"
    "\n"
    ".branch_12:\n"
    "    MOVEQ   #8,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .branch_16\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  8(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    BTST    #1,(A2)\n"
    "    BEQ.S   .branch_13\n"
    "\n"
    "    MOVE.B  8(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .branch_14\n"
    "\n"
    ".branch_13:\n"
    "    MOVE.B  8(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".branch_14:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .branch_15\n"
    "\n"
    "    BSET    #2,-31(A5)\n"
    "    BRA.S   .branch_16\n"
    "\n"
    ".branch_15:\n"
    "    BCLR    #2,-31(A5)\n"
    "\n"
    ".branch_16:\n"
    "    MOVEQ   #9,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .branch_20\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  9(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D0,A2\n"
    "    BTST    #1,(A2)\n"
    "    BEQ.S   .branch_17\n"
    "\n"
    "    MOVE.B  9(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .branch_18\n"
    "\n"
    ".branch_17:\n"
    "    MOVE.B  9(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".branch_18:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .branch_19\n"
    "\n"
    "    BSET    #3,-31(A5)\n"
    "    BRA.S   .branch_20\n"
    "\n"
    ".branch_19:\n"
    "    BCLR    #3,-31(A5)\n"
    "\n"
    ".branch_20:\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .branch_24\n"
    "\n"
    "    MOVEA.L -24(A5),A0\n"
    "    MOVE.B  10(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #1,(A1)\n"
    "    BEQ.S   .branch_21\n"
    "\n"
    "    MOVE.B  10(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    SUB.L   D1,D0\n"
    "    BRA.S   .branch_22\n"
    "\n"
    ".branch_21:\n"
    "    MOVE.B  10(A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "\n"
    ".branch_22:\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.L   D1,D0\n"
    "    BNE.S   .branch_23\n"
    "\n"
    "    BSET    #4,-31(A5)\n"
    "    BRA.S   .branch_24\n"
    "\n"
    ".branch_23:\n"
    "    BCLR    #4,-31(A5)\n"
    "\n"
    ".branch_24:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  -28(A5),D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  -32(A5),D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.B  -29(A5),D2\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.B  -30(A5),D3\n"
    "    PEA     -27(A5)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  -36(A5),-(A7)\n"
    "    BSR.W   ESQDISP_FillProgramInfoHeaderFields\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "\n"
    ".lab_0918:\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.W   .branch\n"
    "\n"
    "_ESQDISP_ParseProgramInfoCommandRecord_Return:\n"
    "ESQDISP_ParseProgramInfoCommandRecord_Return:\n"
    "    MOVEM.L (A7)+,D2-D3/D5-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
