__asm__(
    ".globl _ESQDISP_DrawStatusBanner\n"
    ".globl _ESQDISP_DrawStatusBanner_Impl\n"
    ".globl _ESQDISP_DrawStatusBanner_Impl_Return\n"
    "_ESQDISP_DrawStatusBanner:\n"
    "ESQDISP_DrawStatusBanner:\n"
    "_ESQDISP_DrawStatusBanner_Impl:\n"
    "ESQDISP_DrawStatusBanner_Impl:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D2-D3/D5-D7/A2,-(A7)\n"
    "    MOVE.W  38(A7),D7\n"
    "    MOVEQ   #0,D5\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    PEA     CLOCK_DaySlotIndex\n"
    "    JSR     ESQFUNC_JMPTBL_ESQ_GetHalfHourSlotIndex(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.W  D0,CLOCK_HalfHourSlotIndex\n"
    "    TST.W   ESQDISP_StatusBannerClampGateFlag\n"
    "    BEQ.S   .lab_0934\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  ESQ_STR_B,D0\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.B  ESQ_STR_E,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_ESQ_ClampBannerCharRange(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".lab_0934:\n"
    "    JSR     ESQFUNC_JMPTBL_LADFUNC_UpdateHighlightState(PC)\n"
    "\n"
    "    TST.W   D7\n"
    "    BEQ.S   .lab_0935\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.W  D0,BANNER_ResetPendingFlag\n"
    "\n"
    ".lab_0935:\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCS.S   .lab_0937\n"
    "\n"
    "    MOVEQ   #39,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   .lab_0937\n"
    "\n"
    "    MOVE.W  WDISP_BannerSlotCursor,D1\n"
    "    EXT.L   D1\n"
    "    MOVEQ   #0,D2\n"
    "    NOT.B   D2\n"
    "    AND.L   D2,D1\n"
    "    MOVE.B  D1,TEXTDISP_PrimaryGroupCode\n"
    "    MOVE.W  CLOCK_CacheDayIndex0,D0\n"
    "    MOVEQ   #31,D3\n"
    "    CMP.W   D3,D0\n"
    "    BNE.S   .lab_0936\n"
    "\n"
    "    MOVE.W  CLOCK_CacheMonthIndex0,D0\n"
    "    MOVEQ   #11,D3\n"
    "    CMP.W   D3,D0\n"
    "    BNE.S   .lab_0936\n"
    "\n"
    "    MOVE.B  #$1,TEXTDISP_SecondaryGroupCode\n"
    "    BRA.S   .lab_093A\n"
    "\n"
    ".lab_0936:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D1,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    AND.L   D2,D0\n"
    "    MOVE.B  D0,TEXTDISP_SecondaryGroupCode\n"
    "    BRA.S   .lab_093A\n"
    "\n"
    ".lab_0937:\n"
    "    MOVE.W  WDISP_BannerSlotCursor,D1\n"
    "    EXT.L   D1\n"
    "    MOVEQ   #0,D2\n"
    "    NOT.B   D2\n"
    "    AND.L   D2,D1\n"
    "    MOVE.B  D1,TEXTDISP_SecondaryGroupCode\n"
    "    MOVE.W  WDISP_BannerSlotCursor,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .lab_0939\n"
    "\n"
    "    MOVE.W  CLOCK_CacheYear,D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVEQ   #3,D1\n"
    "    AND.L   D1,D0\n"
    "    BNE.S   .lab_0938\n"
    "\n"
    "    MOVE.B  #$6e,TEXTDISP_PrimaryGroupCode\n"
    "    BRA.S   .lab_093A\n"
    "\n"
    ".lab_0938:\n"
    "    MOVE.B  #$6d,TEXTDISP_PrimaryGroupCode\n"
    "    BRA.S   .lab_093A\n"
    "\n"
    ".lab_0939:\n"
    "    MOVE.W  WDISP_BannerSlotCursor,D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #1,D0\n"
    "    AND.L   D2,D0\n"
    "    MOVE.B  D0,TEXTDISP_PrimaryGroupCode\n"
    "\n"
    ".lab_093A:\n"
    "    MOVE.W  DST_PrimaryCountdown,D0\n"
    "    MOVE.W  ESQDISP_LastPrimaryCountdownValue,D1\n"
    "    CMP.W   D0,D1\n"
    "    BEQ.S   .lab_093C\n"
    "\n"
    "    MOVE.W  D0,ESQDISP_LastPrimaryCountdownValue\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .lab_093C\n"
    "\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    SUBQ.W  #3,D0\n"
    "    BNE.S   .lab_093B\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQDISP_SecondaryPersistArmGateFlag\n"
    "    BRA.S   .lab_093C\n"
    "\n"
    ".lab_093B:\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    MOVEQ   #46,D1\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .lab_093C\n"
    "\n"
    "    CLR.W   ESQDISP_SecondaryPropagationDoneFlag\n"
    "\n"
    ".lab_093C:\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".lab_093D:\n"
    "    TST.L   D5\n"
    "    BNE.S   .lab_0941\n"
    "\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.S   .lab_0941\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEQ   #20,D1\n"
    "    JSR     ESQIFF_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    LEA     WDISP_StatusDayEntry0,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    TST.L   16(A1)\n"
    "    BNE.S   .lab_093E\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentDayOfYear,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D6,D1\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    CMP.L   (A1),D1\n"
    "    BEQ.S   .lab_093F\n"
    "\n"
    ".lab_093E:\n"
    "    MOVE.W  CLOCK_CurrentDayOfYear,D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D6,D0\n"
    "    MOVE.L  D0,24(A7)\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEQ   #20,D1\n"
    "    JSR     ESQIFF_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  24(A7),D0\n"
    "    ADDI.L  #$100,D0\n"
    "    CMP.L   (A0),D0\n"
    "    BEQ.S   .lab_093F\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   .lab_0940\n"
    "\n"
    ".lab_093F:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".lab_0940:\n"
    "    MOVE.L  D0,D5\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.S   .lab_093D\n"
    "\n"
    ".lab_0941:\n"
    "    TST.L   D5\n"
    "    BEQ.S   .lab_0945\n"
    "\n"
    "    LEA     WDISP_StatusDayEntry1,A0\n"
    "    MOVEA.L A0,A1\n"
    "    LEA     WDISP_StatusDayEntry0,A2\n"
    "    MOVEQ   #4,D0\n"
    "\n"
    ".lab_0942:\n"
    "    MOVE.L  (A1)+,(A2)+\n"
    "    DBF     D0,.lab_0942\n"
    "    LEA     WDISP_StatusDayEntry2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    LEA     WDISP_StatusDayEntry1,A2\n"
    "    MOVEQ   #4,D0\n"
    "\n"
    ".lab_0943:\n"
    "    MOVE.L  (A1)+,(A2)+\n"
    "    DBF     D0,.lab_0943\n"
    "    LEA     WDISP_StatusDayEntry3,A0\n"
    "    LEA     WDISP_StatusDayEntry2,A1\n"
    "    MOVEQ   #4,D0\n"
    "\n"
    ".lab_0944:\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    DBF     D0,.lab_0944\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,TLIBA1_StatusBannerPropagateGuard\n"
    "\n"
    ".lab_0945:\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .lab_0946\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQDISP_SecondaryPersistArmGateFlag\n"
    "\n"
    ".lab_0946:\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCS.S   .lab_0947\n"
    "\n"
    "    TST.W   ESQDISP_SecondaryPersistArmGateFlag\n"
    "    BNE.S   .lab_0947\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.L  D1,ESQDISP_SecondaryPersistRequestFlag\n"
    "    MOVE.W  #1,ESQDISP_SecondaryPersistArmGateFlag\n"
    "\n"
    ".lab_0947:\n"
    "    MOVEQ   #44,D1\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .lab_0948\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D1,ESQDISP_SecondaryPropagationDoneFlag\n"
    "\n"
    ".lab_0948:\n"
    "    MOVEQ   #45,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCS.S   ESQDISP_DrawStatusBanner_Impl_Return\n"
    "\n"
    "    TST.W   ESQDISP_SecondaryPropagationDoneFlag\n"
    "    BNE.S   ESQDISP_DrawStatusBanner_Impl_Return\n"
    "\n"
    "    BSR.W   ESQDISP_PropagatePrimaryTitleMetadataToSecondary\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_LOCAVAIL_SyncSecondaryFilterForCurrentGroup(PC)\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_P_TYPE_EnsureSecondaryList(PC)\n"
    "\n"
    "    MOVE.W  #1,ESQDISP_SecondaryPropagationDoneFlag\n"
    "\n"
    "_ESQDISP_DrawStatusBanner_Impl_Return:\n"
    "ESQDISP_DrawStatusBanner_Impl_Return:\n"
    "    MOVEM.L (A7)+,D2-D3/D5-D7/A2\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
