__asm__(
    ".globl _ESQDISP_FillProgramInfoHeaderFields\n"
    ".globl _ESQDISP_FillProgramInfoHeaderFields_Return\n"
    "_ESQDISP_FillProgramInfoHeaderFields:\n"
    "ESQDISP_FillProgramInfoHeaderFields:\n"
    "    MOVEM.L D4-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 28(A7),A3\n"
    "    MOVE.B  35(A7),D7\n"
    "    MOVE.W  38(A7),D6\n"
    "    MOVE.B  43(A7),D5\n"
    "    MOVE.B  47(A7),D4\n"
    "    MOVEA.L 48(A7),A2\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   ESQDISP_FillProgramInfoHeaderFields_Return\n"
    "\n"
    "    MOVE.B  D7,40(A3)\n"
    "    MOVE.W  D6,46(A3)\n"
    "    MOVE.B  D5,41(A3)\n"
    "    MOVE.B  D4,42(A3)\n"
    "    LEA     43(A3),A0\n"
    "    PEA     2.W\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_STRING_CopyPadNul\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    CLR.B   45(A3)\n"
    "\n"
    "_ESQDISP_FillProgramInfoHeaderFields_Return:\n"
    "ESQDISP_FillProgramInfoHeaderFields_Return:\n"
    "    MOVEM.L (A7)+,D4-D7/A2-A3\n"
    "    RTS\n"
);
