__asm__(
    ".globl _ESQDISP_ApplyStatusMaskToIndicators\n"
    "_ESQDISP_ApplyStatusMaskToIndicators:\n"
    "ESQDISP_ApplyStatusMaskToIndicators:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  8(A7),D7\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .evaluate_primary_indicator_group\n"
    "\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .evaluate_secondary_indicator_group\n"
    "\n"
    ".evaluate_primary_indicator_group:\n"
    "    BTST    #4,D7\n"
    "    BEQ.S   .primary_no_bit4\n"
    "\n"
    "    BTST    #5,D7\n"
    "    BEQ.S   .primary_bit4_only\n"
    "\n"
    "    PEA     1.W\n"
    "    PEA     4.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .evaluate_secondary_indicator_group\n"
    "\n"
    ".primary_bit4_only:\n"
    "    PEA     1.W\n"
    "    PEA     2.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .evaluate_secondary_indicator_group\n"
    "\n"
    ".primary_no_bit4:\n"
    "    PEA     1.W\n"
    "    PEA     7.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".evaluate_secondary_indicator_group:\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .secondary_eval_bit8\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.W   .return\n"
    "\n"
    ".secondary_eval_bit8:\n"
    "    BTST    #8,D7\n"
    "    BEQ.S   .secondary_eval_bit0\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     4.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".secondary_eval_bit0:\n"
    "    BTST    #0,D7\n"
    "    BEQ.S   .secondary_no_bit0\n"
    "\n"
    "    BTST    #2,D7\n"
    "    BEQ.S   .secondary_bit0_without_bit2\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     4.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".secondary_bit0_without_bit2:\n"
    "    BTST    #1,D7\n"
    "    BEQ.S   .secondary_bit0_fallback\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     2.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".secondary_bit0_fallback:\n"
    "    CLR.L   -(A7)\n"
    "    PEA     1.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".secondary_no_bit0:\n"
    "    BTST    #2,D7\n"
    "    BEQ.S   .secondary_no_bit0_no_bit2\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     3.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".secondary_no_bit0_no_bit2:\n"
    "    BTST    #1,D7\n"
    "    BEQ.S   .secondary_no_bits_1_2\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     3.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".secondary_no_bits_1_2:\n"
    "    CLR.L   -(A7)\n"
    "    PEA     7.W\n"
    "    BSR.W   ESQDISP_SetStatusIndicatorColorSlot\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
