__asm__(
    ".globl _ESQDISP_TestEntryGridEligibility\n"
    ".globl _ESQDISP_TestEntryGridEligibility_Return\n"
    "_ESQDISP_TestEntryGridEligibility:\n"
    "ESQDISP_TestEntryGridEligibility:\n"
    "    MOVEM.L D6-D7/A3,-(A7)\n"
    "    MOVEA.L 16(A7),A3\n"
    "    MOVE.W  22(A7),D7\n"
    "\n"
    "    MOVEQ   #0,D6\n"
    "    TST.W   D7\n"
    "    BLE.S   ESQDISP_TestEntryGridEligibility_Return\n"
    "\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   ESQDISP_TestEntryGridEligibility_Return\n"
    "\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   ESQDISP_TestEntryGridEligibility_Return\n"
    "\n"
    "    BTST    #4,7(A3,D7.W)\n"
    "    BNE.S   ESQDISP_TestEntryGridEligibility_lab_091C\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ADDI.W  #$fc,D0\n"
    "    CMPI.B  #$5,0(A3,D0.W)\n"
    "    BCS.S   ESQDISP_TestEntryGridEligibility_lab_091B\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ADDI.W  #$fc,D0\n"
    "    CMPI.B  #$a,0(A3,D0.W)\n"
    "    BLS.S   ESQDISP_TestEntryGridEligibility_lab_091C\n"
    "\n"
    "ESQDISP_TestEntryGridEligibility_lab_091B:\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   ESQDISP_TestEntryGridEligibility_lab_091D\n"
    "\n"
    "ESQDISP_TestEntryGridEligibility_lab_091C:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    "ESQDISP_TestEntryGridEligibility_lab_091D:\n"
    "    MOVE.L  D0,D6\n"
    "\n"
    "_ESQDISP_TestEntryGridEligibility_Return:\n"
    "ESQDISP_TestEntryGridEligibility_Return:\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEM.L (A7)+,D6-D7/A3\n"
    "    RTS\n"
);
