__asm__(
    ".globl _ESQDISP_SetStatusIndicatorColorSlot\n"
    "_ESQDISP_SetStatusIndicatorColorSlot:\n"
    "ESQDISP_SetStatusIndicatorColorSlot:\n"
    "    LINK.W  A5,#-20\n"
    "    MOVEM.L D2-D7,-(A7)\n"
    "    MOVE.L  8(A5),D7\n"
    "    MOVE.L  12(A5),D6\n"
    "\n"
    "    TST.L   D6\n"
    "    BEQ.S   .validate_slot_index\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.W   .return\n"
    "\n"
    ".validate_slot_index:\n"
    "    TST.B   ESQDISP_StatusIndicatorDeferredApplyFlag\n"
    "    BEQ.S   .resolve_cached_color_or_direct_apply\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BEQ.W   .return\n"
    "\n"
    "    MOVE.L  D6,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     ESQDISP_StatusIndicatorColorCache,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    MOVE.L  D7,(A1)\n"
    "    BRA.W   .return\n"
    "\n"
    ".resolve_cached_color_or_direct_apply:\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .apply_if_slot_color_changed\n"
    "\n"
    "    MOVE.L  D6,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     ESQDISP_StatusIndicatorColorCache,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    MOVE.L  (A1),D7\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D1,A1\n"
    "    MOVE.L  D0,(A1)\n"
    "\n"
    ".apply_if_slot_color_changed:\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     ESQDISP_StatusIndicatorColorCache,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVE.L  (A1),D1\n"
    "    CMP.L   D7,D1\n"
    "    BEQ.W   .return\n"
    "\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  D7,(A0)\n"
    "    MOVE.L  #$28f,D4\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D6\n"
    "    BNE.S   .use_slot0_y\n"
    "\n"
    "    MOVEQ   #40,D0\n"
    "    MOVE.L  D0,-16(A5)\n"
    "    BRA.S   .setup_indicator_rastport\n"
    "\n"
    ".use_slot0_y:\n"
    "    MOVEQ   #57,D0\n"
    "    MOVE.L  D0,-16(A5)\n"
    "\n"
    ".setup_indicator_rastport:\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.B  25(A0),D5\n"
    "    EXT.W   D5\n"
    "    EXT.L   D5\n"
    "    MOVE.L  4(A0),-4(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    MOVEQ   #7,D0\n"
    "    CMP.L   D0,D7\n"
    "    BEQ.S   .readPixelAt655x55\n"
    "\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .set_pen_and_fill_indicator\n"
    "\n"
    ".readPixelAt655x55:\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVE.L  #655,D0\n"
    "    MOVEQ   #55,D1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOReadPixel(A6)\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "\n"
    ".set_pen_and_fill_indicator:\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVE.L  D4,D0\n"
    "    ADDQ.L  #6,D0\n"
    "    MOVE.L  -16(A5),D1\n"
    "    MOVE.L  D1,D2\n"
    "    ADDQ.L  #4,D2\n"
    "    MOVE.L  D0,24(A7)\n"
    "    MOVE.L  D4,D0\n"
    "    MOVE.L  D2,D3\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVE.L  24(A7),D2\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -4(A5),4(A0)\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D2-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
