__asm__(
    ".globl _ESQDISP_PromoteSecondaryLineHeadTailIfMarked\n"
    "_ESQDISP_PromoteSecondaryLineHeadTailIfMarked:\n"
    "ESQDISP_PromoteSecondaryLineHeadTailIfMarked:\n"
    "    TST.W   ESQDISP_SecondaryLinePromotePendingFlag\n"
    "    BEQ.S   .clear_pending_line_promote_flag\n"
    "\n"
    "    PEA     1.W\n"
    "    JSR     ESQIFF2_ClearLineHeadTailByMode\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  ESQIFF_SecondaryLineHeadPtr,ESQIFF_PrimaryLineHeadPtr\n"
    "    MOVE.L  ESQIFF_SecondaryLineTailPtr,ESQIFF_PrimaryLineTailPtr\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,ESQIFF_SecondaryLineHeadPtr\n"
    "    MOVE.L  A0,ESQIFF_SecondaryLineTailPtr\n"
    "\n"
    ".clear_pending_line_promote_flag:\n"
    "    CLR.W   ESQDISP_SecondaryLinePromotePendingFlag\n"
    "    RTS\n"
);
