__asm__(
    ".globl _ESQDISP_PropagatePrimaryTitleMetadataToSecondary\n"
    ".globl _ESQDISP_PropagatePrimaryTitleMetadataToSecondary_Return\n"
    "_ESQDISP_PropagatePrimaryTitleMetadataToSecondary:\n"
    "ESQDISP_PropagatePrimaryTitleMetadataToSecondary:\n"
    "    LINK.W  A5,#-40\n"
    "    MOVEM.L D2-D7/A2-A3/A6,-(A7)\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.W   ESQDISP_PropagatePrimaryTitleMetadataToSecondary_Return\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    CMP.W   D1,D0\n"
    "    BLS.W   ESQDISP_PropagatePrimaryTitleMetadataToSecondary_Return\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_secondary_entries:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.W   ESQDISP_PropagatePrimaryTitleMetadataToSecondary_Return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    TST.L   60(A1)\n"
    "    BNE.W   .next_secondary_entry\n"
    "\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    LEA     28(A1),A0\n"
    "    PEA     1.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQSHARED_JMPTBL_ESQ_TestBit1Based(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    ADDQ.L  #1,D0\n"
    "    BNE.W   .next_secondary_entry\n"
    "\n"
    "    MOVEQ   #0,D4\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".loop_primary_candidates:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.W   .next_secondary_entry\n"
    "\n"
    "    TST.L   D4\n"
    "    BNE.W   .next_secondary_entry\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "    MOVE.L  A2,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    JSR     ESQSHARED_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.W   .next_primary_candidate\n"
    "\n"
    "    MOVEQ   #48,D5\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    BTST    #5,Struct_PrimaryEntry__EditorFlagsByte(A1)\n"
    "    BEQ.S   .set_slot_scan_floor_low\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   .store_slot_scan_floor\n"
    "\n"
    ".set_slot_scan_floor_low:\n"
    "    MOVEQ   #44,D0\n"
    "\n"
    ".store_slot_scan_floor:\n"
    "    MOVE.L  D0,-20(A5)\n"
    "\n"
    ".loop_slots_descending:\n"
    "    CMP.L   -20(A5),D5\n"
    "    BLE.W   .next_primary_candidate\n"
    "\n"
    "    TST.L   D4\n"
    "    BNE.W   .next_primary_candidate\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    LEA     Struct_PrimaryEntry__SelectionBitsetBase(A1),A0\n"
    "    MOVE.L  D5,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQSHARED_JMPTBL_ESQ_TestBit1Based(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    ADDQ.L  #1,D0\n"
    "    BNE.W   .next_slot_descending\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEA.L (A1),A2\n"
    "    MOVE.L  D5,D1\n"
    "    ASL.L   #2,D1\n"
    "    ADDA.L  D1,A2\n"
    "    TST.L   Struct_TitleAuxRecord__SelectorTextPtrBase(A2)\n"
    "    BEQ.W   .next_slot_descending\n"
    "\n"
    "    MOVE.L  D7,D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A1\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D2,A2\n"
    "    MOVEA.L (A2),A3\n"
    "    MOVEA.L A0,A2\n"
    "    ADDA.L  D0,A2\n"
    "    MOVEA.L (A2),A6\n"
    "    ADDA.L  D5,A6\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.B  Struct_TitleAuxRecord__SelectorFlagsByteBase(A6),D3\n"
    "    ORI.W   #$80,D3\n"
    "    MOVE.B  D3,8(A3)\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D2,A2\n"
    "    MOVEA.L (A2),A3\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "    ADDA.L  D1,A2\n"
    "    ADDA.L  D2,A1\n"
    "    MOVEA.L (A1),A0\n"
    "    MOVE.L  Struct_TitleAuxRecord__OwnedStringPtr(A0),-(A7)\n"
    "    MOVE.L  Struct_TitleAuxRecord__SelectorTextPtrBase(A2),-(A7)\n"
    "    MOVE.L  A3,60(A7)\n"
    "    JSR     ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L 52(A7),A0\n"
    "    MOVE.L  D0,Struct_TitleAuxRecord__OwnedStringPtr(A0)\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEA.L (A1),A2\n"
    "    MOVE.L  D6,D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A1\n"
    "    MOVEA.L A1,A3\n"
    "    ADDA.L  D1,A3\n"
    "    MOVEA.L (A3),A6\n"
    "    ADDA.L  D5,A6\n"
    "    MOVE.B  252(A6),253(A2)\n"
    "    MOVEA.L A0,A2\n"
    "    ADDA.L  D0,A2\n"
    "    MOVEA.L (A2),A3\n"
    "    MOVEA.L A1,A2\n"
    "    ADDA.L  D1,A2\n"
    "    MOVEA.L (A2),A6\n"
    "    ADDA.L  D5,A6\n"
    "    MOVE.B  301(A6),302(A3)\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "    ADDA.L  D1,A1\n"
    "    MOVEA.L (A1),A0\n"
    "    ADDA.L  D5,A0\n"
    "    MOVE.B  350(A0),351(A2)\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  40(A1),D0\n"
    "    MOVE.L  D0,D1\n"
    "    ORI.W   #$80,D1\n"
    "    MOVE.B  D1,40(A1)\n"
    "    MOVEQ   #1,D4\n"
    "\n"
    ".next_slot_descending:\n"
    "    SUBQ.L  #1,D5\n"
    "    BRA.W   .loop_slots_descending\n"
    "\n"
    ".next_primary_candidate:\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.W   .loop_primary_candidates\n"
    "\n"
    ".next_secondary_entry:\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.W   .loop_secondary_entries\n"
    "\n"
    "_ESQDISP_PropagatePrimaryTitleMetadataToSecondary_Return:\n"
    "ESQDISP_PropagatePrimaryTitleMetadataToSecondary_Return:\n"
    "    MOVEM.L (A7)+,D2-D7/A2-A3/A6\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
