__asm__(
    ".globl _ESQDISP_NormalizeClockAndRedrawBanner\n"
    "_ESQDISP_NormalizeClockAndRedrawBanner:\n"
    "ESQDISP_NormalizeClockAndRedrawBanner:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.L  A3,-(A7)\n"
    "    PEA     CLOCK_DaySlotIndex\n"
    "    JSR     ESQFUNC_JMPTBL_PARSEINI_NormalizeClockData\n"
    "\n"
    "    PEA     DST_BannerWindowPrimary\n"
    "    JSR     DST_UpdateBannerQueue\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .lab_0932\n"
    "\n"
    "    JSR     DST_RefreshBannerBuffer\n"
    "\n"
    ".lab_0932:\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  4(A0),-4(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    JSR     ESQFUNC_JMPTBL_CLEANUP_DrawClockBanner\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -4(A5),4(A0)\n"
    "    PEA     1.W\n"
    "    BSR.W   ESQDISP_DrawStatusBanner_Impl\n"
    "\n"
    "    MOVEA.L -8(A5),A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
