__asm__(
    ".globl _ESQDISP_UpdateStatusMaskAndRefresh\n"
    ".globl _ESQDISP_UpdateStatusMaskAndRefresh_Return\n"
    "_ESQDISP_UpdateStatusMaskAndRefresh:\n"
    "ESQDISP_UpdateStatusMaskAndRefresh:\n"
    "    MOVEM.L D5-D7,-(A7)\n"
    "    MOVE.L  16(A7),D7\n"
    "    MOVE.L  20(A7),D6\n"
    "    MOVEQ   #-1,D5\n"
    "    MOVE.L  ESQDISP_StatusIndicatorMask,D5\n"
    "    TST.L   D6\n"
    "    BEQ.S   .lab_08DB\n"
    "\n"
    "    OR.L    D7,ESQDISP_StatusIndicatorMask\n"
    "    BRA.S   .lab_08DC\n"
    "\n"
    ".lab_08DB:\n"
    "    MOVE.L  D7,D0\n"
    "    NOT.L   D0\n"
    "    AND.L   D0,ESQDISP_StatusIndicatorMask\n"
    "\n"
    ".lab_08DC:\n"
    "    ANDI.L  #$fff,ESQDISP_StatusIndicatorMask\n"
    "    MOVE.L  ESQDISP_StatusIndicatorMask,D0\n"
    "    CMP.L   D0,D5\n"
    "    BEQ.S   ESQDISP_UpdateStatusMaskAndRefresh_Return\n"
    "\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQDISP_ApplyStatusMaskToIndicators\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    "_ESQDISP_UpdateStatusMaskAndRefresh_Return:\n"
    "ESQDISP_UpdateStatusMaskAndRefresh_Return:\n"
    "    MOVEM.L (A7)+,D5-D7\n"
    "    RTS\n"
);
