__asm__(
    ".globl _ESQFUNC_FreeLineTextBuffers\n"
    "_ESQFUNC_FreeLineTextBuffers:\n"
    "ESQFUNC_FreeLineTextBuffers:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_free_line_text_buffers:\n"
    "    MOVEQ   #20,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .return_free_line_text_buffers\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     LADFUNC_LineTextBufferPtrs,A0\n"
    "    ADDA.L  D0,A0\n"
    "\n"
    "    PEA     60.W\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     1235.W\n"
    "    PEA     Global_STR_ESQFUNC_C_6\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     LADFUNC_LineTextBufferPtrs,A0\n"
    "    ADDA.L  D0,A0\n"
    "    CLR.L   (A0)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .loop_free_line_text_buffers\n"
    "\n"
    ".return_free_line_text_buffers:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
