__asm__(
    ".globl _ESQFUNC_DrawDiagnosticsScreen\n"
    "_ESQFUNC_DrawDiagnosticsScreen:\n"
    "ESQFUNC_DrawDiagnosticsScreen:\n"
    "    LINK.W  A5,#-164\n"
    "    MOVEM.L D2-D7,-(A7)\n"
    "\n"
    "    LEA     ESQFUNC_VideoInsertionStateStrings,A0\n"
    "    LEA     -148(A5),A1\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    MOVE.W  #$fff,D0\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsA_ColorRegistersA\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsB_ColorRegistersA\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsA\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsB\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsA_ColorRegistersB\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsB_TailColorWord\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsA_ColorRegistersC\n"
    "    MOVE.W  D0,ESQ_CopperStatusDigitsA_TailColorWord\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L Global_HANDLE_TOPAZ_FONT,A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetFont(A6)\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_SCRIPT_ReadCiaBBit5Mask(PC)\n"
    "\n"
    "    TST.B   D0\n"
    "    BEQ.S   .status_a_false\n"
    "\n"
    "    LEA     ESQFUNC_STR_CLOSED_ENABLED,A0\n"
    "\n"
    "    BRA.S   .status_a_selected\n"
    "\n"
    ".status_a_false:\n"
    "    LEA     ESQFUNC_STR_OPEN_DISABLED,A0\n"
    "\n"
    ".status_a_selected:\n"
    "    MOVE.L  A0,24(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_SCRIPT_GetCtrlLineFlag(PC)\n"
    "\n"
    "    TST.B   D0\n"
    "    BEQ.S   .status_b_false\n"
    "\n"
    "    LEA     ESQFUNC_TAG_CLOSED,A0\n"
    "    BRA.S   .status_b_selected\n"
    "\n"
    ".status_b_false:\n"
    "    LEA     ESQFUNC_TAG_OPEN,A0\n"
    "\n"
    ".status_b_selected:\n"
    "    MOVE.L  A0,28(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_SCRIPT_ReadCiaBBit3Flag(PC)\n"
    "\n"
    "    TST.B   D0\n"
    "    BEQ.S   .status_c_false\n"
    "\n"
    "    LEA     ESQFUNC_STR_CLOSED_ON_AIR,A0\n"
    "    BRA.S   .status_c_selected\n"
    "\n"
    ".status_c_false:\n"
    "    LEA     ESQFUNC_STR_OPEN_OFF_AIR,A0\n"
    "\n"
    ".status_c_selected:\n"
    "    MOVE.W  SCRIPT_CtrlHandshakeStage,D0\n"
    "    SUBQ.W  #2,D0\n"
    "    BNE.S   .select_mode_two\n"
    "\n"
    "    LEA     ESQFUNC_STR_ON_AIR,A1\n"
    "    BRA.S   .format_main_line\n"
    "\n"
    ".select_mode_two:\n"
    "    MOVE.W  SCRIPT_CtrlHandshakeStage,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .select_mode_one\n"
    "\n"
    "    LEA     ESQFUNC_STR_OFF_AIR,A1\n"
    "    BRA.S   .format_main_line\n"
    "\n"
    ".select_mode_one:\n"
    "    LEA     ESQFUNC_STR_NO_DETECT,A1\n"
    "\n"
    ".format_main_line:\n"
    "\n"
    "\n"
    "\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  36(A7),-(A7)\n"
    "    MOVE.L  36(A7),-(A7)\n"
    "    PEA     ESQFUNC_FMT_CARTSW_COLON_PCT_S_CARTREL_COLON_PCT\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     92.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    MOVE.W  SCRIPT_RuntimeMode,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     -148(A5),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.W  ESQPARS2_ReadModeFlags,D0\n"
    "    EXT.L   D0\n"
    "\n"
    "\n"
    "\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     ESQFUNC_FMT_INSERTIME_PCT_S_WINIT_0X_PCT_04X\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     110.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    "\n"
    "    MOVE.W  TEXTDISP_DeferredActionCountdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  TEXTDISP_DeferredActionArmed,D1\n"
    "\n"
    "    MOVE.L  LOCAVAIL_PrimaryFilterState_Field0C,(A7)\n"
    "    MOVE.L  LOCAVAIL_PrimaryFilterState_Field08,-(A7)\n"
    "\n"
    "    MOVE.L  LOCAVAIL_FilterClassId,-(A7)\n"
    "    MOVE.L  LOCAVAIL_FilterStep,-(A7)\n"
    "    MOVE.L  LOCAVAIL_FilterModeFlag,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "\n"
    "\n"
    "    PEA     ESQFUNC_FMT_LOCAL_MODE_PCT_LD_LOCAL_UPDATE_PCT_L\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     92(A7),A7\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     128.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    "\n"
    "    MOVE.W  CLOCK_CacheMonthIndex0,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  CLOCK_CacheDayIndex0,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  CLOCK_CacheYear,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.W  CLOCK_CacheHour,D3\n"
    "    EXT.L   D3\n"
    "    MOVE.W  CLOCK_CacheMinuteOrSecond,D4\n"
    "    EXT.L   D4\n"
    "\n"
    "    MOVE.W  Global_REF_CLOCKDATA_STRUCT,D5\n"
    "    EXT.L   D5\n"
    "\n"
    "    TST.W   CLOCK_CacheAmPmFlag\n"
    "    BEQ.S   .use_am_suffix\n"
    "\n"
    "    LEA     ESQFUNC_STR_PM,A0\n"
    "    BRA.S   .format_clock_line\n"
    "\n"
    ".use_am_suffix:\n"
    "    LEA     ESQFUNC_STR_AM,A0\n"
    "\n"
    ".format_clock_line:\n"
    "\n"
    "    MOVE.W  LOCAVAIL_FilterCooldownTicks,D6\n"
    "    EXT.L   D6\n"
    "    MOVE.L  D6,-(A7)\n"
    "\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D5,-(A7)\n"
    "    MOVE.L  D4,-(A7)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "\n"
    "    PEA     ESQFUNC_FMT_CTIME_PCT_02D_SLASH_PCT_02D_SLASH_PC\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     146.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    MOVE.L  #$20002,D1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,76(A7)\n"
    "    MOVEQ   #4,D1\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,80(A7)\n"
    "    MOVEQ   #2,D1\n"
    "    SWAP    D1\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  80(A7),-(A7)\n"
    "    MOVE.L  80(A7),-(A7)\n"
    "\n"
    "    PEA     ESQFUNC_FMT_L_CHIP_COLON_PCT_07LD_FAST_COLON_PCT\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     68(A7),A7\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     164.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_PARSEINI_ComputeHTCMaxValues(PC)\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  ESQIFF_ParseAttemptCount,D0\n"
    "    MOVE.W  DATACErrs,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  ESQIFF_LineErrorCount,D2\n"
    "    EXT.L   D2\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.W  Global_WORD_MAX_VALUE,D3\n"
    "    MOVE.L  D7,(A7)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "\n"
    "    PEA     ESQFUNC_FMT_DATA_COLON_CMD_CNT_COLON_PCT_08LD_CR\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     182.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  SCRIPT_CtrlCmdCount,D0\n"
    "    MOVE.W  SCRIPT_CtrlCmdChecksumErrorCount,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  SCRIPT_CtrlCmdLengthErrorCount,D2\n"
    "    EXT.L   D2\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.W  CTRL_HDeltaMax,D3\n"
    "    MOVE.L  D0,72(A7)\n"
    "    MOVE.L  D1,76(A7)\n"
    "    MOVE.L  D2,80(A7)\n"
    "    MOVE.L  D3,84(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_PARSEINI_UpdateCtrlHDeltaMax(PC)\n"
    "\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  84(A7),-(A7)\n"
    "    MOVE.L  84(A7),-(A7)\n"
    "    MOVE.L  84(A7),-(A7)\n"
    "    MOVE.L  84(A7),-(A7)\n"
    "\n"
    "    PEA     ESQFUNC_FMT_CTRL_COLON_CMD_CNT_COLON_PCT_08LD_CR\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     72(A7),A7\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     200.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    "    ADDQ.L  #1,ESQFUNC_DiagRowCounter\n"
    "    MOVE.W  Global_RefreshTickCounter,D0\n"
    "    EXT.L   D0\n"
    "    TST.W   ESQDISP_PrimarySecondaryMirrorFlag\n"
    "    BEQ.S   .set_false_text\n"
    "\n"
    "    LEA     Global_STR_TRUE_2,A0\n"
    "    BRA.S   .format_tick_line\n"
    "\n"
    ".set_false_text:\n"
    "    LEA     Global_STR_FALSE_2,A0\n"
    "\n"
    ".format_tick_line:\n"
    "\n"
    "    MOVE.W  SCRIPT_PlaybackFallbackCounter,D1\n"
    "    EXT.L   D1\n"
    "\n"
    "    MOVE.B  ED_MenuStateId,D2\n"
    "    EXT.W   D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  ESQFUNC_DiagRowCounter,-(A7)\n"
    "\n"
    "\n"
    "    PEA     ESQFUNC_FMT_PCT_05LD_COLON_PEP_COLON_PCT_LD_REUS\n"
    "    PEA     -132(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     218.W\n"
    "    PEA     -132(A5)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L Global_HANDLE_PREVUEC_FONT,A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetFont(A6)\n"
    "\n"
    "    MOVEM.L -188(A5),D2-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
