__asm__(
    ".globl _ESQFUNC_DrawEscMenuVersion\n"
    "_ESQFUNC_DrawEscMenuVersion:\n"
    "ESQFUNC_DrawEscMenuVersion:\n"
    "    LINK.W  A5,#-84\n"
    "\n"
    "    CLR.W   ED_DiagnosticsScreenActive\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVE.L  Global_PTR_STR_BUILD_ID,-(A7)\n"
    "    MOVE.L  Global_LONG_BUILD_NUMBER,-(A7)\n"
    "    PEA     Global_STR_BUILD_NUMBER_FORMATTED\n"
    "    PEA     -81(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -81(A5)\n"
    "    PEA     330.W\n"
    "    PEA     175.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   Global_LONG_ROM_VERSION_CHECK,D0\n"
    "    BNE.S   .setRomVersion2_04\n"
    "\n"
    "    LEA     Global_STR_ROM_VERSION_1_3,A0\n"
    "    BRA.S   .format_rom_version_line\n"
    "\n"
    ".setRomVersion2_04:\n"
    "    LEA     Global_STR_ROM_VERSION_2_04,A0\n"
    "\n"
    ".format_rom_version_line:\n"
    "    MOVE.L  A0,-(A7)\n"
    "    PEA     Global_STR_ROM_VERSION_FORMATTED\n"
    "    PEA     -81(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -81(A5)\n"
    "    PEA     360.W\n"
    "    PEA     175.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #3,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    PEA     Global_STR_PUSH_ANY_KEY_TO_CONTINUE_1\n"
    "    PEA     390.W\n"
    "    PEA     175.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
