__asm__(
    ".globl _ESQFUNC_DrawMemoryStatusScreen\n"
    "_ESQFUNC_DrawMemoryStatusScreen:\n"
    "ESQFUNC_DrawMemoryStatusScreen:\n"
    "    LINK.W  A5,#-80\n"
    "    MOVEM.L D2-D7,-(A7)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  4(A0),-76(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    TST.W   ED_DiagnosticsScreenActive\n"
    "    BEQ.W   .return\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #1,D0\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVE.W  ED_DiagnosticsViewMode,D0\n"
    "    BNE.W   .draw_calendar_section\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  ESQIFF_ParseAttemptCount,D0\n"
    "    MOVE.W  DATACErrs,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  ESQIFF_LineErrorCount,D2\n"
    "    EXT.L   D2\n"
    "\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_DATA_CMDS_CERRS_LERRS\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     112.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  SCRIPT_CtrlCmdCount,D0\n"
    "    MOVE.W  SCRIPT_CtrlCmdChecksumErrorCount,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  SCRIPT_CtrlCmdLengthErrorCount,D2\n"
    "    EXT.L   D2\n"
    "\n"
    "    MOVE.L  D2,(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_CTRL_CMDS_CERRS_LERRS\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     142.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     68(A7),A7\n"
    "    MOVEQ   #7,D0\n"
    "    AND.L   ED_DiagAvailMemMask,D0\n"
    "    SUBQ.L  #7,D0\n"
    "    BNE.S   .check_chip_only\n"
    "\n"
    "    MOVE.L  #$20002,D1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "\n"
    "    MOVEQ   #4,D1\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "\n"
    "    MOVEQ   #2,D1\n"
    "    SWAP    D1\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "\n"
    "    MOVE.L  D5,-(A7)\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  D7,-(A7)\n"
    "    PEA     Global_STR_L_CHIP_FAST_MAX\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    BRA.W   .draw_memory_section\n"
    "\n"
    ".check_chip_only:\n"
    "    MOVEQ   #1,D0\n"
    "    AND.L   ED_DiagAvailMemMask,D0\n"
    "    SUBQ.L  #1,D0\n"
    "    BNE.S   .check_fast_only\n"
    "\n"
    "    MOVEQ   #2,D1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "    MOVE.L  D7,-(A7)\n"
    "    PEA     Global_STR_CHIP_PLACEHOLDER\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .draw_memory_section\n"
    "\n"
    ".check_fast_only:\n"
    "    MOVEQ   #2,D0\n"
    "    AND.L   ED_DiagAvailMemMask,D0\n"
    "    SUBQ.L  #2,D0\n"
    "    BNE.S   .check_max_only\n"
    "\n"
    "    MOVEQ   #4,D1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "    MOVE.L  D6,-(A7)\n"
    "    PEA     Global_STR_FAST_PLACEHOLDER\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .draw_memory_section\n"
    "\n"
    ".check_max_only:\n"
    "    MOVEQ   #4,D0\n"
    "    AND.L   ED_DiagAvailMemMask,D0\n"
    "    SUBQ.L  #4,D0\n"
    "    BNE.S   .show_disabled\n"
    "\n"
    "    MOVEQ   #2,D1\n"
    "    SWAP    D1\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOAvailMem(A6)\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "    MOVE.L  D5,-(A7)\n"
    "    PEA     Global_STR_MAX_PLACEHOLDER\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .draw_memory_section\n"
    "\n"
    ".show_disabled:\n"
    "    PEA     Global_STR_MEMORY_TYPES_DISABLED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".draw_memory_section:\n"
    "    PEA     -72(A5)\n"
    "    PEA     172.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  ESQ_SerialRbfErrorCount,D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    PEA     Global_STR_DATA_OVERRUNS_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     202.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_PARSEINI_ComputeHTCMaxValues(PC)\n"
    "\n"
    "    MOVE.L  D0,D4\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  Global_WORD_H_VALUE,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  Global_WORD_T_VALUE,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  Global_WORD_MAX_VALUE,D2\n"
    "    MOVE.L  D2,(A7)\n"
    "    MOVE.L  D4,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_DATA_H_T_C_MAX_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     232.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     76(A7),A7\n"
    "    JSR     ESQFUNC_JMPTBL_PARSEINI_UpdateCtrlHDeltaMax(PC)\n"
    "\n"
    "    MOVE.L  D0,D4\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  CTRL_H,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  CTRL_HPreviousSample,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  CTRL_HDeltaMax,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D4,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_CTRL_H_T_C_MAX_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     262.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     40(A7),A7\n"
    "\n"
    ".draw_calendar_section:\n"
    "    MOVE.W  ED_DiagnosticsViewMode,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.W   .return\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_JULIAN_DAY_NEXT_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     112.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupHeaderCode,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupHeaderCode,D1\n"
    "    MOVE.L  D1,(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_JDAY1_JDAY2_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     142.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupPresentFlag,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupPresentFlag,D1\n"
    "    MOVE.L  D1,(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_CURCLU_NXTCLU_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     72(A7),A7\n"
    "    PEA     -72(A5)\n"
    "    PEA     172.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVE.W  CLOCK_CacheDayIndex0,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  CLOCK_CacheMonthIndex0,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  ESQFUNC_CListLinePointer,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.W  CLOCK_CacheYear,D3\n"
    "    EXT.L   D3\n"
    "    MOVE.L  D3,(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_C_DATE_C_MONTH_LP_YR_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     202.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentDayOfMonth,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  CLOCK_CurrentMonthIndex,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  CLOCK_CurrentLeapYearFlag,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.W  CLOCK_CurrentYearValue,D3\n"
    "    EXT.L   D3\n"
    "    MOVE.L  D3,(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_B_DATE_B_MONTH_LP_YR_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     72(A7),A7\n"
    "    PEA     -72(A5)\n"
    "    PEA     232.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVE.W  DST_PrimaryCountdown,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  DST_SecondaryCountdown,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  WDISP_BannerCharPhaseShift,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D2,(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_C_DST_B_DST_PSHIFT_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     262.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVE.W  CLOCK_CacheHour,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  Global_WORD_CURRENT_HOUR,D1\n"
    "    EXT.L   D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D2\n"
    "    MOVE.L  D2,(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     Global_STR_C_HOUR_B_HOUR_CS_FORMATTED\n"
    "    PEA     -72(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -72(A5)\n"
    "    PEA     292.W\n"
    "    PEA     40.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     80(A7),A7\n"
    "\n"
    ".return:\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -76(A5),4(A0)\n"
    "\n"
    "    MOVEM.L (A7)+,D2-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
