__asm__(
    ".globl _ESQFUNC_UpdateRefreshModeState\n"
    "_ESQFUNC_UpdateRefreshModeState:\n"
    "ESQFUNC_UpdateRefreshModeState:\n"
    "    LINK.W  A5,#0\n"
    "\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  12(A5),D7\n"
    "    MOVE.W  #1,ESQFUNC_WeatherSliceWidthInitGate\n"
    "    TST.L   NEWGRID_MessagePumpSuspendFlag\n"
    "    BEQ.S   .apply_mode_selector_state\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,NEWGRID_RefreshStateFlag\n"
    "    MOVE.L  D0,NEWGRID_MessagePumpSuspendFlag\n"
    "    MOVE.W  #$90,ESQPARS2_BannerRowWidthBytes\n"
    "    MOVE.W  #$230,ESQPARS2_BannerCopyBlockSpanBytes\n"
    "    JSR     ESQSHARED4_ComputeBannerRowBlitGeometry\n"
    "\n"
    ".apply_mode_selector_state:\n"
    "    TST.L   D7\n"
    "    BNE.S   .set_mode_selector_two\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,NEWGRID_ModeSelectorState\n"
    "    BRA.S   .store_last_refresh_request\n"
    "\n"
    ".set_mode_selector_two:\n"
    "    MOVEQ   #2,D0\n"
    "    MOVE.L  D0,NEWGRID_ModeSelectorState\n"
    "    TST.L   NEWGRID_LastRefreshRequest\n"
    "    BNE.S   .store_last_refresh_request\n"
    "\n"
    "    CLR.L   NEWGRID_RefreshStateFlag\n"
    "\n"
    ".store_last_refresh_request:\n"
    "    MOVE.L  D7,NEWGRID_LastRefreshRequest\n"
    "    MOVE.L  (A7)+,D7\n"
    "\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
