__asm__(
    ".globl _ESQFUNC_TrimTextToPixelWidthWordBoundary\n"
    ".globl _ESQFUNC_TrimTextToPixelWidthWordBoundary_Return\n"
    "_ESQFUNC_TrimTextToPixelWidthWordBoundary:\n"
    "ESQFUNC_TrimTextToPixelWidthWordBoundary:\n"
    "    MOVEM.L D6-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 20(A7),A3\n"
    "    MOVE.L  24(A7),D7\n"
    "    MOVEA.L 28(A7),A2\n"
    "    MOVEA.L A2,A0\n"
    "\n"
    ".loop_find_text_nul:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .loop_find_text_nul\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  A2,A0\n"
    "    MOVE.L  A0,D6\n"
    "\n"
    ".loop_fit_text_to_pixel_width:\n"
    "    TST.L   D6\n"
    "    BLE.S   ESQFUNC_TrimTextToPixelWidthWordBoundary_Return\n"
    "\n"
    "    MOVEA.L A3,A1\n"
    "    MOVEA.L A2,A0\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    CMP.L   D7,D0\n"
    "    BLE.S   ESQFUNC_TrimTextToPixelWidthWordBoundary_Return\n"
    "\n"
    ".scan_backward_to_word_boundary:\n"
    "    SUBQ.L  #1,D6\n"
    "    TST.L   D6\n"
    "    BLE.S   .rewind_over_trailing_class3_chars\n"
    "\n"
    "    MOVE.B  -1(A2,D6.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    BTST    #3,(A0)\n"
    "    BEQ.S   .scan_backward_to_word_boundary\n"
    "\n"
    ".rewind_over_trailing_class3_chars:\n"
    "    TST.L   D6\n"
    "    BLE.S   .loop_fit_text_to_pixel_width\n"
    "\n"
    "    MOVE.B  -1(A2,D6.L),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    BTST    #3,(A0)\n"
    "    BEQ.S   .loop_fit_text_to_pixel_width\n"
    "\n"
    "    SUBQ.L  #1,D6\n"
    "    BRA.S   .rewind_over_trailing_class3_chars\n"
    "\n"
    "_ESQFUNC_TrimTextToPixelWidthWordBoundary_Return:\n"
    "ESQFUNC_TrimTextToPixelWidthWordBoundary_Return:\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEM.L (A7)+,D6-D7/A2-A3\n"
    "    RTS\n"
);
