__asm__(
    ".globl _ESQFUNC_SelectAndApplyBrushForCurrentEntry\n"
    "_ESQFUNC_SelectAndApplyBrushForCurrentEntry:\n"
    "ESQFUNC_SelectAndApplyBrushForCurrentEntry:\n"
    "    LINK.W  A5,#-32\n"
    "    MOVEM.L D2/D4-D7,-(A7)\n"
    "    MOVE.W  10(A5),D7\n"
    "    MOVE.L  ESQIFF_BrushIniListHead,-4(A5)\n"
    "    MOVEQ   #0,D5\n"
    "    TST.W   D7\n"
    "    BNE.S   .load_secondary_script_selection\n"
    "\n"
    "    MOVE.L  BRUSH_ScriptPrimarySelection,-24(A5)\n"
    "    BRA.S   .resolve_selection_source\n"
    "\n"
    ".load_secondary_script_selection:\n"
    "    MOVEA.L BRUSH_ScriptSecondarySelection,A0\n"
    "    MOVE.L  A0,-24(A5)\n"
    "\n"
    ".resolve_selection_source:\n"
    "    TST.L   -24(A5)\n"
    "    BNE.W   .use_script_selected_brush\n"
    "\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .load_secondary_current_entry_ptr\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-8(A5)\n"
    "    BRA.S   .compare_entry_tag_00\n"
    "\n"
    ".load_secondary_current_entry_ptr:\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-8(A5)\n"
    "\n"
    ".compare_entry_tag_00:\n"
    "    MOVEA.L -8(A5),A0\n"
    "    ADDA.W  #$2b,A0\n"
    "    PEA     2.W\n"
    "    PEA     ESQFUNC_TAG_00\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_STRING_CompareN(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .compare_entry_tag_11\n"
    "\n"
    "    MOVE.L  BRUSH_SelectedNode,-4(A5)\n"
    "    MOVEQ   #1,D5\n"
    "    BRA.W   .ensure_fallback_selected_brush\n"
    "\n"
    ".compare_entry_tag_11:\n"
    "    MOVEA.L -8(A5),A0\n"
    "    ADDA.W  #$2b,A0\n"
    "    PEA     2.W\n"
    "    PEA     ESQFUNC_TAG_11\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_STRING_CompareN(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .scan_brush_nodes_by_2char_tag\n"
    "\n"
    ".scan_brush_nodes_by_wildcard_chain:\n"
    "    TST.L   -4(A5)\n"
    "    BEQ.S   .fallback_to_type3_or_selected\n"
    "\n"
    "    TST.L   D5\n"
    "    BNE.S   .fallback_to_type3_or_selected\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  364(A0),-20(A5)\n"
    "\n"
    ".loop_match_wildcard_list:\n"
    "    TST.L   -20(A5)\n"
    "    BEQ.S   .advance_brush_node_chain\n"
    "\n"
    "    TST.L   D5\n"
    "    BNE.S   .advance_brush_node_chain\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    ADDA.W  #12,A0\n"
    "    MOVE.L  -20(A5),-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQSHARED_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.S   .advance_wildcard_node\n"
    "\n"
    "    MOVEQ   #1,D5\n"
    "\n"
    ".advance_wildcard_node:\n"
    "    MOVEA.L -20(A5),A0\n"
    "    MOVE.L  8(A0),-20(A5)\n"
    "    BRA.S   .loop_match_wildcard_list\n"
    "\n"
    ".advance_brush_node_chain:\n"
    "    TST.L   D5\n"
    "    BNE.S   .scan_brush_nodes_by_wildcard_chain\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  368(A0),-4(A5)\n"
    "    BRA.S   .scan_brush_nodes_by_wildcard_chain\n"
    "\n"
    ".fallback_to_type3_or_selected:\n"
    "    TST.L   D5\n"
    "    BNE.S   .ensure_fallback_selected_brush\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    BTST    #4,27(A0)\n"
    "    BEQ.S   .ensure_fallback_selected_brush\n"
    "\n"
    "    TST.L   ESQFUNC_FallbackType3BrushNode\n"
    "    BEQ.S   .ensure_fallback_selected_brush\n"
    "\n"
    "    MOVEQ   #1,D5\n"
    "    MOVE.L  ESQFUNC_FallbackType3BrushNode,-4(A5)\n"
    "    BRA.S   .ensure_fallback_selected_brush\n"
    "\n"
    ".scan_brush_nodes_by_2char_tag:\n"
    "    TST.L   -4(A5)\n"
    "    BEQ.S   .ensure_fallback_selected_brush\n"
    "\n"
    "    TST.L   D5\n"
    "    BNE.S   .ensure_fallback_selected_brush\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "    ADDA.W  #$2b,A0\n"
    "    MOVEA.L -4(A5),A1\n"
    "    ADDA.W  #$21,A1\n"
    "    PEA     2.W\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_STRING_CompareN(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .advance_tag_match_node\n"
    "\n"
    "    MOVEQ   #1,D5\n"
    "\n"
    ".advance_tag_match_node:\n"
    "    TST.L   D5\n"
    "    BNE.S   .scan_brush_nodes_by_2char_tag\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  368(A0),-4(A5)\n"
    "    BRA.S   .scan_brush_nodes_by_2char_tag\n"
    "\n"
    ".use_script_selected_brush:\n"
    "    MOVEQ   #1,D5\n"
    "    MOVE.L  -24(A5),-4(A5)\n"
    "\n"
    ".ensure_fallback_selected_brush:\n"
    "    TST.L   D5\n"
    "    BNE.S   .clear_rastports_before_brush_blit\n"
    "\n"
    "    MOVE.L  BRUSH_SelectedNode,-4(A5)\n"
    "\n"
    ".clear_rastports_before_brush_blit:\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #31,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #31,D0\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    "    TST.L   -4(A5)\n"
    "    BEQ.S   .maybe_copy_brush_palette_segment\n"
    "\n"
    "    TST.L   BRUSH_SelectedNode\n"
    "    BNE.S   .blit_selected_brush_to_rast\n"
    "\n"
    "    TST.L   D5\n"
    "    BEQ.S   .maybe_copy_brush_palette_segment\n"
    "\n"
    ".blit_selected_brush_to_rast:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    MOVE.W  2(A0),D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  4(A0),D1\n"
    "    SUBQ.L  #1,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  Global_REF_RASTPORT_2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "\n"
    ".maybe_copy_brush_palette_segment:\n"
    "    TST.L   -4(A5)\n"
    "    BEQ.W   .restore_base_palette_when_no_brush\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    TST.L   328(A0)\n"
    "    BEQ.S   .prepare_plane_mask_bounds\n"
    "\n"
    "    MOVE.L  328(A0),D0\n"
    "    MOVEQ   #1,D1\n"
    "    CMP.L   D1,D0\n"
    "    BEQ.S   .prepare_plane_mask_bounds\n"
    "\n"
    "    SUBQ.L  #3,D0\n"
    "    BNE.S   .apply_brush_palette_mode_postprocess\n"
    "\n"
    ".prepare_plane_mask_bounds:\n"
    "    PEA     5.W\n"
    "    JSR     ESQPARS_JMPTBL_BRUSH_PlaneMaskForIndex(PC)\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    LSL.L   #2,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D4\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  184(A0),D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    JSR     ESQPARS_JMPTBL_BRUSH_PlaneMaskForIndex(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,D1\n"
    "    LSL.L   #2,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVEQ   #0,D6\n"
    "    MOVE.L  D1,-32(A5)\n"
    "\n"
    ".loop_copy_palette_bytes_from_brush:\n"
    "    CMP.L   -32(A5),D6\n"
    "    BGE.S   .apply_brush_palette_mode_postprocess\n"
    "\n"
    "    CMP.L   D4,D6\n"
    "    BGE.S   .apply_brush_palette_mode_postprocess\n"
    "\n"
    "    LEA     WDISP_PaletteTriplesRBase,A0\n"
    "    ADDA.L  D6,A0\n"
    "    MOVEA.L -4(A5),A1\n"
    "    MOVE.L  D6,D0\n"
    "    ADDI.L  #$e8,D0\n"
    "    MOVE.B  0(A1,D0.L),(A0)\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.S   .loop_copy_palette_bytes_from_brush\n"
    "\n"
    ".apply_brush_palette_mode_postprocess:\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L -4(A5),A0\n"
    "    CMP.L   328(A0),D0\n"
    "    BNE.S   .check_palette_mode_three\n"
    "\n"
    "    BSR.W   ESQIFF_RestoreBasePaletteTriples\n"
    "\n"
    "    BRA.S   .return\n"
    "\n"
    ".check_palette_mode_three:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.L   328(A0),D0\n"
    "    BNE.S   .return\n"
    "\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".loop_restore_first_12_palette_bytes:\n"
    "    MOVEQ   #12,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.S   .return\n"
    "\n"
    "    LEA     WDISP_PaletteTriplesRBase,A0\n"
    "    ADDA.L  D6,A0\n"
    "    LEA     ESQFUNC_BasePaletteRgbTriples,A1\n"
    "    ADDA.L  D6,A1\n"
    "    MOVE.B  (A1),(A0)\n"
    "    ADDQ.L  #1,D6\n"
    "    BRA.S   .loop_restore_first_12_palette_bytes\n"
    "\n"
    ".restore_base_palette_when_no_brush:\n"
    "    BSR.W   ESQIFF_RestoreBasePaletteTriples\n"
    "\n"
    ".return:\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEM.L (A7)+,D2/D4-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
