__asm__(
    ".globl _ESQFUNC_CommitSecondaryStateAndPersist\n"
    "_ESQFUNC_CommitSecondaryStateAndPersist:\n"
    "ESQFUNC_CommitSecondaryStateAndPersist:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.W  ESQPARS2_ReadModeFlags,D7\n"
    "    MOVE.W  #$100,ESQPARS2_ReadModeFlags\n"
    "    MOVE.W  #1,ESQDISP_PendingGridReinitFlag\n"
    "    BSR.W   ESQDISP_PropagatePrimaryTitleMetadataToSecondary\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_LOCAVAIL_RebuildFilterStateFromCurrentGroup(PC)\n"
    "\n"
    "    BSR.W   ESQDISP_PromoteSecondaryGroupToPrimary\n"
    "\n"
    "    BSR.W   ESQDISP_MirrorPrimaryEntriesToSecondaryIfEmpty\n"
    "\n"
    "    BSR.W   ESQDISP_PromoteSecondaryLineHeadTailIfMarked\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_DISKIO2_FlushDataFilesIfNeeded(PC)\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_LADFUNC_SaveTextAdsToFile(PC)\n"
    "\n"
    "    PEA     LOCAVAIL_SecondaryFilterState\n"
    "    PEA     LOCAVAIL_PrimaryFilterState\n"
    "    JSR     ESQPARS_JMPTBL_LOCAVAIL_SaveAvailabilityDataFile(PC)\n"
    "\n"
    "    PEA     DST_BannerWindowPrimary\n"
    "    JSR     DATETIME_SavePairToFile(PC)\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_P_TYPE_PromoteSecondaryList(PC)\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_P_TYPE_WritePromoIdDataFile(PC)\n"
    "\n"
    "    BSR.W   ESQFUNC_UpdateDiskWarningAndRefreshTick\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D7,ESQPARS2_ReadModeFlags\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
