__asm__(
    ".globl _ESQFUNC_RebuildPwBrushListFromTagTable\n"
    "_ESQFUNC_RebuildPwBrushListFromTagTable:\n"
    "ESQFUNC_RebuildPwBrushListFromTagTable:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVE.L  D7,-(A7)\n"
    "    CLR.L   -4(A5)\n"
    "    CLR.L   -(A7)\n"
    "    PEA     ESQFUNC_PwBrushListHead\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_build_pw_brush_descriptors:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.L   D0,D7\n"
    "    BGE.W   .return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     ESQFUNC_BrushDescriptorTagStrings,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_AllocBrushNode(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    TST.L   D7\n"
    "    BNE.S   .set_pw_descriptor_type_09\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  #$8,190(A0)\n"
    "    BRA.S   .link_pw_descriptor_or_advance\n"
    "\n"
    ".set_pw_descriptor_type_09:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  #$9,190(A0)\n"
    "\n"
    ".link_pw_descriptor_or_advance:\n"
    "    TST.L   ESQFUNC_PwBrushDescriptorHead\n"
    "    BNE.S   .advance_pw_descriptor_index\n"
    "\n"
    "    MOVE.L  -4(A5),ESQFUNC_PwBrushDescriptorHead\n"
    "\n"
    ".advance_pw_descriptor_index:\n"
    "    ADDQ.L  #1,D7\n"
    "    BRA.W   .loop_build_pw_brush_descriptors\n"
    "\n"
    ".return:\n"
    "    PEA     ESQFUNC_PwBrushListHead\n"
    "    MOVE.L  ESQFUNC_PwBrushDescriptorHead,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_PopulateBrushList(PC)\n"
    "\n"
    "    CLR.L   ESQFUNC_PwBrushDescriptorHead\n"
    "    MOVE.L  -12(A5),D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
