__asm__(
    ".globl _ESQFUNC_AllocateLineTextBuffers\n"
    "_ESQFUNC_AllocateLineTextBuffers:\n"
    "ESQFUNC_AllocateLineTextBuffers:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".lab_0964:\n"
    "    MOVEQ   #20,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     LADFUNC_LineTextBufferPtrs,A0\n"
    "    ADDA.L  D0,A0\n"
    "\n"
    "    MOVE.L  #65537,-(A7)\n"
    "    PEA     60.W\n"
    "    PEA     1222.W\n"
    "    PEA     Global_STR_ESQFUNC_C_5\n"
    "    MOVE.L  A0,20(A7)\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L 4(A7),A0\n"
    "    MOVE.L  D0,(A0)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .lab_0964\n"
    "\n"
    ".return:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,LADFUNC_LineSlotWriteIndex\n"
    "    MOVE.W  D0,LADFUNC_LineSlotSecondaryIndex\n"
    "    MOVE.L  (A7)+,D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
