__asm__(
    ".globl _ESQFUNC_ProcessUiFrameTick\n"
    "_ESQFUNC_ProcessUiFrameTick:\n"
    "ESQFUNC_ProcessUiFrameTick:\n"
    "    TST.W   GCOMMAND_DriveProbeRequestedFlag\n"
    "    BEQ.S   .lab_0971\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_DISKIO_ProbeDrivesAndAssignPaths(PC)\n"
    "\n"
    ".lab_0971:\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   ESQDISP_DisplayActiveFlag,D0\n"
    "    BNE.S   .lab_0972\n"
    "\n"
    "    BSR.W   ESQDISP_PollInputModeAndRefreshSelection\n"
    "\n"
    ".lab_0972:\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_0973\n"
    "\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    ".lab_0973:\n"
    "    JSR     ED_DispatchEscMenuState(PC)\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_0974\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_SCRIPT_HandleSerialCtrlCmd(PC)\n"
    "\n"
    ".lab_0974:\n"
    "    TST.W   CLEANUP_PendingAlertFlag\n"
    "    BEQ.W   .lab_097C\n"
    "\n"
    "    JSR     ESQFUNC_JMPTBL_CLEANUP_ProcessAlerts(PC)\n"
    "\n"
    "    TST.L   ESQDISP_SecondaryPersistRequestFlag\n"
    "    BEQ.S   .lab_0975\n"
    "\n"
    "    CLR.L   ESQDISP_SecondaryPersistRequestFlag\n"
    "    BSR.W   ESQFUNC_CommitSecondaryStateAndPersist\n"
    "\n"
    ".lab_0975:\n"
    "    TST.W   CTASKS_IffTaskDoneFlag\n"
    "    BEQ.W   .lab_097C\n"
    "\n"
    "    BTST    #1,ESQFUNC_IffTaskGateFlags\n"
    "    BEQ.S   .lab_0976\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_0976\n"
    "\n"
    "    BCLR    #1,ESQFUNC_IffTaskGateFlags\n"
    "    JSR     ESQFUNC_JMPTBL_TEXTDISP_ResetSelectionAndRefresh(PC)\n"
    "\n"
    "    BRA.S   .lab_0977\n"
    "\n"
    ".lab_0976:\n"
    "    BTST    #0,ESQFUNC_IffTaskGateFlags\n"
    "    BEQ.S   .lab_0977\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_0977\n"
    "\n"
    "    BCLR    #0,ESQFUNC_IffTaskGateFlags\n"
    "    PEA     1.W\n"
    "    JSR     ESQIFF_PlayNextExternalAssetFrame(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".lab_0977:\n"
    "    TST.L   Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    BNE.S   .lab_0978\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_0978\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetFlags,D0\n"
    "    MOVE.L  D0,D1\n"
    "    ANDI.W  #$fffd,D1\n"
    "    MOVE.W  D1,ESQIFF_ExternalAssetFlags\n"
    "\n"
    ".lab_0978:\n"
    "    MOVE.B  ED_DiagGraphModeChar,D0\n"
    "    MOVEQ   #78,D1\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.S   .lab_0979\n"
    "\n"
    "    TST.L   Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    BNE.S   .lab_0979\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_0979\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetFlags,D0\n"
    "    ANDI.W  #$fffe,D0\n"
    "    MOVE.W  D0,ESQIFF_ExternalAssetFlags\n"
    "\n"
    ".lab_0979:\n"
    "    TST.L   WDISP_WeatherStatusBrushListHead\n"
    "    BNE.S   .lab_097A\n"
    "\n"
    "    TST.L   PARSEINI_BannerBrushResourceHead\n"
    "    BEQ.S   .lab_097A\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    JSR     ESQIFF_QueueIffBrushLoad(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".lab_097A:\n"
    "    CMPI.L  #$1,ESQIFF_LogoBrushListCount\n"
    "    BGE.S   .lab_097B\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    JSR     ESQIFF_ServiceExternalAssetSourceState(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    BRA.S   .lab_097C\n"
    "\n"
    ".lab_097B:\n"
    "    MOVE.B  ED_DiagGraphModeChar,D0\n"
    "    MOVEQ   #78,D1\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.S   .lab_097C\n"
    "\n"
    "    CMPI.L  #$2,ESQIFF_GAdsBrushListCount\n"
    "    BGE.S   .lab_097C\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BNE.S   .lab_097C\n"
    "\n"
    "    PEA     1.W\n"
    "    JSR     ESQIFF_ServiceExternalAssetSourceState(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".lab_097C:\n"
    "    JSR     ESQFUNC_JMPTBL_TEXTDISP_TickDisplayState(PC)\n"
    "\n"
    "    TST.B   ESQDISP_StatusRefreshPendingFlag\n"
    "    BEQ.S   .return\n"
    "\n"
    "    TST.B   GCOMMAND_HighlightHoldoffTickCount\n"
    "    BNE.S   .return\n"
    "\n"
    "    CLR.B   ESQDISP_StatusRefreshPendingFlag\n"
    "    JSR     ESQDISP_RefreshStatusIndicatorsFromCurrentMask(PC)\n"
    "\n"
    ".return:\n"
    "    RTS\n"
);
