__asm__(
    ".globl _ESQFUNC_UpdateDiskWarningAndRefreshTick\n"
    "_ESQFUNC_UpdateDiskWarningAndRefreshTick:\n"
    "ESQFUNC_UpdateDiskWarningAndRefreshTick:\n"
    "    JSR     ESQFUNC_JMPTBL_DISKIO_ProbeDrivesAndAssignPaths(PC)\n"
    "\n"
    "    TST.L   DISKIO_Drive0WriteProtectedCode\n"
    "    BNE.S   .lab_096B\n"
    "\n"
    "    TST.L   DISKIO_DriveMediaStatusCodeTable\n"
    "    BNE.S   .lab_096A\n"
    "\n"
    "    MOVE.W  Global_RefreshTickCounter,D0\n"
    "    ADDQ.W  #1,D0\n"
    "    BNE.S   .lab_096C\n"
    "\n"
    "    CLR.W   Global_RefreshTickCounter\n"
    "    BRA.S   .lab_096C\n"
    "\n"
    ".lab_096A:\n"
    "    MOVE.W  #(-1),Global_RefreshTickCounter\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     90.W\n"
    "    PEA     Global_STR_DISK_0_IS_WRITE_PROTECTED\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    BRA.S   .lab_096C\n"
    "\n"
    ".lab_096B:\n"
    "    MOVE.W  #(-1),Global_RefreshTickCounter\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    PEA     90.W\n"
    "    PEA     Global_STR_YOU_MUST_REINSERT_SYSTEM_DISK_INTO_DRIVE_0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".lab_096C:\n"
    "    RTS\n"
);
