__asm__(
    ".globl _ESQFUNC_FreeExtraTitleTextPointers\n"
    "_ESQFUNC_FreeExtraTitleTextPointers:\n"
    "ESQFUNC_FreeExtraTitleTextPointers:\n"
    "    LINK.W  A5,#-20\n"
    "    MOVEM.L D4-D7,-(A7)\n"
    "\n"
    "    MOVE.W  10(A5),D7\n"
    "    MOVEQ   #0,D4\n"
    "\n"
    ".entry_loop:\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    CMP.W   D0,D4\n"
    "    BGE.S   .return_status\n"
    "\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-8(A5)\n"
    "    MOVEQ   #0,D6\n"
    "    MOVEQ   #34,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGT.S   .cap_limit\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    BRA.S   .set_limit\n"
    "\n"
    ".cap_limit:\n"
    "    MOVEQ   #34,D0\n"
    "\n"
    ".set_limit:\n"
    "    MOVE.L  D0,D5\n"
    "\n"
    ".slot_loop:\n"
    "    TST.W   D5\n"
    "    BMI.S   .next_entry\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L 56(A0,D0.L),A0\n"
    "    MOVE.L  A0,-12(A5)\n"
    "    MOVE.L  A0,D0\n"
    "    BEQ.S   .next_slot\n"
    "\n"
    "    TST.W   D6\n"
    "    BEQ.S   .mark_first_seen\n"
    "\n"
    "    MOVE.L  A0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    JSR     ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L -8(A5),A0\n"
    "    CLR.L   56(A0,D0.L)\n"
    "    BRA.S   .next_slot\n"
    "\n"
    ".mark_first_seen:\n"
    "    MOVEQ   #1,D6\n"
    "\n"
    ".next_slot:\n"
    "    SUBQ.W  #1,D5\n"
    "    BRA.S   .slot_loop\n"
    "\n"
    ".next_entry:\n"
    "    ADDQ.W  #1,D4\n"
    "    BRA.S   .entry_loop\n"
    "\n"
    ".return_status:\n"
    "    MOVEM.L (A7)+,D4-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
