__asm__(
    ".globl _ESQIFF2_ShowVersionMismatchOverlay\n"
    "_ESQIFF2_ShowVersionMismatchOverlay:\n"
    "ESQIFF2_ShowVersionMismatchOverlay:\n"
    "    LINK.W  A5,#-40\n"
    "    MOVEM.L D2-D3,-(A7)\n"
    "\n"
    "    MOVEA.L ESQIFF_RecordBufferPtr,A0\n"
    "    CLR.B   20(A0)\n"
    "    MOVE.L  Global_LONG_PATCH_VERSION_NUMBER,-(A7)\n"
    "    PEA     Global_STR_MAJOR_MINOR_VERSION_1\n"
    "    PEA     ESQIFF_FMT_PCT_S_DOT_PCT_LD\n"
    "    PEA     -40(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    MOVEA.L ESQIFF_RecordBufferPtr,A0\n"
    "    ADDQ.L  #1,A0\n"
    "    MOVE.L  A0,(A7)\n"
    "    PEA     -40(A5)\n"
    "    JSR     ESQSHARED_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    TST.B   D0\n"
    "    BEQ.W   ESQIFF2_ShowVersionMismatchOverlay_Return\n"
    "\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BEQ.S   .lab_0B23\n"
    "\n"
    "    TST.W   ED_DiagnosticsScreenActive\n"
    "    BEQ.W   ESQIFF2_ShowVersionMismatchOverlay_Return\n"
    "\n"
    ".lab_0B23:\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVODisable(A6)\n"
    "\n"
    "    MOVE.W  #$100,ESQPARS2_ReadModeFlags\n"
    "    JSR     GCOMMAND_SeedBannerFromPrefs(PC)\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOEnable(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    CLR.W   ED_DiagnosticsScreenActive\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #2,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEQ   #60,D1\n"
    "    MOVE.L  #679,D2\n"
    "    MOVEQ   #100,D3\n"
    "    NOT.B   D3\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #3,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    PEA     ESQIFF_STR_INCORRECT_VERSION_PLEASE_CORRECT_ASA\n"
    "    PEA     90.W\n"
    "    PEA     30.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVE.L  Global_LONG_PATCH_VERSION_NUMBER,(A7)\n"
    "    PEA     Global_STR_MAJOR_MINOR_VERSION_2\n"
    "    PEA     ESQIFF_FMT_YOUR_VERSION_IS_PCT_S_DOT_PCT_LD\n"
    "    PEA     -40(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -40(A5)\n"
    "    PEA     120.W\n"
    "    PEA     30.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     ESQIFF_STR_CORRECT_VERSION_IS,A0\n"
    "    LEA     -40(A5),A1\n"
    "    MOVEQ   #4,D0\n"
    "\n"
    ".lab_0B24:\n"
    "    MOVE.L  (A0)+,(A1)+\n"
    "    DBF     D0,.lab_0B24\n"
    "\n"
    "    CLR.B   (A1)\n"
    "    MOVEA.L ESQIFF_RecordBufferPtr,A0\n"
    "    ADDQ.L  #1,A0\n"
    "    MOVE.L  A0,(A7)\n"
    "    PEA     -40(A5)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    PEA     Global_STR_APOSTROPHE\n"
    "    PEA     -40(A5)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    PEA     -40(A5)\n"
    "    PEA     150.W\n"
    "    PEA     30.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     72(A7),A7\n"
);
