__asm__(
    ".globl _ESQIFF2_ValidateAsciiNumericByte\n"
    "_ESQIFF2_ValidateAsciiNumericByte:\n"
    "ESQIFF2_ValidateAsciiNumericByte:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.B  11(A7),D7\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.B   D0,D7\n"
    "    BLT.S   .return\n"
    "\n"
    "    MOVEQ   #48,D1\n"
    "    CMP.B   D1,D7\n"
    "    BGT.S   .return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
