__asm__(
    ".globl _ESQIFF2_ClearPrimaryEntryFlags34To39\n"
    "_ESQIFF2_ClearPrimaryEntryFlags34To39:\n"
    "ESQIFF2_ClearPrimaryEntryFlags34To39:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D6-D7,-(A7)\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".lab_0B30:\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   ESQIFF2_ClearPrimaryEntryFlags34To39_Return\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".lab_0B31:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGE.S   .lab_0B32\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    CLR.B   34(A0,D6.W)\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .lab_0B31\n"
    "\n"
    ".lab_0B32:\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .lab_0B30\n"
);
