__asm__(
    ".globl _ESQIFF_SetApenToBrightestPaletteIndex\n"
    "_ESQIFF_SetApenToBrightestPaletteIndex:\n"
    "ESQIFF_SetApenToBrightestPaletteIndex:\n"
    "    LINK.W  A5,#-16\n"
    "    MOVEM.L D2/D4-D7,-(A7)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_PaletteDepthLog2,D0\n"
    "    MOVEQ   #1,D1\n"
    "    ASL.L   D0,D1\n"
    "    MOVE.L  D1,D4\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_PaletteTriplesRBase,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_PaletteTriplesGBase,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_PaletteTriplesBBase,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.L  D0,D6\n"
    "    CLR.L   -14(A5)\n"
    "    MOVEQ   #1,D7\n"
    "\n"
    ".loop_palette_entries:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    CMP.L   D4,D0\n"
    "    BGE.S   .apply_best_palette_index\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEQ   #3,D1\n"
    "    MULS    D1,D0\n"
    "    LEA     WDISP_PaletteTriplesRBase,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  D7,D0\n"
    "    MULS    D1,D0\n"
    "    LEA     WDISP_PaletteTriplesGBase,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A0),D0\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.B  (A1),D2\n"
    "    ADD.L   D2,D0\n"
    "    MOVE.L  D7,D2\n"
    "    MULS    D1,D2\n"
    "    LEA     WDISP_PaletteTriplesBBase,A0\n"
    "    ADDA.L  D2,A0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  (A0),D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.L  D0,D5\n"
    "    CMP.W   D5,D6\n"
    "    BGE.S   .next_palette_entry\n"
    "\n"
    "    MOVE.L  D5,D6\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-14(A5)\n"
    "\n"
    ".next_palette_entry:\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .loop_palette_entries\n"
    "\n"
    ".apply_best_palette_index:\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    LEA     Global_REF_RASTPORT_2+2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  -14(A5),D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEM.L (A7)+,D2/D4-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
