__asm__(
    ".globl _ESQIFF_RunPendingCopperAnimations\n"
    "_ESQIFF_RunPendingCopperAnimations:\n"
    "ESQIFF_RunPendingCopperAnimations:\n"
    "    MOVE.W  COPPER_AnimationLane0_Countdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.S   .service_lane_1b1a\n"
    "\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_NoOp_006A(PC)\n"
    "\n"
    "    MOVE.W  COPPER_AnimationLane0_Countdown,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    MOVE.W  D0,COPPER_AnimationLane0_Countdown\n"
    "    BRA.S   ESQIFF_RunPendingCopperAnimations\n"
    "\n"
    ".service_lane_1b1a:\n"
    "    MOVE.W  COPPER_AnimationLane1_Countdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.S   .service_lane_1b1b\n"
    "\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_NoOp_0074(PC)\n"
    "\n"
    "    MOVE.W  COPPER_AnimationLane1_Countdown,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    MOVE.W  D0,COPPER_AnimationLane1_Countdown\n"
    "    BRA.S   .service_lane_1b1a\n"
    "\n"
    ".service_lane_1b1b:\n"
    "    MOVE.W  COPPER_AnimationLane2_Countdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.S   .service_lane_1b1c\n"
    "\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_DecCopperListsPrimary(PC)\n"
    "\n"
    "    MOVE.W  COPPER_AnimationLane2_Countdown,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    MOVE.W  D0,COPPER_AnimationLane2_Countdown\n"
    "    BRA.S   .service_lane_1b1b\n"
    "\n"
    ".service_lane_1b1c:\n"
    "    MOVE.W  COPPER_AnimationLane3_Countdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.S   .return_run_pending_copper_animations\n"
    "\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_IncCopperListsTowardsTargets(PC)\n"
    "\n"
    "    MOVE.W  COPPER_AnimationLane3_Countdown,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    MOVE.W  D0,COPPER_AnimationLane3_Countdown\n"
    "    BRA.S   .service_lane_1b1c\n"
    "\n"
    ".return_run_pending_copper_animations:\n"
    "    RTS\n"
);
