__asm__(
    ".globl _ESQIFF2_ReadSerialSizedTextRecord\n"
    "_ESQIFF2_ReadSerialSizedTextRecord:\n"
    "ESQIFF2_ReadSerialSizedTextRecord:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D4-D7/A3,-(A7)\n"
    "    MOVEA.L 32(A7),A3\n"
    "    MOVE.L  36(A7),D7\n"
    "    TST.L   D7\n"
    "    BLE.S   .reject_invalid_size\n"
    "\n"
    "    CMPI.L  #$2328,D7\n"
    "    BLT.S   .begin_initial_payload_read\n"
    "\n"
    ".reject_invalid_size:\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   ESQIFF2_ReadSerialSizedTextRecord_Return\n"
    "\n"
    ".begin_initial_payload_read:\n"
    "    MOVEQ   #0,D6\n"
    "    MOVEQ   #0,D4\n"
    "\n"
    ".loop_read_initial_payload:\n"
    "    CMP.L   D7,D6\n"
    "    BGE.S   .parse_trailer_length\n"
    "\n"
    "    CMPI.L  #$2328,D6\n"
    "    BGE.S   .parse_trailer_length\n"
    "\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    MOVE.L  D0,20(A7)\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    MOVE.B  D0,0(A3,D1.L)\n"
    "    ADDQ.L  #1,D6\n"
    "    ADDQ.W  #1,D4\n"
    "    BRA.S   .loop_read_initial_payload\n"
    "\n"
    ".parse_trailer_length:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    CLR.B   0(A3,D0.L)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    MOVE.B  #$20,0(A3,D0.L)\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".loop_read_trailer_bytes:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    TST.B   -1(A3,D0.L)\n"
    "    BEQ.S   .validate_trailer_completion\n"
    "\n"
    "    CMP.L   D5,D6\n"
    "    BGE.S   .validate_trailer_completion\n"
    "\n"
    "    CMPI.W  #$2328,D4\n"
    "    BCC.S   .validate_trailer_completion\n"
    "\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    MOVE.L  D0,20(A7)\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    MOVE.B  D0,0(A3,D1.L)\n"
    "    ADDQ.L  #1,D6\n"
    "    ADDQ.W  #1,D4\n"
    "    BRA.S   .loop_read_trailer_bytes\n"
    "\n"
    ".validate_trailer_completion:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    TST.B   -1(A3,D0.L)\n"
    "    BNE.S   .fail_trailer_validation\n"
    "\n"
    "    CMP.L   D5,D6\n"
    "    BEQ.S   .read_trailing_checksum\n"
    "\n"
    ".fail_trailer_validation:\n"
    "    MOVEQ   #0,D4\n"
    "    CLR.B   (A3)\n"
    "    BRA.S   .finish_sized_record_read\n"
    "\n"
    ".read_trailing_checksum:\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.B  D0,ESQIFF_RecordChecksumByte\n"
    "\n"
    ".finish_sized_record_read:\n"
    "    MOVE.L  D4,D0\n"
);
