__asm__(
    ".globl _ESQIFF_ServicePendingCopperPaletteMoves\n"
    "_ESQIFF_ServicePendingCopperPaletteMoves:\n"
    "ESQIFF_ServicePendingCopperPaletteMoves:\n"
    "    MOVE.L  A4,-(A7)\n"
    "    LEA     Global_REF_LONG_FILE_SCRATCH,A4\n"
    "    MOVE.W  ACCUMULATOR_Row0_SaturateFlag,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .service_row1_pending_move\n"
    "\n"
    "    TST.W   WDISP_AccumulatorRow0_MoveFlags\n"
    "    BEQ.S   .service_row1_pending_move\n"
    "\n"
    "    CLR.W   ACCUMULATOR_Row0_SaturateFlag\n"
    "    MOVE.W  WDISP_AccumulatorRow0_MoveFlags,D0\n"
    "    BTST    #1,D0\n"
    "    BEQ.S   .move_row0_toward_start\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow0_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow0_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardEnd(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .service_row1_pending_move\n"
    "\n"
    ".move_row0_toward_start:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow0_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow0_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardStart(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".service_row1_pending_move:\n"
    "    MOVE.W  ACCUMULATOR_Row1_SaturateFlag,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .service_row2_pending_move\n"
    "\n"
    "    TST.W   WDISP_AccumulatorRow1_MoveFlags\n"
    "    BEQ.S   .service_row2_pending_move\n"
    "\n"
    "    CLR.W   ACCUMULATOR_Row1_SaturateFlag\n"
    "    MOVE.W  WDISP_AccumulatorRow1_MoveFlags,D0\n"
    "    BTST    #1,D0\n"
    "    BEQ.S   .move_row1_toward_start\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow1_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow1_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardEnd(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .service_row2_pending_move\n"
    "\n"
    ".move_row1_toward_start:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow1_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow1_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardStart(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".service_row2_pending_move:\n"
    "    MOVE.W  ACCUMULATOR_Row2_SaturateFlag,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .service_row3_pending_move\n"
    "\n"
    "    TST.W   WDISP_AccumulatorRow2_MoveFlags\n"
    "    BEQ.S   .service_row3_pending_move\n"
    "\n"
    "    CLR.W   ACCUMULATOR_Row2_SaturateFlag\n"
    "    MOVE.W  WDISP_AccumulatorRow2_MoveFlags,D0\n"
    "    BTST    #1,D0\n"
    "    BEQ.S   .move_row2_toward_start\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow2_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow2_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardEnd(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .service_row3_pending_move\n"
    "\n"
    ".move_row2_toward_start:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow2_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow2_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardStart(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".service_row3_pending_move:\n"
    "    MOVE.W  ACCUMULATOR_Row3_SaturateFlag,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .return_service_pending_copper_moves\n"
    "\n"
    "    TST.W   WDISP_AccumulatorRow3_MoveFlags\n"
    "    BEQ.S   .return_service_pending_copper_moves\n"
    "\n"
    "    CLR.W   ACCUMULATOR_Row3_SaturateFlag\n"
    "    MOVE.W  WDISP_AccumulatorRow3_MoveFlags,D0\n"
    "    BTST    #1,D0\n"
    "    BEQ.S   .move_row3_toward_start\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow3_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow3_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardEnd(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.S   .return_service_pending_copper_moves\n"
    "\n"
    ".move_row3_toward_start:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_AccumulatorRow3_CopperIndexStart,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  WDISP_AccumulatorRow3_CopperIndexEnd,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardStart(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".return_service_pending_copper_moves:\n"
    "    MOVEA.L (A7)+,A4\n"
    "    RTS\n"
);
