__asm__(
    ".globl _ESQIFF2_ParseLineHeadTailRecord\n"
    "_ESQIFF2_ParseLineHeadTailRecord:\n"
    "ESQIFF2_ParseLineHeadTailRecord:\n"
    "    MOVEM.L D6-D7/A3,-(A7)\n"
    "    MOVEA.L 16(A7),A3\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A3),D0\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "    AND.L   D1,D0\n"
    "    MOVE.L  D0,D7\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.W   .check_secondary_group\n"
    "\n"
    "    PEA     1.W\n"
    "    BSR.W   ESQIFF2_ClearLineHeadTailByMode\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #18,D0\n"
    "    CMP.B   1(A3),D0\n"
    "    BNE.S   .primary_split_or_head_only\n"
    "\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,ESQIFF_PrimaryLineHeadPtr\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  ESQIFF_RecordLength,D1\n"
    "    CMP.B   -1(A3,D1.L),D0\n"
    "    BNE.S   .primary_tail_only_from_payload\n"
    "\n"
    "    MOVE.L  A0,ESQIFF_PrimaryLineTailPtr\n"
    "    BRA.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".primary_tail_only_from_payload:\n"
    "    LEA     2(A3),A0\n"
    "    MOVE.L  ESQIFF_PrimaryLineTailPtr,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,ESQIFF_PrimaryLineTailPtr\n"
    "    BRA.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".primary_split_or_head_only:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  ESQIFF_RecordLength,D0\n"
    "    MOVEQ   #18,D1\n"
    "    CMP.B   -1(A3,D0.L),D1\n"
    "    BNE.S   .primary_scan_internal_delimiter\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    CLR.B   -1(A3,D1.L)\n"
    "    LEA     1(A3),A0\n"
    "    MOVE.L  ESQIFF_PrimaryLineHeadPtr,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,ESQIFF_PrimaryLineHeadPtr\n"
    "    CLR.L   ESQIFF_PrimaryLineTailPtr\n"
    "    BRA.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".primary_scan_internal_delimiter:\n"
    "    MOVEQ   #3,D6\n"
    "\n"
    ".loop_primary_find_delimiter:\n"
    "    MOVEQ   #18,D0\n"
    "    CMP.B   0(A3,D6.W),D0\n"
    "    BEQ.S   .primary_split_at_found_delimiter\n"
    "\n"
    "    MOVEQ   #103,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGE.S   .primary_split_at_found_delimiter\n"
    "\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .loop_primary_find_delimiter\n"
    "\n"
    ".primary_split_at_found_delimiter:\n"
    "    CLR.B   0(A3,D6.W)\n"
    "    LEA     1(A3),A0\n"
    "    MOVE.L  ESQIFF_PrimaryLineHeadPtr,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    MOVE.L  D0,ESQIFF_PrimaryLineHeadPtr\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  D0,A0\n"
    "    LEA     1(A0),A1\n"
    "    MOVE.L  ESQIFF_PrimaryLineTailPtr,(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,ESQIFF_PrimaryLineTailPtr\n"
    "    BRA.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".check_secondary_group:\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    "    PEA     2.W\n"
    "    BSR.W   ESQIFF2_ClearLineHeadTailByMode\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.W  #1,ESQDISP_SecondaryLinePromotePendingFlag\n"
    "    MOVEQ   #18,D0\n"
    "    CMP.B   1(A3),D0\n"
    "    BNE.S   .secondary_split_or_head_only\n"
    "\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,ESQIFF_SecondaryLineHeadPtr\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  ESQIFF_RecordLength,D1\n"
    "    CMP.B   -1(A3,D1.L),D0\n"
    "    BNE.S   .secondary_tail_only_from_payload\n"
    "\n"
    "    MOVE.L  A0,ESQIFF_SecondaryLineTailPtr\n"
    "    BRA.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".secondary_tail_only_from_payload:\n"
    "    LEA     2(A3),A0\n"
    "    MOVE.L  ESQIFF_SecondaryLineTailPtr,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,ESQIFF_SecondaryLineTailPtr\n"
    "    BRA.W   ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".secondary_split_or_head_only:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  ESQIFF_RecordLength,D0\n"
    "    MOVEQ   #18,D1\n"
    "    CMP.B   -1(A3,D0.L),D1\n"
    "    BNE.S   .secondary_scan_internal_delimiter\n"
    "\n"
    "    LEA     1(A3),A0\n"
    "    MOVE.L  ESQIFF_SecondaryLineHeadPtr,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,ESQIFF_SecondaryLineHeadPtr\n"
    "    CLR.L   ESQIFF_SecondaryLineTailPtr\n"
    "    JMP     ESQIFF2_ParseLineHeadTailRecord_Return\n"
    "\n"
    ".secondary_scan_internal_delimiter:\n"
    "    MOVEQ   #3,D6\n"
    "\n"
    ".loop_secondary_find_delimiter:\n"
    "    MOVEQ   #18,D0\n"
    "    CMP.B   0(A3,D6.W),D0\n"
    "    BEQ.S   .secondary_split_at_found_delimiter\n"
    "\n"
    "    MOVEQ   #103,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGE.S   .secondary_split_at_found_delimiter\n"
    "\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .loop_secondary_find_delimiter\n"
    "\n"
    ".secondary_split_at_found_delimiter:\n"
    "    CLR.B   0(A3,D6.W)\n"
    "    LEA     1(A3),A0\n"
    "    MOVE.L  ESQIFF_SecondaryLineHeadPtr,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    MOVE.L  D0,ESQIFF_SecondaryLineHeadPtr\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A3,A0\n"
    "    ADDA.L  D0,A0\n"
    "    LEA     1(A0),A1\n"
    "    MOVE.L  ESQIFF_SecondaryLineTailPtr,(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,ESQIFF_SecondaryLineTailPtr\n"
);
