__asm__(
    ".globl _ESQIFF_PlayNextExternalAssetFrame\n"
    "_ESQIFF_PlayNextExternalAssetFrame:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D6-D7,-(A7)\n"
    "    MOVE.W  10(A5),D7\n"
    "    BSR.W   ESQIFF_RunCopperDropTransition\n"
    "\n"
    "    TST.W   D7\n"
    "    BEQ.S   .check_logo_head_fallback\n"
    "\n"
    "    TST.L   ESQIFF_GAdsBrushListHead\n"
    "    BNE.S   .validate_asset_list_and_match_index\n"
    "\n"
    ".check_logo_head_fallback:\n"
    "    TST.W   D7\n"
    "    BNE.W   .fallback_restore_base_palette\n"
    "\n"
    "    TST.L   ESQIFF_LogoBrushListHead\n"
    "    BEQ.W   .fallback_restore_base_palette\n"
    "\n"
    ".validate_asset_list_and_match_index:\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    MOVE.W  ESQIFF_ExternalAssetStateTable,D1\n"
    "    CMP.W   D1,D0\n"
    "    BCC.S   .prepare_display_context_for_asset_blit\n"
    "\n"
    "    TST.W   D7\n"
    "    BNE.S   .prepare_display_context_for_asset_blit\n"
    "\n"
    "    TST.W   ESQIFF_ExternalAssetPathCommaFlag\n"
    "    BNE.S   .prepare_display_context_for_asset_blit\n"
    "\n"
    "    BSR.W   ESQIFF_RestoreBasePaletteTriples\n"
    "\n"
    "    JSR     GROUP_AM_JMPTBL_ESQ_SetCopperEffect_OffDisableHighlight(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    JSR     ESQFUNC_JMPTBL_TEXTDISP_SetRastForMode(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    BRA.W   .run_rise_transition_and_service_source\n"
    "\n"
    ".prepare_display_context_for_asset_blit:\n"
    "    JSR     GROUP_AM_JMPTBL_ESQ_SetCopperEffect_OffDisableHighlight(PC)\n"
    "\n"
    "    PEA     1.W\n"
    "    CLR.L   -(A7)\n"
    "    PEA     4.W\n"
    "    JSR     ESQIFF_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    MOVEA.L D0,A0\n"
    "    ADDA.W  #-458,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #2,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.W   D7\n"
    "    BEQ.S   .select_logo_head_for_blit\n"
    "\n"
    "    MOVEA.L ESQIFF_GAdsBrushListHead,A0\n"
    "    BRA.S   .run_asset_frame_side_effects\n"
    "\n"
    ".select_logo_head_for_blit:\n"
    "    MOVEA.L ESQIFF_LogoBrushListHead,A0\n"
    "\n"
    ".run_asset_frame_side_effects:\n"
    "    MOVE.L  A0,-6(A5)\n"
    "    JSR     ESQIFF_JMPTBL_ESQ_NoOp(PC)\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .render_selected_asset_frame\n"
    "\n"
    "    MOVE.W  TEXTDISP_DeferredActionCountdown,D0\n"
    "    SUBQ.W  #2,D0\n"
    "    BEQ.S   .assert_ctrl_line_for_deferred_tick\n"
    "\n"
    "    MOVE.W  TEXTDISP_DeferredActionCountdown,D0\n"
    "    SUBQ.W  #3,D0\n"
    "    BNE.S   .render_selected_asset_frame\n"
    "\n"
    ".assert_ctrl_line_for_deferred_tick:\n"
    "    JSR     ESQIFF_JMPTBL_SCRIPT_AssertCtrlLineIfEnabled(PC)\n"
    "\n"
    ".render_selected_asset_frame:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF_ShowExternalAssetWithCopperFx\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    TST.W   D7\n"
    "    BNE.S   .pop_rendered_asset_head\n"
    "\n"
    "    TST.W   ESQIFF_ExternalAssetPathCommaFlag\n"
    "    BNE.S   .pop_rendered_asset_head\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    ADDA.W  #-458,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    BSR.W   ESQIFF_SetApenToBrightestPaletteIndex\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetStateTable,TEXTDISP_CurrentMatchIndex\n"
    "    PEA     2.W\n"
    "    PEA     1.W\n"
    "    JSR     ESQIFF_JMPTBL_TEXTDISP_DrawChannelBanner(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    ADDA.W  #-458,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    ".pop_rendered_asset_head:\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    ADDA.W  #-458,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    TST.W   D7\n"
    "    BEQ.S   .pop_logo_brush_head\n"
    "\n"
    "    SUBQ.L  #1,ESQIFF_GAdsBrushListCount\n"
    "    MOVE.L  ESQIFF_GAdsBrushListHead,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_PopBrushHead(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,ESQIFF_GAdsBrushListHead\n"
    "    BRA.S   .permit_after_pop\n"
    "\n"
    ".pop_logo_brush_head:\n"
    "    SUBQ.L  #1,ESQIFF_LogoBrushListCount\n"
    "    MOVE.L  ESQIFF_LogoBrushListHead,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_PopBrushHead(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,ESQIFF_LogoBrushListHead\n"
    "\n"
    ".permit_after_pop:\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    BRA.S   .run_rise_transition_and_service_source\n"
    "\n"
    ".fallback_restore_base_palette:\n"
    "    BSR.W   ESQIFF_RestoreBasePaletteTriples\n"
    "\n"
    "    JSR     GROUP_AM_JMPTBL_ESQ_SetCopperEffect_OffDisableHighlight(PC)\n"
    "\n"
    "    PEA     2.W\n"
    "    JSR     ESQFUNC_JMPTBL_TEXTDISP_SetRastForMode(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".run_rise_transition_and_service_source:\n"
    "    MOVE.W  WDISP_AccumulatorCaptureActive,D6\n"
    "    CLR.W   WDISP_AccumulatorCaptureActive\n"
    "    BSR.W   ESQIFF_RunCopperRiseTransition\n"
    "\n"
    "    MOVE.W  D6,WDISP_AccumulatorCaptureActive\n"
    "    TST.W   D7\n"
    "    BEQ.S   .service_source_mode_zero\n"
    "\n"
    "    PEA     1.W\n"
    "    BSR.W   ESQIFF_ServiceExternalAssetSourceState\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    JMP     ESQIFF_PlayNextExternalAssetFrame_Return\n"
    "\n"
    ".service_source_mode_zero:\n"
    "    CLR.L   -(A7)\n"
    "    BSR.W   ESQIFF_ServiceExternalAssetSourceState\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
);
