__asm__(
    ".globl _ESQIFF2_ReadRbfBytesWithXor\n"
    "_ESQIFF2_ReadRbfBytesWithXor:\n"
    "ESQIFF2_ReadRbfBytesWithXor:\n"
    "    MOVEM.L D6-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 20(A7),A3\n"
    "    MOVE.W  26(A7),D7\n"
    "    MOVEA.L 28(A7),A2\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".loop_read_serial_byte_with_xor:\n"
    "    CMP.W   D7,D6\n"
    "    BGE.S   ESQIFF2_ReadSerialBytesWithXor_Return\n"
    "\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.B  D0,(A3)\n"
    "    ADDQ.L  #1,A3\n"
    "    EOR.B   D0,(A2)\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .loop_read_serial_byte_with_xor\n"
);
