__asm__(
    ".globl _ESQIFF_DeallocateAdsAndLogoLstData\n"
    "_ESQIFF_DeallocateAdsAndLogoLstData:\n"
    "ESQIFF_DeallocateAdsAndLogoLstData:\n"
    "    TST.L   Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    BEQ.S   .deallocLogoLstData\n"
    "\n"
    "    TST.L   Global_REF_LONG_GFX_G_ADS_FILESIZE\n"
    "    BEQ.S   .deallocLogoLstData\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_FILESIZE,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_DATA,-(A7)\n"
    "    PEA     1988.W\n"
    "    PEA     Global_STR_ESQIFF_C_7\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    CLR.L   Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    CLR.L   Global_REF_LONG_GFX_G_ADS_FILESIZE\n"
    "\n"
    ".deallocLogoLstData:\n"
    "    TST.L   Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    BEQ.S   .return\n"
    "\n"
    "    TST.L   Global_REF_LONG_DF0_LOGO_LST_FILESIZE\n"
    "    BEQ.S   .return\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_FILESIZE,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_DATA,-(A7)\n"
    "    PEA     1994.W\n"
    "    PEA     Global_STR_ESQIFF_C_8\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    CLR.L   Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    CLR.L   Global_REF_LONG_DF0_LOGO_LST_FILESIZE\n"
    "\n"
    ".return:\n"
    "    RTS\n"
);
