__asm__(
    ".globl _ESQIFF2_ReadSerialRecordIntoBuffer\n"
    "_ESQIFF2_ReadSerialRecordIntoBuffer:\n"
    "ESQIFF2_ReadSerialRecordIntoBuffer:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D4-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVE.W  18(A5),D6\n"
    "    MOVEQ   #0,D4\n"
    "    MOVE.W  D4,-6(A5)\n"
    "\n"
    ".loop_read_record_body:\n"
    "    CMPI.W  #$2328,D4\n"
    "    BCC.W   .read_and_store_trailing_checksum\n"
    "\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    MOVE.L  D0,20(A7)\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    MOVE.B  D0,0(A3,D1.L)\n"
    "    TST.B   D0\n"
    "    BNE.S   .check_escape_or_delimiter_bytes\n"
    "\n"
    "    TST.W   D7\n"
    "    BNE.S   .guard_short_record_terminator\n"
    "\n"
    "    BRA.W   .read_and_store_trailing_checksum\n"
    "\n"
    ".guard_short_record_terminator:\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D4\n"
    "    BHI.W   .read_and_store_trailing_checksum\n"
    "\n"
    ".check_escape_or_delimiter_bytes:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    MOVEQ   #20,D1\n"
    "    CMP.B   0(A3,D0.L),D1\n"
    "    BNE.S   .check_0x12_delimiter_case\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .check_0x12_delimiter_case\n"
    "\n"
    "    ADDQ.W  #1,D4\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".loop_copy_0x14_extension:\n"
    "    CMP.W   D6,D5\n"
    "    BCC.S   .loop_read_record_body\n"
    "\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    MOVE.L  D4,D0\n"
    "    ADDQ.W  #1,D4\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    MOVE.L  D1,20(A7)\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    MOVE.B  D0,0(A3,D1.L)\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.S   .loop_copy_0x14_extension\n"
    "\n"
    ".check_0x12_delimiter_case:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D4,D0\n"
    "    MOVEQ   #18,D1\n"
    "    CMP.B   0(A3,D0.L),D1\n"
    "    BNE.S   .advance_record_offset\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .advance_record_offset\n"
    "\n"
    "    ADDQ.W  #1,D4\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    MOVE.L  D4,D0\n"
    "    ADDQ.W  #1,D4\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    MOVE.L  D1,20(A7)\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.L  20(A7),D1\n"
    "    MOVE.B  D0,0(A3,D1.L)\n"
    "    ADDQ.W  #1,-6(A5)\n"
    "    CMPI.W  #$12e,-6(A5)\n"
    "    BCS.W   .loop_read_record_body\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    JMP     ESQIFF2_ReadSerialRecordIntoBuffer_Return\n"
    "\n"
    ".advance_record_offset:\n"
    "    ADDQ.W  #1,D4\n"
    "    BRA.W   .loop_read_record_body\n"
    "\n"
    ".read_and_store_trailing_checksum:\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVE.B  D0,ESQIFF_RecordChecksumByte\n"
    "    MOVE.L  D4,D0\n"
);
