__asm__(
    ".globl _ESQIFF_QueueIffBrushLoad\n"
    "_ESQIFF_QueueIffBrushLoad:\n"
    "ESQIFF_QueueIffBrushLoad:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.L  8(A7),D7\n"
    "    TST.L   ESQIFF_BannerBrushResourceCursor\n"
    "    BEQ.S   .seed_resource_cursor\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.S   .skip_resource_seed\n"
    "\n"
    ".seed_resource_cursor:\n"
    "    MOVE.L  PARSEINI_BannerBrushResourceHead,ESQIFF_BannerBrushResourceCursor\n"
    "\n"
    ".skip_resource_seed:\n"
    "    MOVEQ   #0,D0\n"
    "    TST.L   D0\n"
    "    BEQ.W   .queue_standard_iff_task\n"
    "\n"
    "    PEA     ESQIFF_STR_WEATHER\n"
    "    MOVE.L  ESQIFF_BannerBrushResourceCursor,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_STRING_CompareNoCase(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .render_weather_overlay_now\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.W   .queue_standard_iff_task\n"
    "\n"
    ".render_weather_overlay_now:\n"
    "    MOVE.B  WDISP_WeatherStatusCountdown,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.B   D1,D0\n"
    "    BLS.W   .finalize_and_advance_resource_cursor\n"
    "\n"
    "    MOVE.W  WDISP_WeatherStatusDigitChar,D0\n"
    "    MOVEQ   #48,D1\n"
    "    CMP.W   D1,D0\n"
    "    BEQ.W   .finalize_and_advance_resource_cursor\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  ESQIFF_BannerBrushResourceCursor,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_AllocBrushNode(PC)\n"
    "\n"
    "    MOVE.L  D0,CTASKS_PendingIffBrushDescriptor\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.B  #11,190(A0)\n"
    "    MOVEA.L CTASKS_PendingIffBrushDescriptor,A0\n"
    "    MOVE.W  #$280,128(A0)\n"
    "    MOVEA.L CTASKS_PendingIffBrushDescriptor,A0\n"
    "    MOVE.W  #160,130(A0)\n"
    "    MOVEA.L CTASKS_PendingIffBrushDescriptor,A0\n"
    "    MOVE.B  #3,136(A0)\n"
    "    MOVE.L  CTASKS_PendingIffBrushDescriptor,(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_CloneBrushRecord(PC)\n"
    "\n"
    "    MOVE.L  D0,WDISP_WeatherStatusBrushListHead\n"
    "    MOVE.L  D0,(A7)\n"
    "    BSR.W   ESQIFF_DrawWeatherStatusOverlayIntoBrush\n"
    "\n"
    "    PEA     238.W\n"
    "    MOVE.L  CTASKS_PendingIffBrushDescriptor,-(A7)\n"
    "    PEA     724.W\n"
    "    PEA     Global_STR_ESQIFF_C_2\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    BRA.S   .finalize_and_advance_resource_cursor\n"
    "\n"
    ".queue_standard_iff_task:\n"
    "    TST.L   ESQIFF_BannerBrushResourceCursor\n"
    "    BEQ.S   .finalize_and_advance_resource_cursor\n"
    "\n"
    "    TST.L   ESQIFF_BannerBrushResourceCursor\n"
    "    BEQ.S   .finalize_and_advance_resource_cursor\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  ESQIFF_BannerBrushResourceCursor,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_AllocBrushNode(PC)\n"
    "\n"
    "    MOVE.L  D0,CTASKS_PendingIffBrushDescriptor\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.B  #$6,190(A0)\n"
    "    MOVE.W  #6,CTASKS_IffTaskState\n"
    "    JSR     ESQIFF_JMPTBL_CTASKS_StartIffTaskProcess(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".finalize_and_advance_resource_cursor:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.L   D0,D7\n"
    "    BEQ.S   .return\n"
    "\n"
    "    MOVEA.L ESQIFF_BannerBrushResourceCursor,A0\n"
    "    MOVE.L  234(A0),ESQIFF_BannerBrushResourceCursor\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
