__asm__(
    ".globl _ESQIFF2_ValidateFieldIndexAndLength\n"
    "_ESQIFF2_ValidateFieldIndexAndLength:\n"
    "ESQIFF2_ValidateFieldIndexAndLength:\n"
    "    MOVEM.L D6-D7,-(A7)\n"
    "    MOVE.W  14(A7),D7\n"
    "    MOVE.W  18(A7),D6\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.W   D0,D7\n"
    "    BLE.S   .validate_field_length_bound\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   ESQIFF2_ValidateFieldIndexAndLength_Return\n"
    "\n"
    ".validate_field_length_bound:\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .validate_non_field1_length\n"
    "\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .return_valid_field_bounds\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   ESQIFF2_ValidateFieldIndexAndLength_Return\n"
    "\n"
    ".validate_non_field1_length:\n"
    "    MOVEQ   #7,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .return_valid_field_bounds\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   ESQIFF2_ValidateFieldIndexAndLength_Return\n"
    "\n"
    ".return_valid_field_bounds:\n"
    "    MOVEQ   #1,D0\n"
);
