__asm__(
    ".globl _ESQIFF_ServiceExternalAssetSourceState\n"
    "_ESQIFF_ServiceExternalAssetSourceState:\n"
    "ESQIFF_ServiceExternalAssetSourceState:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.W  10(A7),D7\n"
    "    TST.W   Global_WORD_SELECT_CODE_IS_RAVESC\n"
    "    BNE.S   .return\n"
    "\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    "    TST.W   COI_AttentionOverlayBusyFlag\n"
    "    BNE.S   .return\n"
    "\n"
    "    TST.W   D7\n"
    "    BEQ.S   .configure_source_for_secondary_mode\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQIFF_AssetSourceSelect\n"
    "    MOVEQ   #-1,D1\n"
    "    MOVE.W  D1,ESQIFF_GAdsSourceEnabled\n"
    "    BRA.S   .reload_logo_catalog_if_needed\n"
    "\n"
    ".configure_source_for_secondary_mode:\n"
    "    CLR.W   ESQIFF_GAdsSourceEnabled\n"
    "    MOVE.W  #(-1),ESQIFF_AssetSourceSelect\n"
    "\n"
    ".reload_logo_catalog_if_needed:\n"
    "    TST.L   DISKIO_Drive0WriteProtectedCode\n"
    "    BNE.S   .reload_gads_catalog_if_needed\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetFlags,D0\n"
    "    ANDI.W  #2,D0\n"
    "    SUBQ.W  #2,D0\n"
    "    BEQ.S   .reload_gads_catalog_if_needed\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    BSR.W   ESQIFF_ReloadExternalAssetCatalogBuffers\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".reload_gads_catalog_if_needed:\n"
    "    TST.L   DISKIO_DriveWriteProtectStatusCodeDrive1\n"
    "    BNE.S   .queue_next_asset_after_reload_checks\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetFlags,D0\n"
    "    ANDI.W  #1,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .queue_next_asset_after_reload_checks\n"
    "\n"
    "    PEA     1.W\n"
    "    BSR.W   ESQIFF_ReloadExternalAssetCatalogBuffers\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".queue_next_asset_after_reload_checks:\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    "    BSR.W   ESQIFF_QueueNextExternalAssetIffJob\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
