__asm__(
    ".globl _ESQIFF_RestoreBasePaletteTriples\n"
    "_ESQIFF_RestoreBasePaletteTriples:\n"
    "ESQIFF_RestoreBasePaletteTriples:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".lab_0A46:\n"
    "    MOVEQ   #24,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .return\n"
    "\n"
    "    LEA     WDISP_PaletteTriplesRBase,A0\n"
    "    ADDA.W  D7,A0\n"
    "    LEA     ESQFUNC_BasePaletteRgbTriples,A1\n"
    "    ADDA.W  D7,A1\n"
    "    MOVE.B  (A1),(A0)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .lab_0A46\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
