__asm__(
    ".globl _ESQIFF2_ClearLineHeadTailByMode\n"
    "_ESQIFF2_ClearLineHeadTailByMode:\n"
    "ESQIFF2_ClearLineHeadTailByMode:\n"
    "    MOVE.L  D7,-(A7)\n"
    "    MOVE.W  10(A7),D7\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .clear_primary_line_head_tail\n"
    "\n"
    "    MOVE.L  ESQIFF_SecondaryLineHeadPtr,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    MOVE.L  D0,ESQIFF_SecondaryLineHeadPtr\n"
    "    MOVE.L  ESQIFF_SecondaryLineTailPtr,(A7)\n"
    "    CLR.L   -(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,ESQIFF_SecondaryLineTailPtr\n"
    "    BRA.S   .return_clear_line_head_tail\n"
    "\n"
    ".clear_primary_line_head_tail:\n"
    "    MOVE.L  ESQIFF_PrimaryLineHeadPtr,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    MOVE.L  D0,ESQIFF_PrimaryLineHeadPtr\n"
    "    MOVE.L  ESQIFF_PrimaryLineTailPtr,(A7)\n"
    "    CLR.L   -(A7)\n"
    "    BSR.W   ESQPARS_ReplaceOwnedString\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,ESQIFF_PrimaryLineTailPtr\n"
    "\n"
    ".return_clear_line_head_tail:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
