__asm__(
    ".globl _ESQIFF_RenderWeatherStatusBrushSlice\n"
    ".globl _ESQIFF_RenderWeatherStatusBrushSlice_Return\n"
    "_ESQIFF_RenderWeatherStatusBrushSlice:\n"
    "ESQIFF_RenderWeatherStatusBrushSlice:\n"
    "    MOVEM.L D2/D6-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVEA.L 28(A7),A2\n"
    "\n"
    "    MOVE.L  A2,D0\n"
    "    BNE.S   .ensure_slice_state_initialized\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQIFF_WeatherSliceRemainingWidth\n"
    "    BRA.W   ESQIFF_RenderWeatherStatusBrushSlice_Return\n"
    "\n"
    ".ensure_slice_state_initialized:\n"
    "    MOVE.W  ESQIFF_WeatherSliceRemainingWidth,D0\n"
    "    TST.W   D0\n"
    "    BLE.S   .reset_slice_state\n"
    "\n"
    "    TST.W   ESQFUNC_WeatherSliceWidthInitGate\n"
    "    BEQ.S   .clamp_slice_width\n"
    "\n"
    ".reset_slice_state:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQFUNC_WeatherSliceWidthInitGate\n"
    "    MOVE.W  178(A2),D1\n"
    "    MOVE.B  #$1,ESQIFF_WeatherSliceValidateGateFlag\n"
    "    MOVE.W  D0,ESQIFF_WeatherSliceSourceOffset\n"
    "    MOVE.W  D1,ESQIFF_WeatherSliceRemainingWidth\n"
    "\n"
    ".clamp_slice_width:\n"
    "    MOVE.W  ESQIFF_WeatherSliceRemainingWidth,D0\n"
    "    MOVEQ   #30,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .use_max_slice_width\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "    BRA.S   .dispatch_slice_blit_by_mode\n"
    "\n"
    ".use_max_slice_width:\n"
    "    MOVE.L  D1,D7\n"
    "\n"
    ".dispatch_slice_blit_by_mode:\n"
    "    MOVEQ   #9,D0\n"
    "    CMP.B   32(A2),D0\n"
    "    BNE.S   .blit_centered_slice\n"
    "\n"
    "    MOVEQ   #42,D6\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  176(A2),D0\n"
    "    ADD.L   D6,D0\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    LEA     60(A3),A0\n"
    "    MOVE.W  ESQIFF_WeatherSliceSourceOffset,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  176(A2),D0\n"
    "    MOVE.L  #$28e,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D6\n"
    "    SUBQ.L  #1,D6\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ADD.L   D6,D1\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    LEA     60(A3),A0\n"
    "    MOVE.W  ESQIFF_WeatherSliceSourceOffset,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D2,(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(PC)\n"
    "\n"
    "    LEA     52(A7),A7\n"
    "    BRA.S   .update_slice_progress_and_return\n"
    "\n"
    ".blit_centered_slice:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  176(A2),D0\n"
    "    MOVE.L  #696,D1\n"
    "    SUB.L   D0,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .half_centered_offset_ready\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".half_centered_offset_ready:\n"
    "    ASR.L   #1,D1\n"
    "    MOVE.L  D1,D6\n"
    "    SUBQ.L  #1,D6\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D0,D1\n"
    "    ADD.L   D6,D1\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    LEA     60(A3),A0\n"
    "    MOVE.W  ESQIFF_WeatherSliceSourceOffset,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D6,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVEQ   #11,D0\n"
    "    CMP.B   32(A2),D0\n"
    "    BNE.S   .update_slice_progress_and_return\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.B   ESQIFF_WeatherSliceValidateGateFlag,D0\n"
    "    BNE.S   .update_slice_progress_and_return\n"
    "\n"
    "    MOVE.B  CONFIG_NewgridSelectionCode16EnabledFlag,D0\n"
    "    MOVEQ   #89,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .update_slice_progress_and_return\n"
    "\n"
    "    PEA     16.W\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_NEWGRID_ValidateSelectionCode(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    CLR.B   ESQIFF_WeatherSliceValidateGateFlag\n"
    "\n"
    ".update_slice_progress_and_return:\n"
    "    SUB.W   D7,ESQIFF_WeatherSliceRemainingWidth\n"
    "    ADD.W   D7,ESQIFF_WeatherSliceSourceOffset\n"
    "    MOVE.L  D7,D0\n"
    "    TST.W   D0\n"
    "    BPL.S   .store_half_slice_width\n"
    "\n"
    "    ADDQ.W  #1,D0\n"
    "\n"
    ".store_half_slice_width:\n"
    "    ASR.W   #1,D0\n"
    "    MOVE.W  D0,52(A3)\n"
    "    MOVE.W  ESQIFF_WeatherSliceRemainingWidth,D0\n"
    "\n"
    "_ESQIFF_RenderWeatherStatusBrushSlice_Return:\n"
    "ESQIFF_RenderWeatherStatusBrushSlice_Return:\n"
    "    MOVEM.L (A7)+,D2/D6-D7/A2-A3\n"
    "    RTS\n"
);
