__asm__(
    ".globl _ESQIFF_ShowExternalAssetWithCopperFx\n"
    "_ESQIFF_ShowExternalAssetWithCopperFx:\n"
    "ESQIFF_ShowExternalAssetWithCopperFx:\n"
    "    LINK.W  A5,#-36\n"
    "    MOVEM.L D2/D4-D7,-(A7)\n"
    "    MOVE.W  10(A5),D7\n"
    "    TST.W   D7\n"
    "    BEQ.S   .select_primary_or_secondary_brush_head\n"
    "\n"
    "    MOVE.L  ESQIFF_GAdsBrushListHead,-22(A5)\n"
    "\n"
    ".select_primary_or_secondary_brush_head:\n"
    "    TST.W   D7\n"
    "    BNE.S   .ensure_brush_head_available\n"
    "\n"
    "    MOVEA.L ESQIFF_LogoBrushListHead,A0\n"
    "    MOVE.L  A0,-22(A5)\n"
    "\n"
    ".ensure_brush_head_available:\n"
    "    TST.L   -22(A5)\n"
    "    BEQ.W   .set_missing_asset_pending_flags\n"
    "\n"
    "    BSR.W   ESQIFF_RunCopperDropTransition\n"
    "\n"
    "    MOVEQ   #20,D6\n"
    "    MOVEA.L -22(A5),A0\n"
    "    ADD.W   178(A0),D6\n"
    "    BTST    #2,199(A0)\n"
    "    BEQ.S   .set_transition_divisor_two\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    BRA.S   .compute_transition_steps\n"
    "\n"
    ".set_transition_divisor_two:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".compute_transition_steps:\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVE.L  D1,D0\n"
    "    MOVE.L  20(A7),D1\n"
    "    JSR     ESQIFF_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "    MOVEQ   #120,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .clamp_transition_steps\n"
    "\n"
    "    MOVE.L  D0,D6\n"
    "\n"
    ".clamp_transition_steps:\n"
    "    ADDI.W  #22,D6\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    PEA     1000.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_SCRIPT_BeginBannerCharTransition(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".wait_banner_transition_idle:\n"
    "    TST.W   SCRIPT_BannerTransitionActive\n"
    "    BNE.S   .wait_banner_transition_idle\n"
    "\n"
    "    MOVE.W  #1,WDISP_AccumulatorCaptureActive\n"
    "    CLR.W   WDISP_AccumulatorFlushPending\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".loop_copy_accumulator_rows:\n"
    "    MOVEQ   #4,D0\n"
    "    CMP.L   D0,D5\n"
    "    BGE.S   .select_display_context_mode\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    ASL.L   #3,D0\n"
    "    MOVEA.L -22(A5),A0\n"
    "    ADDA.L  D0,A0\n"
    "    LEA     200(A0),A1\n"
    "    LEA     WDISP_AccumulatorRowTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  A0,28(A7)\n"
    "    MOVEA.L A1,A0\n"
    "    MOVEA.L 28(A7),A1\n"
    "    MOVEQ   #8,D0\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOCopyMem(A6)\n"
    "\n"
    "    ADDQ.L  #1,D5\n"
    "    BRA.S   .loop_copy_accumulator_rows\n"
    "\n"
    ".select_display_context_mode:\n"
    "    CLR.W   WDISP_AccumulatorCaptureActive\n"
    "    MOVE.W  #1,WDISP_AccumulatorFlushPending\n"
    "    MOVE.L  #$8004,D0\n"
    "    MOVEA.L -22(A5),A0\n"
    "    AND.L   196(A0),D0\n"
    "    CMPI.L  #$8004,D0\n"
    "    BNE.S   .select_mode_flag198_bit7\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  184(A0),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    PEA     4.W\n"
    "    JSR     ESQIFF_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    MOVEQ   #20,D4\n"
    "    BRA.S   .clear_rast_and_blit_asset\n"
    "\n"
    ".select_mode_flag198_bit7:\n"
    "    BTST    #7,198(A0)\n"
    "    BEQ.S   .select_mode_flag199_bit2\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  184(A0),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    PEA     6.W\n"
    "    JSR     ESQIFF_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    MOVEQ   #10,D4\n"
    "    BRA.S   .clear_rast_and_blit_asset\n"
    "\n"
    ".select_mode_flag199_bit2:\n"
    "    BTST    #2,199(A0)\n"
    "    BEQ.S   .select_mode_fallback\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  184(A0),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    PEA     5.W\n"
    "    JSR     ESQIFF_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    MOVEQ   #20,D4\n"
    "    BRA.S   .clear_rast_and_blit_asset\n"
    "\n"
    ".select_mode_fallback:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  184(A0),D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    PEA     7.W\n"
    "    JSR     ESQIFF_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,WDISP_DisplayContextBase\n"
    "    MOVEQ   #10,D4\n"
    "\n"
    ".clear_rast_and_blit_asset:\n"
    "    MOVEA.L D0,A0\n"
    "    ADDA.W  #-458,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    ADDA.W  #-458,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #7,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    MOVE.W  2(A0),D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  4(A0),D1\n"
    "    SUBQ.L  #1,D1\n"
    "    LEA     10(A0),A1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D4,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  -22(A5),-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVEA.L -22(A5),A0\n"
    "    TST.L   328(A0)\n"
    "    BEQ.S   .refresh_palette_triples_from_asset\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   328(A0),D0\n"
    "    BNE.S   .capture_accumulator_thresholds\n"
    "\n"
    ".refresh_palette_triples_from_asset:\n"
    "    PEA     5.W\n"
    "    JSR     ESQPARS_JMPTBL_BRUSH_PlaneMaskForIndex(PC)\n"
    "\n"
    "    MOVE.L  D0,D1\n"
    "    LSL.L   #2,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L -22(A5),A0\n"
    "    MOVE.B  184(A0),D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  D1,-14(A5)\n"
    "    JSR     ESQPARS_JMPTBL_BRUSH_PlaneMaskForIndex(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,D1\n"
    "    LSL.L   #2,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVEQ   #0,D5\n"
    "    MOVE.L  D1,-18(A5)\n"
    "\n"
    ".branch:\n"
    "    CMP.L   -18(A5),D5\n"
    "    BGE.S   .capture_accumulator_thresholds\n"
    "\n"
    "    CMP.L   -14(A5),D5\n"
    "    BGE.S   .capture_accumulator_thresholds\n"
    "\n"
    "    LEA     WDISP_PaletteTriplesRBase,A0\n"
    "    ADDA.L  D5,A0\n"
    "    MOVEA.L -22(A5),A1\n"
    "    MOVE.L  D5,D0\n"
    "    ADDI.L  #$e8,D0\n"
    "    MOVE.B  0(A1,D0.L),(A0)\n"
    "    ADDQ.L  #1,D5\n"
    "    BRA.S   .branch\n"
    "\n"
    ".capture_accumulator_thresholds:\n"
    "    MOVE.B  WDISP_AccumulatorRow0_CopperIndexStart,D0\n"
    "    MOVEQ   #32,D1\n"
    "    CMP.B   D1,D0\n"
    "    BCC.S   .branch_1\n"
    "\n"
    "    MOVE.B  WDISP_AccumulatorRow0_CopperIndexEnd,D0\n"
    "    CMP.B   D1,D0\n"
    "    BCC.S   .branch_1\n"
    "\n"
    "    MOVE.W  WDISP_AccumulatorRow0_Value,D0\n"
    "    CMPI.W  #$4000,D0\n"
    "    BGE.S   .branch_1\n"
    "\n"
    "    MOVE.W  D0,ACCUMULATOR_Row0_CaptureValue\n"
    "    BRA.S   .branch_2\n"
    "\n"
    ".branch_1:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ACCUMULATOR_Row0_CaptureValue\n"
    "\n"
    ".branch_2:\n"
    "    MOVE.B  WDISP_AccumulatorRow1_CopperIndexStart,D2\n"
    "    CMP.B   D1,D2\n"
    "    BCC.S   .branch_3\n"
    "\n"
    "    MOVE.B  WDISP_AccumulatorRow1_CopperIndexEnd,D2\n"
    "    CMP.B   D1,D2\n"
    "    BCC.S   .branch_3\n"
    "\n"
    "    MOVE.W  WDISP_AccumulatorRow1_Value,D2\n"
    "    CMPI.W  #$4000,D2\n"
    "    BGE.S   .branch_3\n"
    "\n"
    "    MOVE.W  D2,ACCUMULATOR_Row1_CaptureValue\n"
    "    BRA.S   .branch_4\n"
    "\n"
    ".branch_3:\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  D2,ACCUMULATOR_Row1_CaptureValue\n"
    "\n"
    ".branch_4:\n"
    "    MOVE.B  WDISP_AccumulatorRow2_CopperIndexStart,D0\n"
    "    CMP.B   D1,D0\n"
    "    BCC.S   .branch_5\n"
    "\n"
    "    MOVE.B  WDISP_AccumulatorRow2_CopperIndexEnd,D0\n"
    "    CMP.B   D1,D0\n"
    "    BCC.S   .branch_5\n"
    "\n"
    "    MOVE.W  WDISP_AccumulatorRow2_Value,D0\n"
    "    CMPI.W  #$4000,D0\n"
    "    BGE.S   .branch_5\n"
    "\n"
    "    MOVE.W  D0,ACCUMULATOR_Row2_CaptureValue\n"
    "    BRA.S   .branch_6\n"
    "\n"
    ".branch_5:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ACCUMULATOR_Row2_CaptureValue\n"
    "\n"
    ".branch_6:\n"
    "    MOVE.B  WDISP_AccumulatorRow3_CopperIndexStart,D2\n"
    "    CMP.B   D1,D2\n"
    "    BCC.S   .branch_7\n"
    "\n"
    "    MOVE.B  WDISP_AccumulatorRow3_CopperIndexEnd,D2\n"
    "    CMP.B   D1,D2\n"
    "    BCC.S   .branch_7\n"
    "\n"
    "    MOVE.W  WDISP_AccumulatorRow3_Value,D1\n"
    "    CMPI.W  #$4000,D1\n"
    "    BGE.S   .branch_7\n"
    "\n"
    "    MOVE.W  D1,ACCUMULATOR_Row3_CaptureValue\n"
    "    BRA.S   .branch_8\n"
    "\n"
    ".branch_7:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D1,ACCUMULATOR_Row3_CaptureValue\n"
    "\n"
    ".branch_8:\n"
    "    TST.W   ACCUMULATOR_Row0_CaptureValue\n"
    "    BNE.S   .branch_9\n"
    "\n"
    "    TST.W   ACCUMULATOR_Row1_CaptureValue\n"
    "    BNE.S   .branch_9\n"
    "\n"
    "    TST.W   ACCUMULATOR_Row2_CaptureValue\n"
    "    BNE.S   .branch_9\n"
    "\n"
    "    TST.W   D1\n"
    "    BEQ.S   .branch_10\n"
    "\n"
    ".branch_9:\n"
    "    MOVE.W  #1,WDISP_AccumulatorCaptureActive\n"
    "    BRA.S   .branch_11\n"
    "\n"
    ".branch_10:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,WDISP_AccumulatorCaptureActive\n"
    "\n"
    ".branch_11:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ACCUMULATOR_Row0_Sum\n"
    "    MOVE.W  D0,ACCUMULATOR_Row0_SaturateFlag\n"
    "    MOVE.W  D0,ACCUMULATOR_Row1_Sum\n"
    "    MOVE.W  D0,ACCUMULATOR_Row1_SaturateFlag\n"
    "    MOVE.W  D0,ACCUMULATOR_Row2_Sum\n"
    "    MOVE.W  D0,ACCUMULATOR_Row2_SaturateFlag\n"
    "    MOVE.W  D0,ACCUMULATOR_Row3_Sum\n"
    "    MOVE.W  D0,ACCUMULATOR_Row3_SaturateFlag\n"
    "    BSR.W   ESQIFF_RunCopperRiseTransition\n"
    "\n"
    "    JMP     ESQIFF_ShowExternalAssetWithCopperFx_Return\n"
    "\n"
    ".set_missing_asset_pending_flags:\n"
    "    TST.W   D7\n"
    "    BEQ.S   .branch_12\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   .branch_13\n"
    "\n"
    ".branch_12:\n"
    "    MOVEQ   #2,D0\n"
    "\n"
    ".branch_13:\n"
    "    OR.L    D0,ESQFUNC_MissingAssetRetryMask\n"
    "\n"
);
