__asm__(
    ".globl _ESQIFF_ReloadExternalAssetCatalogBuffers\n"
    "_ESQIFF_ReloadExternalAssetCatalogBuffers:\n"
    "ESQIFF_ReloadExternalAssetCatalogBuffers:\n"
    "    MOVEM.L D2-D3/D6-D7,-(A7)\n"
    "    MOVE.L  20(A7),D7\n"
    "\n"
    "    TST.W   CTASKS_IffTaskDoneFlag\n"
    "    BEQ.W   .return\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BNE.W   .maybe_reload_logo_catalog\n"
    "\n"
    "    MOVE.B  ED_DiagGraphModeChar,D0\n"
    "    MOVEQ   #78,D1\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.W   .maybe_reload_logo_catalog\n"
    "\n"
    "    TST.L   DISKIO_DriveWriteProtectStatusCodeDrive1\n"
    "    BNE.W   .maybe_reload_logo_catalog\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     ESQIFF_GAdsBrushListHead\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,ESQIFF_GAdsBrushListCount\n"
    "    CLR.W   ESQIFF_GAdsListLineIndex\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    TST.L   Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    BEQ.S   .loadGfxGAdsFile\n"
    "\n"
    "    TST.L   Global_REF_LONG_GFX_G_ADS_FILESIZE\n"
    "    BEQ.S   .loadGfxGAdsFile\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_FILESIZE,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_DATA,-(A7)\n"
    "    PEA     882.W\n"
    "    PEA     Global_STR_ESQIFF_C_3\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".loadGfxGAdsFile:\n"
    "    CLR.L   Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    CLR.L   Global_REF_LONG_GFX_G_ADS_FILESIZE\n"
    "\n"
    "    PEA     MODE_OLDFILE\n"
    "    MOVE.L  Global_PTR_STR_GFX_G_ADS,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_DOS_OpenFileWithMode(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,D6\n"
    "    TST.L   D6\n"
    "    BLE.S   .update_gads_line_cursor_shadow\n"
    "\n"
    "    MOVE.L  D6,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_DISKIO_GetFilesizeFromHandle(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,Global_REF_LONG_GFX_G_ADS_FILESIZE\n"
    "    TST.L   D0\n"
    "    BLE.S   .gfxGAdsFileWithoutData\n"
    "\n"
    "    ADDQ.L  #1,D0\n"
    "    PEA     (MEMF_PUBLIC).W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     898.W\n"
    "    PEA     Global_STR_ESQIFF_C_4\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    MOVE.L  D6,D1\n"
    "    MOVE.L  D0,D2\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_FILESIZE,D3\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVORead(A6)\n"
    "\n"
    "    CMP.L   Global_REF_LONG_GFX_G_ADS_FILESIZE,D0\n"
    "    BNE.S   .gfxGAdsFileWithoutData\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetFlags,D0\n"
    "    ORI.W   #1,D0\n"
    "    MOVE.W  D0,ESQIFF_ExternalAssetFlags\n"
    "\n"
    ".gfxGAdsFileWithoutData:\n"
    "    MOVE.L  D6,D1\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOClose(A6)\n"
    "\n"
    ".update_gads_line_cursor_shadow:\n"
    "    TST.W   SCRIPT_CtrlInterfaceEnabledFlag\n"
    "    BEQ.S   .clear_gads_line_cursor_shadow\n"
    "\n"
    "    MOVE.W  #1,ESQIFF_GAdsListLineIndex\n"
    "    BRA.S   .maybe_reload_logo_catalog\n"
    "\n"
    ".clear_gads_line_cursor_shadow:\n"
    "    CLR.W   ESQIFF_GAdsListLineIndex\n"
    "\n"
    ".maybe_reload_logo_catalog:\n"
    "    TST.L   D7\n"
    "    BNE.W   .return\n"
    "\n"
    "    TST.L   DISKIO_Drive0WriteProtectedCode\n"
    "    BNE.W   .return\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     ESQIFF_LogoBrushListHead\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,ESQIFF_LogoBrushListCount\n"
    "    CLR.W   ESQIFF_LogoListLineIndex\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    TST.L   Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    BEQ.S   .loadDf0LogoLstFile\n"
    "\n"
    "    TST.L   Global_REF_LONG_DF0_LOGO_LST_FILESIZE\n"
    "    BEQ.S   .loadDf0LogoLstFile\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_FILESIZE,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_DATA,-(A7)\n"
    "    PEA     963.W\n"
    "    PEA     Global_STR_ESQIFF_C_5\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "\n"
    ".loadDf0LogoLstFile:\n"
    "    CLR.L   Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    CLR.L   Global_REF_LONG_DF0_LOGO_LST_FILESIZE\n"
    "    PEA     MODE_OLDFILE\n"
    "    MOVE.L  Global_PTR_STR_DF0_LOGO_LST,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_DOS_OpenFileWithMode(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,D6\n"
    "    TST.L   D6\n"
    "    BLE.S   .return\n"
    "\n"
    "    MOVE.L  D6,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_DISKIO_GetFilesizeFromHandle(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,Global_REF_LONG_DF0_LOGO_LST_FILESIZE\n"
    "    TST.L   D0\n"
    "    BLE.S   .df0LogoLstFileWithoutData\n"
    "\n"
    "    ADDQ.L  #1,D0\n"
    "    PEA     (MEMF_PUBLIC).W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     979.W\n"
    "    PEA     Global_STR_ESQIFF_C_6\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    MOVE.L  D6,D1\n"
    "    MOVE.L  D0,D2\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_FILESIZE,D3\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVORead(A6)\n"
    "\n"
    "    CMP.L   Global_REF_LONG_DF0_LOGO_LST_FILESIZE,D0\n"
    "    BNE.S   .df0LogoLstFileWithoutData\n"
    "\n"
    "    MOVE.W  ESQIFF_ExternalAssetFlags,D0\n"
    "    ORI.W   #2,D0\n"
    "    MOVE.W  D0,ESQIFF_ExternalAssetFlags\n"
    "\n"
    ".df0LogoLstFileWithoutData:\n"
    "    MOVE.L  D6,D1\n"
    "    MOVEA.L Global_REF_DOS_LIBRARY_2,A6\n"
    "    JSR     _LVOClose(A6)\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D2-D3/D6-D7\n"
    "    RTS\n"
);
