__asm__(
    ".globl _ESQIFF2_ApplyIncomingStatusPacket\n"
    "_ESQIFF2_ApplyIncomingStatusPacket:\n"
    "ESQIFF2_ApplyIncomingStatusPacket:\n"
    "    MOVEM.L D2/D6-D7/A3,-(A7)\n"
    "    MOVEA.L 20(A7),A3\n"
    "\n"
    "    MOVE.B  ED_DiagVinModeChar,D6\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".lab_0AB9:\n"
    "    MOVEQ   #20,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .lab_0ABA\n"
    "\n"
    "    LEA     ESQ_STR_B,A0\n"
    "    ADDA.W  D7,A0\n"
    "    MOVE.B  0(A3,D7.W),(A0)\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .lab_0AB9\n"
    "\n"
    ".lab_0ABA:\n"
    "    TST.L   LOCAVAIL_FilterModeFlag\n"
    "    BNE.S   .branch\n"
    "\n"
    "    MOVE.B  ED_DiagVinModeChar,D0\n"
    "    CMP.B   D0,D6\n"
    "    BEQ.S   .branch\n"
    "\n"
    "    MOVE.W  SCRIPT_RuntimeMode,D0\n"
    "    BEQ.S   .branch\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,SCRIPT_RuntimeModeDeferredFlag\n"
    "\n"
    ".branch:\n"
    "    MOVE.B  ESQ_STR_6,D0\n"
    "    MOVEQ   #49,D1\n"
    "    CMP.B   D1,D0\n"
    "    BCS.S   .branch_1\n"
    "\n"
    "    MOVEQ   #72,D1\n"
    "    CMP.B   D1,D0\n"
    "    BLS.S   .branch_2\n"
    "\n"
    ".branch_1:\n"
    "    MOVE.B  #$36,ESQ_STR_6\n"
    "\n"
    ".branch_2:\n"
    "    PEA     DST_BannerWindowPrimary\n"
    "    JSR     ESQPARS_JMPTBL_DST_UpdateBannerQueue(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_3\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_DST_RefreshBannerBuffer(PC)\n"
    "\n"
    ".branch_3:\n"
    "    PEA     1.W\n"
    "    JSR     ESQDISP_DrawStatusBanner(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.B  CLOCK_MinuteEventBaseMinute,D0\n"
    "    MOVEQ   #9,D1\n"
    "    CMP.B   D1,D0\n"
    "    BHI.S   .branch_4\n"
    "\n"
    "    MOVEQ   #0,D2\n"
    "    CMP.B   D2,D0\n"
    "    BHI.S   .branch_5\n"
    "\n"
    ".branch_4:\n"
    "    MOVEQ   #1,D2\n"
    "    MOVE.B  D2,CLOCK_MinuteEventBaseMinute\n"
    "\n"
    ".branch_5:\n"
    "    MOVE.B  CLOCK_MinuteEventBaseOffset,D0\n"
    "    CMP.B   D1,D0\n"
    "    BHI.S   .branch_6\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.B   D1,D0\n"
    "    BHI.S   .branch_7\n"
    "\n"
    ".branch_6:\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.B  D1,CLOCK_MinuteEventBaseOffset\n"
    "\n"
    ".branch_7:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  CLOCK_MinuteEventBaseMinute,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  CLOCK_MinuteEventBaseOffset,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_ESQ_SeedMinuteEventThresholds(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.W   ED_DiagnosticsScreenActive\n"
    "    BEQ.S   .branch_8\n"
    "\n"
    "    JSR     ED_DrawDiagnosticModeText(PC)\n"
    "\n"
    ".branch_8:\n"
    "    TST.L   ED_SavedScrollSpeedIndex\n"
    "    BEQ.S   .branch_8_continue\n"
    "    JMP     ESQIFF2_ApplyIncomingStatusPacket_Return\n"
    "\n"
    ".branch_8_continue:\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  ESQ_STR_SATELLITE_DELIVERED_SCROLL_SPEED,D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVE.L  D0,D7\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BLT.S   .branch_9\n"
    "\n"
    "    MOVEQ   #8,D1\n"
    "    CMP.W   D1,D7\n"
    "    BGT.S   .branch_9\n"
    "\n"
    "    MOVE.W  D7,ESQPARS2_StateIndex\n"
    "    JMP     ESQIFF2_ApplyIncomingStatusPacket_Return\n"
    "\n"
    ".branch_9:\n"
    "    MOVE.W  #4,ESQPARS2_StateIndex\n"
);
