__asm__(
    ".globl _ESQIFF_HandleBrushIniReloadHotkey\n"
    "_ESQIFF_HandleBrushIniReloadHotkey:\n"
    "ESQIFF_HandleBrushIniReloadHotkey:\n"
    "    MOVE.L  D7,-(A7)\n"
    "\n"
    "    MOVE.B  11(A7),D7\n"
    "    MOVEQ   #97,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .return\n"
    "\n"
    "    JSR     ESQIFF_JMPTBL_DISKIO_ForceUiRefreshIfIdle(PC)\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     ESQIFF_BrushIniListHead\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FreeBrushList(PC)\n"
    "\n"
    "    PEA     Global_STR_DF0_BRUSH_INI_2\n"
    "    JSR     GROUP_AK_JMPTBL_PARSEINI_ParseIniBufferAndDispatch(PC)\n"
    "\n"
    "    PEA     ESQIFF_BrushIniListHead\n"
    "    MOVE.L  PARSEINI_ParsedDescriptorListHead,-(A7)\n"
    "    JSR     GROUP_AU_JMPTBL_BRUSH_PopulateBrushList(PC)\n"
    "\n"
    "    PEA     ESQIFF_TAG_DT\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushByLabel(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    TST.L   BRUSH_SelectedNode\n"
    "    BNE.S   .ensure_type3_brush_cache\n"
    "\n"
    "    PEA     ESQIFF_BrushIniListHead\n"
    "    PEA     ESQIFF_TAG_DITHER\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FindBrushByPredicate(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,BRUSH_SelectedNode\n"
    "\n"
    ".ensure_type3_brush_cache:\n"
    "    PEA     ESQIFF_BrushIniListHead\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FindType3Brush(PC)\n"
    "\n"
    "    MOVE.L  D0,ESQFUNC_FallbackType3BrushNode\n"
    "    JSR     ESQIFF_JMPTBL_DISKIO_ResetCtrlInputStateIfIdle(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".return:\n"
    "    MOVE.L  (A7)+,D7\n"
    "    RTS\n"
);
