__asm__(
    ".globl _ESQIFF2_ParseGroupRecordAndRefresh\n"
    "_ESQIFF2_ParseGroupRecordAndRefresh:\n"
    "ESQIFF2_ParseGroupRecordAndRefresh:\n"
    "    LINK.W  A5,#-20\n"
    "    MOVEM.L D2/D4-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A3)+,D0\n"
    "    MOVEQ   #0,D1\n"
    "    NOT.B   D1\n"
    "    AND.L   D1,D0\n"
    "    MOVE.L  D0,D7\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .check_secondary_group_record\n"
    "\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupRecordLength,D0\n"
    "    MOVE.W  ESQIFF_RecordLength,D1\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .primary_record_changed\n"
    "\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupRecordChecksum,D0\n"
    "    MOVE.B  ESQIFF_RecordChecksumByte,D2\n"
    "    CMP.B   D2,D0\n"
    "    BEQ.S   .check_secondary_group_record\n"
    "\n"
    ".primary_record_changed:\n"
    "    MOVE.W  D1,TEXTDISP_PrimaryGroupRecordLength\n"
    "    MOVE.B  ESQIFF_RecordChecksumByte,TEXTDISP_PrimaryGroupRecordChecksum\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,TEXTDISP_MaxEntryTitleLength\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D1\n"
    "    CMP.W   D0,D1\n"
    "    BLS.S   .init_parse_state\n"
    "\n"
    "    PEA     1.W\n"
    "    BSR.W   ESQPARS_RemoveGroupEntryAndReleaseStrings\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,NEWGRID_RefreshStateFlag\n"
    "    BRA.S   .init_parse_state\n"
    "\n"
    ".check_secondary_group_record:\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .return_group_not_target\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupRecordLength,D0\n"
    "    MOVE.W  ESQIFF_RecordLength,D1\n"
    "    CMP.W   D1,D0\n"
    "    BNE.S   .secondary_record_changed\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupRecordChecksum,D0\n"
    "    MOVE.B  ESQIFF_RecordChecksumByte,D2\n"
    "    CMP.B   D2,D0\n"
    "    BEQ.S   .return_group_not_target\n"
    "\n"
    ".secondary_record_changed:\n"
    "    MOVE.W  D1,TEXTDISP_SecondaryGroupRecordLength\n"
    "    MOVE.B  ESQIFF_RecordChecksumByte,TEXTDISP_SecondaryGroupRecordChecksum\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,TEXTDISP_MaxEntryTitleLength\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D1\n"
    "    CMP.W   D0,D1\n"
    "    BLS.S   .init_parse_state\n"
    "\n"
    "    PEA     2.W\n"
    "    BSR.W   ESQPARS_RemoveGroupEntryAndReleaseStrings\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    BRA.S   .init_parse_state\n"
    "\n"
    ".return_group_not_target:\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   ESQIFF2_ParseGroupRecordAndRefresh_Return\n"
    "\n"
    ".init_parse_state:\n"
    "    MOVEQ   #1,D6\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,ESQIFF_ParseField0Buffer\n"
    "    MOVE.B  D0,ESQIFF_ParseField1Buffer\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".init_field2_defaults_loop:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.W   D0,D5\n"
    "    BGE.S   .parse_next_byte_loop_entry\n"
    "\n"
    "    LEA     ESQIFF_ParseField2Buffer,A0\n"
    "    ADDA.W  D5,A0\n"
    "    MOVE.B  #$ff,(A0)\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.S   .init_field2_defaults_loop\n"
    "\n"
    ".parse_next_byte_loop_entry:\n"
    "    CLR.B   ESQIFF_ParseField3Buffer\n"
    "    MOVEQ   #0,D4\n"
    "    MOVEQ   #0,D5\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-8(A5)\n"
    "    CLR.L   -12(A5)\n"
    "    CLR.W   -14(A5)\n"
    "\n"
    ".parse_next_byte_loop:\n"
    "    MOVE.B  (A3)+,D0\n"
    "    MOVE.B  D0,-3(A5)\n"
    "    TST.B   D0\n"
    "    BEQ.W   .flush_pending_entry_and_return\n"
    "\n"
    "    TST.L   -12(A5)\n"
    "    BNE.W   .flush_pending_entry_and_return\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    SUBQ.W  #1,D1\n"
    "    BEQ.W   .handle_token_0x01\n"
    "\n"
    "    SUBI.W  #16,D1\n"
    "    BEQ.W   .handle_token_0x11\n"
    "\n"
    "    SUBQ.W  #1,D1\n"
    "    BEQ.S   .handle_token_0x12\n"
    "\n"
    "    SUBQ.W  #2,D1\n"
    "    BEQ.W   .handle_token_0x14\n"
    "\n"
    "    BRA.W   .handle_default_data_byte\n"
    "\n"
    ".handle_token_0x12:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF2_ValidateFieldIndexAndLength\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_1\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    BRA.S   .parse_next_byte_loop\n"
    "\n"
    ".branch_1:\n"
    "    MOVE.L  D4,D0\n"
    "    MULS    #10,D0\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    ADDA.L  D0,A0\n"
    "    ADDA.W  D5,A0\n"
    "    CLR.B   (A0)\n"
    "    TST.L   -8(A5)\n"
    "    BNE.S   .branch_4\n"
    "\n"
    "    TST.W   -14(A5)\n"
    "    BNE.S   .branch_3\n"
    "\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    LEA     ESQIFF_ParseField3Buffer,A1\n"
    "\n"
    ".branch_2:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .branch_2\n"
    "\n"
    ".branch_3:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,ESQIFF_ParseField0TailBuffer\n"
    "    MOVE.B  D0,ESQIFF_ParseField1TailByte\n"
    "    MOVE.B  D0,ESQIFF_ParseField3TailBuffer\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D7,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D6,D1\n"
    "    PEA     ESQIFF_ParseField3Buffer\n"
    "    PEA     ESQIFF_ParseField2Buffer\n"
    "    PEA     ESQIFF_ParseField1Buffer\n"
    "    PEA     ESQIFF_ParseField0Buffer\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQSHARED_CreateGroupEntryAndTitle(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,-14(A5)\n"
    "    BRA.S   .branch_5\n"
    "\n"
    ".branch_4:\n"
    "    CLR.L   -8(A5)\n"
    "\n"
    ".branch_5:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,ESQIFF_ParseField0Buffer\n"
    "    MOVE.B  D0,ESQIFF_ParseField1Buffer\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".branch_6:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.W   D0,D5\n"
    "    BGE.S   .branch_7\n"
    "\n"
    "    LEA     ESQIFF_ParseField2Buffer,A0\n"
    "    ADDA.W  D5,A0\n"
    "    MOVE.B  #$ff,(A0)\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.S   .branch_6\n"
    "\n"
    ".branch_7:\n"
    "    CLR.B   ESQIFF_ParseField3Buffer\n"
    "    MOVEQ   #0,D4\n"
    "    MOVEQ   #0,D5\n"
    "    MOVE.B  (A3)+,D6\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".handle_token_0x11:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF2_ValidateFieldIndexAndLength\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_8\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".branch_8:\n"
    "    MOVE.L  D4,D0\n"
    "    MULS    #10,D0\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    ADDA.L  D0,A0\n"
    "    ADDA.W  D5,A0\n"
    "    CLR.B   (A0)\n"
    "    MOVEQ   #1,D4\n"
    "    MOVEQ   #0,D5\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".handle_token_0x14:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF2_ValidateFieldIndexAndLength\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_9\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".branch_9:\n"
    "    MOVE.L  D4,D0\n"
    "    MULS    #10,D0\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    ADDA.L  D0,A0\n"
    "    ADDA.W  D5,A0\n"
    "    CLR.B   (A0)\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".branch_10:\n"
    "    MOVEQ   #6,D0\n"
    "    CMP.W   D0,D5\n"
    "    BGE.W   .parse_next_byte_loop\n"
    "\n"
    "    LEA     ESQIFF_ParseField2Buffer,A0\n"
    "    ADDA.W  D5,A0\n"
    "    MOVE.B  (A3)+,(A0)\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.S   .branch_10\n"
    "\n"
    ".handle_token_0x01:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF2_ValidateFieldIndexAndLength\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_11\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".branch_11:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   D0,D4\n"
    "    BEQ.S   .branch_12\n"
    "\n"
    "    MOVE.L  D4,D0\n"
    "    MULS    #10,D0\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    ADDA.L  D0,A0\n"
    "    ADDA.W  D5,A0\n"
    "    CLR.B   (A0)\n"
    "\n"
    ".branch_12:\n"
    "    MOVEQ   #3,D4\n"
    "    MOVEQ   #0,D5\n"
    "    MOVE.W  #1,-14(A5)\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".handle_default_data_byte:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF2_ValidateFieldIndexAndLength\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_13\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-12(A5)\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".branch_13:\n"
    "    MOVE.L  D4,D0\n"
    "    MULS    #10,D0\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  D5,D0\n"
    "    ADDQ.W  #1,D5\n"
    "    ADDA.W  D0,A0\n"
    "    MOVE.B  -3(A5),(A0)\n"
    "    BRA.W   .parse_next_byte_loop\n"
    "\n"
    ".flush_pending_entry_and_return:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   ESQIFF2_ValidateFieldIndexAndLength\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .branch_14\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    JMP     ESQIFF2_ParseGroupRecordAndRefresh_Return\n"
    "\n"
    ".branch_14:\n"
    "    MOVE.L  D4,D0\n"
    "    MULS    #10,D0\n"
    "    LEA     ESQIFF_ParseField0Buffer,A0\n"
    "    ADDA.L  D0,A0\n"
    "    ADDA.W  D5,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,(A0)\n"
    "    MOVE.B  D0,ESQIFF_ParseField0TailBuffer\n"
    "    MOVE.B  D0,ESQIFF_ParseField1TailByte\n"
    "    MOVE.B  D0,ESQIFF_ParseField3TailBuffer\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D7,D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D6,D1\n"
    "    PEA     ESQIFF_ParseField3Buffer\n"
    "    PEA     ESQIFF_ParseField2Buffer\n"
    "    PEA     ESQIFF_ParseField1Buffer\n"
    "    PEA     ESQIFF_ParseField0Buffer\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     ESQSHARED_CreateGroupEntryAndTitle(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D7,D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    BSR.W   ESQIFF2_PadEntriesToMaxTitleWidth\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_TEXTDISP_ApplySourceConfigAllEntries(PC)\n"
    "\n"
    "    JSR     ESQPARS_JMPTBL_NEWGRID_RebuildIndexCache(PC)\n"
);
