__asm__(
    ".globl _ESQIFF2_ReadRbfBytesToBuffer\n"
    "_ESQIFF2_ReadRbfBytesToBuffer:\n"
    "ESQIFF2_ReadRbfBytesToBuffer:\n"
    "    LINK.W  A5,#-4\n"
    "    MOVEM.L D6-D7/A3,-(A7)\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVE.W  30(A7),D7\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".loop_read_serial_byte_to_buffer:\n"
    "    CMP.W   D7,D6\n"
    "    BGE.S   ESQIFF2_ReadSerialBytesToBuffer_Return\n"
    "\n"
    "    JSR     ESQFUNC_WaitForClockChangeAndServiceUi(PC)\n"
    "\n"
    "    MOVEA.L A3,A0\n"
    "    ADDQ.L  #1,A3\n"
    "    MOVE.L  A0,12(A7)\n"
    "    JSR     ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(PC)\n"
    "\n"
    "    MOVEA.L 12(A7),A0\n"
    "    MOVE.B  D0,(A0)\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.S   .loop_read_serial_byte_to_buffer\n"
);
