__asm__(
    ".globl _ESQIFF2_ShowAttentionOverlay\n"
    "_ESQIFF2_ShowAttentionOverlay:\n"
    "ESQIFF2_ShowAttentionOverlay:\n"
    "    LINK.W  A5,#-140\n"
    "    MOVEM.L D2-D3/D5-D7,-(A7)\n"
    "    MOVE.B  11(A5),D7\n"
    "    MOVEQ   #-1,D5\n"
    "    TST.W   Global_UIBusyFlag\n"
    "    BEQ.S   .lab_0B27\n"
    "\n"
    "    TST.W   ED_DiagnosticsScreenActive\n"
    "    BEQ.W   ESQIFF2_ShowAttentionOverlay_Return\n"
    "\n"
    ".lab_0B27:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D7,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BLT.S   .lab_0B2A\n"
    "\n"
    "    CMPI.W  #5,D0\n"
    "    BGE.S   .lab_0B2A\n"
    "\n"
    "    ADD.W   D0,D0\n"
    "    MOVE.W  .lab_0B28(PC,D0.W),D0\n"
    "    JMP     .lab_0B28+2(PC,D0.W)\n"
    "\n"
    ".lab_0B28:\n"
    "    DC.W    .lab_0B29_0008-.lab_0B28-2\n"
    "    DC.W    .lab_0B29_000C-.lab_0B28-2\n"
    "    DC.W    .lab_0B29_0010-.lab_0B28-2\n"
    "    DC.W    .lab_0B29_0014-.lab_0B28-2\n"
    "    DC.W    .lab_0B29_0018-.lab_0B28-2\n"
    "\n"
    ".lab_0B29_0008:\n"
    "    MOVEQ   #1,D5\n"
    "    BRA.S   .lab_0B2A\n"
    "\n"
    ".lab_0B29_000C:\n"
    "    MOVEQ   #2,D5\n"
    "    BRA.S   .lab_0B2A\n"
    "\n"
    ".lab_0B29_0010:\n"
    "    MOVEQ   #8,D5\n"
    "    BRA.S   .lab_0B2A\n"
    "\n"
    ".lab_0B29_0014:\n"
    "    MOVEQ   #9,D5\n"
    "    BRA.S   .lab_0B2A\n"
    "\n"
    ".lab_0B29_0018:\n"
    "    MOVEQ   #10,D5\n"
    "\n"
    ".lab_0B2A:\n"
    "    TST.L   D5\n"
    "    BLE.W   ESQIFF2_ShowAttentionOverlay_Return\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVODisable(A6)\n"
    "\n"
    "    MOVE.W  #$100,ESQPARS2_ReadModeFlags\n"
    "    JSR     GCOMMAND_SeedBannerFromPrefs(PC)\n"
    "\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOEnable(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  4(A0),-138(A5)\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "    CLR.W   ED_DiagnosticsScreenActive\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #2,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEQ   #65,D1\n"
    "    MOVE.L  #$2ac,D2\n"
    "    MOVEQ   #40,D3\n"
    "    NOT.B   D3\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #3,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.B  28(A0),D6\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    PEA     Global_STR_PLEASE_STANDBY_2\n"
    "    PEA     90.W\n"
    "    PEA     35.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    PEA     Global_STR_ATTENTION_SYSTEM_ENGINEER_2\n"
    "    PEA     120.W\n"
    "    PEA     35.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    MOVE.L  D5,(A7)\n"
    "    PEA     Global_STR_REPORT_ERROR_CODE_FORMATTED\n"
    "    PEA     -128(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    PEA     -128(A5)\n"
    "    PEA     150.W\n"
    "    PEA     35.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     56(A7),A7\n"
    "    MOVEQ   #9,D0\n"
    "    CMP.L   D0,D5\n"
    "    BEQ.S   .lab_0B2B\n"
    "\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.L   D0,D5\n"
    "    BNE.S   .lab_0B2C\n"
    "\n"
    ".lab_0B2B:\n"
    "    MOVE.L  BRUSH_SnapshotDepth,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_BRUSH_PlaneMaskForIndex(PC)\n"
    "\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  BRUSH_SnapshotWidth,-(A7)\n"
    "    PEA     BRUSH_SnapshotHeader\n"
    "    PEA     Global_STR_FILE_WIDTH_COLORS_FORMATTED\n"
    "    PEA     -128(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVE.W  #1,COI_AttentionOverlayBusyFlag\n"
    "    BRA.S   .lab_0B2D\n"
    "\n"
    ".lab_0B2C:\n"
    "    PEA     BRUSH_SnapshotHeader\n"
    "    PEA     Global_STR_FILE_PERCENT_S\n"
    "    PEA     -128(A5)\n"
    "    JSR     GROUP_AM_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "\n"
    ".lab_0B2D:\n"
    "    PEA     -128(A5)\n"
    "    PEA     180.W\n"
    "    PEA     35.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    PEA     Global_STR_PRESS_ESC_TWICE_TO_RESUME_SCROLL\n"
    "    PEA     210.W\n"
    "    PEA     35.W\n"
    "    MOVE.L  Global_REF_RASTPORT_1,-(A7)\n"
    "    JSR     ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  -138(A5),4(A0)\n"
);
