__asm__(
    ".globl _ESQIFF_DrawWeatherStatusOverlayIntoBrush\n"
    "_ESQIFF_DrawWeatherStatusOverlayIntoBrush:\n"
    "ESQIFF_DrawWeatherStatusOverlayIntoBrush:\n"
    "    LINK.W  A5,#-68\n"
    "    MOVEM.L D2/D5-D7/A3,-(A7)\n"
    "\n"
    "    MOVEA.L 8(A5),A3\n"
    "    CLR.L   -4(A5)\n"
    "    MOVEQ   #0,D7\n"
    "    MOVEQ   #30,D6\n"
    "    MOVEQ   #0,D5\n"
    "    CLR.L   -24(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  WDISP_WeatherStatusBrushIndex,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     ESQFUNC_STR_I5,A0\n"
    "    ADDA.L  D0,A0\n"
    "    PEA     ESQFUNC_PwBrushListHead\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_FindBrushByPredicate(PC)\n"
    "\n"
    "    MOVE.L  -4(A5),(A7)\n"
    "    MOVE.L  WDISP_WeatherStatusOverlayTextPtr,-(A7)\n"
    "    MOVE.L  D0,-52(A5)\n"
    "    JSR     ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEA.L D0,A0\n"
    "\n"
    ".scan_text_end:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .scan_text_end\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  D0,A0\n"
    "    MOVE.L  A0,D1\n"
    "    ADDQ.L  #1,D1\n"
    "    MOVE.L  D0,-8(A5)\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    MOVE.L  D1,-28(A5)\n"
    "\n"
    ".replace_delimiter_with_nul_loop:\n"
    "    MOVEA.L -8(A5),A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.S   .prepare_first_segment_ptr\n"
    "\n"
    "    MOVEQ   #24,D0\n"
    "    CMP.B   (A0),D0\n"
    "    BNE.S   .advance_scan_ptr\n"
    "\n"
    "    CLR.B   (A0)\n"
    "    ADDQ.L  #1,D5\n"
    "\n"
    ".advance_scan_ptr:\n"
    "    ADDQ.L  #1,-8(A5)\n"
    "    BRA.S   .replace_delimiter_with_nul_loop\n"
    "\n"
    ".prepare_first_segment_ptr:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  A0,-8(A5)\n"
    "    TST.B   (A0)\n"
    "    BNE.S   .clamp_segment_count\n"
    "\n"
    "    ADDQ.L  #1,-8(A5)\n"
    "    SUBQ.L  #1,D5\n"
    "\n"
    ".clamp_segment_count:\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.L   D0,D5\n"
    "    BLE.S   .setup_rastport_state\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "\n"
    ".setup_rastport_state:\n"
    "    MOVE.B  64(A3),-65(A5)\n"
    "    MOVE.B  61(A3),-66(A5)\n"
    "    LEA     36(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #1,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L Global_HANDLE_PREVUEC_FONT,A0\n"
    "    JSR     _LVOSetFont(A6)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #7,D0\n"
    "    JSR     _LVOSetRast(A6)\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L -52(A5),A0\n"
    "    MOVE.L  D0,356(A0)\n"
    "    MOVE.L  D0,360(A0)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  176(A3),D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  178(A3),D1\n"
    "    LEA     36(A3),A1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(PC)\n"
    "\n"
    "    LEA     28(A7),A7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_HANDLE_PREVUEC_FONT,A0\n"
    "    MOVE.W  20(A0),D0\n"
    "    MOVE.L  D5,D1\n"
    "    ADDQ.L  #1,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .half_line_count_ready\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".half_line_count_ready:\n"
    "    ASR.L   #1,D1\n"
    "    MOVE.L  D0,-48(A5)\n"
    "    MOVE.L  D1,-32(A5)\n"
    "    JSR     ESQIFF_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    MOVEQ   #80,D1\n"
    "    ADD.L   D1,D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  -32(A5),D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,-36(A5)\n"
    "    MOVE.L  D1,D0\n"
    "    MOVE.L  D1,-40(A5)\n"
    "    MOVE.L  -36(A5),D1\n"
    "    JSR     ESQIFF_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  176(A3),D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVEA.L -52(A5),A0\n"
    "    MOVE.W  176(A0),D2\n"
    "    SUB.L   D2,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .half_brush_width_delta_ready\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".half_brush_width_delta_ready:\n"
    "    ASR.L   #1,D1\n"
    "    MOVE.L  D0,-44(A5)\n"
    "    MOVE.L  D1,-56(A5)\n"
    "\n"
    ".render_segment_loop:\n"
    "    MOVE.L  -24(A5),D0\n"
    "    CMP.L   D5,D0\n"
    "    BGE.W   .restore_rastport_and_free_text\n"
    "\n"
    "    TST.L   D0\n"
    "    BPL.S   .half_segment_index_ready\n"
    "\n"
    "    ADDQ.L  #1,D0\n"
    "\n"
    ".half_segment_index_ready:\n"
    "    ASR.L   #1,D0\n"
    "    MOVE.L  -44(A5),D1\n"
    "    MOVE.L  -48(A5),D2\n"
    "    ADD.L   D1,D2\n"
    "    MOVE.L  D2,D1\n"
    "    JSR     ESQIFF_JMPTBL_MATH_Mulu32(PC)\n"
    "\n"
    "    ADD.L   -44(A5),D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVEA.L Global_HANDLE_PREVUEC_FONT,A0\n"
    "    MOVE.W  26(A0),D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.L  D0,D6\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  20(A0),D0\n"
    "    MOVE.L  D6,D2\n"
    "    ADD.L   D0,D2\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D1,D0\n"
    "    SUB.L   D0,D2\n"
    "    MOVEQ   #80,D0\n"
    "    ADD.L   D0,D0\n"
    "    CMP.L   D0,D2\n"
    "    BGE.W   .restore_rastport_and_free_text\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.L  -8(A5),-(A7)\n"
    "    MOVE.L  -56(A5),-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQFUNC_TrimTextToPixelWidthWordBoundary\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.L  D0,-60(A5)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  -56(A5),D1\n"
    "    SUB.L   D0,D1\n"
    "    SUBQ.L  #1,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .center_left_segment_x_offset_ready\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".center_left_segment_x_offset_ready:\n"
    "    ASR.L   #1,D1\n"
    "    MOVE.L  D1,D7\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.L  D0,-64(A5)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  D7,D0\n"
    "    MOVE.L  D6,D1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  -60(A5),D0\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    "    ADDQ.L  #1,-24(A5)\n"
    "    MOVE.L  -24(A5),D0\n"
    "    CMP.L   D5,D0\n"
    "    BGE.W   .advance_to_next_segment\n"
    "\n"
    "    MOVEA.L -8(A5),A0\n"
    "\n"
    ".scan_segment_end_left:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .scan_segment_end_left\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  -8(A5),A0\n"
    "    MOVE.L  A0,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    ADD.L   D0,-8(A5)\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.L  -8(A5),-(A7)\n"
    "    MOVE.L  -56(A5),-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    BSR.W   ESQFUNC_TrimTextToPixelWidthWordBoundary\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.L  D0,-60(A5)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  -56(A5),D1\n"
    "    ADD.L   D0,D1\n"
    "    TST.L   D1\n"
    "    BPL.S   .center_right_segment_x_offset_ready\n"
    "\n"
    "    ADDQ.L  #1,D1\n"
    "\n"
    ".center_right_segment_x_offset_ready:\n"
    "    ASR.L   #1,D1\n"
    "    MOVEQ   #0,D2\n"
    "    MOVE.W  176(A3),D2\n"
    "    SUB.L   D1,D2\n"
    "    MOVE.L  D2,D7\n"
    "    SUBQ.L  #1,D7\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.L  D0,-64(A5)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  D7,D0\n"
    "    MOVE.L  D6,D1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.L  -60(A5),D0\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    "    ADDQ.L  #1,-24(A5)\n"
    "\n"
    ".advance_to_next_segment:\n"
    "    MOVEA.L -8(A5),A0\n"
    "\n"
    ".scan_segment_end_generic:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .scan_segment_end_generic\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  -8(A5),A0\n"
    "    MOVE.L  A0,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    ADD.L   D0,-8(A5)\n"
    "\n"
    "    BRA.W   .render_segment_loop\n"
    "\n"
    ".restore_rastport_and_free_text:\n"
    "    MOVE.L  -28(A5),-(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    PEA     672.W\n"
    "    PEA     Global_STR_ESQIFF_C_1\n"
    "    JSR     ESQIFF_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.B  -65(A5),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    LEA     36(A3),A0\n"
    "    MOVE.B  -66(A5),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    MOVEA.L A0,A1\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEM.L -88(A5),D2/D5-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
