__asm__(
    ".globl _ESQIFF_QueueNextExternalAssetIffJob\n"
    "_ESQIFF_QueueNextExternalAssetIffJob:\n"
    "ESQIFF_QueueNextExternalAssetIffJob:\n"
    "    LINK.W  A5,#-144\n"
    "    MOVEM.L D2/D5-D7,-(A7)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,-138(A5)\n"
    "    MOVEA.L AbsExecBase,A6\n"
    "    JSR     _LVOForbid(A6)\n"
    "\n"
    "    TST.W   CTASKS_IffTaskDoneFlag\n"
    "    BNE.S   .permit_and_return_no_job\n"
    "\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   .return\n"
    "\n"
    ".permit_and_return_no_job:\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .check_gads_quota\n"
    "\n"
    "    CMPI.L  #$1,ESQIFF_LogoBrushListCount\n"
    "    BLT.S   .check_gads_quota\n"
    "\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   .return\n"
    "\n"
    ".check_gads_quota:\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BNE.S   .begin_path_selection\n"
    "\n"
    "    CMPI.L  #$2,ESQIFF_GAdsBrushListCount\n"
    "    BLT.S   .begin_path_selection\n"
    "\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   .return\n"
    "\n"
    ".begin_path_selection:\n"
    "    JSR     _LVOPermit(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,-40(A5)\n"
    "    MOVE.W  ESQIFF_LogoListLineIndex,D6\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.W  D1,-128(A5)\n"
    "    TST.L   Global_REF_LONG_DF0_LOGO_LST_DATA\n"
    "    BEQ.S   .check_gads_blob_for_source0\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D2\n"
    "    BNE.S   .scan_candidate_paths\n"
    "\n"
    ".check_gads_blob_for_source0:\n"
    "    TST.L   Global_REF_LONG_GFX_G_ADS_DATA\n"
    "    BEQ.W   .finalize_no_candidate\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D2\n"
    "    BNE.W   .finalize_no_candidate\n"
    "\n"
    ".scan_candidate_paths:\n"
    "    MOVE.B  D0,-41(A5)\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D5\n"
    "\n"
    ".loop_read_candidate_path:\n"
    "    PEA     -40(A5)\n"
    "    BSR.W   ESQIFF_ReadNextExternalAssetPathEntry\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    LEA     -40(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".loop_measure_candidate_len:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .loop_measure_candidate_len\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D0\n"
    "    BEQ.W   .check_scan_progress_or_retry\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .validate_source0_path_prefixes\n"
    "\n"
    "    TST.W   ESQIFF_ExternalAssetPathCommaFlag\n"
    "    BEQ.S   .build_wildcard_probe_path\n"
    "\n"
    "    MOVE.W  #1,-128(A5)\n"
    "    BRA.W   .finalize_candidate_filter\n"
    "\n"
    ".build_wildcard_probe_path:\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_rewrite_bang_to_wildcard:\n"
    "    MOVEQ   #40,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .probe_match_index_by_wildcard\n"
    "\n"
    "    MOVE.B  -40(A5,D7.W),-80(A5,D7.W)\n"
    "    TST.B   -80(A5,D7.W)\n"
    "    BEQ.S   .probe_match_index_by_wildcard\n"
    "\n"
    "    MOVEQ   #33,D0\n"
    "    CMP.B   -80(A5,D7.W),D0\n"
    "    BNE.S   .advance_probe_char\n"
    "\n"
    "    MOVE.B  #$2a,-80(A5,D7.W)\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    CLR.B   -79(A5,D0.L)\n"
    "    BRA.S   .probe_match_index_by_wildcard\n"
    "\n"
    ".advance_probe_char:\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .loop_rewrite_bang_to_wildcard\n"
    "\n"
    ".probe_match_index_by_wildcard:\n"
    "    PEA     -80(A5)\n"
    "    JSR     GCOMMAND_FindPathSeparator(PC)\n"
    "\n"
    "    MOVE.L  D0,(A7)\n"
    "    JSR     ESQIFF_JMPTBL_TEXTDISP_FindEntryIndexByWildcard(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .yield_grid_while_scanning\n"
    "\n"
    "    MOVE.W  #1,-128(A5)\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,ESQIFF_ExternalAssetStateTable\n"
    "    BRA.S   .finalize_candidate_filter\n"
    "\n"
    ".validate_source0_path_prefixes:\n"
    "    MOVEQ   #4,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -40(A5)\n"
    "    PEA     ESQIFF_PATH_DF0_COLON\n"
    "    JSR     ESQIFF_JMPTBL_STRING_CompareNoCaseN(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .finalize_candidate_filter\n"
    "\n"
    "    MOVEQ   #11,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -40(A5)\n"
    "    PEA     ESQIFF_PATH_RAM_COLON_LOGOS_SLASH\n"
    "    JSR     ESQIFF_JMPTBL_STRING_CompareNoCaseN(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BEQ.S   .finalize_candidate_filter\n"
    "\n"
    "    MOVE.W  #1,-128(A5)\n"
    "    BRA.S   .finalize_candidate_filter\n"
    "\n"
    ".yield_grid_while_scanning:\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    ".check_scan_progress_or_retry:\n"
    "    MOVE.W  ESQIFF_LogoListLineIndex,D0\n"
    "    CMP.W   D0,D6\n"
    "    BNE.W   .loop_read_candidate_path\n"
    "\n"
    ".finalize_candidate_filter:\n"
    "    MOVE.W  D5,TEXTDISP_CurrentMatchIndex\n"
    "    TST.W   -128(A5)\n"
    "    BEQ.W   .finalize_no_candidate\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .set_logo_poll_limit\n"
    "\n"
    "    MOVE.L  #$fa00,-134(A5)\n"
    "    BRA.S   .snapshot_candidate_path\n"
    "\n"
    ".set_logo_poll_limit:\n"
    "    MOVE.L  #$13880,-134(A5)\n"
    "\n"
    ".snapshot_candidate_path:\n"
    "    LEA     -40(A5),A0\n"
    "    LEA     -120(A5),A1\n"
    "\n"
    ".loop_copy_candidate_snapshot:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .loop_copy_candidate_snapshot\n"
    "\n"
    ".loop_queue_until_path_changes:\n"
    "    MOVE.W  #1,-130(A5)\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .select_gads_list_head\n"
    "\n"
    "    MOVEA.L ESQIFF_LogoBrushListHead,A0\n"
    "    MOVE.L  A0,-142(A5)\n"
    "    BRA.S   .test_duplicate_head_path\n"
    "\n"
    ".select_gads_list_head:\n"
    "    MOVEA.L ESQIFF_GAdsBrushListHead,A0\n"
    "    MOVE.L  A0,-142(A5)\n"
    "\n"
    ".test_duplicate_head_path:\n"
    "    MOVE.L  A0,D0\n"
    "    BEQ.S   .allocate_descriptor_if_needed\n"
    "\n"
    "    CMPA.L  ESQIFF_LogoBrushListHead,A0\n"
    "    BNE.S   .allocate_descriptor_if_needed\n"
    "\n"
    "    LEA     -40(A5),A0\n"
    "    MOVEA.L -142(A5),A1\n"
    "\n"
    ".loop_compare_candidate_with_head:\n"
    "    MOVE.B  (A0)+,D0\n"
    "    CMP.B   (A1)+,D0\n"
    "    BNE.S   .allocate_descriptor_if_needed\n"
    "\n"
    "    TST.B   D0\n"
    "    BNE.S   .loop_compare_candidate_with_head\n"
    "\n"
    "    BNE.S   .allocate_descriptor_if_needed\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,-138(A5)\n"
    "\n"
    ".allocate_descriptor_if_needed:\n"
    "    TST.L   -138(A5)\n"
    "    BNE.S   .poll_until_path_change_or_timeout\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    PEA     -40(A5)\n"
    "    JSR     ESQIFF_JMPTBL_BRUSH_AllocBrushNode(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D1\n"
    "    MOVE.L  D0,ESQIFF_PendingExternalBrushNode\n"
    "    TST.W   D1\n"
    "    BEQ.S   .init_gads_pending_descriptor\n"
    "\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.B  #$4,190(A0)\n"
    "    MOVE.L  D0,CTASKS_PendingLogoBrushDescriptor\n"
    "    BRA.S   .start_iff_task_for_pending_descriptor\n"
    "\n"
    ".init_gads_pending_descriptor:\n"
    "    MOVEA.L D0,A0\n"
    "    MOVE.B  #$5,190(A0)\n"
    "    MOVE.L  D0,CTASKS_PendingGAdsBrushDescriptor\n"
    "\n"
    ".start_iff_task_for_pending_descriptor:\n"
    "    JSR     ESQIFF_JMPTBL_CTASKS_StartIffTaskProcess(PC)\n"
    "\n"
    ".poll_until_path_change_or_timeout:\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.W   -130(A5),D0\n"
    "    BNE.S   .compare_snapshot_with_current_path\n"
    "\n"
    "    PEA     -40(A5)\n"
    "    BSR.W   ESQIFF_ReadNextExternalAssetPathEntry\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "\n"
    ".compare_snapshot_with_current_path:\n"
    "    LEA     -120(A5),A0\n"
    "    LEA     -40(A5),A1\n"
    "\n"
    ".loop_compare_paths:\n"
    "    MOVE.B  (A0)+,D0\n"
    "    CMP.B   (A1)+,D0\n"
    "    BNE.S   .retry_queue_loop_if_timeout\n"
    "\n"
    "    TST.B   D0\n"
    "    BNE.S   .loop_compare_paths\n"
    "\n"
    "    BEQ.S   .finalize_no_candidate\n"
    "\n"
    ".retry_queue_loop_if_timeout:\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.W   -130(A5),D0\n"
    "    BEQ.W   .loop_queue_until_path_changes\n"
    "\n"
    ".finalize_no_candidate:\n"
    "    TST.W   -128(A5)\n"
    "    BNE.S   .return_current_timeout_state\n"
    "\n"
    "    MOVEQ   #-1,D0\n"
    "    MOVE.W  D0,-130(A5)\n"
    "\n"
    ".return_current_timeout_state:\n"
    "    MOVE.W  -130(A5),D0\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D2/D5-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
