__asm__(
    ".globl _ESQIFF_ReadNextExternalAssetPathEntry\n"
    "_ESQIFF_ReadNextExternalAssetPathEntry:\n"
    "ESQIFF_ReadNextExternalAssetPathEntry:\n"
    "    LINK.W  A5,#-16\n"
    "    MOVEM.L D4-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    JSR     ESQDISP_ProcessGridMessagesIfIdle(PC)\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .select_gads_catalog\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_FILESIZE,D4\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_DATA,-14(A5)\n"
    "    MOVE.W  ESQIFF_LogoListLineIndex,D6\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,ESQIFF_ExternalAssetPathCommaFlag\n"
    "    BRA.S   .begin_line_seek\n"
    "\n"
    ".select_gads_catalog:\n"
    "    MOVE.W  ESQIFF_GAdsSourceEnabled,D0\n"
    "    BEQ.S   .return_no_catalog_enabled\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_FILESIZE,D4\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_DATA,-14(A5)\n"
    "    MOVE.W  ESQIFF_GAdsListLineIndex,D6\n"
    "    BRA.S   .begin_line_seek\n"
    "\n"
    ".return_no_catalog_enabled:\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   .return\n"
    "\n"
    ".begin_line_seek:\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_seek_to_target_line:\n"
    "    CMP.W   D6,D7\n"
    "    BGE.S   .begin_entry_copy\n"
    "\n"
    "    TST.L   D4\n"
    "    BLE.S   .begin_entry_copy\n"
    "\n"
    "    MOVEA.L -14(A5),A0\n"
    "    MOVE.B  (A0)+,D5\n"
    "    MOVE.L  A0,-14(A5)\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.B   D0,D5\n"
    "    BNE.S   .consume_seek_char\n"
    "\n"
    "    ADDQ.W  #1,D7\n"
    "\n"
    ".consume_seek_char:\n"
    "    SUBQ.L  #1,D4\n"
    "    BRA.S   .loop_seek_to_target_line\n"
    "\n"
    ".begin_entry_copy:\n"
    "    TST.L   D4\n"
    "    BNE.S   .advance_line_index_counter\n"
    "\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .reload_gads_catalog_start\n"
    "\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_FILESIZE,D4\n"
    "    MOVE.L  Global_REF_LONG_DF0_LOGO_LST_DATA,-14(A5)\n"
    "    BRA.S   .reset_line_index_to_one\n"
    "\n"
    ".reload_gads_catalog_start:\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_FILESIZE,D4\n"
    "    MOVE.L  Global_REF_LONG_GFX_G_ADS_DATA,-14(A5)\n"
    "\n"
    ".reset_line_index_to_one:\n"
    "    MOVEQ   #1,D6\n"
    "    BRA.S   .store_updated_line_index\n"
    "\n"
    ".advance_line_index_counter:\n"
    "    ADDQ.W  #1,D6\n"
    "\n"
    ".store_updated_line_index:\n"
    "    MOVE.W  ESQIFF_AssetSourceSelect,D0\n"
    "    BEQ.S   .store_gads_line_index\n"
    "\n"
    "    MOVE.W  D6,ESQIFF_LogoListLineIndex\n"
    "    BRA.S   .loop_copy_entry_chars\n"
    "\n"
    ".store_gads_line_index:\n"
    "    MOVE.W  D6,ESQIFF_GAdsListLineIndex\n"
    "\n"
    ".loop_copy_entry_chars:\n"
    "    MOVEA.L -14(A5),A0\n"
    "    MOVE.B  (A0)+,D5\n"
    "    MOVE.L  A0,-14(A5)\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.B   D0,D5\n"
    "    BEQ.S   .terminate_and_return_entry\n"
    "\n"
    "    MOVEQ   #13,D0\n"
    "    CMP.B   D0,D5\n"
    "    BEQ.S   .terminate_and_return_entry\n"
    "\n"
    "    MOVEQ   #32,D0\n"
    "    CMP.B   D0,D5\n"
    "    BEQ.S   .terminate_and_return_entry\n"
    "\n"
    "    MOVE.L  D4,D0\n"
    "    SUBQ.L  #1,D4\n"
    "    TST.L   D0\n"
    "    BLE.S   .terminate_and_return_entry\n"
    "\n"
    "    MOVEQ   #44,D0\n"
    "    CMP.B   D0,D5\n"
    "    BNE.S   .append_entry_char\n"
    "\n"
    "    CLR.B   (A3)\n"
    "    MOVE.W  #1,ESQIFF_ExternalAssetPathCommaFlag\n"
    "    BRA.S   .terminate_and_return_entry\n"
    "\n"
    ".append_entry_char:\n"
    "    MOVE.B  D5,(A3)+\n"
    "    BRA.S   .loop_copy_entry_chars\n"
    "\n"
    ".terminate_and_return_entry:\n"
    "    CLR.B   (A3)\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D4-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
