__asm__(
    ".globl _ESQIFF2_PadEntriesToMaxTitleWidth\n"
    "_ESQIFF2_PadEntriesToMaxTitleWidth:\n"
    "ESQIFF2_PadEntriesToMaxTitleWidth:\n"
    "    LINK.W  A5,#-24\n"
    "    MOVEM.L D4-D7,-(A7)\n"
    "    MOVE.B  11(A5),D7\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D7,D0\n"
    "    BNE.S   .check_primary_group_match\n"
    "\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    MOVE.W  D0,-12(A5)\n"
    "    BRA.S   .start_entry_padding_loop\n"
    "\n"
    ".check_primary_group_match:\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .return_group_not_matched\n"
    "\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    MOVE.W  D0,-12(A5)\n"
    "    BRA.S   .start_entry_padding_loop\n"
    "\n"
    ".return_group_not_matched:\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   ESQIFF2_PadEntriesToMaxTitleWidth_Return\n"
    "\n"
    ".start_entry_padding_loop:\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".loop_entries_for_padding:\n"
    "    CMP.W   -12(A5),D6\n"
    "    BGE.W   ESQIFF2_PadEntriesToMaxTitleWidth_Return\n"
    "\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    CMP.B   D0,D7\n"
    "    BNE.S   .load_primary_entry_pointer\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    BRA.S   .measure_current_title_length\n"
    "\n"
    ".load_primary_entry_pointer:\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "\n"
    ".measure_current_title_length:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    ADDQ.L  #1,A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".loop_find_title_nul:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .loop_find_title_nul\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.W  TEXTDISP_MaxEntryTitleLength,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  A1,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVE.L  D0,D4\n"
    "    TST.W   D4\n"
    "    BLE.S   .next_entry_after_padding\n"
    "\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".loop_fill_space_buffer:\n"
    "    MOVEQ   #10,D0\n"
    "    CMP.W   D0,D5\n"
    "    BGE.S   .append_space_buffer\n"
    "\n"
    "    MOVE.B  #$20,-24(A5,D5.W)\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.S   .loop_fill_space_buffer\n"
    "\n"
    ".append_space_buffer:\n"
    "    CLR.B   -24(A5,D4.W)\n"
    "    MOVEA.L -4(A5),A0\n"
    "    ADDQ.L  #1,A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    PEA     -24(A5)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L -4(A5),A0\n"
    "    ADDQ.L  #1,A0\n"
    "    LEA     -24(A5),A1\n"
    "\n"
    ".copy_padded_title_back:\n"
    "    MOVE.B  (A1)+,(A0)+\n"
    "    BNE.S   .copy_padded_title_back\n"
    "\n"
    ".next_entry_after_padding:\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.W   .loop_entries_for_padding\n"
);
