__asm__(
    ".globl _ESQSHARED4_LoadCopperColorWordsFromNibbleTable\n"
    "_ESQSHARED4_LoadCopperColorWordsFromNibbleTable:\n"
    "ESQSHARED4_LoadCopperColorWordsFromNibbleTable:\n"
    "    MOVEQ   #7,D4\n"
    ".lab_0CA2:\n"
    "    JSR     ESQSHARED4_DecodeRgbNibbleTriplet\n"
    "    CMPI.W  #4,D3\n"
    "    BEQ.W   .lab_0CA3\n"
    "    CMPI.W  #$1c,D3\n"
    "    BEQ.W   .lab_0CA4\n"
    "    MOVE.W  D0,0(A2,D3.W)\n"
    "    MOVE.W  D0,0(A3,D3.W)\n"
    "    BRA.W   .lab_0CA5\n"
    ".lab_0CA3:\n"
    "    LEA     ESQ_BannerColorSweepProgramA,A4\n"
    "    MOVE.W  D0,(A4)\n"
    "    LEA     ESQ_BannerColorSweepProgramB,A4\n"
    "    MOVE.W  D0,(A4)\n"
    "    LEA     ESQ_BannerColorSweepProgramA_AnchorColorWord,A4\n"
    "    MOVE.W  D0,(A4)\n"
    "    LEA     ESQ_BannerColorSweepProgramB_AnchorColorWord,A4\n"
    "    MOVE.W  D0,(A4)\n"
    "    BRA.W   .lab_0CA5\n"
    ".lab_0CA4:\n"
    "    LEA     ESQ_BannerColorSweepProgramA_TailColorWord,A4\n"
    "    MOVE.W  D0,(A4)\n"
    "    LEA     ESQ_BannerColorSweepProgramB_TailColorWord,A4\n"
    "    MOVE.W  D0,(A4)\n"
    ".lab_0CA5:\n"
    "    ADDQ.W  #4,D3\n"
    "    DBF     D4,.lab_0CA2\n"
    "    RTS\n"
);
