__asm__(
    ".globl _ESQSHARED4_BlitBannerRowsForActiveField\n"
    "_ESQSHARED4_BlitBannerRowsForActiveField:\n"
    "ESQSHARED4_BlitBannerRowsForActiveField:\n"
    "    MOVEM.L D0/A0-A1,-(A7)\n"
    "    MOVE.L  ESQPARS2_BannerRowCopySpanBytes,D1\n"
    "    MOVE.L  ESQPARS2_BannerRowCopyStrideBytes,D0\n"
    "    TST.L   ESQPARS2_ActiveCopperListSelectFlag\n"
    "    BNE.S   .lab_0C9F\n"
    "    ADDI.L  #$58,D0\n"
    "    LEA     ESQ_CopperListBannerA,A0\n"
    "    BRA.S   .lab_0CA0\n"
    ".lab_0C9F:\n"
    "    LEA     ESQ_CopperListBannerB,A0\n"
    ".lab_0CA0:\n"
    "    MOVE.L  D0,ESQPARS2_BannerCopyTailOffset\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.L  D1,ESQPARS2_BannerCopySourceOffset\n"
    "    JSR     ESQSHARED4_CopyInterleavedRowWordsFromOffset\n"
    "    LEA     ESQSHARED_BannerRowScratchRasterBase0,A1\n"
    "    MOVEA.L (A1),A0\n"
    "    JSR     ESQSHARED4_CopyBannerRowsWithByteOffset\n"
    "    LEA     ESQSHARED_BannerRowScratchRasterBase1,A1\n"
    "    MOVEA.L (A1),A0\n"
    "    JSR     ESQSHARED4_CopyBannerRowsWithByteOffset\n"
    "    LEA     ESQSHARED_BannerRowScratchRasterBase2,A1\n"
    "    MOVEA.L (A1),A0\n"
    "    JSR     ESQSHARED4_CopyBannerRowsWithByteOffset\n"
    "    MOVEM.L (A7)+,D0/A0-A1\n"
    "    RTS\n"
);
