__asm__(
    ".globl _ESQSHARED4_SetBannerCopperColorAndThreshold\n"
    "_ESQSHARED4_SetBannerCopperColorAndThreshold:\n"
    "ESQSHARED4_SetBannerCopperColorAndThreshold:\n"
    "    MOVE.B  D0,(A4)\n"
    "    LEA     ESQ_CopperListBannerB,A4\n"
    "    MOVE.B  D0,(A4)\n"
    "    LEA     ESQ_BannerSweepWaitRowA,A4\n"
    "    ADDI.B  #$1,D0\n"
    "    MOVE.B  D0,(A4)\n"
    "    LEA     ESQ_BannerSweepWaitRowB,A4\n"
    "    MOVE.B  D0,(A4)\n"
    "    ADDI.B  #$11,D0\n"
    "    LEA     ESQ_BannerSweepWaitStartProgramA,A4\n"
    "    MOVE.B  D0,(A4)\n"
    "    LEA     ESQ_BannerSweepWaitStartProgramB,A4\n"
    "    MOVE.B  D0,(A4)\n"
    "    ADDQ.W  #1,D0\n"
    "    LEA     ESQ_BannerSweepWaitEndProgramA,A4\n"
    "    MOVE.B  D0,(A4)\n"
    "    LEA     ESQ_BannerSweepWaitEndProgramB,A4\n"
    "    MOVE.B  D0,(A4)\n"
    "    ANDI.W  #$ff,D0\n"
    "    MOVE.W  D0,ESQPARS2_BannerColorThreshold\n"
    "    RTS\n"
);
