__asm__(
    ".globl _ESQSHARED4_CopyPlanesFromContextToSnapshot\n"
    "_ESQSHARED4_CopyPlanesFromContextToSnapshot:\n"
    "ESQSHARED4_CopyPlanesFromContextToSnapshot:\n"
    "    MOVEM.L D1/A1-A4,-(A7)\n"
    "    LEA     20(A1),A1\n"
    "    LEA     ESQPARS2_BannerSnapshotPlane0DstPtr,A2\n"
    "    MOVEA.L (A1),A3\n"
    "    MOVEA.L (A2)+,A4\n"
    "    MOVE.L  #$2b,D1\n"
    ".lab_0C94:\n"
    "    MOVE.L  (A3)+,(A4)+\n"
    "    DBF     D1,.lab_0C94\n"
    "    MOVE.L  A3,(A1)+\n"
    "    MOVEA.L (A1),A3\n"
    "    MOVEA.L (A2)+,A4\n"
    "    MOVE.L  #$2b,D1\n"
    ".lab_0C95:\n"
    "    MOVE.L  (A3)+,(A4)+\n"
    "    DBF     D1,.lab_0C95\n"
    "    MOVE.L  A3,(A1)+\n"
    "    MOVEA.L (A1),A3\n"
    "    MOVEA.L (A2)+,A4\n"
    "    MOVE.L  #$2b,D1\n"
    ".lab_0C96:\n"
    "    MOVE.L  (A3)+,(A4)+\n"
    "    DBF     D1,.lab_0C96\n"
    "    MOVE.L  A3,(A1)+\n"
    "    MOVEM.L (A7)+,D1/A1-A4\n"
    "    RTS\n"
);
