__asm__(
    ".globl _ESQSHARED4_TickCopperAndBannerTransitions\n"
    "_ESQSHARED4_TickCopperAndBannerTransitions:\n"
    "ESQSHARED4_TickCopperAndBannerTransitions:\n"
    "    MOVEM.L D0-D3/A0-A6,-(A7)\n"
    "    LEA     BLTDDAT,A0\n"
    "    LEA     ESQ_CopperEffectListA,A2\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.W  VPOSR,D0\n"
    "    BPL.S   .lab_0C83\n"
    "    LEA     ESQ_CopperEffectListB,A2\n"
    "    MOVEQ   #0,D1\n"
    ".lab_0C83:\n"
    "    MOVE.L  A2,COP1LCH\n"
    "    MOVE.L  D1,ESQPARS2_ActiveCopperListSelectFlag\n"
    "    TST.W   ESQPARS2_CopperProgramPendingFlag\n"
    "    BEQ.S   .lab_0C84\n"
    "    JSR     ESQSHARED4_ProgramDisplayWindowAndCopper\n"
    "    MOVE.W  #0,ESQPARS2_CopperProgramPendingFlag\n"
    "    BRA.W   .lab_0C8B\n"
    ".lab_0C84:\n"
    "    JSR     SCRIPT_UpdateBannerCharTransition\n"
    "    TST.W   SCRIPT_BannerTransitionActive\n"
    "    BNE.W   .lab_0C8B\n"
    "    TST.B   GCOMMAND_HighlightHoldoffTickCount\n"
    "    BNE.W   .lab_0C8A\n"
    "    CMPI.W  #$200,ESQPARS2_ReadModeFlags\n"
    "    BNE.W   .lab_0C85\n"
    "    MOVE.W  #$100,ESQPARS2_ReadModeFlags\n"
    "    BRA.W   .lab_0C89\n"
    ".lab_0C85:\n"
    "    CMPI.W  #$102,ESQPARS2_ReadModeFlags\n"
    "    BNE.W   .lab_0C86\n"
    "    BRA.W   .lab_0C8B\n"
    ".lab_0C86:\n"
    "    CMPI.W  #$101,ESQPARS2_ReadModeFlags\n"
    "    BNE.W   .lab_0C87\n"
    "    BRA.W   .lab_0C8B\n"
    ".lab_0C87:\n"
    "    CMPI.W  #$100,ESQPARS2_ReadModeFlags\n"
    "    BEQ.W   .lab_0C8B\n"
    "    TST.W   ESQPARS2_ReadModeFlags\n"
    "    BMI.S   .lab_0C88\n"
    "    MOVEQ   #1,D0\n"
    "    SUB.W   D0,ESQPARS2_ReadModeFlags\n"
    "    BRA.W   .lab_0C8B\n"
    ".lab_0C88:\n"
    "    SUBQ.W  #1,ESQPARS2_HighlightTickCountdown\n"
    "    BPL.S   .lab_0C8B\n"
    ".lab_0C89:\n"
    "    MOVE.W  ESQPARS2_StateIndex,ESQPARS2_HighlightTickCountdown\n"
    "    TST.W   ED2_HighlightTickEnabledFlag\n"
    "    BEQ.S   .lab_0C8B\n"
    "    JSR     GCOMMAND_TickHighlightState\n"
    "    BRA.S   .lab_0C8B\n"
    ".lab_0C8A:\n"
    "    SUBQ.B  #1,GCOMMAND_HighlightHoldoffTickCount\n"
    "    SUBQ.W  #1,ESQPARS2_HighlightTickCountdown\n"
    "    JSR     ESQSHARED4_BlitBannerRowsForActiveField\n"
    ".lab_0C8B:\n"
    "    MOVEM.L (A7)+,D0-D3/A0-A6\n"
    "    RTS\n"
);
