__asm__(
    ".globl _FLIB_AppendClockStampedLogEntry\n"
    ".globl _FLIB_AppendClockStampedLogEntry_Return\n"
    "_FLIB_AppendClockStampedLogEntry:\n"
    "FLIB_AppendClockStampedLogEntry:\n"
    "    LINK.W  A5,#-132\n"
    "    MOVEM.L D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "\n"
    ".lab_0CB6:\n"
    "    TST.L   ESQPARS2_LogAppendSpinlock\n"
    "    BNE.S   .lab_0CB6\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,ESQPARS2_LogAppendSpinlock\n"
    "    MOVE.W  FLIB_LogEntryByteCount,D0\n"
    "    CMPI.W  #$2710,D0\n"
    "    BLE.S   .lab_0CB7\n"
    "\n"
    "    CLR.L   ESQPARS2_LogAppendSpinlock\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.W   FLIB_AppendClockStampedLogEntry_Return\n"
    "\n"
    ".lab_0CB7:\n"
    "    MOVEA.L A3,A0\n"
    "\n"
    ".branch:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .branch\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  A3,A0\n"
    "    MOVE.L  A0,D7\n"
    "    MOVEQ   #100,D0\n"
    "    CMP.W   D0,D7\n"
    "    BLE.S   .branch_1\n"
    "\n"
    "    MOVE.L  D0,D7\n"
    "    CLR.B   99(A3)\n"
    "\n"
    ".branch_1:\n"
    "    MOVE.W  CLOCK_CacheHour,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #100,D1\n"
    "    JSR     NEWGRID_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.W  CLOCK_CacheMinuteOrSecond,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D1,8(A7)\n"
    "    MOVEQ   #100,D1\n"
    "    JSR     NEWGRID_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.W  Global_REF_CLOCKDATA_STRUCT,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D1,12(A7)\n"
    "    MOVEQ   #100,D1\n"
    "    JSR     NEWGRID_JMPTBL_MATH_DivS32(PC)\n"
    "\n"
    "    TST.W   CLOCK_CacheAmPmFlag\n"
    "    BEQ.S   .branch_2\n"
    "\n"
    "    LEA     ESQPARS2_LogTagPm,A0\n"
    "    BRA.S   .branch_3\n"
    "\n"
    ".branch_2:\n"
    "    LEA     ESQPARS2_LogTagAm,A0\n"
    "\n"
    ".branch_3:\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  20(A7),-(A7)\n"
    "    MOVE.L  20(A7),-(A7)\n"
    "    PEA     ESQPARS2_LogTimestampFmt\n"
    "    PEA     -119(A5)\n"
    "    JSR     GROUP_AW_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    ADDI.W  #14,D7\n"
    "    PEA     ESQPARS2_LogFieldTab\n"
    "    PEA     -119(A5)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    MOVE.L  A3,(A7)\n"
    "    PEA     -119(A5)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    PEA     ESQPARS2_LogLineTerminator\n"
    "    PEA     -119(A5)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVE.W  FLIB_LogEntryByteCount,D0\n"
    "    MOVE.L  D0,D1\n"
    "    ADD.W   D7,D1\n"
    "    MOVE.W  D1,FLIB_LogEntryByteCount\n"
    "    EXT.L   D1\n"
    "    ADDQ.L  #1,D1\n"
    "    PEA     (MEMF_PUBLIC).W\n"
    "    MOVE.L  D1,-(A7)\n"
    "    PEA     173.W\n"
    "    PEA     Global_STR_FLIB_C_1\n"
    "    JSR     NEWGRID_JMPTBL_MEMORY_AllocateMemory(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.W  FLIB_LogEntryByteCount,D1\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    CMP.W   D7,D1\n"
    "    BEQ.S   .branch_5\n"
    "\n"
    "    MOVEA.L NEWGRID2_ErrorLogEntryPtr,A0\n"
    "    MOVEA.L D0,A1\n"
    "\n"
    ".branch_4:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .branch_4\n"
    "\n"
    "    BRA.S   .branch_6\n"
    "\n"
    ".branch_5:\n"
    "    MOVEA.L D0,A0\n"
    "    CLR.B   (A0)\n"
    "\n"
    ".branch_6:\n"
    "    PEA     -119(A5)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    JSR     GROUP_AR_JMPTBL_STRING_AppendAtNull(PC)\n"
    "\n"
    "    MOVE.L  NEWGRID2_ErrorLogEntryPtr,(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    JSR     ESQPARS_ReplaceOwnedString(PC)\n"
    "\n"
    "    MOVE.L  D0,NEWGRID2_ErrorLogEntryPtr\n"
    "    MOVE.W  FLIB_LogEntryByteCount,D0\n"
    "    EXT.L   D0\n"
    "    ADDQ.L  #1,D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    PEA     198.W\n"
    "    PEA     Global_STR_FLIB_C_2\n"
    "    JSR     NEWGRID_JMPTBL_MEMORY_DeallocateMemory(PC)\n"
    "\n"
    "    CLR.L   ESQPARS2_LogAppendSpinlock\n"
    "\n"
    "_FLIB_AppendClockStampedLogEntry_Return:\n"
    "FLIB_AppendClockStampedLogEntry_Return:\n"
    "    MOVEM.L -140(A5),D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
