/*
 * Target 603 GCC trial symbol.
 * Keep this as a raw code-label body to preserve the original unsigned divide core.
 */
__asm__(
    ".text\n\t"
    ".globl MATH_DivU32\n"
    "MATH_DivU32:\n\t"
    "move.l %d2,-(%sp)\n\t"
    "swap %d1\n\t"
    "move.w %d1,%d2\n\t"
    "bne.w .div_long\n\t"
    "swap %d0\n\t"
    "swap %d1\n\t"
    "swap %d2\n\t"
    "move.w %d0,%d2\n\t"
    "beq.w .div_simple_done\n\t"
    "divu %d1,%d2\n\t"
    "move.w %d2,%d0\n"
    ".div_simple_done:\n\t"
    "swap %d0\n\t"
    "move.w %d0,%d2\n\t"
    "divu %d1,%d2\n\t"
    "move.w %d2,%d0\n\t"
    "swap %d2\n\t"
    "move.w %d2,%d1\n\t"
    "move.l (%sp)+,%d2\n\t"
    "rts\n"
    ".div_long:\n\t"
    "move.l %d3,-(%sp)\n\t"
    "moveq #16,%d3\n\t"
    "cmpi.w #0x80,%d1\n\t"
    "bcc.w .shift8\n\t"
    "rol.l #8,%d1\n\t"
    "subq.w #8,%d3\n"
    ".shift8:\n\t"
    "cmpi.w #0x800,%d1\n\t"
    "bcc.w .shift4\n\t"
    "rol.l #4,%d1\n\t"
    "subq.w #4,%d3\n"
    ".shift4:\n\t"
    "cmpi.w #0x2000,%d1\n\t"
    "bcc.w .shift2\n\t"
    "rol.l #2,%d1\n\t"
    "subq.w #2,%d3\n"
    ".shift2:\n\t"
    "tst.w %d1\n\t"
    "bmi.w .shift1\n\t"
    "rol.l #1,%d1\n\t"
    "subq.w #1,%d3\n"
    ".shift1:\n\t"
    "move.w %d0,%d2\n\t"
    "lsr.l %d3,%d0\n\t"
    "swap %d2\n\t"
    "clr.w %d2\n\t"
    "lsr.l %d3,%d2\n\t"
    "swap %d3\n\t"
    "divu %d1,%d0\n\t"
    "move.w %d0,%d3\n\t"
    "move.w %d2,%d0\n\t"
    "move.w %d3,%d2\n\t"
    "swap %d1\n\t"
    "mulu %d1,%d2\n\t"
    "sub.l %d2,%d0\n\t"
    "bcc.w .div_finalize\n\t"
    "subq.w #1,%d3\n\t"
    "add.l %d1,%d0\n"
    ".adjust_loop:\n\t"
    "bcc.s .adjust_loop\n"
    ".div_finalize:\n\t"
    "moveq #0,%d1\n\t"
    "move.w %d3,%d1\n\t"
    "swap %d3\n\t"
    "rol.l %d3,%d0\n\t"
    "swap %d0\n\t"
    "exg %d0,%d1\n\t"
    "move.l (%sp)+,%d3\n\t"
    "move.l (%sp)+,%d2\n\t"
    "rts\n\t");
