__asm__(
    ".globl _RENDER_SHORT_MONTH_SHORT_DAY_OF_WEEK_DAY\n"
    "_RENDER_SHORT_MONTH_SHORT_DAY_OF_WEEK_DAY:\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    LINK.W  A5,#-36\n"
    "    MOVEM.L D2-D3/D5-D7,-(A7)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.L  #Global_REF_696_400_BITMAP,4(A0)\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentDayOfWeekIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     Global_JMPTBL_SHORT_DAYS_OF_WEEK,A0\n"
    "    ADDA.L  D0,A0\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentMonthIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     Global_JMPTBL_SHORT_MONTHS,A1\n"
    "    ADDA.L  D0,A1\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentDayOfMonth,D0\n"
    "    EXT.L   D0\n"
    "\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  (A1),-(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    PEA     Global_STR_SHORT_MONTH_SHORT_DAY_OF_WEEK_FORMATTED\n"
    "    PEA     -32(A5)\n"
    "    JSR     GROUP_AE_JMPTBL_WDISP_SPrintf(PC)\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #7,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  32(A0),D0\n"
    "    ANDI.W  #$fff7,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  D0,32(A0)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  58(A0),D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  D0,D3\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.L  D0,D1\n"
    "    MOVEQ   #40,D2\n"
    "    NOT.B   D2\n"
    "    JSR     _LVORectFill(A6)\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    MOVEQ   #3,D0\n"
    "    JSR     _LVOSetAPen(A6)\n"
    "\n"
    "    LEA     -32(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".date_text_len_loop:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .date_text_len_loop\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D6\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    JSR     _LVOTextLength(A6)\n"
    "\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #108,D0\n"
    "    ADD.L   D0,D0\n"
    "    SUB.L   D5,D0\n"
    "    TST.L   D0\n"
    "    BPL.S   .center_date_text_x\n"
    "\n"
    "    ADDQ.L  #1,D0\n"
    "\n"
    ".center_date_text_x:\n"
    "    ASR.L   #1,D0\n"
    "    MOVE.L  D0,D7\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  62(A0),D0\n"
    "    MOVE.L  D0,20(A7)\n"
    "    MOVEA.L A0,A1\n"
    "    MOVE.L  D7,D0\n"
    "    MOVE.L  20(A7),D1\n"
    "    JSR     _LVOMove(A6)\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A1\n"
    "    LEA     -32(A5),A0\n"
    "    JSR     _LVOText(A6)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_RASTPORT_1,A0\n"
    "    MOVE.W  58(A0),D0\n"
    "    SUBQ.L  #2,D0\n"
    "    PEA     192.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     208.W\n"
    "    PEA     40.W\n"
    "    PEA     44.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  4(A0),-(A7)\n"
    "    JSR     GROUP_AD_JMPTBL_GRAPHICS_BltBitMapRastPort(PC)\n"
    "\n"
    "    MOVEM.L -56(A5),D2-D3/D5-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
