__asm__(
    ".globl _TEXTDISP_UpdateChannelRangeFlags\n"
    "_TEXTDISP_UpdateChannelRangeFlags:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D2/D7,-(A7)\n"
    "    MOVE.W  TEXTDISP_ChannelSourceMode,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .use_alt_channel_source\n"
    "\n"
    "    MOVE.L  #TEXTDISP_PrimarySearchText,-4(A5)\n"
    "    MOVE.W  TEXTDISP_PrimaryChannelCode,D7\n"
    "    BRA.S   .ensure_channel_default\n"
    "\n"
    ".use_alt_channel_source:\n"
    "    LEA     TEXTDISP_SecondarySearchText,A0\n"
    "    MOVE.W  TEXTDISP_SecondaryChannelCode,D7\n"
    "    MOVE.L  A0,-4(A5)\n"
    "\n"
    ".ensure_channel_default:\n"
    "    TST.W   D7\n"
    "    BNE.S   .check_channel_range_primary\n"
    "\n"
    "    MOVEQ   #48,D7\n"
    "\n"
    ".check_channel_range_primary:\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   D0,D7\n"
    "    BLT.S   .check_channel_range_alt\n"
    "\n"
    "    MOVEQ   #67,D0\n"
    "    CMP.W   D0,D7\n"
    "    BLE.S   .channel_enabled\n"
    "\n"
    ".check_channel_range_alt:\n"
    "    MOVEQ   #72,D0\n"
    "    CMP.W   D0,D7\n"
    "    BLT.S   .fallback_defaults\n"
    "\n"
    "    MOVEQ   #77,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGT.S   .fallback_defaults\n"
    "\n"
    ".channel_enabled:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    LEA     Global_STR_TEXTDISP_C_3,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.W  CLOCK_CurrentDayOfWeekIndex,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.L  D1,D2\n"
    "    ASL.L   D0,D2\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A0),D0\n"
    "    AND.L   D2,D0\n"
    "    TST.L   D0\n"
    "    BEQ.S   .fallback_defaults\n"
    "\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  -4(A5),-(A7)\n"
    "    BSR.W   TEXTDISP_FindEntryMatchIndex\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.B  D0,TEXTDISP_BannerCharFallback\n"
    "    BRA.S   .return\n"
    "\n"
    ".fallback_defaults:\n"
    "    MOVE.B  #$64,TEXTDISP_BannerCharSelected\n"
    "    MOVE.B  #$31,TEXTDISP_BannerCharFallback\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D2/D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
