__asm__(
    ".globl _TEXTDISP_FindEntryMatchIndex\n"
    "_TEXTDISP_FindEntryMatchIndex:\n"
    "    LINK.W  A5,#-56\n"
    "    MOVEM.L D5-D7/A2-A3,-(A7)\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVE.B  19(A5),D6\n"
    "    MOVEQ   #0,D0\n"
    "    SUBA.L  A0,A0\n"
    "    MOVE.L  A0,-34(A5)\n"
    "    MOVE.L  A0,-38(A5)\n"
    "    MOVE.L  D0,-22(A5)\n"
    "    MOVE.L  D0,-18(A5)\n"
    "    MOVEA.L 8(A5),A0\n"
    "    TST.B   (A0)\n"
    "    BNE.S   .have_input\n"
    "\n"
    "    MOVEQ   #49,D0\n"
    "    BRA.W   .return\n"
    "\n"
    ".have_input:\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .select_group_default\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    BRA.S   .store_group_count\n"
    "\n"
    ".select_group_default:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".store_group_count:\n"
    "    MOVE.L  D0,D5\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .load_group2_tables\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_GetEntryAuxPointerByMode(PC)\n"
    "\n"
    "    MOVEA.L D0,A3\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    PEA     1.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_GetEntryPointerByMode(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L D0,A2\n"
    "    BRA.S   .dispatch_mode\n"
    "\n"
    ".load_group2_tables:\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    PEA     2.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_GetEntryAuxPointerByMode(PC)\n"
    "\n"
    "    MOVEA.L D0,A3\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    PEA     2.W\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_GetEntryPointerByMode(PC)\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L D0,A2\n"
    "\n"
    ".dispatch_mode:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .mode_forward\n"
    "\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .group1_count\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    ADDQ.L  #1,D0\n"
    "    BRA.S   .store_group1_count\n"
    "\n"
    ".group1_count:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".store_group1_count:\n"
    "    MOVE.L  D0,D5\n"
    "    BRA.W   .begin_scan\n"
    "\n"
    ".mode_forward:\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .mode_backward\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_DISPLIB_FindPreviousValidEntryIndex(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    TST.W   D5\n"
    "    BEQ.S   .mode_forward_fallback\n"
    "\n"
    "    BTST    #7,7(A3,D5.W)\n"
    "    BEQ.S   .begin_scan\n"
    "\n"
    ".mode_forward_fallback:\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .mode_forward_group2_count\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    BRA.S   .mode_forward_store_default\n"
    "\n"
    ".mode_forward_group2_count:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".mode_forward_store_default:\n"
    "    MOVE.L  D0,D5\n"
    "    BRA.S   .begin_scan\n"
    "\n"
    ".mode_backward:\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .mode_default\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    SUBQ.L  #1,D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_DISPLIB_FindPreviousValidEntryIndex(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    TST.W   D5\n"
    "    BEQ.S   .mode_backward_fallback\n"
    "\n"
    "    BTST    #7,7(A3,D5.W)\n"
    "    BEQ.S   .begin_scan\n"
    "\n"
    ".mode_backward_fallback:\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .mode_backward_group2_count\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    BRA.S   .mode_backward_store_default\n"
    "\n"
    ".mode_backward_group2_count:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".mode_backward_store_default:\n"
    "    MOVE.L  D0,D5\n"
    "    BRA.S   .begin_scan\n"
    "\n"
    ".mode_default:\n"
    "    MOVEQ   #1,D5\n"
    "\n"
    ".begin_scan:\n"
    "    MOVE.L  8(A5),-(A7)\n"
    "    BSR.W   TEXTDISP_FindControlToken\n"
    "\n"
    "    PEA     -26(A5)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -34(A5)\n"
    "    MOVE.L  8(A5),-(A7)\n"
    "    MOVE.L  D0,-52(A5)\n"
    "    BSR.W   TEXTDISP_FindQuotedSpan\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    MOVEA.L -34(A5),A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.B  (A0),D1\n"
    "    CLR.B   (A0)\n"
    "    MOVE.L  D0,-44(A5)\n"
    "    MOVE.B  D1,-39(A5)\n"
    "\n"
    ".scan_loop:\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   D0,D5\n"
    "    BGE.W   .restore_input_char\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    TST.L   56(A3,D0.L)\n"
    "    BEQ.W   .next_entry\n"
    "\n"
    "    MOVE.B  7(A3,D5.W),D0\n"
    "    AND.B   D6,D0\n"
    "    CMP.B   D6,D0\n"
    "    BNE.W   .next_entry\n"
    "\n"
    "    LEA     28(A2),A0\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     TLIBA2_JMPTBL_ESQ_TestBit1Based(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    ADDQ.L  #1,D0\n"
    "    BNE.W   .next_entry\n"
    "\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L 56(A3,D0.L),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A0,-14(A5)\n"
    "    BSR.W   TEXTDISP_FindControlToken\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.L  D0,-56(A5)\n"
    "    MOVE.L  D1,-18(A5)\n"
    "    MOVE.L  D1,-22(A5)\n"
    "    TST.L   -52(A5)\n"
    "    BNE.S   .compare_control_token\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.L  D1,-22(A5)\n"
    "    BRA.S   .compare_entry_text\n"
    "\n"
    ".compare_control_token:\n"
    "    TST.L   D0\n"
    "    BEQ.S   .compare_entry_text\n"
    "\n"
    "    MOVEA.L -52(A5),A0\n"
    "    MOVE.B  (A0),D1\n"
    "    MOVEA.L D0,A0\n"
    "    CMP.B   (A0),D1\n"
    "    BNE.S   .compare_entry_text\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.L  D1,-22(A5)\n"
    "\n"
    ".compare_entry_text:\n"
    "    MOVEQ   #1,D1\n"
    "    CMP.L   -22(A5),D1\n"
    "    BNE.W   .check_match\n"
    "\n"
    "    PEA     -30(A5)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     -38(A5)\n"
    "    MOVE.L  -14(A5),-(A7)\n"
    "    BSR.W   TEXTDISP_FindQuotedSpan\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVEA.L -38(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVE.B  (A1),D1\n"
    "    CLR.B   (A1)\n"
    "    MOVE.L  D0,-48(A5)\n"
    "    MOVE.B  D1,-40(A5)\n"
    "    TST.L   -26(A5)\n"
    "    BEQ.S   .substring_match\n"
    "\n"
    "    TST.L   -30(A5)\n"
    "    BEQ.S   .restore_entry_char\n"
    "\n"
    "    MOVE.L  -44(A5),D1\n"
    "    CMP.L   D0,D1\n"
    "    BNE.S   .restore_entry_char\n"
    "\n"
    "    MOVE.L  -38(A5),-(A7)\n"
    "    MOVE.L  -34(A5),-(A7)\n"
    "    JSR     STRING_CompareNoCase(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    SEQ     D1\n"
    "    NEG.B   D1\n"
    "    EXT.W   D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-18(A5)\n"
    "    BRA.S   .restore_entry_char\n"
    "\n"
    ".substring_match:\n"
    "    MOVE.L  -44(A5),D1\n"
    "    CMP.L   D0,D1\n"
    "    BGT.S   .restore_entry_char\n"
    "\n"
    "    MOVE.L  -34(A5),-(A7)\n"
    "    MOVE.L  -38(A5),-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQ_FindSubstringCaseFold(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.L   D0\n"
    "    SNE     D1\n"
    "    NEG.B   D1\n"
    "    EXT.W   D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-18(A5)\n"
    "\n"
    ".restore_entry_char:\n"
    "    MOVEA.L -38(A5),A0\n"
    "    ADDA.L  -48(A5),A0\n"
    "    MOVE.B  -40(A5),D0\n"
    "    MOVE.B  D0,(A0)\n"
    "\n"
    ".check_match:\n"
    "    TST.L   -18(A5)\n"
    "    BEQ.S   .next_entry\n"
    "\n"
    "    TST.L   -22(A5)\n"
    "    BNE.S   .restore_input_char\n"
    "\n"
    ".next_entry:\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.W   .scan_loop\n"
    "\n"
    ".restore_input_char:\n"
    "    MOVEA.L -34(A5),A0\n"
    "    ADDA.L  -44(A5),A0\n"
    "    MOVE.B  -39(A5),D0\n"
    "    MOVE.B  D0,(A0)\n"
    "    MOVE.L  D5,D0\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D5-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
