__asm__(
    ".globl _TEXTDISP_FindControlToken\n"
    "_TEXTDISP_FindControlToken:\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVEA.L 8(A7),A3\n"
    "\n"
    ".scan_loop:\n"
    "    TST.B   (A3)\n"
    "    BEQ.S   .not_found\n"
    "\n"
    "    BTST    #7,(A3)\n"
    "    BEQ.S   .skip_byte\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A3),D0\n"
    "    SUBI.W  #$84,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #5,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #2,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #3,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #6,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #1,D0\n"
    "    BEQ.S   .found_token\n"
    "\n"
    "    SUBQ.W  #8,D0\n"
    "    BNE.S   .skip_byte\n"
    "\n"
    ".found_token:\n"
    "    MOVE.L  A3,D0\n"
    "    BRA.S   .return\n"
    "\n"
    ".skip_byte:\n"
    "    ADDQ.L  #1,A3\n"
    "    BRA.S   .scan_loop\n"
    "\n"
    ".not_found:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".return:\n"
    "    MOVEA.L (A7)+,A3\n"
    "    RTS\n"
);
