__asm__(
    ".globl _TEXTDISP_SelectBestMatchFromList\n"
    "_TEXTDISP_SelectBestMatchFromList:\n"
    "TEXTDISP_SelectBestMatchFromList:\n"
    "    LINK.W  A5,#-24\n"
    "    MOVEM.L D2-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVE.W  18(A5),D6\n"
    "    MOVEA.L 20(A5),A2\n"
    "    MOVE.W  #$fffa,-12(A5)\n"
    "    MOVE.W  #$5a1,-20(A5)\n"
    "    MOVE.W  #$fa5f,-22(A5)\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  D0,TEXTDISP_BannerFallbackValidFlag\n"
    "    MOVE.B  D0,TEXTDISP_BannerSelectedValidFlag\n"
    "    MOVE.B  #$64,TEXTDISP_BannerCharSelected\n"
    "    LEA     TEXTDISP_Tag_SPT_Select,A0\n"
    "    MOVEA.L A2,A1\n"
    "    MOVE.B  D0,-23(A5)\n"
    "\n"
    ".compare_spt_prefix:\n"
    "    MOVE.B  (A0)+,D1\n"
    "    CMP.B   (A1)+,D1\n"
    "    BNE.S   .set_spt_flag\n"
    "\n"
    "    TST.B   D1\n"
    "    BNE.S   .compare_spt_prefix\n"
    "\n"
    "    BNE.S   .set_spt_flag\n"
    "\n"
    "    MOVE.B  #$8,-13(A5)\n"
    "    BRA.S   .init_channel_range\n"
    "\n"
    ".set_spt_flag:\n"
    "    MOVE.B  D0,-13(A5)\n"
    "\n"
    ".init_channel_range:\n"
    "    MOVE.W  #$31,-6(A5)\n"
    "    MOVE.W  -6(A5),D0\n"
    "    MOVE.B  D0,TEXTDISP_BannerCharFallback\n"
    "    TST.W   D6\n"
    "    BNE.S   .ensure_channel_default\n"
    "\n"
    "    MOVEQ   #48,D6\n"
    "\n"
    ".ensure_channel_default:\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLT.S   .check_channel_range_alt\n"
    "\n"
    "    MOVEQ   #67,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .channel_enabled\n"
    "\n"
    ".check_channel_range_alt:\n"
    "    MOVEQ   #72,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLT.W   .return_error\n"
    "\n"
    "    MOVEQ   #77,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGT.W   .return_error\n"
    "\n"
    ".channel_enabled:\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    LEA     Global_STR_TEXTDISP_C_3,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.W  CLOCK_CurrentDayOfWeekIndex,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #1,D1\n"
    "    ASL.L   D0,D1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A0),D0\n"
    "    AND.L   D1,D0\n"
    "    TST.L   D0\n"
    "    BEQ.W   .return_error\n"
    "\n"
    "    MOVEQ   #0,D5\n"
    "\n"
    ".candidate_loop:\n"
    "    CMP.W   D7,D5\n"
    "    BGE.W   .finalize_candidates\n"
    "\n"
    "    LEA     TEXTDISP_CandidateIndexList,A0\n"
    "    ADDA.W  D5,A0\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  (A0),D0\n"
    "    MOVE.W  D0,TEXTDISP_CurrentMatchIndex\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  -13(A5),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     1.W\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_FindEntryMatchIndex\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-4(A5)\n"
    "    MOVEQ   #49,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.W   .ensure_entry_index\n"
    "\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .compute_time_group2\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    EXT.L   D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    BSR.W   TEXTDISP_ComputeTimeOffset\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-18(A5)\n"
    "    BRA.S   .after_time_offset\n"
    "\n"
    ".compute_time_group2:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.W  -4(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   TEXTDISP_ComputeTimeOffset\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-18(A5)\n"
    "\n"
    ".after_time_offset:\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BNE.S   .compute_special_flag\n"
    "\n"
    "    CLR.B   -23(A5)\n"
    "    BRA.S   .compute_entry_index\n"
    "\n"
    ".compute_special_flag:\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D1\n"
    "    MOVE.W  -4(A5),D2\n"
    "    CMP.W   D1,D2\n"
    "    BLT.S   .set_special_true\n"
    "\n"
    "    CMP.W   D2,D1\n"
    "    BNE.S   .set_special_false\n"
    "\n"
    "    TST.W   D0\n"
    "    BGT.S   .set_special_false\n"
    "\n"
    ".set_special_true:\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   .store_special_flag\n"
    "\n"
    ".set_special_false:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".store_special_flag:\n"
    "    MOVE.B  D0,-23(A5)\n"
    "\n"
    ".compute_entry_index:\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .set_group2_min\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D0\n"
    "    BRA.S   .compare_min_index\n"
    "\n"
    ".set_group2_min:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".compare_min_index:\n"
    "    MOVE.W  -4(A5),D1\n"
    "    EXT.L   D1\n"
    "    CMP.L   D0,D1\n"
    "    BGT.S   .use_current_index\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  -13(A5),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     2.W\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_FindEntryMatchIndex\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-16(A5)\n"
    "    MOVEQ   #49,D1\n"
    "    CMP.W   D1,D0\n"
    "    BGE.S   .mark_found_primary\n"
    "\n"
    "    MOVE.B  #$1,TEXTDISP_BannerFallbackValidFlag\n"
    "    BRA.S   .compute_time_secondary\n"
    "\n"
    ".mark_found_primary:\n"
    "    MOVE.W  -4(A5),D0\n"
    "    MOVE.W  D0,-16(A5)\n"
    "    BRA.S   .compute_time_secondary\n"
    "\n"
    ".use_current_index:\n"
    "    MOVE.W  -4(A5),D0\n"
    "    MOVE.W  D0,-16(A5)\n"
    "\n"
    ".compute_time_secondary:\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .compute_time_secondary_group2\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_PrimaryGroupCode,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    EXT.L   D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    BSR.W   TEXTDISP_ComputeTimeOffset\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-18(A5)\n"
    "    BRA.S   .after_secondary_time\n"
    "\n"
    ".compute_time_secondary_group2:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_SecondaryGroupCode,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D1,A0\n"
    "    MOVE.W  -16(A5),D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  (A0),-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    BSR.W   TEXTDISP_ComputeTimeOffset\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-18(A5)\n"
    "\n"
    ".after_secondary_time:\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_entry_table\n"
    "\n"
    "    MOVE.W  CLOCK_HalfHourSlotIndex,D1\n"
    "    MOVE.W  -4(A5),D2\n"
    "    CMP.W   D1,D2\n"
    "    BNE.S   .select_entry_table\n"
    "\n"
    "    TST.W   D0\n"
    "    BLE.S   .select_entry_table\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  -13(A5),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    PEA     3.W\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_FindEntryMatchIndex\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  D0,-4(A5)\n"
    "\n"
    ".select_entry_table:\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_group2_table\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-10(A5)\n"
    "    BRA.S   .after_entry_table\n"
    "\n"
    ".select_group2_table:\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-10(A5)\n"
    "\n"
    ".after_entry_table:\n"
    "    MOVE.W  -18(A5),D0\n"
    "    TST.W   D0\n"
    "    BLE.S   .check_best_match\n"
    "\n"
    "    MOVE.W  -16(A5),D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D1\n"
    "    MOVE.W  -12(A5),D2\n"
    "    MOVEA.L -10(A5),A0\n"
    "    MOVE.L  D1,D3\n"
    "    ADDI.L  #400,D3\n"
    "    CMP.W   0(A0,D3.L),D2\n"
    "    BLS.S   .check_best_match\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.B  D1,TEXTDISP_BannerSelectedValidFlag\n"
    "    MOVE.W  -16(A5),D3\n"
    "    MOVE.B  D3,TEXTDISP_BannerCharSelected\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D4\n"
    "    MOVE.B  D4,TEXTDISP_BannerSelectedEntryIndex\n"
    "    MOVE.B  -23(A5),D2\n"
    "    MOVE.B  D2,TEXTDISP_BannerSelectedIsSpecialFlag\n"
    "\n"
    ".check_best_match:\n"
    "    TST.W   D0\n"
    "    BLE.S   .check_alt_match\n"
    "\n"
    "    CMP.W   -20(A5),D0\n"
    "    BGE.S   .check_alt_match\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    MOVE.B  D1,TEXTDISP_BannerFallbackValidFlag\n"
    "    MOVE.W  -16(A5),D1\n"
    "    MOVE.B  D1,TEXTDISP_BannerCharFallback\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    MOVE.B  D2,TEXTDISP_BannerFallbackEntryIndex\n"
    "    MOVE.B  -23(A5),D3\n"
    "    MOVE.B  D3,TEXTDISP_BannerFallbackIsSpecialFlag\n"
    "    MOVE.W  D0,-20(A5)\n"
    "    BRA.W   .update_last_seen\n"
    "\n"
    ".check_alt_match:\n"
    "    TST.B   TEXTDISP_BannerSelectedValidFlag\n"
    "    BNE.S   .check_fallback_match\n"
    "\n"
    "    TST.W   D0\n"
    "    BGT.S   .check_fallback_match\n"
    "\n"
    "    MOVE.W  -22(A5),D1\n"
    "    CMP.W   D1,D0\n"
    "    BLE.S   .check_fallback_match\n"
    "\n"
    "    MOVE.W  -16(A5),D2\n"
    "    EXT.L   D2\n"
    "    ADD.L   D2,D2\n"
    "    MOVE.W  -12(A5),D3\n"
    "    MOVEA.L -10(A5),A0\n"
    "    MOVE.L  D2,D4\n"
    "    ADDI.L  #400,D4\n"
    "    CMP.W   0(A0,D4.L),D3\n"
    "    BLS.S   .check_fallback_match\n"
    "\n"
    "    MOVE.W  -16(A5),D2\n"
    "    MOVE.B  D2,TEXTDISP_BannerCharSelected\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D3\n"
    "    MOVE.B  D3,TEXTDISP_BannerSelectedEntryIndex\n"
    "    MOVE.B  -23(A5),D4\n"
    "    MOVE.B  D4,TEXTDISP_BannerSelectedIsSpecialFlag\n"
    "\n"
    ".check_fallback_match:\n"
    "    TST.B   TEXTDISP_BannerFallbackValidFlag\n"
    "    BNE.S   .update_last_seen\n"
    "\n"
    "    TST.W   D0\n"
    "    BGT.S   .update_last_seen\n"
    "\n"
    "    CMP.W   -22(A5),D0\n"
    "    BLE.S   .update_last_seen\n"
    "\n"
    "    MOVE.W  -16(A5),D1\n"
    "    MOVE.B  D1,TEXTDISP_BannerCharFallback\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D2\n"
    "    MOVE.B  D2,TEXTDISP_BannerFallbackEntryIndex\n"
    "    MOVE.B  -23(A5),TEXTDISP_BannerFallbackIsSpecialFlag\n"
    "    MOVE.W  D0,-22(A5)\n"
    "\n"
    ".update_last_seen:\n"
    "    MOVE.W  -16(A5),D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,D0\n"
    "    MOVEA.L -10(A5),A0\n"
    "    MOVE.L  D0,D1\n"
    "    ADDI.L  #400,D1\n"
    "    MOVE.W  0(A0,D1.L),-12(A5)\n"
    "    MOVE.W  -4(A5),D0\n"
    "    MOVE.W  TEXTDISP_FindModeActiveFlag,D1\n"
    "    MOVE.W  D0,-6(A5)\n"
    "    SUBQ.W  #1,D1\n"
    "    BNE.S   .ensure_entry_index\n"
    "\n"
    "    MOVEQ   #2,D0\n"
    "    BRA.W   .return\n"
    "\n"
    ".ensure_entry_index:\n"
    "    MOVEQ   #49,D0\n"
    "    CMP.W   -6(A5),D0\n"
    "    BNE.S   .next_candidate\n"
    "\n"
    "    TST.W   TEXTDISP_SbeFilterActiveFlag\n"
    "    BNE.S   .next_candidate\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  -13(A5),D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    CLR.L   -(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_FindEntryMatchIndex\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D1\n"
    "    MOVE.B  D1,TEXTDISP_BannerFallbackEntryIndex\n"
    "    MOVE.W  D0,-6(A5)\n"
    "\n"
    ".next_candidate:\n"
    "    ADDQ.W  #1,D5\n"
    "    BRA.W   .candidate_loop\n"
    "\n"
    ".finalize_candidates:\n"
    "    CMPI.W  #$31,-6(A5)\n"
    "    BGE.S   .normalize_channel_code\n"
    "\n"
    "    CMPI.W  #$3d,-20(A5)\n"
    "    BGE.S   .bump_usage_count\n"
    "\n"
    "    MOVEQ   #100,D0\n"
    "    MOVE.B  D0,TEXTDISP_BannerCharSelected\n"
    "\n"
    ".bump_usage_count:\n"
    "    MOVE.B  TEXTDISP_BannerCharSelected,D0\n"
    "    MOVEQ   #100,D1\n"
    "    CMP.B   D1,D0\n"
    "    BEQ.S   .return_ok\n"
    "\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .load_group2_table_for_usage\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_BannerSelectedEntryIndex,D1\n"
    "    MOVE.L  D1,D2\n"
    "    EXT.L   D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    MOVE.L  (A0),-10(A5)\n"
    "    BRA.S   .after_usage_table\n"
    "\n"
    ".load_group2_table_for_usage:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  TEXTDISP_BannerSelectedEntryIndex,D1\n"
    "    MOVE.L  D1,D2\n"
    "    EXT.L   D2\n"
    "    ASL.L   #2,D2\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D2,A0\n"
    "    MOVE.L  (A0),-10(A5)\n"
    "\n"
    ".after_usage_table:\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D0,D1\n"
    "    MOVE.L  D1,D0\n"
    "    EXT.L   D0\n"
    "    ADD.L   D0,D0\n"
    "    MOVEA.L -10(A5),A0\n"
    "    MOVE.L  D0,D1\n"
    "    ADDI.L  #400,D1\n"
    "    ADDQ.W  #1,0(A0,D1.L)\n"
    "\n"
    ".return_ok:\n"
    "    MOVEQ   #2,D0\n"
    "    BRA.S   .return\n"
    "\n"
    ".normalize_channel_code:\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .check_channel_range_1\n"
    "\n"
    "    MOVEQ   #58,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLT.S   .set_default_channel\n"
    "\n"
    ".check_channel_range_1:\n"
    "    MOVEQ   #62,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .check_channel_range_2\n"
    "\n"
    "    MOVEQ   #68,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLT.S   .set_default_channel\n"
    "\n"
    ".check_channel_range_2:\n"
    "    MOVEQ   #71,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .channel_ok\n"
    "\n"
    "    MOVEQ   #78,D0\n"
    "    CMP.W   D0,D6\n"
    "    BGE.S   .channel_ok\n"
    "\n"
    ".set_default_channel:\n"
    "    MOVEQ   #68,D6\n"
    "    MOVEQ   #1,D0\n"
    "    BRA.S   .return\n"
    "\n"
    ".channel_ok:\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   .return\n"
    "\n"
    ".return_error:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D2-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
    "\n"
);
