__asm__(
    ".globl _TEXTDISP_FormatEntryTime\n"
    "_TEXTDISP_FormatEntryTime:\n"
    "    LINK.W  A5,#-16\n"
    "    MOVEM.L D4-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_group2\n"
    "\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEA.L (A1),A2\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    ADDA.L  D1,A2\n"
    "    MOVE.L  56(A2),-4(A5)\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVE.B  498(A1),D6\n"
    "    BRA.S   .have_entry\n"
    "\n"
    ".select_group2:\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    MOVEA.L A0,A1\n"
    "    ADDA.L  D0,A1\n"
    "    MOVEA.L (A1),A2\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    ASL.L   #2,D1\n"
    "    ADDA.L  D1,A2\n"
    "    MOVE.L  56(A2),-4(A5)\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVE.B  498(A1),D6\n"
    "\n"
    ".have_entry:\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  D6,D1\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_ComputeScheduleOffsetForRow(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,D5\n"
    "    TST.L   -4(A5)\n"
    "    BEQ.W   .clear_output\n"
    "\n"
    "    MOVEA.L -4(A5),A0\n"
    "    TST.B   (A0)\n"
    "    BEQ.W   .clear_output\n"
    "\n"
    "    MOVEQ   #40,D0\n"
    "    CMP.B   (A0),D0\n"
    "    BNE.S   .format_minutes\n"
    "\n"
    "    MOVEQ   #58,D0\n"
    "    CMP.B   3(A0),D0\n"
    "    BEQ.S   .parse_hhmm\n"
    "\n"
    ".format_minutes:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  CLOCK_FormatVariantCode,D0\n"
    "    MOVEQ   #30,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.L  D1,D5\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_CLEANUP_FormatClockFormatEntry(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    BRA.W   .return\n"
    "\n"
    ".parse_hhmm:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  4(A0),D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     MATH_Mulu32(PC)\n"
    "\n"
    "    MOVEQ   #0,D1\n"
    "    MOVE.B  5(A0),D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVE.L  D0,D4\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  CLOCK_FormatVariantCode,D0\n"
    "    MOVEQ   #30,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.L  D1,D5\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #30,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  CLOCK_FormatVariantCode,D0\n"
    "    MOVE.L  D1,24(A7)\n"
    "    MOVEQ   #30,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    MOVE.L  24(A7),D0\n"
    "    CMP.L   D1,D0\n"
    "    BGE.S   .round_hour\n"
    "\n"
    "    ADDQ.W  #1,D5\n"
    "\n"
    ".round_hour:\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    DIVS    #$1e,D0\n"
    "    SWAP    D0\n"
    "    MOVE.L  D0,D4\n"
    "    MOVEQ   #48,D0\n"
    "    CMP.W   D0,D5\n"
    "    BLE.S   .wrap_hour\n"
    "\n"
    "    SUBI.W  #$30,D5\n"
    "\n"
    ".wrap_hour:\n"
    "    MOVE.L  D5,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    MOVEA.L Global_REF_STR_CLOCK_FORMAT,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A1\n"
    "    MOVEA.L A3,A2\n"
    "\n"
    ".copy_clock_format:\n"
    "    MOVE.B  (A1)+,(A2)+\n"
    "    BNE.S   .copy_clock_format\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  3(A3),D0\n"
    "    MOVEQ   #48,D1\n"
    "    SUB.L   D1,D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.L  D4,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.L  D1,D4\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    MOVEQ   #48,D1\n"
    "    ADD.L   D1,D0\n"
    "    MOVE.B  D0,3(A3)\n"
    "    MOVE.L  D4,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #10,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    MOVEQ   #48,D0\n"
    "    ADD.L   D0,D1\n"
    "    MOVE.B  D1,4(A3)\n"
    "    BRA.S   .return\n"
    "\n"
    ".clear_output:\n"
    "    CLR.B   (A3)\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D4-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
