__asm__(
    ".globl _TEXTDISP_FindQuotedSpan\n"
    "_TEXTDISP_FindQuotedSpan:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    CLR.L   -8(A5)\n"
    "    MOVEA.L 20(A5),A0\n"
    "    CLR.L   (A0)\n"
    "    PEA     34.W\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    TST.L   D0\n"
    "    BEQ.S   .check_second_quote\n"
    "\n"
    "    MOVEA.L D0,A0\n"
    "    ADDQ.L  #1,A0\n"
    "    PEA     34.W\n"
    "    MOVE.L  A0,-(A7)\n"
    "    JSR     STR_FindCharPtr(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,-8(A5)\n"
    "\n"
    ".check_second_quote:\n"
    "    TST.L   -8(A5)\n"
    "    BNE.S   .mark_has_quotes\n"
    "\n"
    "    TST.L   -4(A5)\n"
    "    BNE.S   .maybe_skip_prefix\n"
    "\n"
    "    MOVEA.L A3,A0\n"
    "    MOVE.L  A0,-4(A5)\n"
    "\n"
    ".maybe_skip_prefix:\n"
    "    MOVEQ   #40,D0\n"
    "    MOVEA.L -4(A5),A0\n"
    "    CMP.B   (A0),D0\n"
    "    BNE.S   .select_end_ptr\n"
    "\n"
    "    ADDQ.L  #8,-4(A5)\n"
    "\n"
    ".select_end_ptr:\n"
    "    MOVEA.L 16(A5),A0\n"
    "    MOVE.L  A0,-8(A5)\n"
    "    BEQ.S   .scan_to_end\n"
    "\n"
    "    SUBQ.L  #1,-8(A5)\n"
    "    BRA.S   .trim_leading_ctrl\n"
    "\n"
    ".scan_to_end:\n"
    "    MOVEA.L A3,A0\n"
    "\n"
    ".scan_to_end_loop:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .scan_to_end_loop\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  A3,A0\n"
    "    MOVE.L  A0,D0\n"
    "    MOVEA.L A3,A1\n"
    "    ADDA.L  D0,A1\n"
    "    SUBQ.L  #1,A1\n"
    "    MOVE.L  A1,-8(A5)\n"
    "    BRA.S   .trim_leading_ctrl\n"
    "\n"
    ".mark_has_quotes:\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L 20(A5),A0\n"
    "    MOVE.L  D0,(A0)\n"
    "\n"
    ".trim_leading_ctrl:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.B  (A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #3,(A1)\n"
    "    BEQ.S   .trim_trailing_ctrl\n"
    "\n"
    "    ADDQ.L  #1,-4(A5)\n"
    "    BRA.S   .trim_leading_ctrl\n"
    "\n"
    ".trim_trailing_ctrl:\n"
    "    MOVEA.L -8(A5),A0\n"
    "    MOVE.B  (A0),D0\n"
    "    EXT.W   D0\n"
    "    EXT.L   D0\n"
    "    LEA     WDISP_CharClassTable,A1\n"
    "    ADDA.L  D0,A1\n"
    "    BTST    #3,(A1)\n"
    "    BEQ.S   .return\n"
    "\n"
    "    SUBQ.L  #1,-8(A5)\n"
    "    BRA.S   .trim_trailing_ctrl\n"
    "\n"
    ".return:\n"
    "    MOVEA.L -4(A5),A0\n"
    "    MOVE.L  A0,(A2)\n"
    "    MOVE.L  -8(A5),D0\n"
    "    SUB.L   -4(A5),D0\n"
    "    MOVE.L  D0,D7\n"
    "    ADDQ.L  #1,D7\n"
    "    MOVE.L  D7,D0\n"
    "    MOVEM.L (A7)+,D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
