__asm__(
    ".globl _TEXTDISP_DrawInsetRectFrame\n"
    "_TEXTDISP_DrawInsetRectFrame:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D2-D7/A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVEQ   #0,D6\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    MOVE.W  2(A0),D0\n"
    "    MOVE.L  D0,D4\n"
    "    SUBQ.W  #1,D4\n"
    "    MOVEQ   #0,D5\n"
    "    MOVE.W  4(A0),D0\n"
    "    SUBQ.W  #1,D0\n"
    "    MOVEM.W D0,-8(A5)\n"
    "    MOVEQ   #2,D1\n"
    "    CMP.W   D1,D7\n"
    "    BNE.S   .check_mode_3\n"
    "\n"
    "    MOVE.L  D4,D1\n"
    "    TST.W   D1\n"
    "    BPL.S   .calc_half_width\n"
    "\n"
    "    ADDQ.W  #1,D1\n"
    "\n"
    ".calc_half_width:\n"
    "    ASR.W   #1,D1\n"
    "    MOVE.L  D1,D6\n"
    "    ADDQ.W  #1,D6\n"
    "\n"
    ".check_mode_3:\n"
    "    MOVEQ   #3,D1\n"
    "    CMP.W   D1,D7\n"
    "    BNE.S   .draw_in_entry_rast\n"
    "\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D5,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.L  D4,D3\n"
    "    EXT.L   D3\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  Global_REF_RASTPORT_2,-(A7)\n"
    "    BSR.W   TLIBA1_DrawFormattedTextBlock\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "    BRA.S   .return\n"
    "\n"
    ".draw_in_entry_rast:\n"
    "    LEA     10(A0),A1\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D5,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D4,D2\n"
    "    EXT.L   D2\n"
    "    MOVE.W  -8(A5),D3\n"
    "    EXT.L   D3\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  A1,-(A7)\n"
    "    BSR.W   TLIBA1_DrawFormattedTextBlock\n"
    "\n"
    "    LEA     24(A7),A7\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D2-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
