__asm__(
    ".globl _TEXTDISP_BuildEntryShortName\n"
    "_TEXTDISP_BuildEntryShortName:\n"
    "    LINK.W  A5,#-12\n"
    "    MOVEM.L D6-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    MOVEA.L 12(A5),A2\n"
    "    CLR.B   (A2)\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   .return\n"
    "\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_FindAliasIndexByName\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    MOVE.L  D0,D7\n"
    "    EXT.L   D7\n"
    "    MOVEQ   #-1,D0\n"
    "    CMP.L   D0,D7\n"
    "    BEQ.S   .fallback_entry_name\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_AliasPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVE.L  (A0),-4(A5)\n"
    "    MOVEA.L -4(A5),A1\n"
    "    MOVEA.L 4(A1),A0\n"
    "    MOVEA.L A2,A1\n"
    "\n"
    ".copy_alias:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_alias\n"
    "\n"
    "    BRA.S   .return\n"
    "\n"
    ".fallback_entry_name:\n"
    "    LEA     19(A3),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_fallback:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_fallback\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D6\n"
    "    MOVEQ   #8,D0\n"
    "    CMP.L   D0,D6\n"
    "    BGE.S   .return\n"
    "\n"
    "    TST.L   D6\n"
    "    BEQ.S   .return\n"
    "\n"
    "    LEA     TEXTDISP_CenterAlignToken,A0\n"
    "    MOVEA.L A2,A1\n"
    "\n"
    ".prepend_align:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .prepend_align\n"
    "\n"
    "    LEA     19(A3),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D6-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
