__asm__(
    ".globl _TEXTDISP_BuildMatchIndexList\n"
    "_TEXTDISP_BuildMatchIndexList:\n"
    "    LINK.W  A5,#-20\n"
    "    MOVEM.L D4-D7/A2-A3,-(A7)\n"
    "    MOVE.W  14(A5),D7\n"
    "    MOVEQ   #0,D5\n"
    "    TST.L   8(A5)\n"
    "    BEQ.W   .return\n"
    "\n"
    "    MOVE.L  8(A5),-(A7)\n"
    "    PEA     TEXTDISP_Tag_PPV\n"
    "    JSR     UNKNOWN_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.S   .check_sbe_pattern\n"
    "\n"
    "    MOVEQ   #1,D4\n"
    "    BRA.S   .check_sports_pattern\n"
    "\n"
    ".check_sbe_pattern:\n"
    "    MOVE.L  8(A5),-(A7)\n"
    "    PEA     TEXTDISP_Tag_SBE\n"
    "    JSR     UNKNOWN_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.S   .set_pattern_flag\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.W  D0,TEXTDISP_SbeFilterActiveFlag\n"
    "    MOVE.L  D0,D4\n"
    "    BRA.S   .check_sports_pattern\n"
    "\n"
    ".set_pattern_flag:\n"
    "    MOVEQ   #0,D4\n"
    "\n"
    ".check_sports_pattern:\n"
    "    MOVE.L  8(A5),-(A7)\n"
    "    PEA     TEXTDISP_Tag_SPORTS\n"
    "    JSR     UNKNOWN_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    TST.B   D0\n"
    "    SEQ     D1\n"
    "    NEG.B   D1\n"
    "    EXT.W   D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  8(A5),(A7)\n"
    "    PEA     TEXTDISP_Tag_SPT_Filter\n"
    "    MOVE.W  D1,-16(A5)\n"
    "    JSR     UNKNOWN_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.B   D0\n"
    "    BNE.S   .ensure_filter_pattern\n"
    "\n"
    "    LEA     Global_STR_ASTERISK_2,A0\n"
    "    MOVE.L  A0,8(A5)\n"
    "\n"
    ".ensure_filter_pattern:\n"
    "    LEA     TEXTDISP_Tag_FIND1,A0\n"
    "    MOVEA.L 8(A5),A1\n"
    "\n"
    ".compare_find_prefix:\n"
    "    MOVE.B  (A0)+,D0\n"
    "    CMP.B   (A1)+,D0\n"
    "    BNE.S   .set_find_mode_flag\n"
    "\n"
    "    TST.B   D0\n"
    "    BNE.S   .compare_find_prefix\n"
    "\n"
    "    BNE.S   .set_find_mode_flag\n"
    "\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.W  D0,TEXTDISP_FindModeActiveFlag\n"
    "    MOVE.L  #Global_STR_ASTERISK_3,8(A5)\n"
    "    BRA.S   .init_scan\n"
    "\n"
    ".set_find_mode_flag:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  D0,TEXTDISP_FindModeActiveFlag\n"
    "\n"
    ".init_scan:\n"
    "    MOVEQ   #0,D5\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .set_group2_count\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_PrimaryGroupEntryCount,D0\n"
    "    MOVE.L  D0,-20(A5)\n"
    "    BRA.S   .init_index\n"
    "\n"
    ".set_group2_count:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupEntryCount,D0\n"
    "    MOVE.L  D0,-20(A5)\n"
    "\n"
    ".init_index:\n"
    "    MOVEQ   #0,D6\n"
    "\n"
    ".entry_loop:\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    CMP.L   -20(A5),D0\n"
    "    BGE.W   .return\n"
    "\n"
    "    MOVE.W  TEXTDISP_ActiveGroupId,D0\n"
    "    SUBQ.W  #1,D0\n"
    "    BNE.S   .load_group2_entry\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_PrimaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A3\n"
    "    LEA     TEXTDISP_PrimaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "    BRA.S   .check_entry_filters\n"
    "\n"
    ".load_group2_entry:\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_SecondaryTitlePtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A3\n"
    "    LEA     TEXTDISP_SecondaryEntryPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "\n"
    ".check_entry_filters:\n"
    "    BTST    #3,27(A2)\n"
    "    BNE.S   .next_entry\n"
    "\n"
    "    MOVEQ   #69,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .check_cmd_E\n"
    "\n"
    "    BTST    #7,40(A2)\n"
    "    BEQ.S   .next_entry\n"
    "\n"
    ".check_cmd_E:\n"
    "    TST.W   D4\n"
    "    BEQ.S   .check_editor_flag\n"
    "\n"
    "    BTST    #4,27(A2)\n"
    "    BNE.S   .record_match\n"
    "\n"
    ".check_editor_flag:\n"
    "    TST.W   -16(A5)\n"
    "    BEQ.S   .match_wildcard\n"
    "\n"
    "    MOVE.L  A2,-(A7)\n"
    "    JSR     TEXTDISP_ShouldOpenEditorForEntry(PC)\n"
    "\n"
    "    ADDQ.W  #4,A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .record_match\n"
    "\n"
    ".match_wildcard:\n"
    "    MOVE.L  8(A5),-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    JSR     UNKNOWN_JMPTBL_ESQ_WildcardMatch(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    TST.B   D0\n"
    "    BNE.S   .next_entry\n"
    "\n"
    ".record_match:\n"
    "    LEA     TEXTDISP_CandidateIndexList,A0\n"
    "    ADDA.W  D5,A0\n"
    "    MOVE.L  D6,D0\n"
    "    MOVE.B  D0,(A0)\n"
    "    ADDQ.W  #1,D5\n"
    "\n"
    ".next_entry:\n"
    "    ADDQ.W  #1,D6\n"
    "    BRA.W   .entry_loop\n"
    "\n"
    ".return:\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEM.L (A7)+,D4-D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
