__asm__(
    ".globl _TEXTDISP_FindAliasIndexByName\n"
    "_TEXTDISP_FindAliasIndexByName:\n"
    "    LINK.W  A5,#-24\n"
    "    MOVEM.L D7/A2-A3,-(A7)\n"
    "    MOVEA.L 8(A5),A3\n"
    "    LEA     12(A3),A0\n"
    "    LEA     -21(A5),A1\n"
    "\n"
    ".copy_name:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_name\n"
    "\n"
    "    MOVEQ   #0,D7\n"
    "\n"
    ".loop_aliases:\n"
    "    MOVE.W  TEXTDISP_AliasCount,D0\n"
    "    CMP.W   D0,D7\n"
    "    BGE.S   .not_found\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    ASL.L   #2,D0\n"
    "    LEA     TEXTDISP_AliasPtrTable,A0\n"
    "    ADDA.L  D0,A0\n"
    "    MOVEA.L (A0),A2\n"
    "    MOVEA.L (A2),A0\n"
    "\n"
    ".measure_alias:\n"
    "    TST.B   (A0)+\n"
    "    BNE.S   .measure_alias\n"
    "\n"
    "    SUBQ.L  #1,A0\n"
    "    SUBA.L  (A2),A0\n"
    "    MOVE.L  A0,-(A7)\n"
    "    MOVE.L  (A2),-(A7)\n"
    "    PEA     -21(A5)\n"
    "    JSR     STRING_CompareNoCaseN(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    TST.L   D0\n"
    "    BNE.S   .next_alias\n"
    "\n"
    "    MOVE.L  D7,D0\n"
    "    BRA.S   .return\n"
    "\n"
    ".next_alias:\n"
    "    ADDQ.W  #1,D7\n"
    "    BRA.S   .loop_aliases\n"
    "\n"
    ".not_found:\n"
    "    MOVEQ   #-1,D0\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D7/A2-A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
