__asm__(
    ".globl _TEXTDISP_ComputeTimeOffset\n"
    "_TEXTDISP_ComputeTimeOffset:\n"
    "    LINK.W  A5,#-36\n"
    "    MOVEM.L D2-D7/A3,-(A7)\n"
    "    MOVE.W  10(A5),D7\n"
    "    MOVEA.L 12(A5),A3\n"
    "    MOVE.W  18(A5),D6\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D6,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  D6,D2\n"
    "    EXT.L   D2\n"
    "    MOVEQ   #0,D3\n"
    "    MOVE.B  498(A3),D3\n"
    "    MOVE.L  D3,-(A7)\n"
    "    MOVE.L  D2,-(A7)\n"
    "    MOVE.L  D0,36(A7)\n"
    "    MOVE.L  D1,40(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_ComputeScheduleOffsetForRow(PC)\n"
    "\n"
    "    EXT.L   D0\n"
    "    PEA     -8(A5)\n"
    "    PEA     -20(A5)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  52(A7),-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  56(A7),-(A7)\n"
    "    JSR     TLIBA2_ComputeBroadcastTimeWindow(PC)\n"
    "\n"
    "    LEA     32(A7),A7\n"
    "    MOVE.W  CLOCK_CurrentYearValue,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  -20(A5),D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D4\n"
    "    TST.L   D4\n"
    "    BNE.S   .fallback_offset_1\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentMonthIndex,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  -16(A5),D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D4\n"
    "\n"
    ".fallback_offset_1:\n"
    "    TST.L   D4\n"
    "    BNE.S   .fallback_offset_2\n"
    "\n"
    "    MOVE.W  CLOCK_CurrentDayOfMonth,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  -12(A5),D1\n"
    "    SUB.L   D0,D1\n"
    "    MOVE.L  D1,D4\n"
    "\n"
    ".fallback_offset_2:\n"
    "    MOVE.L  -8(A5),D0\n"
    "    MOVEQ   #60,D1\n"
    "    JSR     MATH_Mulu32(PC)\n"
    "\n"
    "    ADD.L   -4(A5),D0\n"
    "    MOVE.L  D0,D5\n"
    "    MOVE.W  Global_WORD_CURRENT_HOUR,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #12,D1\n"
    "    JSR     MATH_DivS32(PC)\n"
    "\n"
    "    TST.W   CLOCK_CurrentAmPmFlag\n"
    "    BEQ.S   .use_zero_bias\n"
    "\n"
    "    MOVEQ   #12,D0\n"
    "    BRA.S   .apply_hour_bias\n"
    "\n"
    ".use_zero_bias:\n"
    "    MOVEQ   #0,D0\n"
    "\n"
    ".apply_hour_bias:\n"
    "    ADD.L   D0,D1\n"
    "    MOVEQ   #60,D0\n"
    "    JSR     MATH_Mulu32(PC)\n"
    "\n"
    "    MOVE.W  Global_WORD_CURRENT_MINUTE,D1\n"
    "    EXT.L   D1\n"
    "    ADD.L   D1,D0\n"
    "    SUB.L   D0,D5\n"
    "    MOVE.L  D4,D0\n"
    "    MOVE.L  #$5a0,D1\n"
    "    JSR     MATH_Mulu32(PC)\n"
    "\n"
    "    ADD.L   D0,D5\n"
    "    MOVE.L  D5,D0\n"
    "    MOVEM.L (A7)+,D2-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
