__asm__(
    ".globl _TEXTDISP_DrawChannelBanner\n"
    "_TEXTDISP_DrawChannelBanner:\n"
    "    LINK.W  A5,#-8\n"
    "    MOVEM.L D5-D7,-(A7)\n"
    "    MOVE.W  10(A5),D7\n"
    "    MOVE.W  14(A5),D6\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_group2\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    BRA.S   .dispatch_group\n"
    "\n"
    ".select_group2:\n"
    "    MOVEQ   #2,D1\n"
    "\n"
    ".dispatch_group:\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_GetEntryPointerByMode(PC)\n"
    "\n"
    "    PEA     TEXTDISP_EntryShortNameScratch\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  D0,-4(A5)\n"
    "    BSR.W   TEXTDISP_BuildEntryShortName\n"
    "\n"
    "    LEA     TEXTDISP_EntryShortNameScratch,A0\n"
    "    LEA     TEXTDISP_ChannelLabelBuffer,A1\n"
    "\n"
    ".copy_short_name:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_short_name\n"
    "\n"
    "    PEA     1.W\n"
    "    BSR.W   TEXTDISP_BuildChannelLabel\n"
    "\n"
    "    LEA     20(A7),A7\n"
    "    CLR.W   TEXTDISP_LinePenOverrideStateWord\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.W   D0,D6\n"
    "    BNE.S   .select_rast\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    BRA.S   .init_rect\n"
    "\n"
    ".select_rast:\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A0\n"
    "    ADDQ.W  #2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #0,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    ".init_rect:\n"
    "    MOVE.W  #1,TEXTDISP_LinePenOverrideEnabledFlag\n"
    "    MOVEQ   #0,D5\n"
    "    MOVEA.L WDISP_DisplayContextBase,A0\n"
    "    MOVE.W  2(A0),D5\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   D0,D7\n"
    "    BNE.S   .trim_and_draw\n"
    "\n"
    "    TST.L   D5\n"
    "    BPL.S   .adjust_half_width\n"
    "\n"
    "    ADDQ.L  #1,D5\n"
    "\n"
    ".adjust_half_width:\n"
    "    ASR.L   #1,D5\n"
    "\n"
    ".trim_and_draw:\n"
    "    MOVE.L  D5,-(A7)\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    BSR.W   TEXTDISP_TrimTextToPixelWidth\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,(A7)\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    BSR.W   TEXTDISP_DrawInsetRectFrame\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    MOVEQ   #3,D0\n"
    "    CMP.W   D0,D6\n"
    "    BNE.S   .set_drawmode_normal\n"
    "\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    "    BRA.S   .return\n"
    "\n"
    ".set_drawmode_normal:\n"
    "    MOVEA.L Global_REF_RASTPORT_2,A0\n"
    "    ADDQ.W  #2,A0\n"
    "    MOVEA.L A0,A1\n"
    "    MOVEQ   #1,D0\n"
    "    MOVEA.L Global_REF_GRAPHICS_LIBRARY,A6\n"
    "    JSR     _LVOSetDrMd(A6)\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D5-D7\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
