__asm__(
    ".globl _TEXTDISP_SelectGroupAndEntry\n"
    "_TEXTDISP_SelectGroupAndEntry:\n"
    "    MOVEM.L D5-D7/A2-A3,-(A7)\n"
    "    MOVEA.L 24(A7),A3\n"
    "    MOVEA.L 28(A7),A2\n"
    "    MOVE.W  34(A7),D7\n"
    "    MOVEQ   #-1,D0\n"
    "    MOVE.W  D0,TEXTDISP_PrimaryFirstMatchIndex\n"
    "    MOVE.W  D0,TEXTDISP_SecondaryFirstMatchIndex\n"
    "    CLR.W   TEXTDISP_SbeFilterActiveFlag\n"
    "    MOVE.W  #1,TEXTDISP_ActiveGroupId\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_BuildMatchIndexList\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,D6\n"
    "    TST.W   D6\n"
    "    BEQ.S   .check_group1_result\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    BSR.W   TEXTDISP_SelectBestMatchFromList\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_CandidateIndexList,D0\n"
    "    MOVE.W  D0,TEXTDISP_PrimaryFirstMatchIndex\n"
    "\n"
    ".check_group1_result:\n"
    "    TST.W   D6\n"
    "    BEQ.S   .try_group2\n"
    "\n"
    "    TST.W   D5\n"
    "    BNE.S   .after_group2\n"
    "\n"
    ".try_group2:\n"
    "    MOVE.W  TEXTDISP_SecondaryGroupRecordLength,D0\n"
    "    MOVEQ   #0,D1\n"
    "    CMP.W   D1,D0\n"
    "    BLS.S   .after_group2\n"
    "\n"
    "    MOVE.W  D1,TEXTDISP_ActiveGroupId\n"
    "    MOVE.L  D7,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A3,-(A7)\n"
    "    BSR.W   TEXTDISP_BuildMatchIndexList\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVE.L  D0,D6\n"
    "    TST.W   D6\n"
    "    BEQ.S   .after_group2\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVE.L  D7,D1\n"
    "    EXT.L   D1\n"
    "    MOVE.L  A3,-(A7)\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    MOVE.L  A2,-(A7)\n"
    "    BSR.W   TEXTDISP_SelectBestMatchFromList\n"
    "\n"
    "    LEA     16(A7),A7\n"
    "    MOVE.L  D0,D5\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_CandidateIndexList,D0\n"
    "    MOVE.W  D0,TEXTDISP_SecondaryFirstMatchIndex\n"
    "\n"
    ".after_group2:\n"
    "    TST.W   D6\n"
    "    BEQ.S   .no_match\n"
    "\n"
    "    TST.W   D5\n"
    "    BNE.S   .select_index\n"
    "\n"
    ".no_match:\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.W  D0,TEXTDISP_ActiveGroupId\n"
    "    MOVEQ   #0,D0\n"
    "    BRA.S   .return\n"
    "\n"
    ".select_index:\n"
    "    MOVEQ   #2,D0\n"
    "    CMP.W   D0,D5\n"
    "    BNE.S   .use_primary_index\n"
    "\n"
    "    MOVE.B  TEXTDISP_BannerCharSelected,D0\n"
    "    MOVEQ   #100,D1\n"
    "    CMP.B   D1,D0\n"
    "    BNE.S   .use_alt_index\n"
    "\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerFallbackEntryIndex,D0\n"
    "    BRA.S   .store_selected_index\n"
    "\n"
    ".use_alt_index:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_BannerSelectedEntryIndex,D0\n"
    "\n"
    ".store_selected_index:\n"
    "    MOVE.W  D0,TEXTDISP_CurrentMatchIndex\n"
    "    BRA.S   .return_success\n"
    "\n"
    ".use_primary_index:\n"
    "    MOVEQ   #0,D0\n"
    "    MOVE.B  TEXTDISP_CandidateIndexList,D0\n"
    "    MOVE.W  D0,TEXTDISP_CurrentMatchIndex\n"
    "\n"
    ".return_success:\n"
    "    MOVEQ   #1,D0\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D5-D7/A2-A3\n"
    "    RTS\n"
);
