__asm__(
    ".globl _TEXTDISP_BuildChannelLabel\n"
    "_TEXTDISP_BuildChannelLabel:\n"
    "    LINK.W  A5,#-20\n"
    "    MOVEM.L D6-D7/A3,-(A7)\n"
    "    MOVE.W  10(A5),D7\n"
    "    MOVE.W  TEXTDISP_CurrentMatchIndex,D0\n"
    "    EXT.L   D0\n"
    "    TST.W   TEXTDISP_ActiveGroupId\n"
    "    BEQ.S   .select_group\n"
    "\n"
    "    MOVEQ   #1,D1\n"
    "    BRA.S   .dispatch_group\n"
    "\n"
    ".select_group:\n"
    "    MOVEQ   #2,D1\n"
    "\n"
    ".dispatch_group:\n"
    "    MOVE.L  D1,-(A7)\n"
    "    MOVE.L  D0,-(A7)\n"
    "    JSR     TLIBA1_JMPTBL_ESQDISP_GetEntryPointerByMode(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "    MOVEA.L D0,A3\n"
    "    MOVE.L  A3,D0\n"
    "    BEQ.S   .clear_name\n"
    "\n"
    "    LEA     1(A3),A0\n"
    "    LEA     -17(A5),A1\n"
    "\n"
    ".copy_entry_name:\n"
    "    MOVE.B  (A0)+,(A1)+\n"
    "    BNE.S   .copy_entry_name\n"
    "\n"
    "    BRA.S   .measure_name\n"
    "\n"
    ".clear_name:\n"
    "    CLR.B   -17(A5)\n"
    "\n"
    ".measure_name:\n"
    "    LEA     -17(A5),A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".measure_loop:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .measure_loop\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D6\n"
    "    CLR.L   TEXTDISP_ChannelLabelReadyFlag\n"
    "    MOVEQ   #1,D0\n"
    "    CMP.W   D0,D6\n"
    "    BLE.S   .return\n"
    "\n"
    "    MOVE.L  D6,D0\n"
    "    EXT.L   D0\n"
    "    MOVEQ   #32,D1\n"
    "    CMP.B   -19(A5,D0.L),D1\n"
    "    BEQ.S   .return\n"
    "\n"
    "    TST.W   D7\n"
    "    BEQ.S   .append_channel_prefix\n"
    "\n"
    "    PEA     Global_STR_ALIGNED_ON\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     STRING_AppendAtNull(PC)\n"
    "\n"
    "    ADDQ.W  #8,A7\n"
    "\n"
    ".append_channel_prefix:\n"
    "    PEA     Global_STR_ALIGNED_CHANNEL_1\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     1(A3),A0\n"
    "    MOVE.L  A0,(A7)\n"
    "    PEA     TEXTDISP_ChannelLabelBuffer\n"
    "    JSR     STRING_AppendAtNull(PC)\n"
    "\n"
    "    LEA     12(A7),A7\n"
    "    LEA     TEXTDISP_ChannelLabelBuffer,A0\n"
    "    MOVEA.L A0,A1\n"
    "\n"
    ".finalize_label:\n"
    "    TST.B   (A1)+\n"
    "    BNE.S   .finalize_label\n"
    "\n"
    "    SUBQ.L  #1,A1\n"
    "    SUBA.L  A0,A1\n"
    "    MOVE.L  A1,D0\n"
    "    LEA     TEXTDISP_ChannelLabelBufferTerminatorByte,A0\n"
    "    ADDA.L  D0,A0\n"
    "    CLR.B   (A0)\n"
    "    MOVEQ   #1,D0\n"
    "    MOVE.L  D0,TEXTDISP_ChannelLabelReadyFlag\n"
    "\n"
    ".return:\n"
    "    MOVEM.L (A7)+,D6-D7/A3\n"
    "    UNLK    A5\n"
    "    RTS\n"
);
