/* MERGED MODULE: modules/groups/_main/a/a.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQ_StartupEntry, ESQ_ReturnWithStackCode, ESQ_ShutdownAndReturn
 */
#include "lib_esq_startup_entry.c"
#include "lib_esq_shutdown_and_return.c"
