/* MERGED MODULE: modules/groups/a/a/app2_p7.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQ_AdvanceBannerCharIndex, ESQ_AdjustBracketedHourInString
 */
#include "esq_advance_banner_char_index.c"
#include "esq_adjust_bracketed_hour_in_string.c"
