/* MERGED MODULE: modules/groups/a/a/app2_esq_findsubstringcasefold.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQ_FindSubstringCaseFold, ESQ_WriteDecFixedWidth
 */
#include "esq_find_substring_case_fold.c"
#include "esq_write_dec_fixed_width.c"
