/* MERGED MODULE: modules/groups/a/c/cleanup2_p1_p0_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: CLEANUP_DrawDateBannerSegment, CLEANUP_DrawBannerSpacerSegment, CLEANUP_DrawTimeBannerSegment
 */
#include "cleanup_draw_date_banner_segment.c"
#include "cleanup_draw_banner_spacer_segment.c"
#include "cleanup_draw_time_banner_segment.c"
