/* MERGED MODULE: modules/groups/a/e/coi_p3_coi_formatentrydisplaytext_coi_renderclockformatentryvariant.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: COI_RenderClockFormatEntryVariant, COI_FormatEntryDisplayText
 */
#include "coi_render_clock_format_entry_variant.c"
#include "coi_format_entry_display_text.c"
