/* MERGED MODULE: modules/groups/a/e/coi_p3_coi_getanimfieldpointerbymode_coi_getanimfieldpointerbymode.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: COI_SelectAnimFieldPointer, COI_GetAnimFieldPointerByMode
 */
#include "coi_select_anim_field_pointer.c"
#include "coi_get_anim_field_pointer_by_mode.c"
