/* MERGED MODULE: modules/groups/a/e/coi_p4_coi_testentrywithintimewindow_coi_processentryselectionstate.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: COI_ProcessEntrySelectionState, COI_TestEntryWithinTimeWindow
 */
#include "coi_process_entry_selection_state.c"
#include "coi_test_entry_within_time_window.c"
