/* RESTORES: (data module -- no function)
 * MODULE:   data/dst.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 256 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

/* Forward declarations. The type has to match the definition exactly
 * or 6.51 rejects the pair. */
extern char DST_PATH_DF0_COLON_DST_DOT_DAT[];

char DST_PATH_DF0_COLON_DST_DOT_DAT[12] = "df0:dst.dat";
long DST_DefaultDatPathPtr[1] = {
    (long)DST_PATH_DF0_COLON_DST_DOT_DAT
};
char DST_FMT_PCT_C_InTimePrefixChar[4] = "%c";
char DST_FMT_PCT_04D_PCT_03D_InTimeDateCode[10] = "%04d%03d";
char DST_FMT_PCT_02D_COLON_PCT_02D_InTimeClock[10] = "%02d:%02d";
char DST_STR_NO_IN_TIME[14] = " NO IN TIME ";
char DST_FMT_PCT_C_OutTimePrefixChar[4] = "%c";
char DST_FMT_PCT_04D_PCT_03D_OutTimeDateCode[10] = "%04d%03d";
char DST_FMT_PCT_02D_COLON_PCT_02D_OutTimeClock[10] = "%02d:%02d";
char DST_STR_NO_OUT_TIME[14] = " NO OUT TIME ";
char DST_STR_NO_DST_DATA[14] = " NO DST DATA ";
char DST_STR_G2_COLON[6] = " g2:";
char DST_STR_G3_COLON[6] = " g3:";
char Global_STR_DST_C_1[6] = "DST.c";
char Global_STR_DST_C_2[6] = "DST.c";
char Global_STR_DST_C_3[6] = "DST.c";
char Global_STR_DST_C_4[6] = "DST.c";
char Global_STR_DST_C_5[6] = "DST.c";
char Global_STR_DST_C_6[6] = "DST.c";
char Global_STR_G2[4] = "g2";
char Global_STR_G3[4] = "g3";
char Global_STR_DST_C_7[6] = "DST.c";
unsigned char DST_FMT_PCT_S_COLON_PCT_S_PCT_S_PCT_02D_PCT_[50] = "%s:  %s%s%02d, '%d (%03d) %2d:%02d:%02d %s %s %s\n";
char DST_TAG_PM[4] = "PM";
char DST_TAG_AM[4] = "AM";
char DST_TAG_DST[4] = "DST";
char DST_TAG_STD[4] = "STD";
char DST_STR_LEAP_YEAR[10] = "Leap Year";
unsigned char DST_STR_NORM_YEAR[12] = "Norm Year";
