/* RESTORES: (data module -- no function)
 * MODULE:   data/brush.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 180 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char BRUSH_STR_IFF_FORM[6] = "FORM";

char BRUSH_STR_ALIAS_CODE_00[4] = "00";
char BRUSH_STR_ALIAS_CODE_11[4] = "11";
char BRUSH_STR_ALIAS_CODE_DT[4] = "DT";
unsigned char BRUSH_STR_FALLBACK_DITHER[10] = "DITHER";
