/* RESTORES: (data module -- no function)
 * MODULE:   data/diskio_p2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 2272 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_DISKIO_C_2[10] = "DISKIO.c";
char Global_STR_PERCENT_LD[4] = "%ld";
char Global_STR_DISKIO_C_3[10] = "DISKIO.c";
char Global_STR_DISKIO_C_4[10] = "DISKIO.c";
char Global_STR_DISKIO_C_5[10] = "DISKIO.c";
char Global_STR_DISKIO_C_6[10] = "DISKIO.c";
char Global_STR_DISKIO_C_7[10] = "DISKIO.c";
char Global_STR_DISKIO_C_8[10] = "DISKIO.c";
long DISKIO_Drive0Dh2AssignDoneFlag = 1;
long DISKIO_Drive1GfxAssignDoneFlag = 1;
char DISKIO_STR_TRACKDISK_DEVICE[18] = "trackdisk.device";
char DISKIO_CMD_ASSIGN_FONTS_DH2[34] = "ram:assign >nil: FONTS: DH2:FONTS";
char DISKIO_CMD_ASSIGN_ENV_DH2[28] = "ram:assign >nil: ENV: DH2:";
char DISKIO_CMD_ASSIGN_SYS_DH2[28] = "ram:assign >nil: SYS: DH2:";
char DISKIO_CMD_ASSIGN_S_DH2[26] = "ram:assign >nil: S: DH2:S";
char DISKIO_CMD_ASSIGN_C_DH2[26] = "ram:assign >nil: C: DH2:C";
char DISKIO_CMD_ASSIGN_L_DH2[26] = "ram:assign >nil: L: DH2:L";
char DISKIO_CMD_ASSIGN_LIBS_DH2[32] = "ram:assign >nil: LIBS: DH2:LIBS";
char DISKIO_CMD_ASSIGN_DEVS_DH2[32] = "ram:assign >nil: DEVS: DH2:DEVS";
char DISKIO_PATH_DF1_G_ADS[10] = "df1:g.ads";
char DISKIO_CMD_ASSIGN_GFX_DF1[28] = "ram:assign >nil: gfx: DF1:";
char DISKIO_CMD_ASSIGN_GFX_PC1[28] = "ram:assign >nil: gfx: PC1:";
char DISKIO_TAG_NRLS[6] = "NRLS";
char DISKIO_TAG_LRBN[6] = "LRBN";
char DISKIO_TAG_MSN[4] = "MSN";
unsigned char DISKIO_Pc1MountAssignFlag[2] = {
    0x00, 0x00
};
char DISKIO_CMD_MOUNT_PC1[12] = "Mount PC1:";
char DISKIO_CMD_ASSIGN_GFX_PC1_EXPLICIT[18] = "Assign GFX: PC1:";
char Global_STR_DF0_CONFIG_DAT_1[16] = "df0:config.dat";
unsigned char Global_STR_DEFAULT_CONFIG_FORMATTED[204] = "%01ld%01lc%01ld%01ld%02ld%02ld%01lc%01lc%01lc%01lc%01ld%01ld%01lc%01lc%01lc%01lc%01lc%01lc%01lc%02ld%02ld%01lc%01lc%01lc%02ld%02ld%02ld%03ld%01ld%2.2s%01lc%01lc%01lc%01c%01c%01d%01c%01c%01c%01c%01c%01c\n";
char Global_STR_DF0_CONFIG_DAT_2[16] = "df0:config.dat";
char Global_STR_DISKIO_C_9[10] = "DISKIO.c";
unsigned char DISKIO_FMT_CHANNEL_LINE_UP_PCT_LD[24] = "Channel Line Up # %ld\n";
unsigned char DISKIO_FMT_ETID_PCT_LD_PCT_02LX[22] = "ETID = %ld ($%02lx)\n";
unsigned char DISKIO_FMT_CHAN_NUM_PCT_S[18] = "chan_num = '%s'\n";
unsigned char DISKIO_FMT_SOURCE_PCT_S[16] = "source = '%s'\n";
unsigned char DISKIO_FMT_CALL_LET_PCT_S[18] = "call_let = '%s'\n";
char DISKIO_FMT_ATTR_PCT_02LX[16] = "attr = $%02lx (";
char DISKIO_STR_NONE_CompactSourceAttrFlags[6] = " NONE";
char DISKIO_STR_HILITE_SRC_CompactSourceAttrFlags[12] = " HILITE_SRC";
char DISKIO_STR_SUM_SRC_CompactSourceAttrFlags[10] = " SUM_SRC";
char DISKIO_STR_VIDEO_TAG_DISABLE_CompactSourceAttrFlags[20] = " VIDEO_TAG_DISABLE";
char DISKIO_STR_PPV_SRC_CompactSourceAttrFlags[10] = " PPV_SRC";
char DISKIO_STR_DITTO_CompactSourceAttrFlags[8] = " DITTO";
char DISKIO_STR_ALTHILITESRC_CompactSourceAttrFlags[14] = " ALTHILITESRC";
char DISKIO_STR_0X80[6] = " 0x80";
unsigned char DISKIO_STR_AttrFlagsCloseParenNewline_A[4] = " )\n";
char DISKIO_FMT_TSLT_MASK_PCT_02LX_PCT_02LX_PCT_02LX[58] = "tslt_mask = ($%02lx $%02lx $%02lx $%02lx $%02lx $%02lx) ";
unsigned char DISKIO_STR_NONE_TimeSlotMaskAllSet[8] = "(NONE)\n";
unsigned char Global_STR_OFF_AIR_2[12] = "(OFF AIR)\n";
char DISKIO_STR_TimeSlotListOpenParen[2] = "(";
char DISKIO_FMT_PCT_S_TimeSlotMaskEntry[4] = "%s ";
unsigned char DISKIO_STR_TimeSlotListCloseParenNewline[4] = ")\n";
char DISKIO_FMT_BLKOUT_MASK_PCT_02LX_PCT_02LX_PCT_02[60] = "blkout_mask = ($%02lx $%02lx $%02lx $%02lx $%02lx $%02lx) ";
unsigned char DISKIO_STR_NONE_BlackoutMaskEmpty[8] = "(NONE)\n";
unsigned char DISKIO_STR_BLACKED_OUT[16] = "(BLACKED OUT)\n";
char DISKIO_STR_BlackoutListOpenParen[2] = "(";
char DISKIO_FMT_PCT_S_BlackoutMaskEntry[4] = "%s ";
unsigned char DISKIO_STR_BlackoutListCloseParenNewline[4] = ")\n";
unsigned char DISKIO_FMT_FLAG1_0X_PCT_02X_FLAG2_0X_PCT_04X_BG_DefaultCoiDump[82] = "flag1 = 0x%02X, flag2 = 0x%04X, BgColor = 0x%02X, FgColor = 0x%02X, BrushId = %s\n";
unsigned char DISKIO_FMT_COI_DASH_PTR_PCT_08LX[20] = "COI->Ptr = $%08lx\n";
unsigned char DISKIO_STR_DEF_COI_INFORMATION_FOLLOWS_COLON[32] = "\tdef_COI information follows:\n";
unsigned char DISKIO_STR_DEF_DEFAULT[22] = "\tdef_default = \"%s\"\n";
unsigned char DISKIO_FMT_DEF_CITY_PCT_08LX_STAR_DEF_CITY[40] = "\tdef_city = $%08lx ; *def_city = \"%s\"\n";
unsigned char DISKIO_FMT_DEF_ORDER_PCT_08LX_STAR_DEF_ORDER[42] = "\tdef_order = $%08lx ; *def_order = \"%s\"\n";
unsigned char DISKIO_FMT_DEF_PRICE_PCT_08LX_STAR_DEF_PRICE[42] = "\tdef_price = $%08lx ; *def_price = \"%s\"\n";
unsigned char DISKIO_FMT_DEF_TELE_PCT_08LX_STAR_DEF_TELE[40] = "\tdef_tele = $%08lx ; *def_tele = \"%s\"\n";
unsigned char DISKIO_FMT_DEF_EVENT_PCT_08LX_STAR_DEF_EVENT[42] = "\tdef_event = $%08lx ; *def_event = \"%s\"\n";
unsigned char DISKIO_FMT_EXCEPTION_COUNT_IS_PCT_LD[26] = "\tException_count is %ld\n";
unsigned char DISKIO_FMT_EXCEPTION_BLOCK_PCT_08LX[28] = "\tException_Block = $%08lx\n";
unsigned char DISKIO_FMT_CHANNEL_LINE_UP_PCT_D[24] = "\nChannel Line Up # %d, ";
unsigned char DISKIO_FMT_ETID_PCT_D_CHAN_NUM_PCT_S_SOURCE_PCT[52] = "ETID=%d, chan_num='%s', source='%s', call_let='%s'\n";
char DISKIO_STR_ATTR[10] = "  attr=(";
char DISKIO_STR_NONE_VerboseSourceAttrFlags[6] = " NONE";
char DISKIO_STR_HILITE_SRC_VerboseSourceAttrFlags[12] = " HILITE_SRC";
char DISKIO_STR_SUM_SRC_VerboseSourceAttrFlags[10] = " SUM_SRC";
char DISKIO_STR_VIDEO_TAG_DISABLE_VerboseSourceAttrFlags[20] = " VIDEO_TAG_DISABLE";
char DISKIO_STR_PPV_SRC_VerboseSourceAttrFlags[10] = " PPV_SRC";
char DISKIO_STR_DITTO_VerboseSourceAttrFlags[8] = " DITTO";
char DISKIO_STR_ALTHILITESRC_VerboseSourceAttrFlags[14] = " ALTHILITESRC";
char DISKIO_STR_STEREO[8] = " STEREO";
unsigned char DISKIO_STR_ProgramAttrCloseParenNewline[4] = " )\n";
char DISKIO_FMT_TSLT_MASK_PCT_02X_PCT_02X_PCT_02X_PC[52] = "  tslt_mask=($%02x $%02x $%02x $%02x $%02x $%02x) ";
unsigned char DISKIO_FMT_BLKOUT_MASK_PCT_02X_PCT_02X_PCT_02X_[52] = "blkout_mask=($%02x $%02x $%02x $%02x $%02x $%02x)\n";
unsigned char DISKIO_FMT_FLAG1_0X_PCT_02X_FLAG2_0X_PCT_04X_BG_VerboseSourceRecord[84] = "  flag1 = 0x%02X, flag2 = 0x%04X, BgColor = 0x%02X, FgColor = 0x%02X, BrushId = %s\n";
unsigned char DISKIO_FMT_PROGRAM_INFO_PCT_LD[20] = "Program Info # %ld\n";
unsigned char DISKIO_FMT_PROG_SRCE_PCT_S_VerboseProgramInfo[18] = "prog_srce = '%s'\n";
unsigned char DISKIO_STR_NewlineOnly_A[2] = {
    0x0a, 0x00
};
char DISKIO_FMT_PCT_02LD_PCT_S_COLON_ATTR_PCT_02LX[34] = "    (%02ld) [%s]: attr = $%02lx (";
char DISKIO_STR_NONE_VerboseProgramAttrFlags[6] = " NONE";
char DISKIO_STR_MOVIE_VerboseProgramAttrFlags[8] = " MOVIE";
char DISKIO_STR_ALTHILITE_PROG_VerboseProgramAttrFlags[16] = " ALTHILITE_PROG";
char DISKIO_STR_TAG_PROG_VerboseProgramAttrFlags[10] = " TAG_PROG";
char DISKIO_STR_0X10[6] = " 0x10";
char DISKIO_STR_0X20_VerboseProgramAttrFlags[6] = " 0x20";
char DISKIO_STR_0X40[6] = " 0x40";
char DISKIO_STR_PREV_DAYS_DATA_VerboseProgramAttrFlags[16] = " PREV_DAYS_DATA";
unsigned char DISKIO_STR_ProgramAttrCloseAndProgPrefix[24] = " )\n         prog_str = ";
unsigned char DISKIO_FMT_PCT_S_VerboseProgramStringLine[6] = "'%s'\n";
unsigned char DISKIO_STR_NullLine[6] = "NULL\n";
unsigned char DISKIO_STR_NewlineOnly_B[2] = {
    0x0a, 0x00
};
unsigned char DISKIO_FMT_PROGRAM_INFO_PCT_D[20] = "Program Info # %d\n";
unsigned char DISKIO_STR_NewlineOnly_C[2] = {
    0x0a, 0x00
};
unsigned char DISKIO_FMT_PROG_SRCE_PCT_S_ProgramInfoAttrTable[18] = "prog_srce = '%s'\n";
char DISKIO_FMT_PCT_02D_PCT_S_COLON_ATTR[24] = "  %02d) [%s]: attr = (";
char DISKIO_STR_NONE_ProgramInfoAttrTable[6] = " NONE";
char DISKIO_STR_MOVIE_ProgramInfoAttrTable[8] = " MOVIE";
char DISKIO_STR_ALTHILITE_PROG_ProgramInfoAttrTable[16] = " ALTHILITE_PROG";
char DISKIO_STR_TAG_PROG_ProgramInfoAttrTable[10] = " TAG_PROG";
char DISKIO_STR_SPORTSPROG[12] = " SPORTSPROG";
char DISKIO_STR_0X20_ProgramInfoAttrTable[6] = " 0x20";
char DISKIO_STR_REPEATPROG[12] = " REPEATPROG";
char DISKIO_STR_PREV_DAYS_DATA_ProgramInfoAttrTable[16] = " PREV_DAYS_DATA";
unsigned char DISKIO_STR_ProgramAttrCloseAndProgQuotedPrefix[18] = " )\n    prog_str='";
char DISKIO_TAG_NONE[6] = "NONE";
unsigned char DISKIO_FMT_ProgramStringSuffixWithTypeFields[52] = "'\n    p_type=%03d, movie_cat=%03d, color=0x%02x\n";
