/* RESTORES: (data module -- no function)
 * MODULE:   data/esqpars2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 568 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

/* Forward declarations. The type has to match the definition exactly
 * or 6.51 rejects the pair. */
extern char Global_STR_RATING_R[];
extern char Global_STR_RATING_ADULT[];
extern char Global_STR_RATING_PG[];
extern char Global_STR_RATING_NR[];
extern char Global_STR_RATING_PG_13[];
extern char Global_STR_RATING_G[];
extern char Global_STR_RATING_NC_17[];
extern char Global_STR_TV_Y[];
extern char Global_STR_TV_Y7[];
extern char Global_STR_TV_PG[];
extern char Global_STR_TV_G[];
extern char Global_STR_TV_M[];
extern char Global_STR_TV_MA[];
extern char Global_STR_TV_14[];

char Global_ESQPARS2_C_1[12] = "ESQPARS2.c";
char Global_ESQPARS2_C_2[12] = "ESQPARS2.c";
char Global_ESQPARS2_C_3[12] = "ESQPARS2.c";
char Global_ESQPARS2_C_4[12] = "ESQPARS2.c";
char Global_STR_CLOSED_CAPTIONED[6] = "(CC)";
char Global_STR_IN_STEREO[10] = "In Stereo";
char Global_STR_RATING_R[4] = "(R)";
char Global_STR_RATING_ADULT[8] = "(Adult)";
char Global_STR_RATING_PG[6] = "(PG)";
char Global_STR_RATING_NR[6] = "(NR)";
char Global_STR_RATING_PG_13[8] = "(PG-13)";
char Global_STR_RATING_G[4] = "(G)";
char Global_STR_RATING_NC_17[8] = "(NC-17)";
long Global_TBL_MOVIE_RATINGS[7] = {
    (long)Global_STR_RATING_R, (long)Global_STR_RATING_ADULT, (long)Global_STR_RATING_PG, (long)Global_STR_RATING_NR,
    (long)Global_STR_RATING_PG_13, (long)Global_STR_RATING_G, (long)Global_STR_RATING_NC_17
};
unsigned char ESQPARS2_MovieRatingTokenGlyphMap[8] = {
    0x84, 0x86, 0x85, 0x8c, 0x87, 0x8d, 0x8f, 0x00
};
char Global_STR_TV_Y[8] = "(TV-Y)";
char Global_STR_TV_Y7[8] = "(TV-Y7)";
char Global_STR_TV_PG[8] = "(TV-PG)";
char Global_STR_TV_G[8] = "(TV-G)";
char Global_STR_TV_M[8] = "(TV-M)";
char Global_STR_TV_MA[8] = "(TV-MA)";
char Global_STR_TV_14[8] = "(TV-14)";
long Global_TBL_TV_PROGRAM_RATINGS[7] = {
    (long)Global_STR_TV_Y, (long)Global_STR_TV_Y7, (long)Global_STR_TV_PG, (long)Global_STR_TV_G,
    (long)Global_STR_TV_M, (long)Global_STR_TV_MA, (long)Global_STR_TV_14
};
unsigned char ESQPARS2_TvRatingTokenGlyphMap[8] = {
    0x90, 0x93, 0x9b, 0x99, 0xa3, 0xa3, 0x9a, 0x00
};
char Global_STR_ESQPARS2_C_1[12] = "ESQPARS2.c";
char ESQPARS2_DurationFmt_DecimalWithSpace[4] = "%d ";
char ESQPARS2_DurationFmt_OpenParenHours[6] = "(%d ";
char ESQPARS2_DurationFmt_OpenParenMinutes[6] = "(%d ";
char ESQPARS2_DurationFmt_CloseParen[2] = ")";
unsigned char Global_STR_ESQPARS2_C_2[14] = "ESQPARS2.c";
long Global_LONG_PATCH_VERSION_NUMBER = 4;
unsigned char ESQPARS2_BannerSnapshotPlane0DstPtr[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSnapshotPlane0DstPtrLo[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSnapshotPlane1DstPtr[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSnapshotPlane1DstPtrLo[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSnapshotPlane2DstPtr[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSnapshotPlane2DstPtrLo[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_SnapshotLivePlane0Base[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_SnapshotLivePlane1Base[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_SnapshotLivePlane2Base[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerRowOffsetResetPtrPlane0[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerRowOffsetResetPtrPlane1[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerRowOffsetResetPtrPlane2Table[36] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_CopperProgramPendingFlag[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_EdDiagResetScratchFlag[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSweepEntryGuardCounter[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSweepDelayCounter[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_HighlightTickCountdown[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_StateIndex[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerQueueAttentionCountdown[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerTailBiasValue[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSweepBaseColor[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerSweepOffsetColor[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_ReadModeFlags[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerColorStepCounter[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerColorClampThreshold[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerQueueBuffer[100] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerColorThreshold[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerColorBaseValue[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerRowCopyWordCount[2] = {
    0x00, 0x00
};
unsigned char ESQPARS2_BannerRowCopySpanBytes[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerRowCopyStrideBytes[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerCopySourceOffset[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_BannerCopyTailOffset[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQSHARED_BlitAddressOffset[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_ActiveCopperListSelectFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
long ESQPARS2_BannerRowCount = 34;
short ESQPARS2_BannerRowWidthBytes = 256;
short ESQPARS2_BannerCopyBlockSpanBytes = 192;
short ESQPARS2_BannerCopyBlockWordLimit = 16;
unsigned char ESQPARS2_BannerQueueAttentionDelayTicks[8] = {
    0x00, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
unsigned char ESQPARS2_LogAppendSpinlock[4] = {
    0x00, 0x00, 0x00, 0x00
};
char ESQPARS2_LogTimestampFmt[24] = "%02ld:%02ld:%02ld %2.2s";
char ESQPARS2_LogTagPm[4] = "PM";
char ESQPARS2_LogTagAm[4] = "AM";
