/* RESTORES: (data module -- no function)
 * MODULE:   data/kybd.s
 * STATUS:   behavioural
 *
 * DO-NOT-LINK: NOT LAYOUT-NEUTRAL. The bytes here are correct and were verified
 *   against the assembler, but this module does not START on a longword
 *   boundary in the DATA section. gen_units.coalesce() force-closes the
 *   assembly group in front of a replaced module, so replacing this one pads
 *   that group and moves every symbol after it. Linked with three others like
 *   it the DATA hunk grew from 55,820 to 55,832 and the display froze.
 *   `python3 tools/data_to_c.py data/kybd.s --write` now refuses it and prints the
 *   offset. See AGENTS.md.
 *
 *
 * Generated by tools/data_to_c.py, then read. 48 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

unsigned char Global_STR_KYBD_C[10] = {
    0x4b, 0x59, 0x42, 0x44, 0x2e, 0x63, 0x00, 0x00, 0x00, 0x00
};
unsigned char KYBD_PATH_DF0_LOCAL_ADS[13] = {
    0x64, 0x66, 0x30, 0x3a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x61, 0x64,
    0x73
};
unsigned char KYBD_CustomPaletteCaptureScratchBase = 0;
unsigned char KYBD_CustomPaletteTriplesRBase = 0;
unsigned char KYBD_CustomPaletteTriplesGBase = 0;
unsigned char KYBD_CustomPaletteTriplesBBase[22] = {
    0x03, 0x0c, 0x0c, 0x0c, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x00, 0x05, 0x01,
    0x02, 0x01, 0x06, 0x0a, 0x05, 0x05, 0x05, 0x00, 0x00, 0x03
};
