/* RESTORES: (data module -- no function)
 * MODULE:   data/p_type.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 252 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_P_TYPE_C_1[10] = "P_TYPE.c";
char Global_STR_P_TYPE_C_2[10] = "P_TYPE.c";
char Global_STR_P_TYPE_C_3[10] = "P_TYPE.c";
char Global_STR_P_TYPE_C_4[10] = "P_TYPE.c";
char Global_STR_P_TYPE_C_5[10] = "P_TYPE.c";
char P_TYPE_PATH_DF0_COLON_PROMOID_DOT_DAT_Write[16] = "df0:PromoId.Dat";
char P_TYPE_STR_CURDAY_COLON_WriteSection[8] = "CURDAY:";
unsigned char P_TYPE_FMT_PCT_03D_PCT_02D[20] = " %03d %02d\nTYPES: ";
unsigned char P_TYPE_STR_NO_DATA[10] = "No Data\n\n";
char P_TYPE_STR_NXTDAY_COLON_WriteSection[8] = "NXTDAY:";
char P_TYPE_PATH_DF0_COLON_PROMOID_DOT_DAT_Load[16] = "df0:PromoId.Dat";
char P_TYPE_STR_CURDAY_COLON_LoadSection[8] = "CURDAY:";
unsigned char P_TYPE_STR_TYPES_COLON[16] = {
    0x54, 0x59, 0x50, 0x45, 0x53, 0x3a, 0x20, 0x00, 0x54, 0x59, 0x50, 0x45,
    0x53, 0x3a, 0x20, 0x00
};
char P_TYPE_STR_NXTDAY_COLON_LoadSection[8] = "NXTDAY:";
unsigned char Global_STR_P_TYPE_C_6[12] = "P_TYPE.c";
unsigned char P_TYPE_WeatherBrushRefreshPendingFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char P_TYPE_WeatherCurrentMsgPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char P_TYPE_WeatherForecastMsgPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char P_TYPE_WeatherBottomLineMsgPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
char P_TYPE_STR_QTABLE[8] = "Qtable";
char P_TYPE_TAG_BACKDROP[10] = "BACKDROP";
char P_TYPE_TAG_GRADIENT[10] = "GRADIENT";
char P_TYPE_TAG_TEXTADS[8] = "TEXTADS";
char P_TYPE_TAG_BRUSH[6] = "BRUSH";
char P_TYPE_TAG_BANNER[8] = "BANNER";
char P_TYPE_STR_DEFAULT_TEXT[14] = "DEFAULT TEXT";
