/* RESTORES: (data module -- no function)
 * MODULE:   data/p_type_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 80 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char P_TYPE_STR_SOURCE_CONFIG[14] = "SOURCE CONFIG";
unsigned char PARSEINI_DelimSpaceTab_Section1[4] = " \t";
char Global_STR_PARSEINI_C_1[12] = "PARSEINI.c";
unsigned char PARSEINI_DelimSpaceTab_Section2[4] = " \t";
unsigned char PARSEINI_DelimSpaceTab_Section4_5[4] = " \t";
unsigned char PARSEINI_DelimSpaceTab_Section6[4] = " \t";
unsigned char PARSEINI_DelimSpaceTab_Section7[4] = " \t";
unsigned char PARSEINI_DelimSpaceTab_Section8[4] = " \t";
char Global_STR_PARSEINI_C_2[12] = "PARSEINI.c";
long PARSEINI_CurrentRangeTableIndex = 4294967295;
unsigned char PARSEINI_DelimSpaceTab_RangeKey[4] = " \t";
unsigned char PARSEINI_DelimSpaceSemicolonTab_RangeValue[4] = " ;\t";
char PARSEINI_TAG_TABLE[6] = "TABLE";
