/* RESTORES: (data module -- no function)
 * MODULE:   data/flib_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 136 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char FLIB_FMT_PCT_02LD_COLON_PCT_02LD_COLON_PCT_02[24] = "%02ld:%02ld:%02ld:%02ld";
char FLIB_STR_DIGITAL_NICHE_LISTINGS[24] = "Digital Niche Listings";
char FLIB_STR_DIGITAL_MULTIPLEX_LISTINGS[28] = "Digital Multiplex Listings";
char FLIB_FMT_DIGITAL_MULTIPLEX_AT_PCT_S[24] = "Digital Multiplex at %s";
char FLIB_STR_DIGITAL_PPV_LISTINGS[22] = "Digital PPV Listings";
char Global_STR_DIGITAL_PPV_PERIOD[14] = "Digital PPV.";
