/* RESTORES: (data module -- no function)
 * MODULE:   data/ladfunc_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 84 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

short LOCAVAIL_FilterWindowHalfSpan = -1;
char Global_STR_LOCAVAIL_C_1[12] = "LOCAVAIL.c";
char Global_STR_LOCAVAIL_C_2[12] = "LOCAVAIL.c";
char Global_STR_LOCAVAIL_C_3[12] = "LOCAVAIL.c";
char Global_STR_LOCAVAIL_C_4[12] = "LOCAVAIL.c";
char Global_STR_LOCAVAIL_C_5[12] = "LOCAVAIL.c";
char LOCAVAIL_TAG_FV[4] = "FV";
char Global_STR_LOCAVAIL_C_6[12] = "LOCAVAIL.c";
char LOCAVAIL_STR_YYLLZ_FilterGateCheck[6] = "YyLlZ";
