/* RESTORES: (data module -- no function)
 * MODULE:   data/clock.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 184 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_EXTRA_TIME_FORMAT[14] = "%2d:%02d:%02d";
char Global_STR_GRID_TIME_FORMAT[14] = "%2d:%02d:%02d";
char Global_STR_GRID_TIME_FORMAT_DUPLICATE[16] = "%2d:%02d:%02d ";
char Global_STR_12_44_44_SINGLE_SPACE[10] = "12:44:44 ";
char Global_STR_12_44_44_PM[12] = "12:44:44 PM";
unsigned char Global_STR_SHORT_MONTH_SHORT_DAY_OF_WEEK_FORMATTED[14] = "%s%s%ld  ";
char CLOCK_STR_TEMPLATE_CODE_SET_FGN[4] = "FGN";
unsigned char CLOCK_AlignedInsetRenderGateFlag[3] = {
    0x00, 0x04, 0x0c
};
unsigned char CLOCK_FileEofMarkerCtrlZ = 26;
unsigned char COI_FieldDelimiterTab = 9;
unsigned char COI_RecordTerminatorCrLf[3] = {
    0x0d, 0x0a, 0x00
};
char CLOCK_STR_FALLBACK_ENTRY_FLAGS_PRIMARY[12] = "NYYYYYXX00";
char CLOCK_FMT_WRAP_CHAR_STRING_CHAR[8] = "%c%s%c";
char CLOCK_STR_DOUBLE_SPACE[4] = "  ";
char CLOCK_STR_FALLBACK_ENTRY_FLAGS_SECONDARY[12] = "NYYYYYXX00";
char CLOCK_STR_TOKEN_PAIR_DEFAULTS[12] = "NYYYYYXX00";
unsigned char CLEANUP_TokenPairScratch[2] = {
    0x00, 0x00
};
char CLOCK_STR_TOKEN_OUTPUT_TEMPLATE[12] = "NYYYYYXX00";
unsigned char CLOCK_STR_BOOL_CHARS_YyNn[0] = {
};
char CLOCK_STR_BOOL_CHARS_YyNnAlias[6] = "YyNn";
char CLOCK_STR_EMPTY_TOKEN_TEMPLATE[12] = "NNNNNNXX00";
char CLOCK_STR_MISSING_TITLE_TEMPLATE[12] = "NNNNNNXX00";
