/* RESTORES: (data module -- no function)
 * MODULE:   data/kybd_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 32 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

unsigned char KYBD_CustomPaletteTriplesBBase[22] = {
    0x03, 0x0c, 0x0c, 0x0c, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x00, 0x05, 0x01,
    0x02, 0x01, 0x06, 0x0a, 0x05, 0x05, 0x05, 0x00, 0x00, 0x03
};
