/* RESTORES: (data module -- no function)
 * MODULE:   data/ed2_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 2928 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char ED2_STR_LINE[6] = " Line";
unsigned char ED_CustomPaletteCapturePhaseMod4[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ED_CustomPaletteCaptureIndexOrSentinel[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ED_CustomPaletteTriplesDefaultTemplate24B[24] = {
    0x00, 0x00, 0x03, 0x0c, 0x0c, 0x0c, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x00,
    0x05, 0x01, 0x02, 0x01, 0x06, 0x0a, 0x05, 0x05, 0x05, 0x00, 0x00, 0x03
};
char ED2_STR_ALL_DATA_IS_TO_BE_SAVED_DOT[26] = "All data is to be saved.";
char ED2_STR_TV_GUIDE_DATA_IS_TO_BE_SAVED_DOT[30] = "TV Guide data is to be saved.";
char ED2_STR_TEXT_ADS_WILL_BE_LOADED_FROM_DH2_COL[34] = "Text Ads will be loaded from DH2:";
char Global_STR_COMPUTER_WILL_RESET[22] = "Computer will reset!";
char Global_STR_GO_OFF_AIR_FOR_1_2_MINS[26] = "(go off-air for 1-2 mins)";
char Global_STR_SAVING_EVERYTHING_TO_DISK[28] = "Saving \"EVERYTHING\" to disk";
char Global_STR_SAVING_PREVUE_DATA_TO_DISK[28] = "Saving Prevue data to disk";
char Global_STR_LOADING_TEXT_ADS_FROM_DH2[28] = "Loading Text Ads from DH2:";
char Global_STR_REBOOTING_COMPUTER[28] = "Rebooting Computer........";
char ED2_STR_NUMBER_TOO_BIG[24] = " Number too big        ";
char ED2_STR_NUMBER_TOO_SMALL[24] = " Number too small      ";
char ED2_STR_PUSH_ESC_TO_EXIT_ATTRIBUTE_EDIT_DOT[34] = " Push ESC to exit Attribute Edit.";
char ED2_STR_PUSH_RETURN_TO_ENTER_SELECTION[32] = " Push RETURN to enter selection";
char ED2_STR_PUSH_ANY_KEY_TO_SELECT[24] = " Push any key to select";
char ED2_STR_LOCAL_EDIT_NOT_AVAILABLE[26] = "Local Edit not available";
char Global_STR_VER_PERCENT_S_PERCENT_L_D[12] = "Ver %s.%ld";
char Global_STR_NINE_POINT_ZERO[4] = "9.0";
char Global_STR_BAUD_RATE_DIAGNOSTIC_MODE[10] = "%ld baud";
char Global_STR_DISK_0_IS_VAR_FULL_WITH_VAR_ERRORS[40] = "Disk 0 is %2ld%% full with %2ld Errors";
unsigned char ED2_DiagnosticDiskUsagePercent[2] = {
    0x00, 0x00
};
unsigned char ED2_DiagnosticDiskSoftErrorCount[2] = {
    0x00, 0x00
};
char Global_STR_PUSH_ANY_KEY_TO_CONTINUE_2[26] = "Push any key to continue.";
unsigned char ED2_HighlightTickEnabledFlag[2] = {
    0x00, 0x00
};
unsigned char ED2_SelectedEntryDataPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ED2_SelectedEntryTitlePtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
char ED2_FMT_SCRSPD_PCT_D[10] = "SCRSPD=%d";
char ED2_FMT_MR_PCT_D_SBS_PCT_D_SPORT_PCT_D[22] = "MR=%d SBS=%d Sport=%d";
char ED2_FMT_CYCLE_PCT_C_CYCLEFREQ_PCT_D_AFTRORDR[34] = "Cycle=%c CycleFreq=%d AftrOrdr=%d";
char Global_STR_CLOCKCMD_EQUALS_PCT_C[12] = "ClockCmd=%c";

char Global_STR_PI_CLU_POS1[20] = "PI[%d] Clu_pos1=%d";
char Global_STR_CHAN_SOURCE_CALLLTRS_1[30] = "Chan=%s Source=%s CallLtrs=%s";
char ED2_STR_NullFallbackChannel[6] = "NULL";
char ED2_STR_NullFallbackSource[6] = "NULL";
char ED2_STR_NullFallbackCallLetters[6] = "NULL";
char Global_STR_TS_TITLE_TIME[26] = "TS=%d Title='%s' Time=%s";
char ED2_STR_NullFallbackTitle[6] = "NULL";
char ED2_STR_NONE_ProgramFlagSummary[6] = "None ";
char ED2_STR_MOVIE[8] = "Movie ";
char ED2_STR_ALTHILITEPROG[16] = "ALTHILITEPROG ";
char ED2_STR_TAGPROG[10] = "TAGPROG ";
char ED2_STR_SPORTSPROG[12] = "SPORTSPROG ";
char ED2_STR_DVIEW_USED[12] = "DVIEW_USED ";
char ED2_STR_REPEATPROG[12] = "REPEATPROG ";
char ED2_STR_PREVDAYSDATA[14] = "PREVDAYSDATA ";

char Global_STR_CLU_CLU_POS1[20] = "CLU[%d] Clu_pos1=%d";
char Global_STR_CHAN_SOURCE_CALLLTRS_2[30] = "Chan=%s Source=%s CallLtrs=%s";
char ED2_STR_NONE_SourceFlagSummary[6] = "None ";
char ED2_STR_HILITESRC[12] = "HILITESRC ";
char ED2_STR_SUMBYSRC[10] = "SUMBYSRC ";
char ED2_STR_VIDEO_TAG_DISABLE[20] = "VIDEO_TAG_DISABLE ";
char ED2_STR_CAF_PPVSRC[12] = "CAF_PPVSRC ";
char ED2_STR_DITTO[8] = "DITTO ";
char ED2_STR_ALTHILITESRC[14] = "ALTHILITESRC ";
char ED2_STR_STEREO[8] = "STEREO ";
char ED2_STR_GRID[6] = "Grid ";
char ED2_STR_MR[4] = "MR ";
char ED2_STR_DNICHE[8] = "DNICHE ";
char ED2_STR_DMPLEX[8] = "DMPLEX ";
unsigned char ED2_STR_CF2_DPPV[12] = "CF2_DPPV ";
char ED2_STR_CTIME[6] = "CTime";
char ED2_STR_BTIME[6] = "BTime";
char Global_STR_DF0_CLOCK_CMD[14] = "df0:clock.cmd";
unsigned char ED2_STR_ED_DOT_C_COLON_SHORT_DUMP_OF_CLU[26] = "\nED.C: Short DUMP OF CLU\n";
unsigned char ED2_FMT_CLU_POS1_PCT_LD_CURCLU_PCT_S_JDCLU1_[52] = "    clu_pos1=%ld, curclu=%s, jdclu1=%ld, curjd=%ld\n";
char Global_STR_TRUE_1[6] = "TRUE";
char Global_STR_FALSE_1[6] = "FALSE";
unsigned char ED2_STR_ED_DOT_C_COLON_END_OF_DUMP_OF_CLU[28] = "ED.C: END OF DUMP OF CLU\n\n";
unsigned char ED2_FMT_WICON_PCT_LD[14] = "wicon = %ld\n";
unsigned char ED2_FMT_W_MIN_PCT_LD_MINUTES[22] = "w_min = %ld minutes\n";
unsigned char ED2_FMT_WDCNT_EVERY_PCT_LD_TIMES_PCT_LD[36] = "wdcnt = every %ld times     (%ld)\n";
unsigned char ED2_FMT_CWCNT_PCT_LD_TIMES_FROM_NOW_PCT_LD[36] = "cwcnt = %ld times from now  (%ld)\n";
unsigned char ED2_FMT_WDATA_PCT_08LX[16] = "WData = $%08lx\n";
unsigned char ED2_FMT_WCITY_PCT_S[14] = "WCity = '%s'\n";
unsigned char ED2_FMT_WEATHER_ID_PCT_S[20] = "Weather_ID = '%s'\n";
unsigned char ED2_FMT_CWCOLOR_PCT_LD[16] = "cwcolor = %ld\n";
unsigned char ED2_FMT_BANNER_FOR_WEATHER_PCT_D[26] = "\nbanner_for_weather = %d\n";
char ED2_FMT_BITPLANE1_PCT_8LX[18] = "BitPlane1 =%8lx  ";
char Global_STR_DF0_GRADIENT_INI_1[18] = "df0:Gradient.ini";
char ED2_TAG_NRLS[6] = "NRLS";
char ED2_STR_NYYLLZ[8] = "NYyLlZ";
char ED2_TAG_NYLRS[6] = "NYLRS";
char ED2_STR_SILENCE[12] = "  Silence ";
char ED2_STR_LEFT[12] = "Left      ";
char ED2_STR_RIGHT[12] = "     Right";
char ED2_STR_BACKGROUND[12] = "Background";
char ED2_STR_EXT_DOT_VIDEO_ONLY[20] = "  Ext. Video Only ";
char ED2_STR_COMPUTER_ONLY[20] = "  Computer Only   ";
char ED2_STR_OVERLAY_EXT_DOT_VIDEO[20] = "Overlay Ext. Video";
char ED2_STR_NEGATIVE_VIDEO[16] = "Negative Video";
char ED2_STR_VIDEO_SWITCH[14] = "Video Switch ";
char ED2_STR_OPEN[8] = "Open  ";
char ED2_STR_CLOSED[8] = "Closed";
char ED2_STR_START_TAPE_VIDEO[20] = "Start TAPE Video   ";
unsigned char ED2_STR_STOP[10] = "Stop  ";
long Global_REF_BOOL_IS_TEXT_OR_CURSOR = 1;
char Global_STR_EDIT_ADS[10] = "Edit Ads";
char Global_STR_EDIT_ATTRIBUTES[16] = "Edit Attributes";
char Global_STR_CHANGE_SCROLL_SPEED[20] = "Change Scroll Speed";
char Global_STR_DIAGNOSTIC_MODE[16] = "Diagnostic Mode";
char Global_STR_SPECIAL_FUNCTIONS[18] = "Special Functions";
char Global_STR_VERSIONS_SCREEN[16] = "Versions Screen";
char Global_STR_PUSH_ESC_TO_RESUME[20] = " Push ESC to resume";
char Global_STR_PUSH_RETURN_TO_ENTER_SELECTION_1[32] = " Push RETURN to enter selection";
char Global_STR_PUSH_ANY_KEY_TO_SELECT_1[24] = " Push any key to select";
char Global_STR_VIN_BCK_FWD_SSPD_AD_LINE[38] = "VIN:  BCK:  FWD:  SSPD:  #AD:   LINE:";
char Global_STR_TZ_DST_CONT_TXT_GRPH[32] = "TZ :  DST:  CONT:  TEXT:  GRPH:";
char Global_STR_PUSH_RETURN_TO_ENTER_SELECTION_3[32] = " Push RETURN to enter selection";
char Global_STR_PUSH_ANY_KEY_TO_SELECT_2[24] = " Push any key to select";
char ESQ_STR_SATELLITE_DELIVERED_SCROLL_SPEED_PCT_C[38] = "Satellite Delivered scroll speed (%c)";
char Global_STR_SPEED_ZERO_NOT_AVAILABLE[22] = "Speed 0 not available";
char Global_STR_SPEED_ONE_NOT_AVAILABLE[22] = "Speed 1 not available";
char Global_STR_SCROLL_SPEED_2[28] = "Scroll speed = 2 (fastest)";
char Global_STR_SCROLL_SPEED_3[28] = "Scroll speed = 3 (default)";
char Global_STR_SCROLL_SPEED_4[18] = "Scroll speed = 4";
char Global_STR_SCROLL_SPEED_5[18] = "Scroll speed = 5";
char Global_STR_SCROLL_SPEED_6[18] = "Scroll speed = 6";
char Global_STR_SCROLL_SPEED_7[28] = "Scroll speed = 7 (slowest)";
char Global_STR_SAVE_ALL_TO_DISK[18] = "Save ALL to disk";
char Global_STR_SAVE_DATA_TO_DISK[18] = "Save data to disk";
char Global_STR_LOAD_TEXT_ADS_FROM_DISK[24] = "Load text ads from disk";
char Global_STR_REBOOT_COMPUTER[16] = "Reboot computer";
char Global_STR_REGISTER[10] = "register ";
char Global_STR_R_EQUALS[4] = "R= ";
char Global_STR_G_EQUALS[4] = "G= ";
char Global_STR_B_EQUALS[4] = "B= ";
char Global_STR_ARE_YOU_SURE[22] = " Are you sure? (Y/N)";
char Global_STR_ENTER_AD_NUMBER_ONE_HYPHEN[22] = " Enter ad number (1-";
char Global_STR_LEFT_PARENTHESIS_THEN[8] = ") then";
char Global_STR_PUSH_RETURN_TO_ENTER_SELECTION_2[32] = " push RETURN to enter selection";
char Global_STR_SINGLE_SPACE_4[2] = " ";
char Global_STR_AD_NUMBER_QUESTIONMARK[12] = "Ad Number? ";
char Global_STR_CURRENT_COLOR_FORMATTED[22] = " Current Color %02X ";
char Global_STR_TEXT[8] = "   Text";
char Global_STR_CURSOR[8] = " Cursor";
char Global_STR_LINE[6] = " Line";
char Global_STR_PAGE[6] = " Page";
char Global_STR_AD_NUMBER_FORMATTED[16] = "Ad Number %2ld";
char Global_STR_ACTIVE_INACTIVE[16] = "Active Inactive";
char Global_STR_PUSH_ESC_TO_MAKE_ANOTHER_SELECTION[38] = " Push ESC to make another selection.";
char Global_STR_PUSH_HELP_FOR_OTHER_EDIT_FUNCTIONS[38] = " Push HELP for other edit functions.";
char Global_STR_LINE_MODE_ON_TEXT_COLOR_MODE[38] = " Line mode on       Text color mode ";
char Global_STR_EDITING_AD_NUMBER_FORMATTED_1[24] = "Editing Ad Number %2ld";
char Global_STR_EDITING_AD_NUMBER_FORMATTED_2[24] = "Editing Ad Number %2ld";
char ED2_STR_PUSH_ANY_KEY_TO_CONTINUE_DOT[26] = "Push any key to continue.";
char ED2_STR_STAR_STAR_LINE_SLASH_PAGE_COMMANDS_S[30] = "     ** Line/Page Commands **";
char ED2_STR_F1_COLON_HOME_F6_COLON_CLEAR[34] = "F1: Home               F6: Clear";
char ED2_STR_F2_COLON_LINE_SLASH_PAGE_MODE_F7_COL[40] = "F2: Line/Page mode     F7: Insert Line";
char ED2_CMD_F3_COLON_CENTER_F8_COLON_DELETE_LINE[40] = "F3: Center             F8: Delete Line";
char ED2_STR_F4_COLON_LEFT_JUSTIFY_F9_COLON_APPLY[40] = "F4: Left Justify       F9: Apply Color";
char ED2_STR_F5_COLON_RIGHT_JUSTIFY_F10_COLON_INS[40] = "F5: Right Justify     F10: Insert char";
char Global_STR_SHIFT_RIGHT_NEXT_AD_DEL_DELETE_CHAR[40] = "Shift ->: next Ad     DEL: Delete char";
char Global_STR_SHIFT_LEFT_PREV_AD_CTRLC_COLOR_MODE[38] = "Shift <-: prev Ad   CTRLC: Color Mode";
char Global_STR_CTRLF_FOREGROUND_CTRLB_BACKGROUND[38] = "CTRLF: Foreground   CTRLB: Background";
