/* RESTORES: (data module -- no function)
 * MODULE:   data/ladfunc_p2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 360 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_LADFUNC_C_2[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_3[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_4[10] = "LADFUNC.c";
char LADFUNC_TAG_RS_ResetTriggerSet[4] = "RS";
char LADFUNC_TAG_RS_ParseAllowedSet[4] = "RS";
char Global_STR_LADFUNC_C_5[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_6[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_7[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_8[10] = "LADFUNC.c";
char LADFUNC_FMT_AttrEscapePrefixCharHex[8] = "%c%02X";
unsigned char LADFUNC_TextAdLineBreakBuffer[2] = {
    0x00, 0x00
};
char Global_STR_LADFUNC_C_9[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_10[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_11[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_12[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_13[10] = "LADFUNC.c";
char Global_STR_SINGLE_SPACE_1[2] = " ";
char Global_STR_LADFUNC_C_14[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_15[10] = "LADFUNC.c";
char Global_STR_SINGLE_SPACE_2[2] = " ";
char Global_STR_LADFUNC_C_16[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_17[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_18[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_19[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_20[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_21[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_22[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_23[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_24[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_25[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_26[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_27[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_28[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_29[10] = "LADFUNC.c";
char Global_STR_LADFUNC_C_30[10] = "LADFUNC.c";
unsigned char LADFUNC_STR_QuoteAndNewline[4] = "\"\n";
char LADFUNC_STR_Quote[2] = "\"";
char LADFUNC_FMT_ControlCharCaretEscape[6] = "^%lc";
char LADFUNC_FMT_ReplacementQuoteChar[4] = "%lc";
char LADFUNC_FMT_ReplacementCommaChar[4] = "%lc";
char LADFUNC_FMT_HexEscapeByte[8] = "$%02lx";
char LADFUNC_FMT_LiteralChar[4] = "%lc";
unsigned char LOCAVAIL_FilterModeFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char LOCAVAIL_FilterStep[4] = {
    0x00, 0x00, 0x00, 0x00
};
long LOCAVAIL_FilterClassId = 4294967295;
long LOCAVAIL_FilterPrevClassId = 4294967295;
