/* RESTORES: (data module -- no function)
 * MODULE:   data/diskio_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 12 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

unsigned char DISKIO_CurrentDriveRevisionIndex[2] = {
    0x00, 0x00
};
char Global_STR_DISKIO2_C_1[10] = "DISKIO2.c";
