/* RESTORES: (data module -- no function)
 * MODULE:   data/disptext.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 136 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_DISPTEXT_C_1[12] = "DISPTEXT.c";
char DISPTEXT_STR_SINGLE_SPACE_MEASURE[2] = " ";
char DISPTEXT_STR_SINGLE_SPACE_APPEND[2] = " ";
char DISPTEXT_STR_SINGLE_SPACE_DELIM[2] = " ";
long DISPTEXT_InitBuffersPending = 1;
char Global_STR_DISPTEXT_C_2[12] = "DISPTEXT.c";
char Global_STR_DISPTEXT_C_3[12] = "DISPTEXT.c";
char Global_STR_DISPTEXT_C_4[12] = "DISPTEXT.c";
char Global_STR_DISPTEXT_C_5[12] = "DISPTEXT.c";
char DISPTEXT_STR_SINGLE_SPACE_PREFIX_1[2] = " ";
char DISPTEXT_STR_SINGLE_SPACE_PREFIX_2[2] = " ";
char DISPTEXT_STR_SINGLE_SPACE_COPY_PREFIX[2] = " ";
unsigned char DATETIME_MONTH_LENGTH_AND_DAY_OFFSET_TABLES[60] = {
    0x1f, 0x1c, 0x1f, 0x1e, 0x1f, 0x1e, 0x1f, 0x1f, 0x1e, 0x1f, 0x1e, 0x1f,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00, 0x3b,
    0x00, 0x00, 0x00, 0x5a, 0x00, 0x00, 0x00, 0x78, 0x00, 0x00, 0x00, 0x97,
    0x00, 0x00, 0x00, 0xb5, 0x00, 0x00, 0x00, 0xd4, 0x00, 0x00, 0x00, 0xf3,
    0x00, 0x00, 0x01, 0x11, 0x00, 0x00, 0x01, 0x30, 0x00, 0x00, 0x01, 0x4e
};
