/* RESTORES: (data module -- no function)
 * MODULE:   data/common.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 452 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_PLEASE_STANDBY_1[18] = "Please Standby...";
char Global_STR_ATTENTION_SYSTEM_ENGINEER_1[28] = "ATTENTION! SYSTEM ENGINEER";
char Global_STR_REPORT_CODE_ER003[50] = "Report Code ER003 to TV Guide Technical Services.";
unsigned char Global_STR_YOU_CANNOT_RE_RUN_THE_SOFTWARE[66] = "YOU CANNOT RE-RUN THE SOFTWARE IN THIS MANNER.  PLEASE RE-BOOT!!\n";
short COMMON_QueryDiskSoftErrorCountScratch = 0;
unsigned char Global_STR_DISK_ERRORS_FORMATTED[18] = "Disk Errors: %ld\n";
short COMMON_QueryDiskUsagePercentScratch = 0;
char Global_STR_DISK_IS_FULL_FORMATTED[20] = "Disk is %ld%% full";
short CTRL_Bit4CaptureDelayCounter = 0;
short CTRL_Bit3CaptureDelayCounter = 0;
short CTRL_Bit4CapturePhase = 0;
short CTRL_Bit4SampleSlotIndex = 0;
short CTRL_Bit3CapturePhase = 0;
short CTRL_Bit3SampleSlotIndex = 0;
unsigned char CTRL_Bit4SampleScratch[8] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
unsigned char CTRL_Bit3SampleScratch[8] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
short HIGHLIGHT_CopperEffectSeed = 0;
unsigned char HIGHLIGHT_CopperEffectParamA = 0;
unsigned char HIGHLIGHT_CopperEffectParamB[3] = {
    0x00, 0x00, 0x00
};
short CTRL_SampleEntryCount = 0;
unsigned char CTRL_SampleEntryScratch[6] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
char HIGHLIGHT_CustomValue[2] = "?";
long CLOCK_DaySlotIndexPtr = 0;
long CLOCK_CurrentDayOfWeekIndexPtr = 0;
long BANNER_ResetPendingFlag = 0;
short CLOCK_MinuteTrigger30MinusBase = 0;
short CLOCK_MinuteTrigger60MinusBase = 0;
short CLOCK_MinuteTriggerBaseOffsetPlus30 = 0;
short CLOCK_MinuteTriggerBaseOffset = 0;
short ACCUMULATOR_Row0_CaptureValue = 0;
short ACCUMULATOR_Row1_CaptureValue = 0;
short ACCUMULATOR_Row2_CaptureValue = 0;
short ACCUMULATOR_Row3_CaptureValue = 0;
short ACCUMULATOR_Row0_Sum = 0;
short ACCUMULATOR_Row1_Sum = 0;
short ACCUMULATOR_Row2_Sum = 0;
short ACCUMULATOR_Row3_Sum = 0;
short ACCUMULATOR_Row0_SaturateFlag = 0;
short ACCUMULATOR_Row1_SaturateFlag = 0;
short ACCUMULATOR_Row2_SaturateFlag = 0;
unsigned char ACCUMULATOR_Row3_SaturateFlag[10] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
short COPPER_AnimationLane0_Countdown = 0;
short COPPER_AnimationLane1_Countdown = 0;
short COPPER_AnimationLane2_Countdown = 0;
short COPPER_AnimationLane3_Countdown = 0;
unsigned char CLOCK_MonthLengths[48] = {
    0x00, 0x1f, 0x00, 0x1c, 0x00, 0x1f, 0x00, 0x1e, 0x00, 0x1f, 0x00, 0x1e,
    0x00, 0x1f, 0x00, 0x1f, 0x00, 0x1e, 0x00, 0x1f, 0x00, 0x1e, 0x00, 0x1f,
    0x00, 0x1f, 0x00, 0x1d, 0x00, 0x1f, 0x00, 0x1e, 0x00, 0x1f, 0x00, 0x1e,
    0x00, 0x1f, 0x00, 0x1f, 0x00, 0x1e, 0x00, 0x1f, 0x00, 0x1e, 0x00, 0x1f
};
unsigned char CLOCK_HalfHourSlotLookup[48] = {
    0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x01, 0x02,
    0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
    0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a,
    0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26
};
long PARSEINI_ParsedDescriptorListHead = 0;
long CTASKS_PendingLogoBrushDescriptor = 0;
long CTASKS_PendingGAdsBrushDescriptor = 0;
long ESQFUNC_PwBrushDescriptorHead = 0;
long PARSEINI_BannerBrushResourceHead = 0;
long CTASKS_PendingIffBrushDescriptor = 0;
long WDISP_WeatherStatusBrushListHead = 0;
long BRUSH_SelectedNode = 0;
long ESQIFF_GAdsBrushListCount = 0;
long ESQIFF_LogoBrushListCount = 0;
long BRUSH_LoadInProgressFlag = 0;
long BRUSH_PendingAlertCode = 0;
