/* RESTORES: (data module -- no function)
 * MODULE:   data/cleanup.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 172 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_CLEANUP_C_1[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_2[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_3[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_4[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_5[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_6[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_7[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_8[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_9[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_10[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_11[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_12[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_13[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_14[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_15[10] = "CLEANUP.c";
char Global_STR_CLEANUP_C_16[10] = "CLEANUP.c";
unsigned char CLEANUP_AlertCooldownTicks[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char CLEANUP_AlertProcessingFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
long CLEANUP_BannerTickCounter = 60;
