/* RESTORES: (data module -- no function)
 * MODULE:   data/esqdisp.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 60 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_ESQDISP_C[10] = "ESQDISP.c";
unsigned char ESQDISP_StatusIndicatorColorCache[8] = {
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
};
unsigned char ESQDISP_StatusIndicatorMask[6] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
unsigned char Global_REF_INTB_AUD1_INTERRUPT[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char Global_REF_INTB_RBF_INTERRUPT[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQDISP_DisplayActiveFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
short ESQDISP_StatusBannerClampGateFlag = 1;
unsigned char ESQDISP_PendingGridReinitFlag[2] = {
    0x00, 0x00
};
unsigned char ESQDISP_PrimarySecondaryMirrorFlag[2] = {
    0x00, 0x00
};
unsigned char ESQDISP_SecondaryPersistRequestFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQDISP_StatusRefreshPendingFlag[2] = {
    0x00, 0x00
};
unsigned char ESQDISP_ProgramInfoZeroTag[3] = {
    0x30, 0x30, 0x00
};
unsigned char ESQDISP_LatchedInputModeBit = 255;
unsigned char ESQDISP_InputModeDebounceCount[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQDISP_LastPrimaryCountdownValue[2] = {
    0x00, 0x00
};
short ESQDISP_SecondaryPersistArmGateFlag = 1;
