/* RESTORES: (data module -- no function)
 * MODULE:   data/locavail_p2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 124 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char LOCAVAIL_TAG_UVGTI[6] = "UVGTI";
char LOCAVAIL_PATH_DF0_COLON_LOCAVAIL_DOT_DAT_Save[18] = "DF0:LocAvail.dat";
char LOCAVAIL_STR_LA_VER_1_COLON_CURDAY[18] = "LA_VER_1:  curday";
char LOCAVAIL_STR_LA_VER_1_COLON_NXTDAY[18] = "LA_VER_1:  nxtday";
char LOCAVAIL_PATH_DF0_COLON_LOCAVAIL_DOT_DAT_Load[18] = "DF0:LocAvail.dat";
char LOCAVAIL_STR_LA_VER[8] = "LA_VER";
char Global_STR_LOCAVAIL_C_7[12] = "LOCAVAIL.c";
char Global_STR_LOCAVAIL_C_8[12] = "LOCAVAIL.c";
char LOCAVAIL_STR_YYLLZ_FilterStateUpdate[6] = "YyLlZ";
unsigned char NEWGRID_MainRastPortPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_HeaderRastPortPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
