/* RESTORES: (data module -- no function)
 * MODULE:   data/esqpars2_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 24 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

short ESQPARS2_LogFieldTab = 2304;
long ESQPARS2_LogLineTerminator = 218759168;
char Global_STR_FLIB_C_1[8] = "FLIB.c";
char Global_STR_FLIB_C_2[8] = "FLIB.c";
unsigned char FLIB_EmptyLogReplacementString[2] = {
    0x00, 0x00
};
