/* RESTORES: (data module -- no function)
 * MODULE:   data/parseini_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 556 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char PARSEINI_TAG_DONE[6] = "DONE";
char PARSEINI_TAG_COLOR[6] = "COLOR";
unsigned char PARSEINI_CurrentWeatherBlockTempPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
char PARSEINI_TAG_FILENAME_WeatherBlock[10] = "FILENAME";
char PARSEINI_STR_LOADCOLOR[10] = "LOADCOLOR";
char PARSEINI_TAG_ALL[4] = "ALL";
char PARSEINI_TAG_NONE[6] = "NONE";
char PARSEINI_TAG_TEXT[6] = "TEXT";
char PARSEINI_TAG_XPOS[6] = "XPOS";
char PARSEINI_TAG_TYPE[6] = "TYPE";
char PARSEINI_TAG_DITHER[8] = "DITHER";
char PARSEINI_TAG_YPOS[6] = "YPOS";
char PARSEINI_TAG_XSOURCE[8] = "XSOURCE";
char PARSEINI_TAG_YSOURCE[8] = "YSOURCE";
char PARSEINI_TAG_SIZEX[6] = "SIZEX";
char PARSEINI_TAG_SIZEY[6] = "SIZEY";
char PARSEINI_TAG_SOURCE[8] = "SOURCE";
char PARSEINI_TAG_PPV[4] = "PPV";
char Global_STR_PARSEINI_C_3[12] = "PARSEINI.c";
char PARSEINI_STR_HORIZONTAL[12] = "HORIZONTAL";
char PARSEINI_TAG_RIGHT[6] = "RIGHT";
char PARSEINI_TAG_CENTER_HorizontalAlign[8] = "CENTER";
char PARSEINI_TAG_VERTICAL[10] = "VERTICAL";
char PARSEINI_TAG_BOTTOM[8] = "BOTTOM";
char PARSEINI_TAG_CENTER_VerticalAlign[8] = "CENTER";
char PARSEINI_TAG_ID[4] = "ID";
char PARSEINI_TAG_FILENAME_WeatherString[10] = "FILENAME";
char PARSEINI_TAG_WEATHER[8] = "WEATHER";
char PARSEINI_STR_WEATHERCURRENT[16] = "WeatherCurrent";
char PARSEINI_STR_WEATHERFORECAST[16] = "WeatherForecast";
char PARSEINI_STR_BOTTOMLINETAG[14] = "BottomLineTag";
char Global_STR_COLOR_PERCENT_D[8] = "COLOR%d";
char Global_STR_PERCENT_S_2[4] = "%s";
char Global_STR_DF0_GRADIENT_INI_3[18] = "df0:Gradient.ini";
char Global_STR_DF0_BANNER_INI_2[16] = "df0:banner.ini";
char Global_STR_DF0_BANNER_INI_3[16] = "df0:banner.ini";
char Global_STR_DF0_DEFAULT_INI_2[16] = "df0:default.ini";
char Global_STR_DF0_SOURCECFG_INI_1[18] = "df0:SourceCfg.ini";
char Global_STR_LIST_RAM_LOGODIR_TXT_DH2_LOGOS_NOHEAD_QUICK[46] = "list >RAM:logodir.txt DH2:LOGOS nohead quick";
char PARSEINI_PATH_DF0_COLON_LOGO_DOT_LST[14] = "df0:logo.lst";
char PARSEINI_STR_RB_LogoListPrimary[4] = "rb";
char PARSEINI_PATH_RAM_COLON_LOGODIR_DOT_TXT[16] = "RAM:logodir.txt";
char PARSEINI_STR_RB_LogoListSecondary[4] = "rb";
char Global_STR_PARSEINI_C_4[12] = "PARSEINI.c";
char Global_STR_PARSEINI_C_5[12] = "PARSEINI.c";
char Global_STR_DELETE_NIL_DH2_LOGOS[26] = "DELETE > NIL: DH2:LOGOS/";
char Global_STR_PARSEINI_C_6[12] = "PARSEINI.c";
char Global_STR_PARSEINI_C_7[12] = "PARSEINI.c";
unsigned char PARSEINI_FallbackClockDataRecord[28] = {
    0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x07, 0xc2, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00
};
char Global_STR_DF0_ERR_LOG[12] = "df0:err.log";
short PARSEINI_ClockSecondsSnapshot = 0;
short PARSEINI_ClockChangeSampleCounter = 0;
short PARSEINI_ClockChangeActiveFlag = 0;
short PARSEINI_CtrlHClockSnapshot = 0;
short PARSEINI_CtrlHChangeGateCounter = 0;
short PARSEINI_CtrlHChangePendingFlag = 0;
