/* RESTORES: (data module -- no function)
 * MODULE:   data/textdisp_p2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 144 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

/* Forward declarations. The type has to match the definition exactly
 * or 6.51 rejects the pair. */
extern unsigned char TEXTDISP_FormatEntryFallbackWord0[];
extern unsigned char TEXTDISP_FormatEntryFallbackWord1[];

char Global_STR_TEXTDISP_C_2[12] = "TEXTDISP.c";
char Global_STR_DF0_SOURCECFG_INI_2[18] = "df0:SourceCfg.ini";
char Global_STR_TEXTDISP_C_3[12] = "TEXTDISP.c";
unsigned char Global_STR_TEXTDISP_C_4[14] = "TEXTDISP.c";
short TEXTDISP_ActiveGroupId = 1;
unsigned char TEXTDISP_FormatEntryFallbackWord0[6] = {
    0x19, 0x20, 0x20, 0x20, 0x00, 0x00
};
unsigned char TEXTDISP_FormatEntryFallbackWord1[6] = {
    0x18, 0x19, 0x19, 0x19, 0x00, 0x00
};
long TEXTDISP_FormatEntryFallbackTable[10] = {
    (long)TEXTDISP_FormatEntryFallbackWord0, (long)TEXTDISP_FormatEntryFallbackWord1, 0x7f020408L, 0x10204001L,
    0x3e3e0000L, 0x00000024L, 0x42617f7fL, 0x00000000L,
    0x7e1e3e3eL, 0x14001819L
};
unsigned char TEXTDISP_FormatEntryFallbackTable_Tail = 0;
unsigned char TEXTDISP_CenterAlignToken[2] = {
    0x18, 0x00
};
unsigned char TEXTDISP_LeftAlignToken[3] = {
    0x19, 0x00, 0x00
};
char TEXTDISP_Tag_PPV[4] = "PPV";
char TEXTDISP_Tag_SBE[4] = "SBE";
char TEXTDISP_Tag_SPORTS[8] = "SPORTS";
char TEXTDISP_Tag_SPT_Filter[4] = "SPT";
char Global_STR_ASTERISK_2[2] = "*";
char TEXTDISP_Tag_FIND1[6] = "FIND1";
