/* RESTORES: (data module -- no function)
 * MODULE:   data/esqiff.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 452 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_ESQIFF_C_1[10] = "ESQIFF.c";
unsigned char ESQIFF_BannerBrushResourceCursor[4] = {
    0x00, 0x00, 0x00, 0x00
};
char ESQIFF_STR_WEATHER[8] = "weather";
char Global_STR_ESQIFF_C_2[10] = "ESQIFF.c";
unsigned char ESQIFF_WeatherSliceRemainingWidth[2] = {
    0x00, 0x00
};
unsigned char ESQIFF_WeatherSliceSourceOffset[2] = {
    0x00, 0x00
};
short ESQIFF_WeatherSliceValidateGateFlag = 256;
char Global_STR_ESQIFF_C_3[10] = "ESQIFF.c";
char Global_STR_ESQIFF_C_4[10] = "ESQIFF.c";
char Global_STR_ESQIFF_C_5[10] = "ESQIFF.c";
char Global_STR_ESQIFF_C_6[10] = "ESQIFF.c";
unsigned char ESQIFF_PATH_DF0_COLON[12] = {
    0x64, 0x66, 0x30, 0x3a, 0x00, 0x00, 0x64, 0x66, 0x30, 0x3a, 0x00, 0x00
};
unsigned char ESQIFF_PATH_RAM_COLON_LOGOS_SLASH[24] = {
    0x72, 0x61, 0x6d, 0x3a, 0x6c, 0x6f, 0x67, 0x6f, 0x73, 0x2f, 0x20, 0x00,
    0x72, 0x61, 0x6d, 0x3a, 0x6c, 0x6f, 0x67, 0x6f, 0x73, 0x2f, 0x20, 0x00
};
char Global_STR_ESQIFF_C_7[10] = "ESQIFF.c";
char Global_STR_ESQIFF_C_8[10] = "ESQIFF.c";
char Global_STR_DF0_BRUSH_INI_2[14] = "df0:brush.ini";
char ESQIFF_TAG_DT[4] = "DT";
char ESQIFF_TAG_DITHER[8] = "DITHER";
char ESQIFF_FMT_PCT_S_DOT_PCT_LD[8] = "%s.%ld";
char Global_STR_MAJOR_MINOR_VERSION_1[4] = "9.0";
char ESQIFF_STR_INCORRECT_VERSION_PLEASE_CORRECT_ASA[40] = "Incorrect Version! Please correct ASAP!";
char ESQIFF_FMT_YOUR_VERSION_IS_PCT_S_DOT_PCT_LD[28] = "Your version is    '%s.%ld'";
char Global_STR_MAJOR_MINOR_VERSION_2[4] = "9.0";
char ESQIFF_STR_CORRECT_VERSION_IS[22] = "Correct version is '";
char Global_STR_APOSTROPHE[2] = "'";
char Global_STR_PLEASE_STANDBY_2[18] = "Please Standby...";
char Global_STR_ATTENTION_SYSTEM_ENGINEER_2[28] = "ATTENTION SYSTEM ENGINEER!";
char Global_STR_REPORT_ERROR_CODE_FORMATTED[58] = "Report Error Code ER%03d to TV Guide Technical Services.";
char Global_STR_FILE_WIDTH_COLORS_FORMATTED[32] = "File='%s'  Width=%d  Colors=%d";
char Global_STR_FILE_PERCENT_S[10] = "File '%s'";
char Global_STR_PRESS_ESC_TWICE_TO_RESUME_SCROLL[38] = "Press ESC key twice to resume scroll";
