/* RESTORES: (data module -- no function)
 * MODULE:   data/textdisp_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 16 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_ASTERISK_3[2] = "*";
char TEXTDISP_Tag_SPT_Select[4] = "SPT";
char Global_STR_TLIBA1_C_1[10] = "TLIBA1.c";
