/* RESTORES: (data module -- no function)
 * MODULE:   data/gcommand_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 40 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_INPUT_DEVICE[14] = "input.device";
char Global_STR_CONSOLE_DEVICE[16] = "console.device";
unsigned char Global_STR_KYBD_C[10] = {
    0x4b, 0x59, 0x42, 0x44, 0x2e, 0x63, 0x00, 0x00, 0x00, 0x00
};
