/* RESTORES: (data module -- no function)
 * MODULE:   data/tliba1_p2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 936 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_TLIBA1_C_2[10] = "TLIBA1.c";
char Global_STR_TLIBA1_C_3[10] = "TLIBA1.c";
unsigned char TLIBA1_STR_TLIBA1_DOT_C[9] = "TLIBA1.c";
unsigned char TLIBA1_FormatFallbackBuffer[3] = {
    0x00, 0x00, 0x00
};
unsigned char TLIBA1_FormatFallbackFieldPtr0[2] = {
    0x00, 0x00
};
unsigned char TLIBA1_FormatFallbackFieldPtr1[2] = {
    0x00, 0x00
};
unsigned char TLIBA1_FormatFallbackFieldPtr2[2] = {
    0x00, 0x00
};
unsigned char TLIBA1_FormatFallbackFieldPtr3[2] = {
    0x00, 0x00
};
char TLIBA1_FMT_PCT_C_PCT_S[6] = "%c%s";
unsigned char TLIBA1_FMT_STRUCT_TLFORMAT_0X_PCT_X[26] = "struct TLFormat @ 0x%x =\n";
unsigned char TLIBA1_STR_TLFormatStructOpenBraceLine[4] = "{\n";
unsigned char TLIBA1_FMT_TLF_COLOR_PCT_D[20] = "\ttlf_Color =   %d\n";
unsigned char TLIBA1_FMT_TLF_OFFSET_PCT_D[20] = "\ttlf_Offset =  %d\n";
unsigned char TLIBA1_FMT_TLF_FONTSEL_PCT_D[20] = "\ttlf_FontSel = %d\n";
unsigned char TLIBA1_FMT_TLF_ALIGN_PCT_D[20] = "\ttlf_Align =   %d\n";
unsigned char TLIBA1_FMT_TLF_PREGAP_PCT_D[20] = "\ttlf_Pregap =  %d\n";
unsigned char TLIBA1_STR_TLFormatStructCloseBraceLine[4] = "}\n";
unsigned char TLIBA1_PatternTableInitGuard[2] = {
    0x00, 0x00
};
unsigned char TEXTDISP_LrbnEntryWidthPx[2] = {
    0x01, 0x28
};
char TLIBA1_FMT_PCT_03LD_VerticalScaleTick[6] = "%03ld";
char TLIBA1_FMT_PCT_03LD_HorizontalScaleTick[6] = "%03ld";
char TLIBA1_FMT_VIEWMODE_PCT_LD[16] = "ViewMode = %ld";
unsigned char TLIBA1_CurrentViewModeIndex[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char TLIBA1_DiagDiwOffset[2] = {
    0x00, 0x00
};
unsigned char TLIBA1_DiagDdfOffset[2] = {
    0x00, 0x00
};
unsigned char TLIBA1_DiagBplcon1Value[2] = {
    0x00, 0x00
};
unsigned char TLIBA1_FMT_PCT_S_COLON_DIWOFFSET_PCT_04LX_DDFOF[56] = "%s: diwoffset=$%04lx, ddfoffset=$%04lx, bplcon1=$%04lx\n";
unsigned char TLIBA1_FMT_DIWSTRT_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "DIWSTRT: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_DIWSTOP_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "DIWSTOP: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_DDFSTRT_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "DDFSTRT: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_DDFSTOP_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "DDFSTOP: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_BPL1MOD_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "BPL1MOD: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_BPL2MOD_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "BPL2MOD: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_BPLCON0_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "BPLCON0: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_BPLCON1_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "BPLCON1: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_BPLCON2_COLON_0X_PCT_04LX_0X_PCT_04L[34] = "BPLCON2: 0x%04lx 0x%04lx, (%ld)\n";
unsigned char TLIBA1_FMT_BPL1PTH_COLON_0X_PCT_04LX_0X_PCT_04L[26] = "BPL1PTH: 0x%04lx 0x%04lx\n";
unsigned char TLIBA1_FMT_BPL1PTL_COLON_0X_PCT_04LX_0X_PCT_04L[36] = "BPL1PTL: 0x%04lx 0x%04lx, ($%08lx)\n";
unsigned char TLIBA1_FMT_BPL2PTH_COLON_0X_PCT_04LX_0X_PCT_04L[26] = "BPL2PTH: 0x%04lx 0x%04lx\n";
unsigned char TLIBA1_FMT_BPL2PTL_COLON_0X_PCT_04LX_0X_PCT_04L[36] = "BPL2PTL: 0x%04lx 0x%04lx, ($%08lx)\n";
unsigned char TLIBA1_FMT_BPL3PTH_COLON_0X_PCT_04LX_0X_PCT_04L[26] = "BPL3PTH: 0x%04lx 0x%04lx\n";
unsigned char TLIBA1_FMT_BPL3PTL_COLON_0X_PCT_04LX_0X_PCT_04L[36] = "BPL3PTL: 0x%04lx 0x%04lx, ($%08lx)\n";
unsigned char TLIBA1_FMT_BPL4PTH_COLON_0X_PCT_04LX_0X_PCT_04L[26] = "BPL4PTH: 0x%04lx 0x%04lx\n";
unsigned char TLIBA1_FMT_BPL4PTL_COLON_0X_PCT_04LX_0X_PCT_04L[36] = "BPL4PTL: 0x%04lx 0x%04lx, ($%08lx)\n";
unsigned char TLIBA1_FMT_BPL5PTH_COLON_0X_PCT_04LX_0X_PCT_04L[26] = "BPL5PTH: 0x%04lx 0x%04lx\n";
unsigned char TLIBA1_FMT_BPL5PTL_COLON_0X_PCT_04LX_0X_PCT_04L[36] = "BPL5PTL: 0x%04lx 0x%04lx, ($%08lx)\n";
unsigned char TLIBA1_STR_PatternDumpSeparatorNewline[2] = {
    0x0a, 0x00
};
char Global_STR_VM_ARRAY_1[14] = "VM[ARRAY[%ld]";
char Global_STR_VM_ARRAY_2[14] = "VM[ARRAY[%ld]";
unsigned char TLIBA1_STR_PatternDumpLoopNewline[4] = {
    0x0a, 0x00, 0x00, 0x00
};
unsigned char TLIBA1_PreviewSlotRefreshState[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char TLIBA1_PreviewSlotRenderResult[4] = {
    0x00, 0x00, 0x00, 0x00
};
