/* RESTORES: (data module -- no function)
 * MODULE:   data/script_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 32 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

unsigned char TEXTDISP_LastDispatchGroupId[2] = {
    0x00, 0x31
};
unsigned char TEXTDISP_CommandBufferPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char TEXTDISP_CommandPrefixFormat[12] = {
    0x78, 0x78, 0x25, 0x73, 0x12, 0x54, 0x45, 0x4d, 0x50, 0x4f, 0x00, 0x00
};
char Global_STR_TEXTDISP_C_1[12] = "TEXTDISP.c";
char TEXTDISP_DefaultSpacePad[2] = " ";
