/* RESTORES: (data module -- no function)
 * MODULE:   data/esqfunc_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 1800 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

/* Forward declarations for the pointer tables below. The type has to
 * match the definition exactly or 6.51 rejects the pair. */
extern char ESQFUNC_STR_VIDEO_INSERTION_INACTIVE[];
extern char ESQFUNC_STR_VIDEO_INSERTION_START[];
extern char ESQFUNC_STR_VIDEO_INSERTION_INPROGRESS[];
extern char ESQFUNC_STR_VIDEO_INSERTION_STOP[];
extern char Global_STR_DF0_LOGO_LST[];
extern char Global_STR_GFX_G_ADS[];
extern char ESQFUNC_STR_PWBRUSH[];
extern char ESQFUNC_STR_PWI1[];
extern char ESQFUNC_STR_PWI2[];
extern char ESQFUNC_STR_PWI3[];
extern char ESQFUNC_STR_PWI4[];
extern char ESQFUNC_STR_PW[];

char Global_STR_VERTICAL_BLANK_INT[20] = "Vertical Blank Int";
char Global_STR_ESQFUNC_C_2[10] = "ESQFUNC.c";
char Global_STR_JOYSTICK_INT[14] = "JoyStick Int";
char Global_STR_ESQFUNC_C_3[10] = "ESQFUNC.c";
char Global_STR_ESQFUNC_C_4[10] = "ESQFUNC.c";
char Global_STR_RS232_RECEIVE_HANDLER[22] = "RS232 Receive Handler";
char Global_STR_ESQFUNC_C_5[10] = "ESQFUNC.c";
char Global_STR_ESQFUNC_C_6[10] = "ESQFUNC.c";
char Global_STR_DISK_0_IS_WRITE_PROTECTED[26] = "Disk 0 is write protected";
char Global_STR_YOU_MUST_REINSERT_SYSTEM_DISK_INTO_DRIVE_0[46] = "You MUST re-insert SYSTEM disk into drive 0!";
char Global_STR_BUILD_NUMBER_FORMATTED[22] = "Build Number: '%ld%s'";
char Global_STR_ROM_VERSION_FORMATTED[20] = " ROM Version: '%s'";
char Global_STR_ROM_VERSION_1_3[4] = "1.3";
char Global_STR_ROM_VERSION_2_04[6] = "2.04";
char Global_STR_PUSH_ANY_KEY_TO_CONTINUE_1[26] = "Push any key to continue.";
char Global_STR_DATA_CMDS_CERRS_LERRS[42] = "DATA: Cmds:%08ld CErrs:%03ld LErrs:%03ld";
char Global_STR_CTRL_CMDS_CERRS_LERRS[42] = "CTRL: Cmds:%08ld CErrs:%03ld LErrs:%03ld";
char Global_STR_L_CHIP_FAST_MAX[34] = "L_CHIP:%7ld  FAST:%8ld  MAX:%8ld";
char Global_STR_CHIP_PLACEHOLDER[40] = "CHIP:%7ld                             ";
char Global_STR_FAST_PLACEHOLDER[38] = "              FAST:%8ld              ";
char Global_STR_MAX_PLACEHOLDER[38] = "                             MAX:%8ld";
char Global_STR_MEMORY_TYPES_DISABLED[42] = "Memory types disabled (use CTRL C/F/M/A).";
char Global_STR_DATA_OVERRUNS_FORMATTED[20] = "DATA Overruns: %ld";
char Global_STR_DATA_H_T_C_MAX_FORMATTED[44] = "DATA: H:%05ld  T:%05ld  C:%05ld  MAX:%05ld";
char Global_STR_CTRL_H_T_C_MAX_FORMATTED[44] = "CTRL: H:%05ld  T:%05ld  C:%05ld  MAX:%05ld";
char Global_STR_JULIAN_DAY_NEXT_FORMATTED[34] = "julian day = %3ld    next = %3ld";
char Global_STR_JDAY1_JDAY2_FORMATTED[32] = "jday1 = %3ld     jday2 =  %3ld";
char Global_STR_CURCLU_NXTCLU_FORMATTED[28] = " curclu =%2ld nxtclu =%2ld ";
char Global_STR_C_DATE_C_MONTH_LP_YR_FORMATTED[42] = "C.date=%2ld C.month=%2ld lp=%4ld yr=%4ld";
char Global_STR_B_DATE_B_MONTH_LP_YR_FORMATTED[42] = "B.date=%2ld B.month=%2ld lp=%4ld yr=%4ld";
char Global_STR_C_DST_B_DST_PSHIFT_FORMATTED[38] = "C.dst =%2ld B.dst =%2ld pshift =%2ld";
char Global_STR_C_HOUR_B_HOUR_CS_FORMATTED[34] = "C.hour =%3ld B.hour =%3ld cs=%2ld";
unsigned char ESQFUNC_DiagRowCounter[4] = {
    0x00, 0x00, 0x00, 0x00
};
char ESQFUNC_STR_VIDEO_INSERTION_INACTIVE[26] = "VIDEO_INSERTION_INACTIVE";
char ESQFUNC_STR_VIDEO_INSERTION_START[22] = "VIDEO_INSERTION_START";
char ESQFUNC_STR_VIDEO_INSERTION_INPROGRESS[28] = "VIDEO_INSERTION_INPROGRESS";
char ESQFUNC_STR_VIDEO_INSERTION_STOP[22] = "VIDEO_INSERTION_STOP";
long ESQFUNC_VideoInsertionStateStrings[3] = {
    (long)ESQFUNC_STR_VIDEO_INSERTION_INACTIVE, (long)ESQFUNC_STR_VIDEO_INSERTION_START, (long)ESQFUNC_STR_VIDEO_INSERTION_INPROGRESS
};
long ESQFUNC_VideoInsertionStateString_StopPtr[1] = {
    (long)ESQFUNC_STR_VIDEO_INSERTION_STOP
};
char ESQFUNC_FMT_CARTSW_COLON_PCT_S_CARTREL_COLON_PCT[48] = "  CartSW: %s CartREL: %s VidSW: %s on_air: %s ";
char ESQFUNC_STR_CLOSED_ENABLED[18] = "CLOSED (ENABLED)";
char ESQFUNC_STR_OPEN_DISABLED[16] = "OPEN (DISABLED)";
char ESQFUNC_TAG_CLOSED[8] = "CLOSED";
char ESQFUNC_TAG_OPEN[6] = "OPEN";
char ESQFUNC_STR_CLOSED_ON_AIR[16] = "CLOSED (ON AIR)";
char ESQFUNC_STR_OPEN_OFF_AIR[16] = "OPEN (OFF AIR)";
char ESQFUNC_STR_ON_AIR[8] = "ON_AIR";
char ESQFUNC_STR_OFF_AIR[8] = "OFF_AIR";
char ESQFUNC_STR_NO_DETECT[10] = "NO_DETECT";
char ESQFUNC_FMT_INSERTIME_PCT_S_WINIT_0X_PCT_04X[34] = " insertime = %s,  WINIT = 0x%04X ";
char ESQFUNC_FMT_LOCAL_MODE_PCT_LD_LOCAL_UPDATE_PCT_L[96] = " local_mode=%ld local_update=%ld LA_(mode=%d state=%d curEv=%d) laCur(curType=%d curEvent=%d) ";
char ESQFUNC_FMT_CTIME_PCT_02D_SLASH_PCT_02D_SLASH_PC[56] = " CTime = %02d/%02d/%04d %2d:%02d:%02d%s, LATime = %04d ";
char ESQFUNC_STR_PM[4] = "pm";
char ESQFUNC_STR_AM[4] = "am";
char ESQFUNC_FMT_L_CHIP_COLON_PCT_07LD_FAST_COLON_PCT[38] = " L_CHIP:%07ld  FAST:%08ld  MAX:%08ld ";
char ESQFUNC_FMT_DATA_COLON_CMD_CNT_COLON_PCT_08LD_CR[80] = " DATA: CMD CNT:%08ld CRC ERRS:%03ld LEN ERRS:%03ld BUF MAX:%05ld BUF CNT:%05ld";
char ESQFUNC_FMT_CTRL_COLON_CMD_CNT_COLON_PCT_08LD_CR[80] = " CTRL: CMD CNT:%08ld CRC ERRS:%03ld LEN ERRS:%03ld BUF MAX:%05ld BUF CNT:%05ld ";
char ESQFUNC_FMT_PCT_05LD_COLON_PEP_COLON_PCT_LD_REUS[66] = "  %05ld: PEP:%ld REUSED CLU:%s DISPATCH ERRS:%03ld EDSTATE:%ld  ";
char Global_STR_TRUE_2[6] = "TRUE";
char Global_STR_FALSE_2[6] = "FALSE";
unsigned char ESQFUNC_BasePaletteRgbTriples[24] = {
    0x00, 0x00, 0x03, 0x0c, 0x0c, 0x0c, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x00,
    0x05, 0x01, 0x02, 0x01, 0x06, 0x0a, 0x05, 0x05, 0x05, 0x00, 0x00, 0x03
};
short ESQFUNC_WeatherSliceWidthInitGate = 1;
char Global_STR_DF0_LOGO_LST[14] = "df0:logo.lst";
long Global_PTR_STR_DF0_LOGO_LST[1] = {
    (long)Global_STR_DF0_LOGO_LST
};
unsigned char ESQFUNC_FallbackType3BrushNode[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQIFF_BrushIniListHead[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQIFF_GAdsBrushListHead[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQIFF_LogoBrushListHead[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQFUNC_PwBrushListHead[4] = {
    0x00, 0x00, 0x00, 0x00
};
char Global_STR_GFX_G_ADS[10] = "gfx:g.ads";
long Global_PTR_STR_GFX_G_ADS[1] = {
    (long)Global_STR_GFX_G_ADS
};
char ESQFUNC_STR_PWBRUSH[8] = "pwbrush";
char ESQFUNC_STR_PWI1[6] = "pwi1";
char ESQFUNC_STR_PWI2[6] = "pwi2";
char ESQFUNC_STR_PWI3[6] = "pwi3";
char ESQFUNC_STR_PWI4[6] = "pwi4";
char ESQFUNC_STR_PW[2] = "pw";
char ESQFUNC_STR_I5[4] = "i5";
unsigned char ESQFUNC_PwBrushNamePtrTable[0] = {
};
long ESQFUNC_BrushDescriptorTagStrings[1] = {
    (long)ESQFUNC_STR_PWBRUSH
};
long ESQFUNC_WeatherBrushPredicateNames[5] = {
    (long)ESQFUNC_STR_PWI1, (long)ESQFUNC_STR_PWI2, (long)ESQFUNC_STR_PWI3, (long)ESQFUNC_STR_PWI4,
    (long)ESQFUNC_STR_PW
};
unsigned char Global_REF_LONG_GFX_G_ADS_FILESIZE[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char Global_REF_LONG_GFX_G_ADS_DATA[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char Global_REF_LONG_DF0_LOGO_LST_FILESIZE[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char Global_REF_LONG_DF0_LOGO_LST_DATA[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char ESQFUNC_MissingAssetRetryMask[3] = {
    0x00, 0x00, 0x00
};
unsigned char ESQFUNC_IffTaskGateFlags = 0;
char ESQFUNC_TAG_00[4] = "00";
char ESQFUNC_TAG_11[4] = "11";
