/* RESTORES: (data module -- no function)
 * MODULE:   data/script.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 1516 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

/* Forward declarations. The type has to match the definition exactly
 * or 6.51 rejects the pair. */
extern char Global_STR_NO_CURRENT_WEATHER_DATA_AVIALABLE[];
extern char SCRIPT_StrNoForecastWeatherData[];
extern char SCRIPT_StrWeatherDataAvailabilityDisclaimer[];
extern char SCRIPT_StrContinued[];
extern char Global_STR_JANUARY[];
extern char Global_STR_FEBRUARY[];
extern char Global_STR_MARCH[];
extern char Global_STR_APRIL[];
extern char Global_STR_MAY[];
extern char Global_STR_JUNE[];
extern char Global_STR_JULY[];
extern char Global_STR_AUGUST[];
extern char Global_STR_SEPTEMBER[];
extern char Global_STR_OCTOBER[];
extern char Global_STR_NOVEMBER[];
extern char Global_STR_DECEMBER[];
extern char SCRIPT_StrMonthShort_Jan[];
extern char SCRIPT_StrMonthShort_Feb[];
extern char SCRIPT_StrMonthShort_Mar[];
extern char SCRIPT_StrMonthShort_Apr[];
extern char SCRIPT_StrMonthShort_May[];
extern char SCRIPT_StrMonthShort_Jun[];
extern char SCRIPT_StrMonthShort_Jul[];
extern char SCRIPT_StrMonthShort_Aug[];
extern char SCRIPT_StrMonthShort_Sep[];
extern char SCRIPT_StrMonthShort_Oct[];
extern char SCRIPT_StrMonthShort_Nov[];
extern char SCRIPT_StrMonthShort_Dec[];
extern char Global_STR_SUNDAY_1[];
extern char Global_STR_MONDAY_1[];
extern char Global_STR_TUESDAY_1[];
extern char Global_STR_WEDNESDAY_1[];
extern char Global_STR_THURSDAY_1[];
extern char Global_STR_FRIDAY_1[];
extern char Global_STR_SATURDAY_1[];
extern char SCRIPT_StrDayShort_Sun[];
extern char SCRIPT_StrDayShort_Mon[];
extern char SCRIPT_StrDayShort_Tue[];
extern char SCRIPT_StrDayShort_Wed[];
extern char SCRIPT_StrDayShort_Thu[];
extern char SCRIPT_StrDayShort_Fri[];
extern char SCRIPT_StrDayShort_Sat[];
extern char SCRIPT_StrChannelLabel_Monday[];
extern char SCRIPT_StrChannelLabel_Tuesday[];
extern char SCRIPT_StrChannelLabel_Wednesday[];
extern char SCRIPT_StrChannelLabel_Thursday[];
extern char SCRIPT_StrChannelLabel_Friday[];
extern char SCRIPT_StrChannelLabel_Saturday[];
extern char SCRIPT_StrChannelLabel_Sunday[];
extern char SCRIPT_StrChannelLabel_Weekdays[];
extern char SCRIPT_StrChannelLabel_Weeknights[];
extern char SCRIPT_StrChannelLabel_ComingSoon[];
extern char SCRIPT_StrChannelLabel_ThisMonth[];
extern char SCRIPT_StrChannelLabel_NextMonth[];
extern char SCRIPT_StrChannelLabel_ThisFall[];
extern char SCRIPT_StrChannelLabel_ThisSummer[];
extern char SCRIPT_StrChannelLabel_TuesdaysFridays[];
extern char SCRIPT_StrChannelLabel_MondaysSaturdays[];
extern char SCRIPT_StrChannelLabel_Weekends[];
extern char SCRIPT_StrChannelLabel_EveryNight[];
extern char SCRIPT_StrChannelLabel_EveryDay[];
extern unsigned char SCRIPT_ChannelLabelEmptySlot0[];
extern unsigned char SCRIPT_ChannelLabelEmptySlot1[];
extern unsigned char SCRIPT_ChannelLabelEmptySlot2[];
extern unsigned char SCRIPT_ChannelLabelEmptySlot3[];
extern char SCRIPT_StrChannelLabel_MondaysThruSaturdays[];
extern char SCRIPT_StrChannelLabel_MondaysThruThursdays[];
extern char SCRIPT_StrChannelLabel_WeekdayMornings[];
extern char SCRIPT_StrChannelLabel_WeekdayAfternoons[];
extern char SCRIPT_StrChannelLabel_TuesdaysThursdays[];
extern char SCRIPT_StrChannelLabel_ThisWeek[];
extern char SCRIPT_StrSportsOnPrefix[];
extern char SCRIPT_StrMovieSummaryForPrefix[];
extern char SCRIPT_StrSummaryOfPrefix[];
extern char SCRIPT_StrChannelSuffix[];
extern char SCRIPT_StrNoDataPlaceholder[];
extern char Global_STR_ER007_AWAITING_LISTINGS_DATA_TRANSMISSION[];
extern char Global_STR_OFF_AIR_1[];
extern char Global_STR_PREVUESPORTS[];

char Global_STR_SCRIPT_C_1[10] = "SCRIPT.c";
char Global_STR_SCRIPT_C_2[10] = "SCRIPT.c";
unsigned char SCRIPT_SerialReadModeOverflowCount[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char SCRIPT_CtrlLineAssertedFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
char Global_STR_NO_CURRENT_WEATHER_DATA_AVIALABLE[34] = "No Current Weather Data Available";
long Global_STR_PTR_NO_CURRENT_WEATHER_DATA_AVIALABLE[1] = {
    (long)Global_STR_NO_CURRENT_WEATHER_DATA_AVIALABLE
};
char SCRIPT_StrNoForecastWeatherData[36] = "No Forecast Weather Data Available";
long SCRIPT_PtrNoForecastWeatherData[1] = {
    (long)SCRIPT_StrNoForecastWeatherData
};
char SCRIPT_StrWeatherDataAvailabilityDisclaimer[36] = "May not be available in all areas.";
long SCRIPT_PtrWeatherDataAvailabilityDisclaimer[1] = {
    (long)SCRIPT_StrWeatherDataAvailabilityDisclaimer
};
char SCRIPT_StrContinued[10] = "Continued";
long SCRIPT_PtrContinued[1] = {
    (long)SCRIPT_StrContinued
};
char Global_STR_JANUARY[8] = "January";
char Global_STR_FEBRUARY[10] = "February";
char Global_STR_MARCH[6] = "March";
char Global_STR_APRIL[6] = "April";
char Global_STR_MAY[4] = "May";
char Global_STR_JUNE[6] = "June";
char Global_STR_JULY[6] = "July";
char Global_STR_AUGUST[8] = "August";
char Global_STR_SEPTEMBER[10] = "September";
char Global_STR_OCTOBER[8] = "October";
char Global_STR_NOVEMBER[10] = "November";
char Global_STR_DECEMBER[10] = "December";
long Global_JMPTBL_MONTHS[12] = {
    (long)Global_STR_JANUARY, (long)Global_STR_FEBRUARY, (long)Global_STR_MARCH, (long)Global_STR_APRIL,
    (long)Global_STR_MAY, (long)Global_STR_JUNE, (long)Global_STR_JULY, (long)Global_STR_AUGUST,
    (long)Global_STR_SEPTEMBER, (long)Global_STR_OCTOBER, (long)Global_STR_NOVEMBER, (long)Global_STR_DECEMBER
};
char SCRIPT_StrMonthShort_Jan[6] = "Jan ";
char SCRIPT_StrMonthShort_Feb[6] = "Feb ";
char SCRIPT_StrMonthShort_Mar[6] = "Mar ";
char SCRIPT_StrMonthShort_Apr[6] = "Apr ";
char SCRIPT_StrMonthShort_May[6] = "May ";
char SCRIPT_StrMonthShort_Jun[6] = "Jun ";
char SCRIPT_StrMonthShort_Jul[6] = "Jul ";
char SCRIPT_StrMonthShort_Aug[6] = "Aug ";
char SCRIPT_StrMonthShort_Sep[6] = "Sep ";
char SCRIPT_StrMonthShort_Oct[6] = "Oct ";
char SCRIPT_StrMonthShort_Nov[6] = "Nov ";
char SCRIPT_StrMonthShort_Dec[6] = "Dec ";
long Global_JMPTBL_SHORT_MONTHS[12] = {
    (long)SCRIPT_StrMonthShort_Jan, (long)SCRIPT_StrMonthShort_Feb, (long)SCRIPT_StrMonthShort_Mar, (long)SCRIPT_StrMonthShort_Apr,
    (long)SCRIPT_StrMonthShort_May, (long)SCRIPT_StrMonthShort_Jun, (long)SCRIPT_StrMonthShort_Jul, (long)SCRIPT_StrMonthShort_Aug,
    (long)SCRIPT_StrMonthShort_Sep, (long)SCRIPT_StrMonthShort_Oct, (long)SCRIPT_StrMonthShort_Nov, (long)SCRIPT_StrMonthShort_Dec
};
char Global_STR_SUNDAY_1[8] = "Sunday";
char Global_STR_MONDAY_1[8] = "Monday";
char Global_STR_TUESDAY_1[8] = "Tuesday";
char Global_STR_WEDNESDAY_1[10] = "Wednesday";
char Global_STR_THURSDAY_1[10] = "Thursday";
char Global_STR_FRIDAY_1[8] = "Friday";
char Global_STR_SATURDAY_1[10] = "Saturday";
long Global_JMPTBL_DAYS_OF_WEEK[7] = {
    (long)Global_STR_SUNDAY_1, (long)Global_STR_MONDAY_1, (long)Global_STR_TUESDAY_1, (long)Global_STR_WEDNESDAY_1,
    (long)Global_STR_THURSDAY_1, (long)Global_STR_FRIDAY_1, (long)Global_STR_SATURDAY_1
};
char SCRIPT_StrDayShort_Sun[6] = "Sun ";
char SCRIPT_StrDayShort_Mon[6] = "Mon ";
char SCRIPT_StrDayShort_Tue[6] = "Tue ";
char SCRIPT_StrDayShort_Wed[6] = "Wed ";
char SCRIPT_StrDayShort_Thu[6] = "Thu ";
char SCRIPT_StrDayShort_Fri[6] = "Fri ";
char SCRIPT_StrDayShort_Sat[6] = "Sat ";
long Global_JMPTBL_SHORT_DAYS_OF_WEEK[7] = {
    (long)SCRIPT_StrDayShort_Sun, (long)SCRIPT_StrDayShort_Mon, (long)SCRIPT_StrDayShort_Tue, (long)SCRIPT_StrDayShort_Wed,
    (long)SCRIPT_StrDayShort_Thu, (long)SCRIPT_StrDayShort_Fri, (long)SCRIPT_StrDayShort_Sat
};
char SCRIPT_StrChannelLabel_Monday[8] = "Monday";
char SCRIPT_StrChannelLabel_Tuesday[8] = "Tuesday";
char SCRIPT_StrChannelLabel_Wednesday[10] = "Wednesday";
char SCRIPT_StrChannelLabel_Thursday[10] = "Thursday";
char SCRIPT_StrChannelLabel_Friday[8] = "Friday";
char SCRIPT_StrChannelLabel_Saturday[10] = "Saturday";
char SCRIPT_StrChannelLabel_Sunday[8] = "Sunday";
char SCRIPT_StrChannelLabel_Weekdays[10] = "Weekdays";
char SCRIPT_StrChannelLabel_Weeknights[12] = "Weeknights";
char SCRIPT_StrChannelLabel_ComingSoon[12] = "Coming Soon";
char SCRIPT_StrChannelLabel_ThisMonth[12] = "This Month";
char SCRIPT_StrChannelLabel_NextMonth[12] = "Next Month";
char SCRIPT_StrChannelLabel_ThisFall[10] = "This Fall";
char SCRIPT_StrChannelLabel_ThisSummer[12] = "This Summer";
char SCRIPT_StrChannelLabel_TuesdaysFridays[20] = "Tuesdays & Fridays";
char SCRIPT_StrChannelLabel_MondaysSaturdays[20] = "Mondays & Saturdays";
char SCRIPT_StrChannelLabel_Weekends[10] = "Weekends";
char SCRIPT_StrChannelLabel_EveryNight[12] = "Every Night";
char SCRIPT_StrChannelLabel_EveryDay[10] = "Every Day";
unsigned char SCRIPT_ChannelLabelEmptySlot0[0] = {
};
unsigned char SCRIPT_ChannelLabelEmptySlot0_BackingWord[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_ChannelLabelEmptySlot1[0] = {
};
unsigned char SCRIPT_ChannelLabelEmptySlot1_BackingWord[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_ChannelLabelEmptySlot2[0] = {
};
unsigned char SCRIPT_ChannelLabelEmptySlot2_BackingWord[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_ChannelLabelEmptySlot3[0] = {
};
unsigned char SCRIPT_ChannelLabelEmptySlot3_BackingWord[2] = {
    0x00, 0x00
};
char SCRIPT_StrChannelLabel_MondaysThruSaturdays[24] = "Mondays thru Saturdays";
char SCRIPT_StrChannelLabel_MondaysThruThursdays[24] = "Mondays thru Thursdays";
char SCRIPT_StrChannelLabel_WeekdayMornings[18] = "Weekday Mornings";
char SCRIPT_StrChannelLabel_WeekdayAfternoons[20] = "Weekday Afternoons";
char SCRIPT_StrChannelLabel_TuesdaysThursdays[22] = "Tuesdays & Thursdays";
char SCRIPT_StrChannelLabel_ThisWeek[10] = "This Week";
long SCRIPT_ChannelLabelPtrTable[29] = {
    (long)SCRIPT_StrChannelLabel_Monday, (long)SCRIPT_StrChannelLabel_Tuesday, (long)SCRIPT_StrChannelLabel_Wednesday, (long)SCRIPT_StrChannelLabel_Thursday,
    (long)SCRIPT_StrChannelLabel_Friday, (long)SCRIPT_StrChannelLabel_Saturday, (long)SCRIPT_StrChannelLabel_Sunday, (long)SCRIPT_StrChannelLabel_Weekdays,
    (long)SCRIPT_StrChannelLabel_Weeknights, (long)SCRIPT_StrChannelLabel_ComingSoon, (long)SCRIPT_StrChannelLabel_ThisMonth, (long)SCRIPT_StrChannelLabel_NextMonth,
    (long)SCRIPT_StrChannelLabel_ThisFall, (long)SCRIPT_StrChannelLabel_ThisSummer, (long)SCRIPT_StrChannelLabel_TuesdaysFridays, (long)SCRIPT_StrChannelLabel_MondaysSaturdays,
    (long)SCRIPT_StrChannelLabel_Weekends, (long)SCRIPT_StrChannelLabel_EveryNight, (long)SCRIPT_StrChannelLabel_EveryDay, (long)SCRIPT_ChannelLabelEmptySlot0,
    (long)SCRIPT_ChannelLabelEmptySlot1, (long)SCRIPT_ChannelLabelEmptySlot2, (long)SCRIPT_ChannelLabelEmptySlot3, (long)SCRIPT_StrChannelLabel_MondaysThruSaturdays,
    (long)SCRIPT_StrChannelLabel_MondaysThruThursdays, (long)SCRIPT_StrChannelLabel_WeekdayMornings, (long)SCRIPT_StrChannelLabel_WeekdayAfternoons, (long)SCRIPT_StrChannelLabel_TuesdaysThursdays,
    (long)SCRIPT_StrChannelLabel_ThisWeek
};
unsigned char Global_STR_ALIGNED_NOW_SHOWING[13] = {
    0x18, 0x4e, 0x6f, 0x77, 0x20, 0x73, 0x68, 0x6f, 0x77, 0x69, 0x6e, 0x67,
    0x00
};
unsigned char Global_STR_ALIGNED_NEXT_SHOWING[15] = {
    0x18, 0x4e, 0x65, 0x78, 0x74, 0x20, 0x73, 0x68, 0x6f, 0x77, 0x69, 0x6e,
    0x67, 0x20, 0x00
};
unsigned char Global_STR_ALIGNED_TODAY_AT[11] = {
    0x18, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x20, 0x61, 0x74, 0x20, 0x00
};
unsigned char Global_STR_ALIGNED_TOMORROW_AT[14] = {
    0x18, 0x54, 0x6f, 0x6d, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x20, 0x61, 0x74,
    0x20, 0x00
};
char Global_STR_SHOWTIMES_AND_SINGLE_SPACE[11] = "Showtimes ";
char Global_STR_SHOWING_AT_AND_SINGLE_SPACE[12] = "Showing at ";
unsigned char SCRIPT_StrHoursPluralSuffix[5] = {
    0x68, 0x72, 0x73, 0x20, 0x00
};
unsigned char SCRIPT_StrHourSingularSuffix[4] = {
    0x68, 0x72, 0x20, 0x00
};
unsigned char SCRIPT_StrMinutesSuffix[5] = {
    0x6d, 0x69, 0x6e, 0x29, 0x00
};
unsigned char Global_STR_ALIGNED_TONIGHT_AT[13] = {
    0x18, 0x54, 0x6f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x20, 0x61, 0x74, 0x20,
    0x00
};
unsigned char Global_STR_ALIGNED_ON[4] = {
    0x18, 0x6f, 0x6e, 0x00
};
unsigned char Global_STR_ALIGNED_CHANNEL_1[11] = {
    0x18, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x20, 0x00, 0x00
};
char SCRIPT_StrSportsOnPrefix[12] = "Sports on ";
long SCRIPT_PtrSportsOnPrefix[1] = {
    (long)SCRIPT_StrSportsOnPrefix
};
char SCRIPT_StrMovieSummaryForPrefix[20] = "Movie Summary for ";
long SCRIPT_PtrMovieSummaryForPrefix[1] = {
    (long)SCRIPT_StrMovieSummaryForPrefix
};
char SCRIPT_StrSummaryOfPrefix[12] = "Summary of ";
long SCRIPT_PtrSummaryOfPrefix[1] = {
    (long)SCRIPT_StrSummaryOfPrefix
};
char SCRIPT_StrChannelSuffix[10] = " channel ";
long SCRIPT_PtrChannelSuffix[1] = {
    (long)SCRIPT_StrChannelSuffix
};
char SCRIPT_StrNoDataPlaceholder[10] = "No Data.";
long SCRIPT_PtrNoDataPlaceholder[1] = {
    (long)SCRIPT_StrNoDataPlaceholder
};
char Global_STR_ER007_AWAITING_LISTINGS_DATA_TRANSMISSION[48] = "Please Stand By for your Local Listings.  ER007";
long Global_PTR_STR_ER007_AWAITING_LISTINGS_DATA_TRANSMISSION[1] = {
    (long)Global_STR_ER007_AWAITING_LISTINGS_DATA_TRANSMISSION
};
char Global_STR_OFF_AIR_1[10] = "Off Air.";
long SCRIPT_PtrOffAirPlaceholder[1] = {
    (long)Global_STR_OFF_AIR_1
};
char Global_STR_GRID_DATE_FORMAT_STRING[16] = "%s %s %ld %04ld";
char Global_STR_WEATHER_UPDATE_FOR[20] = "Weather Update for ";
unsigned char SCRIPT_CtrlHandshakeStage[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_CtrlHandshakeRetryCount[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_RuntimeModeDispatchLatch[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_CtrlCmdDeferCounter[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_PlaybackFallbackCounter[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_Type20SubtypeCache[2] = {
    0x00, 0x00
};
short SCRIPT_PendingBannerTargetChar = -1;
unsigned char SCRIPT_PendingBannerSpeedMs[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_BannerTransitionStepBudget[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_BannerTransitionActive[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_ReadModeActiveLatch[2] = {
    0x00, 0x00
};
unsigned char BRUSH_ScriptPrimarySelection[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char BRUSH_ScriptSecondarySelection[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char SCRIPT_RuntimeModeDeferredFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char SCRIPT_PendingWeatherCommandChar = 120;
unsigned char SCRIPT_PendingTextdispCmdChar = 0;
unsigned char SCRIPT_PendingTextdispCmdArg[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_CommandTextPtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char SCRIPT_BannerTransitionStepCursor[2] = {
    0x00, 0x00
};
unsigned char SCRIPT_StatusMaskRefreshPending[2] = {
    0x00, 0x00
};
char SCRIPT_BrushTag_Default00_Primary[4] = "00";
char SCRIPT_BrushTag_Default00_Secondary[4] = "00";
char SCRIPT_BrushTag_Clear11_Primary[4] = "11";
char SCRIPT_BrushTag_Clear11_Secondary[4] = "11";
unsigned char SCRIPT_Tag_YL[6] = {
    0x79, 0x6c, 0x00, 0x00, 0x00, 0x00
};
unsigned char TEXTDISP_SourceConfigFlagMask[2] = {
    0x00, 0x00
};
char Global_STR_PREVUESPORTS[14] = "PrevueSports";
long TEXTDISP_PtrPrevueSportsTag[1] = {
    (long)Global_STR_PREVUESPORTS
};
unsigned char SCRIPT_AlignedPrefixEmptyA[2] = {
    0x18, 0x00
};
unsigned char SCRIPT_AlignedPrefixEmptyB[2] = {
    0x18, 0x00
};
char SCRIPT_SpacerTripleA[4] = "   ";
unsigned char SCRIPT_AlignedChannelAbbrevPrefix[6] = {
    0x18, 0x43, 0x68, 0x2e, 0x20, 0x00
};
char SCRIPT_SpacerTripleB[4] = "   ";
unsigned char SCRIPT_AlignedCharFormat[4] = {
    0x18, 0x25, 0x63, 0x00
};
unsigned char SCRIPT_AlignedPrefixEmptyC[2] = {
    0x18, 0x00
};
unsigned char SCRIPT_AlignedPrefixEmptyD[2] = {
    0x18, 0x00
};
char SCRIPT_SpacerTripleC[4] = "   ";
unsigned char SCRIPT_AlignedPrefixEmptyE[2] = {
    0x18, 0x00
};
unsigned char SCRIPT_AlignedPrefixEmptyF[2] = {
    0x18, 0x00
};
unsigned char SCRIPT_AlignedStringFormat[4] = {
    0x18, 0x25, 0x73, 0x00
};
char SCRIPT_StrAtSeparator[6] = " at ";
char SCRIPT_StrVsDotSeparator[6] = " vs. ";
char SCRIPT_StrVsSeparator[6] = " vs ";
unsigned char SCRIPT_AlignedPrefixEmptyG[2] = {
    0x18, 0x00
};
unsigned char Global_STR_ALIGNED_CHANNEL_2[10] = {
    0x18, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x20, 0x00
};
short TEXTDISP_FilterModeId = 768;
char SCRIPT_FilterTag_PPV[4] = "PPV";
char SCRIPT_FilterTag_SBE[4] = "SBE";
char SCRIPT_FilterTag_SPORTS[8] = "SPORTS";
short TEXTDISP_LastDispatchMatchIndex = -1;
