/* RESTORES: (data module -- no function)
 * MODULE:   data/ctasks.s
 * STATUS:   behavioural
 *
 * DO-NOT-LINK: NOT LAYOUT-NEUTRAL. The bytes here are correct and were verified
 *   against the assembler, but this module does not START on a longword
 *   boundary in the DATA section. gen_units.coalesce() force-closes the
 *   assembly group in front of a replaced module, so replacing this one pads
 *   that group and moves every symbol after it. Linked with three others like
 *   it the DATA hunk grew from 55,820 to 55,832 and the display froze.
 *   `python3 tools/data_to_c.py data/ctasks.s --write` now refuses it and prints the
 *   offset. See AGENTS.md.
 *
 *
 * Generated by tools/data_to_c.py, then read. 428 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

/* Forward declarations for the pointer tables below. The type has to
 * match the definition exactly or 6.51 rejects the pair. */
extern char CTASKS_STR_TERM_MISSED_RECORD[];
extern char CTASKS_STR_TERM_WRITE_DISK1[];
extern char CTASKS_STR_TERM_WRITE_DISK2[];
extern char CTASKS_STR_TERM_BATCH_OFF[];
extern char CTASKS_STR_TERM_OPEN_FILE[];
extern char CTASKS_STR_TERM_DL_TOO_LARGE_HEAD[];

char Global_STR_CTASKS_C_1[10] = "CTASKS.c";
char Global_STR_IFF_TASK_1[10] = "iff_task";
char Global_STR_CTASKS_C_2[10] = "CTASKS.c";
char Global_STR_IFF_TASK_2[10] = "iff_task";
short CTASKS_CloseTaskCompletionFlag = 1;
unsigned char CTASKS_CloseTaskFileHandle[4] = {
    0x00, 0x00, 0x00, 0x00
};
char Global_STR_CTASKS_C_3[10] = "CTASKS.c";
char Global_STR_CTASKS_C_4[10] = "CTASKS.c";
char Global_STR_CLOSE_TASK[12] = "close_task";
unsigned char CTASKS_PrimaryOiWritePendingFlag = 0;
unsigned char CTASKS_SecondaryOiWritePendingFlag = 0;
unsigned char CTASKS_PendingPrimaryOiDiskId = 0;
unsigned char CTASKS_PendingSecondaryOiDiskId = 0;
char CTASKS_STR_TERM_MISSED_RECORD[26] = "Terminated: Missed Record";
char CTASKS_STR_TERM_WRITE_DISK1[36] = "Terminated: Error Writing to Disk 1";
char CTASKS_STR_TERM_WRITE_DISK2[36] = "Terminated: Error Writing to Disk 2";
char CTASKS_STR_TERM_BATCH_OFF[28] = "Terminated: Batch OFF Found";
char CTASKS_STR_TERM_OPEN_FILE[32] = "Terminated: Error Opening file";
char CTASKS_STR_TERM_DL_TOO_LARGE_HEAD[30] = "Terminated: DL File Too Large";
long CTASKS_TerminationReasonPtrTable[6] = {
    (long)CTASKS_STR_TERM_MISSED_RECORD, (long)CTASKS_STR_TERM_WRITE_DISK1, (long)CTASKS_STR_TERM_WRITE_DISK2, (long)CTASKS_STR_TERM_BATCH_OFF,
    (long)CTASKS_STR_TERM_OPEN_FILE, (long)CTASKS_STR_TERM_DL_TOO_LARGE_HEAD
};
unsigned char CTASKS_EXT_GRF[5] = {
    0x2e, 0x47, 0x52, 0x46, 0x00
};
unsigned char CTASKS_PATH_CURDAY_DAT[15] = {
    0x64, 0x66, 0x30, 0x3a, 0x63, 0x75, 0x72, 0x64, 0x61, 0x79, 0x2e, 0x64,
    0x61, 0x74, 0x00
};
unsigned char CTASKS_PATH_QTABLE_INI[15] = {
    0x64, 0x66, 0x30, 0x3a, 0x71, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x69,
    0x6e, 0x69, 0x00
};
unsigned char CTASKS_PATH_OINFO_DAT[14] = {
    0x64, 0x66, 0x30, 0x3a, 0x6f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x64, 0x61,
    0x74, 0x00
};
unsigned char Global_STR_DF0_NXTDAY_DAT[15] = {
    0x64, 0x66, 0x30, 0x3a, 0x6e, 0x78, 0x74, 0x64, 0x61, 0x79, 0x2e, 0x64,
    0x61, 0x74, 0x00
};
long DISKIO_SaveOperationReadyFlag = 1;
unsigned char DISKIO_BufferControl[8] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
unsigned char CONFIG_RefreshIntervalMinutes = 2;
unsigned char CTASKS_STR_C = 67;
unsigned char CONFIG_NicheModeCycleBudget_Y = 0;
unsigned char CONFIG_NicheModeCycleBudget_Static = 3;
unsigned char CONFIG_SerializedNumericSlot05 = 24;
unsigned char CONFIG_NewgridWindowSpanHalfHoursPrimary = 24;
unsigned char CTASKS_STR_G = 71;
unsigned char CONFIG_SerializedFlagSlot08_DefaultN = 78;
unsigned char CTASKS_STR_A = 65;
unsigned char CTASKS_STR_E = 69;
unsigned char CONFIG_SerializedNumericSlot10 = 0;
unsigned char CONFIG_NicheModeCycleBudget_Custom = 0;
unsigned char CONFIG_NewgridSelectionCode34PrimaryEnabledFlag = 89;
unsigned char CONFIG_NewgridSelectionCode35EnabledFlag = 89;
unsigned char CONFIG_SerializedFlagSlot15_DefaultN = 78;
unsigned char CONFIG_NewgridSelectionCode34AltEnabledFlag = 78;
unsigned char CONFIG_NewgridSelectionCode32EnabledFlag = 89;
unsigned char CONFIG_RuntimeMode12BannerJumpEnabledFlag = 78;
unsigned char CTASKS_STR_L = 76;
unsigned char CONFIG_SerializedNumericSlot19 = 29;
unsigned char CONFIG_SerializedNumericSlot20 = 6;
unsigned char CONFIG_ModeCycleEnabledFlag = 89;
unsigned char CONFIG_NewgridPlaceholderBevelFlag = 89;
unsigned char CONFIG_NewgridSelectionCode48_49EnabledFlag = 78;
unsigned char CONFIG_SerializedNumericSlot25 = 23;
unsigned char CONFIG_SerializedNumericSlot26 = 36;
unsigned char CONFIG_NewgridWindowSpanHalfHoursAlt[2] = {
    0x0c, 0x00
};
long CONFIG_TimeWindowMinutes = 15;
long CONFIG_ModeCycleGateDuration = 1;
unsigned char CONFIG_NewgridSelectionCode16EnabledFlag = 89;
unsigned char Global_REF_STR_USE_24_HR_CLOCK = 78;
char CONFIG_ParseiniLogoScanEnabledFlag[2] = "Y";
unsigned char CONFIG_BannerCopperHeadByte[2] = {
    0x00, 0x8e
};
unsigned char Global_REF_BYTE_NUMBER_OF_COLOR_PALETTES = 8;
unsigned char ED_DiagTextModeChar = 78;
unsigned char CONFIG_EnsurePc1GfxAssignedFlag = 78;
unsigned char CONFIG_MsnRuntimeModeSelectorChar_LRBN = 78;
unsigned char CONFIG_LRBN_FlagChar = 89;
unsigned char CONFIG_MSN_FlagChar = 78;
char CTASKS_STR_1[2] = "1";
long CONFIG_RefreshIntervalSeconds = 120;
unsigned char DISKIO_OpenCount[4] = {
    0x00, 0x00, 0x00, 0x00
};
