/* RESTORES: (data module -- no function)
 * MODULE:   data/newgrid2.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 96 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_NEWGRID2_C_1[12] = "NEWGRID2.c";
char Global_STR_NEWGRID2_C_2[12] = "NEWGRID2.c";
long NEWGRID2_CachedModeIndex = 0;
long NEWGRID2_DispatchStateIndex = 0;
long NEWGRID2_PendingOperationId = 0;
long NEWGRID2_LastDispatchResult = 0;
long NEWGRID2_BufferAllocationFlag = 1;
char Global_STR_NEWGRID2_C_3[12] = "NEWGRID2.c";
char Global_STR_NEWGRID2_C_4[12] = "NEWGRID2.c";
char Global_STR_NEWGRID2_C_5[12] = "NEWGRID2.c";
char Global_STR_NEWGRID2_C_6[12] = "NEWGRID2.c";
long NEWGRID2_ErrorLogEntryPtr = 0;
