/* RESTORES: (data module -- no function)
 * MODULE:   data/newgrid_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/data_to_c.py, then read. 276 bytes.
 *
 * Every array carries an EXPLICIT size: the span from its label to the next
 * one, padding included. `NStr` ends in `CNOP 0,2` and SAS/C 6.51 does not
 * word-align consecutive char arrays, so the padding has to be declared or it
 * is lost. See src/c/data_displib.c for the whole story, and AGENTS.md for the
 * rule that a data module must be a multiple of 4 bytes.
 */

char Global_STR_NEWGRID_C_2[10] = "NEWGRID.c";
unsigned char Global_STR_44_44_44[20] = {
    0x34, 0x34, 0x3a, 0x34, 0x34, 0x3a, 0x34, 0x34, 0x00, 0x00, 0x34, 0x34,
    0x3a, 0x34, 0x34, 0x3a, 0x34, 0x34, 0x00, 0x00
};
char Global_STR_NEWGRID_C_3[10] = "NEWGRID.c";
unsigned char NEWGRID_ModeCycleCountdown[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_NicheModeCycleBudget_Static = 0;
unsigned char NEWGRID_NicheModeCycleBudget_Y = 0;
unsigned char NEWGRID_NicheModeCycleBudget_Custom = 0;
unsigned char NEWGRID_NicheModeCycleBudget_Global = 0;
unsigned char NEWGRID_MplexModeCycleBudget = 0;
unsigned char NEWGRID_PpvModeCycleBudget = 0;
unsigned char NEWGRID_ModeCandidateIndex[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_ModeSelectionTable[28] = {
    0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x07,
    0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x0a,
    0x00, 0x00, 0x00, 0x0c
};
char Global_STR_SINGLE_SPACE[2] = " ";
char NEWGRID_WrapWordSpacer[2] = " ";
char NEWGRID_WrapReturnSpacer[2] = " ";
unsigned char NEWGRID_MainModeState[4] = {
    0x00, 0x00, 0x00, 0x00
};
short NEWGRID_SelectedDaySlot = 1;
short NEWGRID_RenderDaySlot = 1;
unsigned char NEWGRID_HeaderRedrawPending[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_SecondaryIndexCachePtr[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_GridOperationId[4] = {
    0x00, 0x00, 0x00, 0x00
};
short NEWGRID_EntryPlaceholderModeFlag = 1;
short NEWGRID_PrimeTimeLayoutEnable = 1;
unsigned char NEWGRID_ShowtimeEntryVariantFlag[2] = {
    0x00, 0x00
};
unsigned char NEWGRID_EntrySplitDelimiterMask[15] = {
    0x90, 0x93, 0x9b, 0x99, 0xa3, 0xa3, 0x9a, 0x84, 0x86, 0x85, 0x8c, 0x87,
    0x8d, 0x8f, 0x00
};
unsigned char NEWGRID_GridEntryDelimiterBar[3] = {
    0x91, 0x7c, 0x00
};
char NEWGRID_EntryDetailFmtStr[10] = "%c%s%c %s";
long NEWGRID_GridStateFrameLatch = 4;
long NEWGRID_GridEntriesWorkflowState = 4;
unsigned char NEWGRID_GridSelectionColumnAdjust[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_GridSelectionEntryIndex[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_GridSelectionWorkflowState[4] = {
    0x00, 0x00, 0x00, 0x00
};
long NEWGRID_GridEditorWorkflowState = 4;
unsigned char NEWGRID_SecondarySelectedEntryIndex[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_SecondaryWorkflowState[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_SecondarySelectionHintCounter[4] = {
    0x00, 0x00, 0x00, 0x00
};
long NEWGRID_AltGridStateLatch = 4;
unsigned char NEWGRID_AltEntryAttemptCounter[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_AltEntryCursor[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_AltEntryWorkflowState[4] = {
    0x00, 0x00, 0x00, 0x00
};
long NEWGRID_DetailGridStateLatch = 4;
char NEWGRID_ChannelRowFmt[10] = "%s Ch. %s";
unsigned char NEWGRID_ScheduleSelectionCodeCache[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_ScheduleEditorGateFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_ScheduleAltSelectorFlag[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_ScheduleRowOffset[2] = {
    0x00, 0x00
};
unsigned char NEWGRID_SelectedPrimaryEntryIndex[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_ScheduleWorkflowState[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_SelectionScanEntryIndex[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_SelectionScanRow[2] = {
    0x00, 0x00
};
char NEWGRID_ShowtimeBucketSeparator[4] = ", ";
char Global_STR_SINGLE_SPACE_3[2] = " ";
char Global_STR_COMMA_AND_SINGLE_SPACE_1[4] = ", ";
char NEWGRID_ShowtimeGenreSpacer[2] = " ";
long NEWGRID_ShowtimesWorkflowStateLatch = 4;
unsigned char NEWGRID_ShowtimesWorkflowState[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_ShowtimesColumnAdjust[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_AltSelectionRowCursor[4] = {
    0x00, 0x00, 0x00, 0x00
};
unsigned char NEWGRID_AltSelectionEntryCursor[2] = {
    0x00, 0x00
};
char NEWGRID_ShowtimeListSeparator[4] = ", ";
char NEWGRID_ShowtimeRangeDash[2] = "-";
long NEWGRID_RenderStateLatch = 4;
