/* MERGED MODULE: modules/groups/a/g/diskio1_p1.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: DISKIO1_DumpProgramInfoRecordVerbose, DISKIO1_DumpProgramInfoAttrTable
 */
#include "diskio1_dump_program_info_record_verbose.c"
#include "diskio1_dump_program_info_attr_table.c"
