/* MERGED MODULE: modules/groups/a/k/ed1_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ED1_UpdateEscMenuSelection, ED1_EnterEscMenu, ED1_EnterEscMenu_AfterVersionText
 */
#include "ed1_update_esc_menu_selection.c"
#include "ed1_enter_esc_menu.c"
#include "ed1_enter_esc_menu_after_version_text.c"
