/* MERGED MODULE: modules/groups/a/l/ed3bbbb_p1.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ED_RedrawAllRows, ED_RedrawRow
 */
#include "ed_redraw_all_rows.c"
#include "ed_redraw_row.c"
