/* A4 near-data accessors. GENERATED by tools/a4_resolve.py.
 *
 * modules/submodules/ reaches its globals as `Global_DosIoErr(A4)`.
 * A4 is _Global_REF_LONG_FILE_SCRATCH, at DATA offset 32768, and each name
 * is an equate in src/Prevue.asm giving a displacement from it. So each of
 * these is an ordinary global, and restoring one in C is faithful rather
 * than an analogue.
 *
 * Most of them carry no label of their own: they sit inside the big DS
 * reservations the runtime carves up. Those are reached by indexing the
 * enclosing array, which needs no change to the assembly at all.
 *
 * Each symbol gets TWO forms. `<name>_A4` READS the datum, matching
 * `MOVE.L sym(A4),Dn`. `<name>_A4_ADDR` is its ADDRESS, matching
 * `LEA sym(A4),An`. Picking the wrong one is the defect
 * data_shape_audit.py exists to catch, and it is invisible in a byte
 * comparison -- Global_HandleTableBase is an array base, never a long.
 */
#ifndef ESQ_NEARDATA_H
#define ESQ_NEARDATA_H

extern unsigned char BUFFER_5929_LONGWORDS[];
extern unsigned char DEBUG_AbortRequesterTagChain[];
extern unsigned char DISKIO2_QTableIniFileHandle[];
extern unsigned char FORMAT_ScratchBuffer[];
extern unsigned char Global_REF_DOS_LIBRARY_2[];
extern unsigned char Global_STR_A_PLUS[];
extern unsigned char PREALLOC_HandleNode1_InitRecord[];
extern unsigned char PREALLOC_HandleNode2_InitRecord[];
extern unsigned char WDISP_CharClassTable[];

#define ESQ_StatusPacket__Bit3CaptureGateChar_A4       (*(long *)(DISKIO2_QTableIniFileHandle + 2))
#define ESQ_StatusPacket__Bit3CaptureGateChar_A4_ADDR  ((void *)(DISKIO2_QTableIniFileHandle + 2))

/* Global_AllocBlockSize is its own symbol. */
extern unsigned char PREALLOC_AllocBlockSizeSeed[];
#define Global_AllocBlockSize_A4       (*(long *)PREALLOC_AllocBlockSizeSeed)
#define Global_AllocBlockSize_A4_ADDR  ((void *)PREALLOC_AllocBlockSizeSeed)

#define Global_AllocBytesTotal_A4       (*(long *)(Global_STR_A_PLUS + 26))
#define Global_AllocBytesTotal_A4_ADDR  ((void *)(Global_STR_A_PLUS + 26))

#define Global_AllocListHead_A4       (*(long *)(Global_STR_A_PLUS + 22))
#define Global_AllocListHead_A4_ADDR  ((void *)(Global_STR_A_PLUS + 22))

#define Global_AppErrorCode_A4       (*(long *)(FORMAT_ScratchBuffer + 852))
#define Global_AppErrorCode_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 852))

#define Global_ArgCount_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 82))
#define Global_ArgCount_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 82))

#define Global_ArgvPtr_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 86))
#define Global_ArgvPtr_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 86))

#define Global_ArgvStorage_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 90))
#define Global_ArgvStorage_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 90))

/* Global_CharClassTable is its own symbol. */
extern unsigned char WDISP_CharClassTable[];
#define Global_CharClassTable_A4       (*(long *)WDISP_CharClassTable)
#define Global_CharClassTable_A4_ADDR  ((void *)WDISP_CharClassTable)

#define Global_CommandLineSize_A4       (*(long *)(BUFFER_5929_LONGWORDS + 4))
#define Global_CommandLineSize_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 4))

#define Global_ConsoleNameBuffer_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 24))
#define Global_ConsoleNameBuffer_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 24))

/* Global_DefaultHandleFlags is its own symbol. */
extern unsigned char PREALLOC_DefaultHandleFlagsSeed[];
#define Global_DefaultHandleFlags_A4       (*(long *)PREALLOC_DefaultHandleFlagsSeed)
#define Global_DefaultHandleFlags_A4_ADDR  ((void *)PREALLOC_DefaultHandleFlagsSeed)

#define Global_DosIoErr_A4       (*(long *)(BUFFER_5929_LONGWORDS + 24))
#define Global_DosIoErr_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 24))

/* Global_DosLibrary is its own symbol. */
extern unsigned char Global_REF_DOS_LIBRARY_2[];
#define Global_DosLibrary_A4       (*(long *)Global_REF_DOS_LIBRARY_2)
#define Global_DosLibrary_A4_ADDR  ((void *)Global_REF_DOS_LIBRARY_2)

#define Global_ExitHookPtr_A4       (*(long *)(BUFFER_5929_LONGWORDS + 44))
#define Global_ExitHookPtr_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 44))

#define Global_FormatBufferPtr2_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 16))
#define Global_FormatBufferPtr2_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 16))

#define Global_FormatByteCount2_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 20))
#define Global_FormatByteCount2_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 20))

#define Global_FormatCallbackBufferPtr_A4       (*(long *)(FORMAT_ScratchBuffer + 844))
#define Global_FormatCallbackBufferPtr_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 844))

#define Global_FormatCallbackByteCount_A4       (*(long *)(FORMAT_ScratchBuffer + 848))
#define Global_FormatCallbackByteCount_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 848))

/* Global_GraphicsLibraryBase_A4 is its own symbol. */
extern unsigned char Global_REF_GRAPHICS_LIBRARY[];
#define Global_GraphicsLibraryBase_A4_A4       (*(long *)Global_REF_GRAPHICS_LIBRARY)
#define Global_GraphicsLibraryBase_A4_A4_ADDR  ((void *)Global_REF_GRAPHICS_LIBRARY)

#define Global_HandleEntry0_Flags_A4       (*(long *)(FORMAT_ScratchBuffer + 516))
#define Global_HandleEntry0_Flags_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 516))

#define Global_HandleEntry0_Ptr_A4       (*(long *)(FORMAT_ScratchBuffer + 520))
#define Global_HandleEntry0_Ptr_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 520))

#define Global_HandleEntry1_Flags_A4       (*(long *)(FORMAT_ScratchBuffer + 524))
#define Global_HandleEntry1_Flags_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 524))

#define Global_HandleEntry1_Ptr_A4       (*(long *)(FORMAT_ScratchBuffer + 528))
#define Global_HandleEntry1_Ptr_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 528))

#define Global_HandleEntry2_Flags_A4       (*(long *)(FORMAT_ScratchBuffer + 532))
#define Global_HandleEntry2_Flags_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 532))

#define Global_HandleEntry2_Ptr_A4       (*(long *)(FORMAT_ScratchBuffer + 536))
#define Global_HandleEntry2_Ptr_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 536))

#define Global_HandleTableBase_A4       (*(long *)(FORMAT_ScratchBuffer + 516))
#define Global_HandleTableBase_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 516))

#define Global_HandleTableCount_A4       (*(long *)(Global_STR_A_PLUS + 6))
#define Global_HandleTableCount_A4_ADDR  ((void *)(Global_STR_A_PLUS + 6))

#define Global_HandleTableFlags_A4       (*(long *)(Global_STR_A_PLUS + 30))
#define Global_HandleTableFlags_A4_ADDR  ((void *)(Global_STR_A_PLUS + 30))

#define Global_MemListFirstAllocNode_A4       (*(long *)(Global_STR_A_PLUS + 10))
#define Global_MemListFirstAllocNode_A4_ADDR  ((void *)(Global_STR_A_PLUS + 10))

#define Global_MemListHead_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 4))
#define Global_MemListHead_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 4))

#define Global_MemListTail_A4       (*(long *)(Global_REF_DOS_LIBRARY_2 + 8))
#define Global_MemListTail_A4_ADDR  ((void *)(Global_REF_DOS_LIBRARY_2 + 8))

#define Global_PreallocHandleNode0_A4       (*(long *)(Global_STR_A_PLUS + 34))
#define Global_PreallocHandleNode0_A4_ADDR  ((void *)(Global_STR_A_PLUS + 34))

#define Global_PreallocHandleNode0_HandleIndex_A4       (*(long *)(Global_STR_A_PLUS + 62))
#define Global_PreallocHandleNode0_HandleIndex_A4_ADDR  ((void *)(Global_STR_A_PLUS + 62))

#define Global_PreallocHandleNode0_OpenFlags_A4       (*(long *)(Global_STR_A_PLUS + 58))
#define Global_PreallocHandleNode0_OpenFlags_A4_ADDR  ((void *)(Global_STR_A_PLUS + 58))

/* Global_PreallocHandleNode1 is its own symbol. */
extern unsigned char PREALLOC_HandleNode1_InitRecord[];
#define Global_PreallocHandleNode1_A4       (*(long *)PREALLOC_HandleNode1_InitRecord)
#define Global_PreallocHandleNode1_A4_ADDR  ((void *)PREALLOC_HandleNode1_InitRecord)

#define Global_PreallocHandleNode1_BufferCursor_A4       (*(long *)(PREALLOC_HandleNode1_InitRecord + 4))
#define Global_PreallocHandleNode1_BufferCursor_A4_ADDR  ((void *)(PREALLOC_HandleNode1_InitRecord + 4))

#define Global_PreallocHandleNode1_HandleIndex_A4       (*(long *)(PREALLOC_HandleNode1_InitRecord + 28))
#define Global_PreallocHandleNode1_HandleIndex_A4_ADDR  ((void *)(PREALLOC_HandleNode1_InitRecord + 28))

#define Global_PreallocHandleNode1_OpenFlags_A4       (*(long *)(PREALLOC_HandleNode1_InitRecord + 24))
#define Global_PreallocHandleNode1_OpenFlags_A4_ADDR  ((void *)(PREALLOC_HandleNode1_InitRecord + 24))

#define Global_PreallocHandleNode1_WriteRemaining_A4       (*(long *)(PREALLOC_HandleNode1_InitRecord + 12))
#define Global_PreallocHandleNode1_WriteRemaining_A4_ADDR  ((void *)(PREALLOC_HandleNode1_InitRecord + 12))

#define Global_PreallocHandleNode2_HandleIndex_A4       (*(long *)(PREALLOC_HandleNode2_InitRecord + 28))
#define Global_PreallocHandleNode2_HandleIndex_A4_ADDR  ((void *)(PREALLOC_HandleNode2_InitRecord + 28))

#define Global_PreallocHandleNode2_OpenFlags_A4       (*(long *)(PREALLOC_HandleNode2_InitRecord + 24))
#define Global_PreallocHandleNode2_OpenFlags_A4_ADDR  ((void *)(PREALLOC_HandleNode2_InitRecord + 24))

#define Global_PrintfBufferPtr_A4       (*(long *)(FORMAT_ScratchBuffer + 836))
#define Global_PrintfBufferPtr_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 836))

#define Global_PrintfByteCount_A4       (*(long *)(FORMAT_ScratchBuffer + 840))
#define Global_PrintfByteCount_A4_ADDR  ((void *)(FORMAT_ScratchBuffer + 840))

#define Global_SavedDirLock_A4       (*(long *)(BUFFER_5929_LONGWORDS + 52))
#define Global_SavedDirLock_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 52))

#define Global_SavedExecBase_A4       (*(long *)(BUFFER_5929_LONGWORDS + 56))
#define Global_SavedExecBase_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 56))

#define Global_SavedMsg_A4       (*(long *)(BUFFER_5929_LONGWORDS + 60))
#define Global_SavedMsg_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 60))

#define Global_SavedStackPointer_A4       (*(long *)(BUFFER_5929_LONGWORDS + 64))
#define Global_SavedStackPointer_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 64))

#define Global_ScratchPtr_592_A4       (*(long *)(BUFFER_5929_LONGWORDS + 72))
#define Global_ScratchPtr_592_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 72))

#define Global_SignalCallbackPtr_A4       (*(long *)(BUFFER_5929_LONGWORDS + 48))
#define Global_SignalCallbackPtr_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 48))

#define Global_StreamBufferAllocSize_A4       (*(long *)(WDISP_CharClassTable + 259))
#define Global_StreamBufferAllocSize_A4_ADDR  ((void *)(WDISP_CharClassTable + 259))

#define Global_UNKNOWN36_MessagePtr_A4       (*(long *)(BUFFER_5929_LONGWORDS + 72))
#define Global_UNKNOWN36_MessagePtr_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 72))

#define Global_UNKNOWN36_RequesterOutPtr_A4       (*(long *)(DEBUG_AbortRequesterTagChain + 32))
#define Global_UNKNOWN36_RequesterOutPtr_A4_ADDR  ((void *)(DEBUG_AbortRequesterTagChain + 32))

#define Global_UNKNOWN36_RequesterText0_A4       (*(long *)(DEBUG_AbortRequesterTagChain + 20))
#define Global_UNKNOWN36_RequesterText0_A4_ADDR  ((void *)(DEBUG_AbortRequesterTagChain + 20))

#define Global_UNKNOWN36_RequesterText1_A4       (*(long *)(DEBUG_AbortRequesterTagChain + 40))
#define Global_UNKNOWN36_RequesterText1_A4_ADDR  ((void *)(DEBUG_AbortRequesterTagChain + 40))

#define Global_UNKNOWN36_RequesterText2_A4       (*(long *)(DEBUG_AbortRequesterTagChain + 60))
#define Global_UNKNOWN36_RequesterText2_A4_ADDR  ((void *)(DEBUG_AbortRequesterTagChain + 60))

/* Global_WBStartupCmdBuffer is its own symbol. */
extern unsigned char BUFFER_5929_LONGWORDS[];
#define Global_WBStartupCmdBuffer_A4       (*(long *)BUFFER_5929_LONGWORDS)
#define Global_WBStartupCmdBuffer_A4_ADDR  ((void *)BUFFER_5929_LONGWORDS)

#define Global_WBStartupWindowPtr_A4       (*(long *)(BUFFER_5929_LONGWORDS + 68))
#define Global_WBStartupWindowPtr_A4_ADDR  ((void *)(BUFFER_5929_LONGWORDS + 68))

/* NOT RESOLVED, and left out on purpose rather than guessed at:
 *   Global_GCOMMAND_PpvShowtimesLayoutPen    equate does not evaluate
 */
#endif
