/* MERGED MODULE: modules/groups/a/n/esqdispb_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQDISP_JMPTBL_NEWGRID_ProcessGridMessages, ESQDISP_JMPTBL_GRAPHICS_AllocRaster, ESQDISP_FillProgramInfoHeaderFields
 */
#include "esqdisp_fill_program_info_header_fields.c"
