/* MERGED MODULE: modules/groups/a/n/esqdispb_p0_p1_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQDISP_IsSlotBeyond23, ESQDISP_IsDayOfYearBeyondLimit, ESQDISP_IsSlotNegative, ESQDISP_IsSlotBelowOne
 */
#include "esqdisp_is_slot_beyond_23.c"
#include "esqdisp_is_day_of_year_beyond_limit.c"
#include "esqdisp_is_slot_negative.c"
#include "esqdisp_is_slot_below_one.c"
