/* MERGED MODULE: modules/groups/a/n/esqdispb_p0_p1_p0_esqdisp_drawstatusbanner_impl_esqdisp_drawstatusbanner_impl.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQDISP_DrawStatusBanner, ESQDISP_DrawStatusBanner_Impl
 */
#include "esqdisp_draw_status_banner.c"
#include "esqdisp_draw_status_banner_impl.c"
