/* MERGED MODULE: modules/groups/a/n/esqdispb_p0_esqdisp_testentrybits0and2_core_esqdisp_testentrybits0and2.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQDISP_TestEntryBits0And2, ESQDISP_TestEntryBits0And2_Core
 */
#include "esqdisp_test_entry_bits0and2.c"
#include "esqdisp_test_entry_bits0and2_core.c"
