/* MERGED MODULE: modules/groups/a/o/esqiff2_p2.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQIFF2_ReadRbfBytesToBuffer, ESQIFF2_ReadRbfBytesWithXor
 */
#include "esqiff2_read_rbf_bytes_to_buffer.c"
#include "esqiff2_read_rbf_bytes_with_xor.c"
