/* MERGED MODULE: modules/groups/a/q/esqshared4_esqshared4_copylongwordblockdbfloop_esqshared4_copylongwordblockdbfloop_esqshared4_copyliveplanestosnapshot.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQSHARED4_CopyLivePlanesToSnapshot, ESQSHARED4_CopyLongwordBlockDbfLoop
 */
#include "esqshared4_copy_live_planes_to_snapshot.c"
#include "esqshared4_copy_longword_block_dbf_loop.c"
