/* MERGED MODULE: modules/groups/a/q/esqshared4_p5.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQSHARED4_LoadBannerPaletteFromPreset, ESQSHARED4_SetBannerCopperColorAndThreshold, ESQSHARED4_StepBannerColorDown, ESQSHARED4_ResetBannerColorToStart, ESQSHARED4_ApplyBannerColorStep, ESQSHARED4_ReapplyBannerCopperColor, ESQSHARED4_StepBannerColorUp, ESQSHARED4_RestartBannerColorSweep, ESQSHARED4_ClampBannerColorAtSweepEnd
 */
#include "esqshared4_load_banner_palette_from_preset.c"
#include "esqshared4_set_banner_copper_color_and_threshold.c"
#include "esqshared4_step_banner_color_down.c"
#include "esqshared4_reset_banner_color_to_start.c"
#include "esqshared4_apply_banner_color_step.c"
#include "esqshared4_reapply_banner_copper_color.c"
#include "esqshared4_step_banner_color_up.c"
#include "esqshared4_restart_banner_color_sweep.c"
#include "esqshared4_clamp_banner_color_at_sweep_end.c"
