/* MERGED MODULE: modules/groups/a/q/esqshared4_p3_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQSHARED4_TickCopperAndBannerTransitions, ESQSHARED4_MirrorSnapshotPlanePointers, ESQSHARED4_AdvancePlanePointersOneRow
 */
#include "esqshared4_tick_copper_and_banner_transitions.c"
#include "esqshared4_mirror_snapshot_plane_pointers.c"
#include "esqshared4_advance_plane_pointers_one_row.c"
