/* MERGED MODULE: modules/groups/a/p/esqshared_esqshared_replacetvratingtoken_esqshared_replacetvratingtoken.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQSHARED_ReplaceTvRatingToken, ESQSHARED_UpdateMatchingEntriesByTitle
 */
#include "esqshared_replace_tv_rating_token.c"
#include "esqshared_update_matching_entries_by_title.c"
