/* RESTORES: (jump table -- 2 forwarding thunks)
 * MODULE:   modules/groups/a/r/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern long PARSEINI_WriteErrorLogEntry(void);
extern char * STRING_AppendAtNull(char *dst, char *src);

long GROUP_AR_JMPTBL_PARSEINI_WriteErrorLogEntry(void)
{
    return PARSEINI_WriteErrorLogEntry();
}

char * GROUP_AR_JMPTBL_STRING_AppendAtNull(char *dst, char *src)
{
    return STRING_AppendAtNull(dst, src);
}
