/* RESTORES: (jump table -- 34 forwarding thunks)
 * MODULE:   modules/groups/a/n/esqiffbb_p1_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include "esq-dos.h"

extern long STRING_CompareNoCase(char *a, char *b);
extern struct VmRuntime * TLIBA3_BuildDisplayContextForViewMode(long mode, long unused,
                                                        short highlight);
extern long DISKIO_GetFilesizeFromHandle(BPTR fh);
extern long __asm MATH_DivS32(register __d0 long a, register __d1 long b);
extern long TEXTDISP_FindEntryIndexByWildcard(char *pattern);
extern long STRING_CompareN(char *a, char *b, long n);
extern void ESQ_NoOp(void);
extern void TEXTDISP_DrawChannelBanner(short mode, short drawMode);
extern void ESQ_MoveCopperEntryTowardStart(long from, long to);
extern void MEMORY_DeallocateMemory(char *who, long line, void *block, long size);
extern void DISKIO_ForceUiRefreshIfIdle(void);
extern char * BRUSH_CloneBrushRecord(char *src);
extern void ESQ_MoveCopperEntryTowardEnd(long from, long to);
extern struct Brush4 * BRUSH_FindBrushByPredicate(char *want, struct Brush4Head *h);
extern void BRUSH_FreeBrushList(unsigned char **head, long mode);
extern struct BrushNode * BRUSH_FindType3Brush(struct BrushHead *head);
extern struct BrushNode3 * BRUSH_PopBrushHead(struct BrushNode3 *head);
extern void * BRUSH_AllocBrushNode(char *name, struct BrushNode *tail);
extern void ESQ_NoOp_006A(void);
extern void NEWGRID_ValidateSelectionCode(struct GridPanel *panel, long code);
extern void BRUSH_PopulateBrushList(struct BrushDescriptor *desc,
                             struct BrushListNode **head);
extern void ESQ_NoOp_0074(void);
extern long STRING_CompareNoCaseN(char *a, char *b, long n);
extern void SCRIPT_AssertCtrlLineIfEnabled(void);
extern long SCRIPT_BeginBannerCharTransition(short target, unsigned short rate);
extern void * MEMORY_AllocateMemory(char *who, long line, long size, long requirements);
extern void CTASKS_StartIffTaskProcess(void);
extern long DOS_OpenFileWithMode(char *path, long mode);
extern void ESQ_IncCopperListsTowardsTargets(void);
extern void ESQ_DecCopperListsPrimary(void);
extern void BRUSH_SelectBrushSlot(struct BrushRecord *brush, long x0, long y0, long x1,
                           long y1, struct RastPort *rp, long override);
extern void BRUSH_SelectBrushByLabel(char *label);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);
extern void DISKIO_ResetCtrlInputStateIfIdle(void);

long ESQIFF_JMPTBL_STRING_CompareNoCase(char *a, char *b)
{
    return STRING_CompareNoCase(a, b);
}

struct VmRuntime * ESQIFF_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(long mode, long unused,
                                                        short highlight)
{
    return TLIBA3_BuildDisplayContextForViewMode(mode, unused, highlight);
}

long ESQIFF_JMPTBL_DISKIO_GetFilesizeFromHandle(BPTR fh)
{
    return DISKIO_GetFilesizeFromHandle(fh);
}

long __asm ESQIFF_JMPTBL_MATH_DivS32(register __d0 long a, register __d1 long b)
{
    return MATH_DivS32(a, b);
}

long ESQIFF_JMPTBL_TEXTDISP_FindEntryIndexByWildcard(char *pattern)
{
    return TEXTDISP_FindEntryIndexByWildcard(pattern);
}

long ESQIFF_JMPTBL_STRING_CompareN(char *a, char *b, long n)
{
    return STRING_CompareN(a, b, n);
}

void ESQIFF_JMPTBL_ESQ_NoOp(void)
{
    ESQ_NoOp();
}

void ESQIFF_JMPTBL_TEXTDISP_DrawChannelBanner(short mode, short drawMode)
{
    TEXTDISP_DrawChannelBanner(mode, drawMode);
}

void ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardStart(long from, long to)
{
    ESQ_MoveCopperEntryTowardStart(from, to);
}

void ESQIFF_JMPTBL_MEMORY_DeallocateMemory(char *who, long line, void *block, long size)
{
    MEMORY_DeallocateMemory(who, line, block, size);
}

void ESQIFF_JMPTBL_DISKIO_ForceUiRefreshIfIdle(void)
{
    DISKIO_ForceUiRefreshIfIdle();
}

char * ESQIFF_JMPTBL_BRUSH_CloneBrushRecord(char *src)
{
    return BRUSH_CloneBrushRecord(src);
}

void ESQIFF_JMPTBL_ESQ_MoveCopperEntryTowardEnd(long from, long to)
{
    ESQ_MoveCopperEntryTowardEnd(from, to);
}

struct Brush4 * ESQIFF_JMPTBL_BRUSH_FindBrushByPredicate(char *want, struct Brush4Head *h)
{
    return BRUSH_FindBrushByPredicate(want, h);
}

void ESQIFF_JMPTBL_BRUSH_FreeBrushList(unsigned char **head, long mode)
{
    BRUSH_FreeBrushList(head, mode);
}

struct BrushNode * ESQIFF_JMPTBL_BRUSH_FindType3Brush(struct BrushHead *head)
{
    return BRUSH_FindType3Brush(head);
}

struct BrushNode3 * ESQIFF_JMPTBL_BRUSH_PopBrushHead(struct BrushNode3 *head)
{
    return BRUSH_PopBrushHead(head);
}

void * ESQIFF_JMPTBL_BRUSH_AllocBrushNode(char *name, struct BrushNode *tail)
{
    return BRUSH_AllocBrushNode(name, tail);
}

void ESQIFF_JMPTBL_ESQ_NoOp_006A(void)
{
    ESQ_NoOp_006A();
}

void ESQIFF_JMPTBL_NEWGRID_ValidateSelectionCode(struct GridPanel *panel, long code)
{
    NEWGRID_ValidateSelectionCode(panel, code);
}

void ESQIFF_JMPTBL_BRUSH_PopulateBrushList(struct BrushDescriptor *desc,
                             struct BrushListNode **head)
{
    BRUSH_PopulateBrushList(desc, head);
}

void ESQIFF_JMPTBL_ESQ_NoOp_0074(void)
{
    ESQ_NoOp_0074();
}

long ESQIFF_JMPTBL_STRING_CompareNoCaseN(char *a, char *b, long n)
{
    return STRING_CompareNoCaseN(a, b, n);
}

void ESQIFF_JMPTBL_SCRIPT_AssertCtrlLineIfEnabled(void)
{
    SCRIPT_AssertCtrlLineIfEnabled();
}

long ESQIFF_JMPTBL_SCRIPT_BeginBannerCharTransition(short target, unsigned short rate)
{
    return SCRIPT_BeginBannerCharTransition(target, rate);
}

void * ESQIFF_JMPTBL_MEMORY_AllocateMemory(char *who, long line, long size, long requirements)
{
    return MEMORY_AllocateMemory(who, line, size, requirements);
}

void ESQIFF_JMPTBL_CTASKS_StartIffTaskProcess(void)
{
    CTASKS_StartIffTaskProcess();
}

long ESQIFF_JMPTBL_DOS_OpenFileWithMode(char *path, long mode)
{
    return DOS_OpenFileWithMode(path, mode);
}

void ESQIFF_JMPTBL_ESQ_IncCopperListsTowardsTargets(void)
{
    ESQ_IncCopperListsTowardsTargets();
}

void ESQIFF_JMPTBL_ESQ_DecCopperListsPrimary(void)
{
    ESQ_DecCopperListsPrimary();
}

void ESQIFF_JMPTBL_BRUSH_SelectBrushSlot(struct BrushRecord *brush, long x0, long y0, long x1,
                           long y1, struct RastPort *rp, long override)
{
    BRUSH_SelectBrushSlot(brush, x0, y0, x1, y1, rp, override);
}

void ESQIFF_JMPTBL_BRUSH_SelectBrushByLabel(char *label)
{
    BRUSH_SelectBrushByLabel(label);
}

unsigned long __asm ESQIFF_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}

void ESQIFF_JMPTBL_DISKIO_ResetCtrlInputStateIfIdle(void)
{
    DISKIO_ResetCtrlInputStateIfIdle();
}
