/* RESTORES: (jump table -- 5 forwarding thunks)
 * MODULE:   modules/groups/b/a/textdisp_p3.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern long NEWGRID_ShouldOpenEditor(struct NewGridEditorEntry *e);
extern long ESQDISP_TestEntryGridEligibility(unsigned char *base, short index);
extern void ESQIFF_RunCopperRiseTransition(void);
extern void CLEANUP_BuildAlignedStatusLine(char *line, short flag, short row,
                                    short slot, long kind, long centered);
extern void CLEANUP_DrawInsetRectFrame(struct RastPort *rp, char pen, short w, short h);

long TEXTDISP_JMPTBL_NEWGRID_ShouldOpenEditor(struct NewGridEditorEntry *e)
{
    return NEWGRID_ShouldOpenEditor(e);
}

long TEXTDISP_JMPTBL_ESQDISP_TestEntryGridEligibility(unsigned char *base, short index)
{
    return ESQDISP_TestEntryGridEligibility(base, index);
}

void TEXTDISP_JMPTBL_ESQIFF_RunCopperRiseTransition(void)
{
    ESQIFF_RunCopperRiseTransition();
}

void TEXTDISP_JMPTBL_CLEANUP_BuildAlignedStatusLine(char *line, short flag, short row,
                                    short slot, long kind, long centered)
{
    CLEANUP_BuildAlignedStatusLine(line, flag, row, slot, kind, centered);
}

void TEXTDISP_JMPTBL_CLEANUP_DrawInsetRectFrame(struct RastPort *rp, char pen, short w, short h)
{
    CLEANUP_DrawInsetRectFrame(rp, pen, w, h);
}
