/* RESTORES: (jump table -- 5 forwarding thunks)
 * MODULE:   modules/groups/a/j/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include <stdarg.h>

extern char * STRING_FindSubstring(char *hay, char *needle);
extern void FORMAT_VRawDoFmtWithScratchBuffer(char *fmt, void *args);
extern unsigned long __asm MATH_DivU32(register __d0 unsigned long a,
                                register __d1 unsigned long b);
extern void PARSEINI_WriteRtcFromGlobals(void);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);

char * GROUP_AJ_JMPTBL_STRING_FindSubstring(char *hay, char *needle)
{
    return STRING_FindSubstring(hay, needle);
}

void GROUP_AJ_JMPTBL_FORMAT_RawDoFmtWithScratchBuffer(char *fmt, ...)
{
    va_list ap;

    va_start(ap, fmt);
    FORMAT_VRawDoFmtWithScratchBuffer(fmt, (void *)ap);
    va_end(ap);
}

unsigned long __asm GROUP_AJ_JMPTBL_MATH_DivU32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_DivU32(a, b);
}

void GROUP_AJ_JMPTBL_PARSEINI_WriteRtcFromGlobals(void)
{
    PARSEINI_WriteRtcFromGlobals();
}

unsigned long __asm GROUP_AJ_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}
