/* RESTORES: (jump table -- 17 forwarding thunks)
 * MODULE:   modules/groups/a/g/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern struct MsgPort * SIGNAL_CreateMsgPortWithSignal(char *name, long pri);
extern long __asm MATH_DivS32(register __d0 long a, register __d1 long b);
extern void MEMORY_DeallocateMemory(char *who, long line, void *block, long size);
extern void * STRUCT_AllocWithOwner(void *owner, long size);
extern void TEXTDISP_ResetSelectionAndRefresh(void);
extern void IOSTDREQ_CleanupSignalAndMsgport(struct MsgPort *port);
extern void ESQFUNC_ServiceUiTickIfRunning(void);
extern void STRUCT_FreeWithSizeField(void *block);
extern long PARSE_ReadSignedLongSkipClass3_Alt(char *s);
extern long SCRIPT_BeginBannerCharTransition(short target, unsigned short rate);
extern void LADFUNC2_EmitEscapedStringToScratch(char *s);
extern void * MEMORY_AllocateMemory(char *who, long line, long size, long requirements);
extern long DOS_OpenFileWithMode(char *path, long mode);
extern long SCRIPT_CheckPathExists(char *path);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);
extern void ESQFUNC_UpdateRefreshModeState(long unused, long request);
extern char * STRING_CopyPadNul(char *dst, char *src, long n);

struct MsgPort * GROUP_AG_JMPTBL_SIGNAL_CreateMsgPortWithSignal(char *name, long pri)
{
    return SIGNAL_CreateMsgPortWithSignal(name, pri);
}

long __asm GROUP_AG_JMPTBL_MATH_DivS32(register __d0 long a, register __d1 long b)
{
    return MATH_DivS32(a, b);
}

void GROUP_AG_JMPTBL_MEMORY_DeallocateMemory(char *who, long line, void *block, long size)
{
    MEMORY_DeallocateMemory(who, line, block, size);
}

void * GROUP_AG_JMPTBL_STRUCT_AllocWithOwner(void *owner, long size)
{
    return STRUCT_AllocWithOwner(owner, size);
}

void GROUP_AG_JMPTBL_TEXTDISP_ResetSelectionAndRefresh(void)
{
    TEXTDISP_ResetSelectionAndRefresh();
}

void GROUP_AG_JMPTBL_IOSTDREQ_CleanupSignalAndMsgport(struct MsgPort *port)
{
    IOSTDREQ_CleanupSignalAndMsgport(port);
}

void GROUP_AG_JMPTBL_ESQFUNC_ServiceUiTickIfRunning(void)
{
    ESQFUNC_ServiceUiTickIfRunning();
}

void GROUP_AG_JMPTBL_STRUCT_FreeWithSizeField(void *block)
{
    STRUCT_FreeWithSizeField(block);
}

long GROUP_AG_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(char *s)
{
    return PARSE_ReadSignedLongSkipClass3_Alt(s);
}

long GROUP_AG_JMPTBL_SCRIPT_BeginBannerCharTransition(short target, unsigned short rate)
{
    return SCRIPT_BeginBannerCharTransition(target, rate);
}

void GROUP_AG_JMPTBL_LADFUNC2_EmitEscapedStringToScratch(char *s)
{
    LADFUNC2_EmitEscapedStringToScratch(s);
}

void * GROUP_AG_JMPTBL_MEMORY_AllocateMemory(char *who, long line, long size, long requirements)
{
    return MEMORY_AllocateMemory(who, line, size, requirements);
}

long GROUP_AG_JMPTBL_DOS_OpenFileWithMode(char *path, long mode)
{
    return DOS_OpenFileWithMode(path, mode);
}

long GROUP_AG_JMPTBL_SCRIPT_CheckPathExists(char *path)
{
    return SCRIPT_CheckPathExists(path);
}

unsigned long __asm GROUP_AG_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}

void GROUP_AG_JMPTBL_ESQFUNC_UpdateRefreshModeState(long unused, long request)
{
    ESQFUNC_UpdateRefreshModeState(unused, request);
}

char * GROUP_AG_JMPTBL_STRING_CopyPadNul(char *dst, char *src, long n)
{
    return STRING_CopyPadNul(dst, src, n);
}
