/* RESTORES: (jump table -- 8 forwarding thunks)
 * MODULE:   modules/groups/a/p/esqshared_p3.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern short DST_BuildBannerTimeWord(short a, unsigned char b);
extern void ESQ_ReverseBitsIn6Bytes(unsigned char *dst, unsigned char *src);
extern void ESQ_SetBit1Based(unsigned char *base, long bit);
extern void ESQ_AdjustBracketedHourInString(char *s, long delta);
extern void COI_EnsureAnimObjectAllocated(struct CoiEntry *entry);
extern long ESQ_WildcardMatch(char *text, char *pattern);
extern char * STR_SkipClass3Chars(char *s);
extern long ESQ_TestBit1Based(unsigned char *base, long bit);

short ESQSHARED_JMPTBL_DST_BuildBannerTimeWord(short a, unsigned char b)
{
    return DST_BuildBannerTimeWord(a, b);
}

void ESQSHARED_JMPTBL_ESQ_ReverseBitsIn6Bytes(unsigned char *dst, unsigned char *src)
{
    ESQ_ReverseBitsIn6Bytes(dst, src);
}

void ESQSHARED_JMPTBL_ESQ_SetBit1Based(unsigned char *base, long bit)
{
    ESQ_SetBit1Based(base, bit);
}

void ESQSHARED_JMPTBL_ESQ_AdjustBracketedHourInString(char *s, long delta)
{
    ESQ_AdjustBracketedHourInString(s, delta);
}

void ESQSHARED_JMPTBL_COI_EnsureAnimObjectAllocated(struct CoiEntry *entry)
{
    COI_EnsureAnimObjectAllocated(entry);
}

long ESQSHARED_JMPTBL_ESQ_WildcardMatch(char *text, char *pattern)
{
    return ESQ_WildcardMatch(text, pattern);
}

char * ESQSHARED_JMPTBL_STR_SkipClass3Chars(char *s)
{
    return STR_SkipClass3Chars(s);
}

long ESQSHARED_JMPTBL_ESQ_TestBit1Based(unsigned char *base, long bit)
{
    return ESQ_TestBit1Based(base, bit);
}
