/* RESTORES: (jump table -- 10 forwarding thunks)
 * MODULE:   modules/groups/a/e/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include <stdarg.h>

extern long TLIBA_FindFirstWildcardMatchIndex(char *pattern);
extern short SCRIPT_BuildTokenIndexMap(char *src, short *map, short mapCount,
                                char *tokens, short srcLimit,
                                char terminator, short fillMissing);
extern void * ESQDISP_GetEntryAuxPointerByMode(long index, long mode);
extern void * ESQDISP_GetEntryPointerByMode(long index, long mode);
extern long LADFUNC_ParseHexDigit(char c);
extern void SCRIPT_DeallocateBufferArray(void **arr, short size, short count);
extern long WDISP_VSPrintf(char *buf, char *fmt, void *args);
extern void SCRIPT_AllocateBufferArray(void **arr, short size, short count);
extern long TEXTDISP_ComputeTimeOffset(short row, unsigned char *entry, short mode);
extern char * ESQPARS_ReplaceOwnedString(char *newstr, char *old);

long GROUP_AE_JMPTBL_TLIBA_FindFirstWildcardMatchIndex(char *pattern)
{
    return TLIBA_FindFirstWildcardMatchIndex(pattern);
}

short GROUP_AE_JMPTBL_SCRIPT_BuildTokenIndexMap(char *src, short *map, short mapCount,
                                char *tokens, short srcLimit,
                                char terminator, short fillMissing)
{
    return SCRIPT_BuildTokenIndexMap(src, map, mapCount, tokens, srcLimit, terminator, fillMissing);
}

void * GROUP_AE_JMPTBL_ESQDISP_GetEntryAuxPointerByMode(long index, long mode)
{
    return ESQDISP_GetEntryAuxPointerByMode(index, mode);
}

void * GROUP_AE_JMPTBL_ESQDISP_GetEntryPointerByMode(long index, long mode)
{
    return ESQDISP_GetEntryPointerByMode(index, mode);
}

long GROUP_AE_JMPTBL_LADFUNC_ParseHexDigit(char c)
{
    return LADFUNC_ParseHexDigit(c);
}

void GROUP_AE_JMPTBL_SCRIPT_DeallocateBufferArray(void **arr, short size, short count)
{
    SCRIPT_DeallocateBufferArray(arr, size, count);
}

long GROUP_AE_JMPTBL_WDISP_SPrintf(char *buf, char *fmt, ...)
{
    va_list ap;
    long n;

    va_start(ap, fmt);
    n = WDISP_VSPrintf(buf, fmt, (void *)ap);
    va_end(ap);

    return n;
}

void GROUP_AE_JMPTBL_SCRIPT_AllocateBufferArray(void **arr, short size, short count)
{
    SCRIPT_AllocateBufferArray(arr, size, count);
}

long GROUP_AE_JMPTBL_TEXTDISP_ComputeTimeOffset(short row, unsigned char *entry, short mode)
{
    return TEXTDISP_ComputeTimeOffset(row, entry, mode);
}

char * GROUP_AE_JMPTBL_ESQPARS_ReplaceOwnedString(char *newstr, char *old)
{
    return ESQPARS_ReplaceOwnedString(newstr, old);
}
