/* RESTORES: (jump table -- 12 forwarding thunks)
 * MODULE:   modules/groups/a/k/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void SCRIPT_UpdateSerialShadowFromCtrlByte(unsigned char b);
extern void TLIBA3_SelectNextViewMode(void);
extern long PARSEINI_ParseIniBufferAndDispatch(char *path);
extern void TEXTDISP_FormatEntryTimeForIndex(char *out, short row,
                                      struct EntryTimeCtx *ctx);
extern long GCOMMAND_GetBannerChar(void);
extern void ESQPARS_ApplyRtcBytesAndPersist(char *rtc);
extern long PARSEINI_WriteErrorLogEntry(void);
extern void PARSEINI_ScanLogoDirectory(void);
extern void SCRIPT_DeassertCtrlLineNow(void);
extern void ESQ_SetCopperEffect_Default(void);
extern void ESQ_SetCopperEffect_Custom(void);
extern void CLEANUP_RenderAlignedStatusScreen(short mode, short effectCode,
                                       short suppressFlag);

void GROUP_AK_JMPTBL_SCRIPT_UpdateSerialShadowFromCtrlByte(unsigned char b)
{
    SCRIPT_UpdateSerialShadowFromCtrlByte(b);
}

void GROUP_AK_JMPTBL_TLIBA3_SelectNextViewMode(void)
{
    TLIBA3_SelectNextViewMode();
}

long GROUP_AK_JMPTBL_PARSEINI_ParseIniBufferAndDispatch(char *path)
{
    return PARSEINI_ParseIniBufferAndDispatch(path);
}

void GROUP_AK_JMPTBL_TEXTDISP_FormatEntryTimeForIndex(char *out, short row,
                                      struct EntryTimeCtx *ctx)
{
    TEXTDISP_FormatEntryTimeForIndex(out, row, ctx);
}

long GROUP_AK_JMPTBL_GCOMMAND_GetBannerChar(void)
{
    return GCOMMAND_GetBannerChar();
}

void GROUP_AK_JMPTBL_ESQPARS_ApplyRtcBytesAndPersist(char *rtc)
{
    ESQPARS_ApplyRtcBytesAndPersist(rtc);
}

long GROUP_AK_JMPTBL_PARSEINI_WriteErrorLogEntry(void)
{
    return PARSEINI_WriteErrorLogEntry();
}

void GROUP_AK_JMPTBL_PARSEINI_ScanLogoDirectory(void)
{
    PARSEINI_ScanLogoDirectory();
}

void GROUP_AK_JMPTBL_SCRIPT_DeassertCtrlLineNow(void)
{
    SCRIPT_DeassertCtrlLineNow();
}

void GROUP_AK_JMPTBL_ESQ_SetCopperEffect_Default(void)
{
    ESQ_SetCopperEffect_Default();
}

void GROUP_AK_JMPTBL_ESQ_SetCopperEffect_Custom(void)
{
    ESQ_SetCopperEffect_Custom();
}

void GROUP_AK_JMPTBL_CLEANUP_RenderAlignedStatusScreen(short mode, short effectCode,
                                       short suppressFlag)
{
    CLEANUP_RenderAlignedStatusScreen(mode, effectCode, suppressFlag);
}
