/* RESTORES: (jump table -- 7 forwarding thunks)
 * MODULE:   modules/groups/a/i/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void NEWGRID_SetSelectionMarkers(long primary, long secondary,
                                 char *p1, char *p2, char *s1, char *s2);
extern char * STR_FindCharPtr(char *s, long ch);
extern void TLIBA1_DrawTextWithInsetSegments(struct RastPort *rp, long x, long y,
                                      unsigned char secondary,
                                      unsigned char primary, char *text);
extern long FORMAT_FormatToBuffer2(char *buf, char *fmt, void *args);
extern char * STR_SkipClass3Chars(char *s);
extern char * STRING_AppendAtNull(char *dst, char *src);
extern char * STR_CopyUntilAnyDelimN(char *src, char *dst, long n, char *delims);

void GROUP_AI_JMPTBL_NEWGRID_SetSelectionMarkers(long primary, long secondary,
                                 char *p1, char *p2, char *s1, char *s2)
{
    NEWGRID_SetSelectionMarkers(primary, secondary, p1, p2, s1, s2);
}

char * GROUP_AI_JMPTBL_STR_FindCharPtr(char *s, long ch)
{
    return STR_FindCharPtr(s, ch);
}

void GROUP_AI_JMPTBL_TLIBA1_DrawTextWithInsetSegments(struct RastPort *rp, long x, long y,
                                      unsigned char secondary,
                                      unsigned char primary, char *text)
{
    TLIBA1_DrawTextWithInsetSegments(rp, x, y, secondary, primary, text);
}

long GROUP_AI_JMPTBL_FORMAT_FormatToBuffer2(char *buf, char *fmt, void *args)
{
    return FORMAT_FormatToBuffer2(buf, fmt, args);
}

char * GROUP_AI_JMPTBL_STR_SkipClass3Chars(char *s)
{
    return STR_SkipClass3Chars(s);
}

char * GROUP_AI_JMPTBL_STRING_AppendAtNull(char *dst, char *src)
{
    return STRING_AppendAtNull(dst, src);
}

char * GROUP_AI_JMPTBL_STR_CopyUntilAnyDelimN(char *src, char *dst, long n, char *delims)
{
    return STR_CopyUntilAnyDelimN(src, dst, n, delims);
}
