/* RESTORES: (jump table -- 5 forwarding thunks)
 * MODULE:   modules/groups/b/a/script_p1_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include "esq-dos.h"

extern void MEMORY_DeallocateMemory(char *who, long line, void *block, long size);
extern long DISKIO_WriteBufferedBytes(BPTR fh, char *src, long len);
extern void DISKIO_CloseBufferedFileAndFlush(BPTR fh);
extern void * MEMORY_AllocateMemory(char *who, long line, long size, long requirements);
extern BPTR DISKIO_OpenFileWithBuffer(char *path, long mode);

void SCRIPT_JMPTBL_MEMORY_DeallocateMemory(char *who, long line, void *block, long size)
{
    MEMORY_DeallocateMemory(who, line, block, size);
}

long SCRIPT_JMPTBL_DISKIO_WriteBufferedBytes(BPTR fh, char *src, long len)
{
    return DISKIO_WriteBufferedBytes(fh, src, len);
}

void SCRIPT_JMPTBL_DISKIO_CloseBufferedFileAndFlush(BPTR fh)
{
    DISKIO_CloseBufferedFileAndFlush(fh);
}

void * SCRIPT_JMPTBL_MEMORY_AllocateMemory(char *who, long line, long size, long requirements)
{
    return MEMORY_AllocateMemory(who, line, size, requirements);
}

BPTR SCRIPT_JMPTBL_DISKIO_OpenFileWithBuffer(char *path, long mode)
{
    return DISKIO_OpenFileWithBuffer(path, mode);
}
