/* RESTORES: (jump table -- 16 forwarding thunks)
 * MODULE:   modules/groups/b/a/script3b_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void LOCAVAIL_UpdateFilterStateMachine(struct LocavailCtx *ctx,
                                       struct LocavailState *st);
extern long __asm MATH_DivS32(register __d0 long a, register __d1 long b);
extern void ESQSHARED_ApplyProgramTitleTextFilters(char *s, long flag);
extern long STRING_CompareN(char *a, char *b, long n);
extern void ESQDISP_UpdateStatusMaskAndRefresh(long bits, long set);
extern long GCOMMAND_GetBannerChar(void);
extern long LADFUNC_ParseHexDigit(char c);
extern void ESQPARS_ApplyRtcBytesAndPersist(char *rtc);
extern long PARSE_ReadSignedLongSkipClass3_Alt(char *s);
extern void GCOMMAND_AdjustBannerCopperOffset(char delta);
extern void ESQ_SetCopperEffect_Custom(void);
extern void CLEANUP_RenderAlignedStatusScreen(short mode, short effectCode,
                                       short suppressFlag);
extern void LOCAVAIL_ComputeFilterOffsetForEntry(char *token, struct FilterCtx *ctx);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);
extern void LOCAVAIL_SetFilterModeAndResetState(long mode);
extern char * STRING_CopyPadNul(char *dst, char *src, long n);

void SCRIPT3_JMPTBL_LOCAVAIL_UpdateFilterStateMachine(struct LocavailCtx *ctx,
                                       struct LocavailState *st)
{
    LOCAVAIL_UpdateFilterStateMachine(ctx, st);
}

long __asm SCRIPT3_JMPTBL_MATH_DivS32(register __d0 long a, register __d1 long b)
{
    return MATH_DivS32(a, b);
}

void SCRIPT3_JMPTBL_ESQSHARED_ApplyProgramTitleTextFilters(char *s, long flag)
{
    ESQSHARED_ApplyProgramTitleTextFilters(s, flag);
}

long SCRIPT3_JMPTBL_STRING_CompareN(char *a, char *b, long n)
{
    return STRING_CompareN(a, b, n);
}

void SCRIPT3_JMPTBL_ESQDISP_UpdateStatusMaskAndRefresh(long bits, long set)
{
    ESQDISP_UpdateStatusMaskAndRefresh(bits, set);
}

long SCRIPT3_JMPTBL_GCOMMAND_GetBannerChar(void)
{
    return GCOMMAND_GetBannerChar();
}

long SCRIPT3_JMPTBL_LADFUNC_ParseHexDigit(char c)
{
    return LADFUNC_ParseHexDigit(c);
}

void SCRIPT3_JMPTBL_ESQPARS_ApplyRtcBytesAndPersist(char *rtc)
{
    ESQPARS_ApplyRtcBytesAndPersist(rtc);
}

long SCRIPT3_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(char *s)
{
    return PARSE_ReadSignedLongSkipClass3_Alt(s);
}

void SCRIPT3_JMPTBL_GCOMMAND_AdjustBannerCopperOffset(char delta)
{
    GCOMMAND_AdjustBannerCopperOffset(delta);
}

void SCRIPT3_JMPTBL_ESQ_SetCopperEffect_Custom(void)
{
    ESQ_SetCopperEffect_Custom();
}

void SCRIPT3_JMPTBL_CLEANUP_RenderAlignedStatusScreen(short mode, short effectCode,
                                       short suppressFlag)
{
    CLEANUP_RenderAlignedStatusScreen(mode, effectCode, suppressFlag);
}

void SCRIPT3_JMPTBL_LOCAVAIL_ComputeFilterOffsetForEntry(char *token, struct FilterCtx *ctx)
{
    LOCAVAIL_ComputeFilterOffsetForEntry(token, ctx);
}

unsigned long __asm SCRIPT3_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}

void SCRIPT3_JMPTBL_LOCAVAIL_SetFilterModeAndResetState(long mode)
{
    LOCAVAIL_SetFilterModeAndResetState(mode);
}

char * SCRIPT3_JMPTBL_STRING_CopyPadNul(char *dst, char *src, long n)
{
    return STRING_CopyPadNul(dst, src, n);
}
