/* RESTORES: (jump table -- 14 forwarding thunks)
 * MODULE:   modules/groups/b/a/newgrid_p4_p1_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern long __asm MATH_DivS32(register __d0 long a, register __d1 long b);
extern struct EsqDateTime * DATETIME_SecondsToStruct(long secs, struct EsqDateTime *dt);
extern void GENERATE_GRID_DATE_STRING(char *dst);
extern void MEMORY_DeallocateMemory(char *who, long line, void *block, long size);
extern void CLEANUP_DrawClockFormatList(long startIndex);
extern void DISPTEXT_FreeBuffers(void);
extern void CLEANUP_DrawClockBanner(void);
extern void * MEMORY_AllocateMemory(char *who, long line, long size, long requirements);
extern void DISPTEXT_InitBuffers(void);
extern void CLEANUP_DrawClockFormatFrame(void);
extern long DATETIME_NormalizeStructToSeconds(struct EsqDateTime *dt);
extern char * STR_CopyUntilAnyDelimN(char *src, char *dst, long n, char *delims);
extern long WDISP_UpdateSelectionPreviewPanel(struct PreviewCtx *ctx,
                                       struct GridPanel *panel);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);

long __asm NEWGRID_JMPTBL_MATH_DivS32(register __d0 long a, register __d1 long b)
{
    return MATH_DivS32(a, b);
}

struct EsqDateTime * NEWGRID_JMPTBL_DATETIME_SecondsToStruct(long secs, struct EsqDateTime *dt)
{
    return DATETIME_SecondsToStruct(secs, dt);
}

void NEWGRID_JMPTBL_GENERATE_GRID_DATE_STRING(char *dst)
{
    GENERATE_GRID_DATE_STRING(dst);
}

void NEWGRID_JMPTBL_MEMORY_DeallocateMemory(char *who, long line, void *block, long size)
{
    MEMORY_DeallocateMemory(who, line, block, size);
}

void NEWGRID_JMPTBL_CLEANUP_DrawClockFormatList(long startIndex)
{
    CLEANUP_DrawClockFormatList(startIndex);
}

void NEWGRID_JMPTBL_DISPTEXT_FreeBuffers(void)
{
    DISPTEXT_FreeBuffers();
}

void NEWGRID_JMPTBL_CLEANUP_DrawClockBanner(void)
{
    CLEANUP_DrawClockBanner();
}

void * NEWGRID_JMPTBL_MEMORY_AllocateMemory(char *who, long line, long size, long requirements)
{
    return MEMORY_AllocateMemory(who, line, size, requirements);
}

void NEWGRID_JMPTBL_DISPTEXT_InitBuffers(void)
{
    DISPTEXT_InitBuffers();
}

void NEWGRID_JMPTBL_CLEANUP_DrawClockFormatFrame(void)
{
    CLEANUP_DrawClockFormatFrame();
}

long NEWGRID_JMPTBL_DATETIME_NormalizeStructToSeconds(struct EsqDateTime *dt)
{
    return DATETIME_NormalizeStructToSeconds(dt);
}

char * NEWGRID_JMPTBL_STR_CopyUntilAnyDelimN(char *src, char *dst, long n, char *delims)
{
    return STR_CopyUntilAnyDelimN(src, dst, n, delims);
}

long NEWGRID_JMPTBL_WDISP_UpdateSelectionPreviewPanel(struct PreviewCtx *ctx,
                                       struct GridPanel *panel)
{
    return WDISP_UpdateSelectionPreviewPanel(ctx, panel);
}

unsigned long __asm NEWGRID_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}
