/* RESTORES: (jump table -- 29 forwarding thunks)
 * MODULE:   modules/groups/a/o/esqpars_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void DISKIO2_FlushDataFilesIfNeeded(void);
extern void NEWGRID_RebuildIndexCache(void);
extern long DATETIME_SavePairToFile(struct DateTimePair *p);
extern void ESQPROTO_VerifyChecksumAndParseList(long cmd);
extern long P_TYPE_ParseAndStoreTypeRecord(char *text);
extern void ESQPROTO_CopyLabelToGlobal(char *src);
extern void DST_HandleBannerCommand32_33(char cmd, char *text);
extern void ESQ_SeedMinuteEventThresholds(short base, short offset);
extern void PARSEINI_HandleFontCommand(char *cmd);
extern void TEXTDISP_ApplySourceConfigAllEntries(void);
extern long BRUSH_PlaneMaskForIndex(long index);
extern void SCRIPT_ResetCtrlContextAndClearStatusLine(void);
extern void PARSEINI_WriteRtcFromGlobals(void);
extern long LOCAVAIL_SaveAvailabilityDataFile(struct AvailCtx *primary,
                                       struct AvailCtx *secondary);
extern void DISPLIB_DisplayTextAtPosition(struct RastPort *rp, long x, long y, char *s);
extern long LADFUNC_SaveTextAdsToFile(void);
extern long PARSE_ReadSignedLongSkipClass3_Alt(char *s);
extern long DISKIO2_HandleInteractiveFileTransfer(char mode);
extern void P_TYPE_WritePromoIdDataFile(void);
extern void COI_FreeEntryResources(struct CoiEntry *entry);
extern long DST_UpdateBannerQueue(struct DstBannerPair *pair);
extern void ESQPROTO_VerifyChecksumAndParseRecord(long cmd);
extern void ESQPROTO_ParseDigitLabelAndDisplay(char *src);
extern void DISKIO_ParseConfigBuffer(char *buf, long len);
extern long CLEANUP_ParseAlignedListingBlock(char *block);
extern long SCRIPT_ReadNextRbfByte(void);
extern long ESQ_GenerateXorChecksumByte(long seed, unsigned char *data, long count);
extern void DST_RefreshBannerBuffer(void);
extern long DISKIO_SaveConfigToFileHandle(void);

void ESQPARS_JMPTBL_DISKIO2_FlushDataFilesIfNeeded(void)
{
    DISKIO2_FlushDataFilesIfNeeded();
}

void ESQPARS_JMPTBL_NEWGRID_RebuildIndexCache(void)
{
    NEWGRID_RebuildIndexCache();
}

long ESQPARS_JMPTBL_DATETIME_SavePairToFile(struct DateTimePair *p)
{
    return DATETIME_SavePairToFile(p);
}

void ESQPARS_JMPTBL_ESQPROTO_VerifyChecksumAndParseList(long cmd)
{
    ESQPROTO_VerifyChecksumAndParseList(cmd);
}

long ESQPARS_JMPTBL_P_TYPE_ParseAndStoreTypeRecord(char *text)
{
    return P_TYPE_ParseAndStoreTypeRecord(text);
}

void ESQPARS_JMPTBL_ESQPROTO_CopyLabelToGlobal(char *src)
{
    ESQPROTO_CopyLabelToGlobal(src);
}

void ESQPARS_JMPTBL_DST_HandleBannerCommand32_33(char cmd, char *text)
{
    DST_HandleBannerCommand32_33(cmd, text);
}

void ESQPARS_JMPTBL_ESQ_SeedMinuteEventThresholds(short base, short offset)
{
    ESQ_SeedMinuteEventThresholds(base, offset);
}

void ESQPARS_JMPTBL_PARSEINI_HandleFontCommand(char *cmd)
{
    PARSEINI_HandleFontCommand(cmd);
}

void ESQPARS_JMPTBL_TEXTDISP_ApplySourceConfigAllEntries(void)
{
    TEXTDISP_ApplySourceConfigAllEntries();
}

long ESQPARS_JMPTBL_BRUSH_PlaneMaskForIndex(long index)
{
    return BRUSH_PlaneMaskForIndex(index);
}

void ESQPARS_JMPTBL_SCRIPT_ResetCtrlContextAndClearStatusLine(void)
{
    SCRIPT_ResetCtrlContextAndClearStatusLine();
}

void ESQPARS_JMPTBL_PARSEINI_WriteRtcFromGlobals(void)
{
    PARSEINI_WriteRtcFromGlobals();
}

long ESQPARS_JMPTBL_LOCAVAIL_SaveAvailabilityDataFile(struct AvailCtx *primary,
                                       struct AvailCtx *secondary)
{
    return LOCAVAIL_SaveAvailabilityDataFile(primary, secondary);
}

void ESQPARS_JMPTBL_DISPLIB_DisplayTextAtPosition(struct RastPort *rp, long x, long y, char *s)
{
    DISPLIB_DisplayTextAtPosition(rp, x, y, s);
}

long ESQPARS_JMPTBL_LADFUNC_SaveTextAdsToFile(void)
{
    return LADFUNC_SaveTextAdsToFile();
}

long ESQPARS_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(char *s)
{
    return PARSE_ReadSignedLongSkipClass3_Alt(s);
}

long ESQPARS_JMPTBL_DISKIO2_HandleInteractiveFileTransfer(char mode)
{
    return DISKIO2_HandleInteractiveFileTransfer(mode);
}

void ESQPARS_JMPTBL_P_TYPE_WritePromoIdDataFile(void)
{
    P_TYPE_WritePromoIdDataFile();
}

void ESQPARS_JMPTBL_COI_FreeEntryResources(struct CoiEntry *entry)
{
    COI_FreeEntryResources(entry);
}

long ESQPARS_JMPTBL_DST_UpdateBannerQueue(struct DstBannerPair *pair)
{
    return DST_UpdateBannerQueue(pair);
}

void ESQPARS_JMPTBL_ESQPROTO_VerifyChecksumAndParseRecord(long cmd)
{
    ESQPROTO_VerifyChecksumAndParseRecord(cmd);
}

void ESQPARS_JMPTBL_ESQPROTO_ParseDigitLabelAndDisplay(char *src)
{
    ESQPROTO_ParseDigitLabelAndDisplay(src);
}

void ESQPARS_JMPTBL_DISKIO_ParseConfigBuffer(char *buf, long len)
{
    DISKIO_ParseConfigBuffer(buf, len);
}

long ESQPARS_JMPTBL_CLEANUP_ParseAlignedListingBlock(char *block)
{
    return CLEANUP_ParseAlignedListingBlock(block);
}

long ESQPARS_JMPTBL_SCRIPT_ReadSerialRbfByte(void)
{
    return SCRIPT_ReadNextRbfByte();
}

long ESQPARS_JMPTBL_ESQ_GenerateXorChecksumByte(long seed, unsigned char *data, long count)
{
    return ESQ_GenerateXorChecksumByte(seed, data, count);
}

void ESQPARS_JMPTBL_DST_RefreshBannerBuffer(void)
{
    DST_RefreshBannerBuffer();
}

long ESQPARS_JMPTBL_DISKIO_SaveConfigToFileHandle(void)
{
    return DISKIO_SaveConfigToFileHandle();
}
