/* RESTORES: (jump table -- 4 forwarding thunks)
 * MODULE:   modules/groups/b/a/textdisp2_p0_p0_p1_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern long LOCAVAIL_GetFilterWindowHalfSpan(void);
extern void LADFUNC_DrawEntryPreview(long index);
extern void ESQIFF_RunPendingCopperAnimations(void);
extern void ESQIFF_PlayNextExternalAssetFrame(short mode);

long TEXTDISP2_JMPTBL_LOCAVAIL_GetFilterWindowHalfSpan(void)
{
    return LOCAVAIL_GetFilterWindowHalfSpan();
}

void TEXTDISP2_JMPTBL_LADFUNC_DrawEntryPreview(long index)
{
    LADFUNC_DrawEntryPreview(index);
}

void TEXTDISP2_JMPTBL_ESQIFF_RunPendingCopperAnimations(void)
{
    ESQIFF_RunPendingCopperAnimations();
}

void TEXTDISP2_JMPTBL_ESQIFF_PlayNextExternalAssetFrame(short mode)
{
    ESQIFF_PlayNextExternalAssetFrame(mode);
}
