/* RESTORES: (jump table -- 2 forwarding thunks)
 * MODULE:   modules/groups/a/s/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern char * STR_FindCharPtr(char *s, long ch);
extern char * ESQ_FindSubstringCaseFold(char *hay, char *needle);

char * GROUP_AS_JMPTBL_STR_FindCharPtr(char *s, long ch)
{
    return STR_FindCharPtr(s, ch);
}

char * GROUP_AS_JMPTBL_ESQ_FindSubstringCaseFold(char *hay, char *needle)
{
    return ESQ_FindSubstringCaseFold(hay, needle);
}
