/* RESTORES: (jump table -- 4 forwarding thunks)
 * MODULE:   modules/groups/_main/b/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void DOS_Delay(long ticks);
extern long STREAM_BufferedWriteString(char *text);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);
extern void BUFFER_FlushAllAndCloseWithCode(long code);

void GROUP_MAIN_B_JMPTBL_DOS_Delay(long ticks)
{
    DOS_Delay(ticks);
}

long GROUP_MAIN_B_JMPTBL_STREAM_BufferedWriteString(char *text)
{
    return STREAM_BufferedWriteString(text);
}

unsigned long __asm GROUP_MAIN_B_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}

void GROUP_MAIN_B_JMPTBL_BUFFER_FlushAllAndCloseWithCode(long code)
{
    BUFFER_FlushAllAndCloseWithCode(code);
}
