/* RESTORES: (jump table -- 9 forwarding thunks)
 * MODULE:   modules/groups/a/w/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include <stdarg.h>

extern struct VmRuntime * TLIBA3_BuildDisplayContextForViewMode(long mode, long unused,
                                                        short highlight);
extern void DISPLIB_ApplyInlineAlignmentPadding(char *buf, char mode);
extern void ESQIFF_RunCopperRiseTransition(void);
extern void ESQIFF_RunCopperDropTransition(void);
extern void DISPLIB_DisplayTextAtPosition(struct RastPort *rp, long x, long y, char *s);
extern void MEM_Move(char *src, char *dst, long n);
extern long WDISP_VSPrintf(char *buf, char *fmt, void *args);
extern void ESQ_SetCopperEffect_OffDisableHighlight(void);
extern char * STRING_CopyPadNul(char *dst, char *src, long n);

struct VmRuntime * GROUP_AW_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(long mode, long unused,
                                                        short highlight)
{
    return TLIBA3_BuildDisplayContextForViewMode(mode, unused, highlight);
}

void GROUP_AW_JMPTBL_DISPLIB_ApplyInlineAlignmentPadding(char *buf, char mode)
{
    DISPLIB_ApplyInlineAlignmentPadding(buf, mode);
}

void GROUP_AW_JMPTBL_ESQIFF_RunCopperRiseTransition(void)
{
    ESQIFF_RunCopperRiseTransition();
}

void GROUP_AW_JMPTBL_ESQIFF_RunCopperDropTransition(void)
{
    ESQIFF_RunCopperDropTransition();
}

void GROUP_AW_JMPTBL_DISPLIB_DisplayTextAtPosition(struct RastPort *rp, long x, long y, char *s)
{
    DISPLIB_DisplayTextAtPosition(rp, x, y, s);
}

void GROUP_AW_JMPTBL_MEM_Move(char *src, char *dst, long n)
{
    MEM_Move(src, dst, n);
}

long GROUP_AW_JMPTBL_WDISP_SPrintf(char *buf, char *fmt, ...)
{
    va_list ap;
    long n;

    va_start(ap, fmt);
    n = WDISP_VSPrintf(buf, fmt, (void *)ap);
    va_end(ap);

    return n;
}

void GROUP_AW_JMPTBL_ESQ_SetCopperEffect_OffDisableHighlight(void)
{
    ESQ_SetCopperEffect_OffDisableHighlight();
}

char * GROUP_AW_JMPTBL_STRING_CopyPadNul(char *dst, char *src, long n)
{
    return STRING_CopyPadNul(dst, src, n);
}
