/* RESTORES: (jump table -- 4 forwarding thunks)
 * MODULE:   modules/groups/a/k/xjump2.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void ESQ_SetCopperEffect_AllOn(void);
extern void SCRIPT_AssertCtrlLineNow(void);
extern void TLIBA3_DrawViewModeGuides(struct RastPort *rp);
extern void GCOMMAND_CopyGfxToWorkIfAvailable(void);

void GROUP_AK_JMPTBL_ESQ_SetCopperEffect_AllOn(void)
{
    ESQ_SetCopperEffect_AllOn();
}

void GROUP_AK_JMPTBL_SCRIPT_AssertCtrlLineNow(void)
{
    SCRIPT_AssertCtrlLineNow();
}

void GROUP_AK_JMPTBL_TLIBA3_DrawViewModeGuides(struct RastPort *rp)
{
    TLIBA3_DrawViewModeGuides(rp);
}

void GROUP_AK_JMPTBL_GCOMMAND_CopyGfxToWorkIfAvailable(void)
{
    GCOMMAND_CopyGfxToWorkIfAvailable();
}
