/* RESTORES: (jump table -- 27 forwarding thunks)
 * MODULE:   modules/groups/a/n/esqfunc_p4_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void TEXTDISP_SetRastForMode(short mode);
extern void P_TYPE_PromoteSecondaryList(void);
extern void DISKIO_ProbeDrivesAndAssignPaths(void);
extern long PARSEINI_UpdateCtrlHDeltaMax(void);
extern void ESQ_ClampBannerCharRange(short start, short first, short second);
extern long SCRIPT_ReadHandshakeBit3Flag(void);
extern void TLIBA3_DrawCenteredWrappedTextLines(struct RastPort *rp, char *text, long y);
extern int SCRIPT_GetCtrlLineFlag(void);
extern void LOCAVAIL_SyncSecondaryFilterForCurrentGroup(void);
extern void TEXTDISP_ResetSelectionAndRefresh(void);
extern long PARSEINI_MonitorClockChange(void);
extern long LADFUNC_ParseHexDigit(char c);
extern void CLEANUP_ProcessAlerts(void);
extern long ESQ_GetHalfHourSlotIndex(struct ClockSlotRec *c);
extern void CLEANUP_DrawClockBanner(void);
extern long PARSEINI_ComputeHTCMaxValues(void);
extern void LADFUNC_UpdateHighlightState(void);
extern void P_TYPE_EnsureSecondaryList(void);
extern long SCRIPT_ReadHandshakeBit5Mask(void);
extern void PARSEINI_NormalizeClockData(struct ParseIniClockData *dst,
                                 struct ParseIniClockData *src);
extern long ESQ_TickGlobalCounters(void);
extern void SCRIPT_HandleSerialCtrlCmd(void);
extern void ESQ_HandleSerialRbfInterrupt(volatile short *custom, unsigned char *ring);
extern void TEXTDISP_TickDisplayState(void);
extern void ESQ_PollCtrlInput(void);
extern void LOCAVAIL_RebuildFilterStateFromCurrentGroup(void);
extern char * STRING_CopyPadNul(char *dst, char *src, long n);

void ESQFUNC_JMPTBL_TEXTDISP_SetRastForMode(short mode)
{
    TEXTDISP_SetRastForMode(mode);
}

void ESQFUNC_JMPTBL_P_TYPE_PromoteSecondaryList(void)
{
    P_TYPE_PromoteSecondaryList();
}

void ESQFUNC_JMPTBL_DISKIO_ProbeDrivesAndAssignPaths(void)
{
    DISKIO_ProbeDrivesAndAssignPaths();
}

long ESQFUNC_JMPTBL_PARSEINI_UpdateCtrlHDeltaMax(void)
{
    return PARSEINI_UpdateCtrlHDeltaMax();
}

void ESQFUNC_JMPTBL_ESQ_ClampBannerCharRange(short start, short first, short second)
{
    ESQ_ClampBannerCharRange(start, first, second);
}

long ESQFUNC_JMPTBL_SCRIPT_ReadCiaBBit3Flag(void)
{
    return SCRIPT_ReadHandshakeBit3Flag();
}

void ESQFUNC_JMPTBL_TLIBA3_DrawCenteredWrappedTextLines(struct RastPort *rp, char *text, long y)
{
    TLIBA3_DrawCenteredWrappedTextLines(rp, text, y);
}

int ESQFUNC_JMPTBL_SCRIPT_GetCtrlLineFlag(void)
{
    return SCRIPT_GetCtrlLineFlag();
}

void ESQFUNC_JMPTBL_LOCAVAIL_SyncSecondaryFilterForCurrentGroup(void)
{
    LOCAVAIL_SyncSecondaryFilterForCurrentGroup();
}

void ESQFUNC_JMPTBL_TEXTDISP_ResetSelectionAndRefresh(void)
{
    TEXTDISP_ResetSelectionAndRefresh();
}

long ESQFUNC_JMPTBL_PARSEINI_MonitorClockChange(void)
{
    return PARSEINI_MonitorClockChange();
}

long ESQFUNC_JMPTBL_LADFUNC_ParseHexDigit(char c)
{
    return LADFUNC_ParseHexDigit(c);
}

void ESQFUNC_JMPTBL_CLEANUP_ProcessAlerts(void)
{
    CLEANUP_ProcessAlerts();
}

long ESQFUNC_JMPTBL_ESQ_GetHalfHourSlotIndex(struct ClockSlotRec *c)
{
    return ESQ_GetHalfHourSlotIndex(c);
}

void ESQFUNC_JMPTBL_CLEANUP_DrawClockBanner(void)
{
    CLEANUP_DrawClockBanner();
}

long ESQFUNC_JMPTBL_PARSEINI_ComputeHTCMaxValues(void)
{
    return PARSEINI_ComputeHTCMaxValues();
}

void ESQFUNC_JMPTBL_LADFUNC_UpdateHighlightState(void)
{
    LADFUNC_UpdateHighlightState();
}

void ESQFUNC_JMPTBL_P_TYPE_EnsureSecondaryList(void)
{
    P_TYPE_EnsureSecondaryList();
}

long ESQFUNC_JMPTBL_SCRIPT_ReadCiaBBit5Mask(void)
{
    return SCRIPT_ReadHandshakeBit5Mask();
}

void ESQFUNC_JMPTBL_PARSEINI_NormalizeClockData(struct ParseIniClockData *dst,
                                 struct ParseIniClockData *src)
{
    PARSEINI_NormalizeClockData(dst, src);
}

long ESQFUNC_JMPTBL_ESQ_TickGlobalCounters(void)
{
    return ESQ_TickGlobalCounters();
}

void ESQFUNC_JMPTBL_SCRIPT_HandleSerialCtrlCmd(void)
{
    SCRIPT_HandleSerialCtrlCmd();
}

void ESQFUNC_JMPTBL_ESQ_HandleSerialRbfInterrupt(volatile short *custom, unsigned char *ring)
{
    ESQ_HandleSerialRbfInterrupt(custom, ring);
}

void ESQFUNC_JMPTBL_TEXTDISP_TickDisplayState(void)
{
    TEXTDISP_TickDisplayState();
}

void ESQFUNC_JMPTBL_ESQ_PollCtrlInput(void)
{
    ESQ_PollCtrlInput();
}

void ESQFUNC_JMPTBL_LOCAVAIL_RebuildFilterStateFromCurrentGroup(void)
{
    LOCAVAIL_RebuildFilterStateFromCurrentGroup();
}

char * ESQFUNC_JMPTBL_STRING_CopyPadNul(char *dst, char *src, long n)
{
    return STRING_CopyPadNul(dst, src, n);
}
