/* RESTORES: (jump table -- 5 forwarding thunks)
 * MODULE:   modules/groups/a/v/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern struct IOStdReq * ALLOCATE_AllocAndInitializeIOStdReq(struct MsgPort *replyPort);
extern struct MsgPort * SIGNAL_CreateMsgPortWithSignal(char *name, long pri);
extern void DISKIO_ProbeDrivesAndAssignPaths(void);
extern void ESQ_InvokeGcommandInit(void *a, void *b);
extern long EXEC_CallVector_48(struct InputEvent *event, char *buffer, long length,
                        struct KeyMap *keyMap);

struct IOStdReq * GROUP_AV_JMPTBL_ALLOCATE_AllocAndInitializeIOStdReq(struct MsgPort *replyPort)
{
    return ALLOCATE_AllocAndInitializeIOStdReq(replyPort);
}

struct MsgPort * GROUP_AV_JMPTBL_SIGNAL_CreateMsgPortWithSignal(char *name, long pri)
{
    return SIGNAL_CreateMsgPortWithSignal(name, pri);
}

void GROUP_AV_JMPTBL_DISKIO_ProbeDrivesAndAssignPaths(void)
{
    DISKIO_ProbeDrivesAndAssignPaths();
}

void GROUP_AV_JMPTBL_ESQ_InvokeGcommandInit(void *a, void *b)
{
    ESQ_InvokeGcommandInit(a, b);
}

long GROUP_AV_JMPTBL_EXEC_CallVector_48(struct InputEvent *event, char *buffer, long length,
                        struct KeyMap *keyMap)
{
    return EXEC_CallVector_48(event, buffer, length, keyMap);
}
