/* RESTORES: (jump table -- 2 forwarding thunks)
 * MODULE:   modules/groups/a/u/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern struct BrushNode2 * BRUSH_AppendBrushNode(struct BrushNode2 *head, struct BrushNode2 *node);
extern void BRUSH_PopulateBrushList(struct BrushDescriptor *desc,
                             struct BrushListNode **head);

struct BrushNode2 * GROUP_AU_JMPTBL_BRUSH_AppendBrushNode(struct BrushNode2 *head, struct BrushNode2 *node)
{
    return BRUSH_AppendBrushNode(head, node);
}

void GROUP_AU_JMPTBL_BRUSH_PopulateBrushList(struct BrushDescriptor *desc,
                             struct BrushListNode **head)
{
    BRUSH_PopulateBrushList(desc, head);
}
