/* RESTORES: (jump table -- 10 forwarding thunks)
 * MODULE:   modules/groups/a/y/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include "esq-dos.h"

extern char * DISKIO_ConsumeCStringFromWorkBuffer(void);
extern long DISKIO_ParseLongFromWorkBuffer(void);
extern void DISKIO_WriteDecimalField(BPTR fh, long value);
extern long DISKIO_WriteBufferedBytes(BPTR fh, char *src, long len);
extern void DISKIO_CloseBufferedFileAndFlush(BPTR fh);
extern long STRING_CompareNoCaseN(char *a, char *b, long n);
extern unsigned long __asm MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b);
extern long DISKIO_LoadFileToWorkBuffer(char *path);
extern long SCRIPT_ReadHandshakeBit5Mask(void);
extern BPTR DISKIO_OpenFileWithBuffer(char *path, long mode);

char * GROUP_AY_JMPTBL_DISKIO_ConsumeCStringFromWorkBuffer(void)
{
    return DISKIO_ConsumeCStringFromWorkBuffer();
}

long GROUP_AY_JMPTBL_DISKIO_ParseLongFromWorkBuffer(void)
{
    return DISKIO_ParseLongFromWorkBuffer();
}

void GROUP_AY_JMPTBL_DISKIO_WriteDecimalField(BPTR fh, long value)
{
    DISKIO_WriteDecimalField(fh, value);
}

long GROUP_AY_JMPTBL_DISKIO_WriteBufferedBytes(BPTR fh, char *src, long len)
{
    return DISKIO_WriteBufferedBytes(fh, src, len);
}

void GROUP_AY_JMPTBL_DISKIO_CloseBufferedFileAndFlush(BPTR fh)
{
    DISKIO_CloseBufferedFileAndFlush(fh);
}

long GROUP_AY_JMPTBL_STRING_CompareNoCaseN(char *a, char *b, long n)
{
    return STRING_CompareNoCaseN(a, b, n);
}

unsigned long __asm GROUP_AY_JMPTBL_MATH_Mulu32(register __d0 unsigned long a,
                                register __d1 unsigned long b)
{
    return MATH_Mulu32(a, b);
}

long GROUP_AY_JMPTBL_DISKIO_LoadFileToWorkBuffer(char *path)
{
    return DISKIO_LoadFileToWorkBuffer(path);
}

long GROUP_AY_JMPTBL_SCRIPT_ReadCiaBBit5Mask(void)
{
    return SCRIPT_ReadHandshakeBit5Mask();
}

BPTR GROUP_AY_JMPTBL_DISKIO_OpenFileWithBuffer(char *path, long mode)
{
    return DISKIO_OpenFileWithBuffer(path, mode);
}
