/* RESTORES: (jump table -- 18 forwarding thunks)
 * MODULE:   modules/groups/a/h/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void ESQIFF2_ApplyIncomingStatusPacket(char *packet);
extern void NEWGRID_RebuildIndexCache(void);
extern void ESQSHARED_ApplyProgramTitleTextFilters(char *s, long flag);
extern void ESQDISP_UpdateStatusMaskAndRefresh(long bits, long set);
extern void ESQSHARED_InitEntryDefaults(struct EsqSharedEntry *e);
extern void GCOMMAND_LoadPPVTemplate(void);
extern long LOCAVAIL_SaveAvailabilityDataFile(struct AvailCtx *primary,
                                       struct AvailCtx *secondary);
extern void GCOMMAND_LoadCommandFile(void);
extern long ESQ_WildcardMatch(char *text, char *pattern);
extern void P_TYPE_WritePromoIdDataFile(void);
extern void ESQFUNC_WaitForClockChangeAndServiceUi(void);
extern long ESQ_TestBit1Based(unsigned char *base, long bit);
extern void ESQIFF2_ShowAttentionOverlay(char code);
extern char * STR_FindAnyCharPtr(char *s, char *set);
extern void GCOMMAND_LoadMplexFile(void);
extern long SCRIPT_ReadNextRbfByte(void);
extern void ESQPARS_ClearAliasStringPointers(void);
extern long PARSE_ReadSignedLongSkipClass3(char *s);

void GROUP_AH_JMPTBL_ESQIFF2_ApplyIncomingStatusPacket(char *packet)
{
    ESQIFF2_ApplyIncomingStatusPacket(packet);
}

void GROUP_AH_JMPTBL_NEWGRID_RebuildIndexCache(void)
{
    NEWGRID_RebuildIndexCache();
}

void GROUP_AH_JMPTBL_ESQSHARED_ApplyProgramTitleTextFilters(char *s, long flag)
{
    ESQSHARED_ApplyProgramTitleTextFilters(s, flag);
}

void GROUP_AH_JMPTBL_ESQDISP_UpdateStatusMaskAndRefresh(long bits, long set)
{
    ESQDISP_UpdateStatusMaskAndRefresh(bits, set);
}

void GROUP_AH_JMPTBL_ESQSHARED_InitEntryDefaults(struct EsqSharedEntry *e)
{
    ESQSHARED_InitEntryDefaults(e);
}

void GROUP_AH_JMPTBL_GCOMMAND_LoadPPVTemplate(void)
{
    GCOMMAND_LoadPPVTemplate();
}

long GROUP_AH_JMPTBL_LOCAVAIL_SaveAvailabilityDataFile(struct AvailCtx *primary,
                                       struct AvailCtx *secondary)
{
    return LOCAVAIL_SaveAvailabilityDataFile(primary, secondary);
}

void GROUP_AH_JMPTBL_GCOMMAND_LoadCommandFile(void)
{
    GCOMMAND_LoadCommandFile();
}

long GROUP_AH_JMPTBL_ESQ_WildcardMatch(char *text, char *pattern)
{
    return ESQ_WildcardMatch(text, pattern);
}

void GROUP_AH_JMPTBL_P_TYPE_WritePromoIdDataFile(void)
{
    P_TYPE_WritePromoIdDataFile();
}

void GROUP_AH_JMPTBL_ESQFUNC_WaitForClockChangeAndServiceUi(void)
{
    ESQFUNC_WaitForClockChangeAndServiceUi();
}

long GROUP_AH_JMPTBL_ESQ_TestBit1Based(unsigned char *base, long bit)
{
    return ESQ_TestBit1Based(base, bit);
}

void GROUP_AH_JMPTBL_ESQIFF2_ShowAttentionOverlay(char code)
{
    ESQIFF2_ShowAttentionOverlay(code);
}

char * GROUP_AH_JMPTBL_STR_FindAnyCharPtr(char *s, char *set)
{
    return STR_FindAnyCharPtr(s, set);
}

void GROUP_AH_JMPTBL_GCOMMAND_LoadMplexFile(void)
{
    GCOMMAND_LoadMplexFile();
}

long GROUP_AH_JMPTBL_SCRIPT_ReadSerialRbfByte(void)
{
    return SCRIPT_ReadNextRbfByte();
}

void GROUP_AH_JMPTBL_ESQPARS_ClearAliasStringPointers(void)
{
    ESQPARS_ClearAliasStringPointers();
}

long GROUP_AH_JMPTBL_PARSE_ReadSignedLongSkipClass3(char *s)
{
    return PARSE_ReadSignedLongSkipClass3(s);
}
