/* RESTORES: (jump table -- 13 forwarding thunks)
 * MODULE:   modules/groups/a/c/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void PARSEINI_UpdateClockFromRtc(void);
extern void ESQFUNC_DrawDiagnosticsScreen(void);
extern void ESQFUNC_DrawMemoryStatusScreen(void);
extern void SCRIPT_UpdateCtrlStateMachine(void);
extern void GCOMMAND_UpdateBannerBounds(long left, long top, long right, long bottom);
extern void SCRIPT_PollHandshakeAndApplyTimeout(void);
extern void SCRIPT_ClearCtrlLineIfEnabled(void);
extern void ESQFUNC_FreeExtraTitleTextPointers(short from);
extern void ESQDISP_DrawStatusBanner(short highlight);
extern long DST_UpdateBannerQueue(struct DstBannerPair *pair);
extern void DST_RefreshBannerBuffer(void);
extern void ESQFUNC_DrawEscMenuVersion(void);
extern long PARSEINI_AdjustHoursTo24HrFormat(short hour, short meridiem);

void GROUP_AC_JMPTBL_PARSEINI_UpdateClockFromRtc(void)
{
    PARSEINI_UpdateClockFromRtc();
}

void GROUP_AC_JMPTBL_ESQFUNC_DrawDiagnosticsScreen(void)
{
    ESQFUNC_DrawDiagnosticsScreen();
}

void GROUP_AC_JMPTBL_ESQFUNC_DrawMemoryStatusScreen(void)
{
    ESQFUNC_DrawMemoryStatusScreen();
}

void GROUP_AC_JMPTBL_SCRIPT_UpdateCtrlStateMachine(void)
{
    SCRIPT_UpdateCtrlStateMachine();
}

void GROUP_AC_JMPTBL_GCOMMAND_UpdateBannerBounds(long left, long top, long right, long bottom)
{
    GCOMMAND_UpdateBannerBounds(left, top, right, bottom);
}

void GROUP_AC_JMPTBL_SCRIPT_UpdateCtrlLineTimeout(void)
{
    SCRIPT_PollHandshakeAndApplyTimeout();
}

void GROUP_AC_JMPTBL_SCRIPT_ClearCtrlLineIfEnabled(void)
{
    SCRIPT_ClearCtrlLineIfEnabled();
}

void GROUP_AC_JMPTBL_ESQFUNC_FreeExtraTitleTextPointers(short from)
{
    ESQFUNC_FreeExtraTitleTextPointers(from);
}

void GROUP_AC_JMPTBL_ESQDISP_DrawStatusBanner(short highlight)
{
    ESQDISP_DrawStatusBanner(highlight);
}

long GROUP_AC_JMPTBL_DST_UpdateBannerQueue(struct DstBannerPair *pair)
{
    return DST_UpdateBannerQueue(pair);
}

void GROUP_AC_JMPTBL_DST_RefreshBannerBuffer(void)
{
    DST_RefreshBannerBuffer();
}

void GROUP_AC_JMPTBL_ESQFUNC_DrawEscMenuVersion(void)
{
    ESQFUNC_DrawEscMenuVersion();
}

long GROUP_AC_JMPTBL_PARSEINI_AdjustHoursTo24HrFormat(short hour, short meridiem)
{
    return PARSEINI_AdjustHoursTo24HrFormat(hour, meridiem);
}
