/* RESTORES: (jump table -- 12 forwarding thunks)
 * MODULE:   modules/groups/a/k/ed1b_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void NEWGRID_DrawTopBorderLine(void);
extern void LOCAVAIL_ResetFilterCursorState(struct LocAvailFilterCursor *st);
extern void GCOMMAND_ResetHighlightMessages(void);
extern long LADFUNC_SetPackedPenLowNibble(unsigned char packed, unsigned char low);
extern long LADFUNC_SaveTextAdsToFile(void);
extern void ESQ_ColdReboot(void);
extern void ESQSHARED4_LoadDefaultPaletteToCopper_NoOp(void);
extern void GCOMMAND_SeedBannerDefaults(void);
extern void MEM_Move(char *src, char *dst, long n);
extern void GCOMMAND_SeedBannerFromPrefs(void);
extern void CLEANUP_DrawDateTimeBannerRow(void);
extern long LADFUNC_SetPackedPenHighNibble(unsigned char high, unsigned char low);

void ED1_JMPTBL_NEWGRID_DrawTopBorderLine(void)
{
    NEWGRID_DrawTopBorderLine();
}

void ED1_JMPTBL_LOCAVAIL_ResetFilterCursorState(struct LocAvailFilterCursor *st)
{
    LOCAVAIL_ResetFilterCursorState(st);
}

void ED1_JMPTBL_GCOMMAND_ResetHighlightMessages(void)
{
    GCOMMAND_ResetHighlightMessages();
}

long ED1_JMPTBL_LADFUNC_MergeHighLowNibbles(unsigned char packed, unsigned char low)
{
    return LADFUNC_SetPackedPenLowNibble(packed, low);
}

long ED1_JMPTBL_LADFUNC_SaveTextAdsToFile(void)
{
    return LADFUNC_SaveTextAdsToFile();
}

void ED1_JMPTBL_ESQ_ColdReboot(void)
{
    ESQ_ColdReboot();
}

void ED1_JMPTBL_ESQSHARED4_LoadDefaultPaletteToCopper_NoOp(void)
{
    ESQSHARED4_LoadDefaultPaletteToCopper_NoOp();
}

void ED1_JMPTBL_GCOMMAND_SeedBannerDefaults(void)
{
    GCOMMAND_SeedBannerDefaults();
}

void ED1_JMPTBL_MEM_Move(char *src, char *dst, long n)
{
    MEM_Move(src, dst, n);
}

void ED1_JMPTBL_GCOMMAND_SeedBannerFromPrefs(void)
{
    GCOMMAND_SeedBannerFromPrefs();
}

void ED1_JMPTBL_CLEANUP_DrawDateTimeBannerRow(void)
{
    CLEANUP_DrawDateTimeBannerRow();
}

long ED1_JMPTBL_LADFUNC_PackNibblesToByte(unsigned char high, unsigned char low)
{
    return LADFUNC_SetPackedPenHighNibble(high, low);
}
