/* RESTORES: (jump table -- 18 forwarding thunks)
 * MODULE:   modules/groups/a/d/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern struct VmRuntime * TLIBA3_BuildDisplayContextForViewMode(long mode, long unused,
                                                        short highlight);
extern void SCRIPT_UpdateSerialShadowFromCtrlByte(unsigned char b);
extern void DATETIME_NormalizeMonthRange(struct DateTimeRec *d);
extern void TEXTDISP_DrawChannelBanner(short mode, short drawMode);
extern void TEXTDISP_FormatEntryTime(char *out, short row);
extern void ESQIFF_RunCopperRiseTransition(void);
extern void TEXTDISP_BuildEntryShortName(struct TextDispNameEntry *e, char *out);
extern void GRAPHICS_BltBitMapRastPort(struct BitMap *srcBitMap, long xSrc, long ySrc,
                                struct RastPort *destRP, long xDest, long yDest,
                                long xSize, long ySize, unsigned long minterm);
extern void ESQIFF_RunCopperDropTransition(void);
extern short TLIBA1_BuildClockFormatEntryIfVisible(short row, short slot, char *out,
                                            short mode);
extern void TEXTDISP_BuildChannelLabel(short mode);
extern void TEXTDISP_DrawInsetRectFrame(char *text, short mode);
extern void TEXTDISP_TrimTextToPixelWidth(unsigned char *text, long maxWidth);
extern char * TLIBA3_GetViewModeRastPort(long index);
extern long ESQFUNC_SelectAndApplyBrushForCurrentEntry(short mode);
extern long DATETIME_AdjustMonthIndex(struct DateRec *d);
extern long DST_ComputeBannerIndex(struct DstBannerRecord *rec, short a,
                            unsigned char b);
extern long TLIBA3_GetViewModeHeight(long mode);

struct VmRuntime * GROUP_AD_JMPTBL_TLIBA3_BuildDisplayContextForViewMode(long mode, long unused,
                                                        short highlight)
{
    return TLIBA3_BuildDisplayContextForViewMode(mode, unused, highlight);
}

void GROUP_AD_JMPTBL_SCRIPT_UpdateSerialShadowFromCtrlByte(unsigned char b)
{
    SCRIPT_UpdateSerialShadowFromCtrlByte(b);
}

void GROUP_AD_JMPTBL_DATETIME_NormalizeMonthRange(struct DateTimeRec *d)
{
    DATETIME_NormalizeMonthRange(d);
}

void GROUP_AD_JMPTBL_TEXTDISP_DrawChannelBanner(short mode, short drawMode)
{
    TEXTDISP_DrawChannelBanner(mode, drawMode);
}

void GROUP_AD_JMPTBL_TEXTDISP_FormatEntryTime(char *out, short row)
{
    TEXTDISP_FormatEntryTime(out, row);
}

void GROUP_AD_JMPTBL_ESQIFF_RunCopperRiseTransition(void)
{
    ESQIFF_RunCopperRiseTransition();
}

void GROUP_AD_JMPTBL_TEXTDISP_BuildEntryShortName(struct TextDispNameEntry *e, char *out)
{
    TEXTDISP_BuildEntryShortName(e, out);
}

void GROUP_AD_JMPTBL_GRAPHICS_BltBitMapRastPort(struct BitMap *srcBitMap, long xSrc, long ySrc,
                                struct RastPort *destRP, long xDest, long yDest,
                                long xSize, long ySize, unsigned long minterm)
{
    GRAPHICS_BltBitMapRastPort(srcBitMap, xSrc, ySrc, destRP, xDest, yDest, xSize, ySize, minterm);
}

void GROUP_AD_JMPTBL_ESQIFF_RunCopperDropTransition(void)
{
    ESQIFF_RunCopperDropTransition();
}

short GROUP_AD_JMPTBL_TLIBA1_BuildClockFormatEntryIfVisible(short row, short slot, char *out,
                                            short mode)
{
    return TLIBA1_BuildClockFormatEntryIfVisible(row, slot, out, mode);
}

void GROUP_AD_JMPTBL_TEXTDISP_BuildChannelLabel(short mode)
{
    TEXTDISP_BuildChannelLabel(mode);
}

void GROUP_AD_JMPTBL_TEXTDISP_DrawInsetRectFrame(char *text, short mode)
{
    TEXTDISP_DrawInsetRectFrame(text, mode);
}

void GROUP_AD_JMPTBL_TEXTDISP_TrimTextToPixelWidth(unsigned char *text, long maxWidth)
{
    TEXTDISP_TrimTextToPixelWidth(text, maxWidth);
}

char * GROUP_AD_JMPTBL_TLIBA3_GetViewModeRastPort(long index)
{
    return TLIBA3_GetViewModeRastPort(index);
}

long GROUP_AD_JMPTBL_ESQFUNC_SelectAndApplyBrushForCurrentEntry(short mode)
{
    return ESQFUNC_SelectAndApplyBrushForCurrentEntry(mode);
}

long GROUP_AD_JMPTBL_DATETIME_AdjustMonthIndex(struct DateRec *d)
{
    return DATETIME_AdjustMonthIndex(d);
}

long GROUP_AD_JMPTBL_DST_ComputeBannerIndex(struct DstBannerRecord *rec, short a,
                            unsigned char b)
{
    return DST_ComputeBannerIndex(rec, a, b);
}

long GROUP_AD_JMPTBL_TLIBA3_GetViewModeHeight(long mode)
{
    return TLIBA3_GetViewModeHeight(mode);
}
