/* RESTORES: (jump table -- 31 forwarding thunks)
 * MODULE:   modules/groups/a/m/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include <stdarg.h>

extern struct MsgPort * SIGNAL_CreateMsgPortWithSignal(char *name, long pri);
extern void LADFUNC_ClearBannerRectEntries(void);
extern void PARSEINI_UpdateClockFromRtc(void);
extern void SCRIPT_InitCtrlContext(void);
extern void DISKIO2_ParseIniFileFromDisk(void);
extern void ESQ_CheckTopazFontGuard(void);
extern void P_TYPE_ResetListsAndLoadPromoIds(void);
extern long LADFUNC_LoadTextAdsFromFile(void);
extern long DISKIO_LoadConfigFromDisk(void);
extern void TEXTDISP_LoadSourceConfig(void);
extern void KYBD_InitializeInputDevices(void);
extern void ESQ_CheckCompatibleVideoChip(void);
extern void ESQ_CheckAvailableFastMemory(void);
extern void * STRUCT_AllocWithOwner(void *owner, long size);
extern void GCOMMAND_ResetBannerFadeState(void);
extern void TLIBA3_InitPatternTable(void);
extern long ESQ_FormatDiskErrorMessage(void);
extern void SCRIPT_PrimeBannerTransitionFromHexCode(void);
extern void LOCAVAIL_ResetFilterStateStruct(struct LocAvailFilterState *st);
extern void ESQ_InitAudio1Dma(void);
extern void LIST_InitHeader(long *list);
extern void ESQ_SetCopperEffect_OnEnableHighlight(void);
extern long LOCAVAIL_LoadAvailabilityDataFile(struct LaState *group1,
                                       struct LaState *group2);
extern void GCOMMAND_InitPresetDefaults(void);
extern void OVERRIDE_INTUITION_FUNCS(void);
extern void BUFFER_FlushAllAndCloseWithCode(long code);
extern void FLIB2_ResetAndLoadListingTemplates(void);
extern long WDISP_VSPrintf(char *buf, char *fmt, void *args);
extern void ESQ_SetCopperEffect_OffDisableHighlight(void);
extern void CLEANUP_ShutdownSystem(void);
extern void LADFUNC_AllocBannerRectEntries(void);

struct MsgPort * GROUP_AM_JMPTBL_SIGNAL_CreateMsgPortWithSignal(char *name, long pri)
{
    return SIGNAL_CreateMsgPortWithSignal(name, pri);
}

void GROUP_AM_JMPTBL_LADFUNC_ClearBannerRectEntries(void)
{
    LADFUNC_ClearBannerRectEntries();
}

void GROUP_AM_JMPTBL_PARSEINI_UpdateClockFromRtc(void)
{
    PARSEINI_UpdateClockFromRtc();
}

void GROUP_AM_JMPTBL_SCRIPT_InitCtrlContext(void)
{
    SCRIPT_InitCtrlContext();
}

void GROUP_AM_JMPTBL_DISKIO2_ParseIniFileFromDisk(void)
{
    DISKIO2_ParseIniFileFromDisk();
}

void GROUP_AM_JMPTBL_ESQ_CheckTopazFontGuard(void)
{
    ESQ_CheckTopazFontGuard();
}

void GROUP_AM_JMPTBL_P_TYPE_ResetListsAndLoadPromoIds(void)
{
    P_TYPE_ResetListsAndLoadPromoIds();
}

long GROUP_AM_JMPTBL_LADFUNC_LoadTextAdsFromFile(void)
{
    return LADFUNC_LoadTextAdsFromFile();
}

long GROUP_AM_JMPTBL_DISKIO_LoadConfigFromDisk(void)
{
    return DISKIO_LoadConfigFromDisk();
}

void GROUP_AM_JMPTBL_TEXTDISP_LoadSourceConfig(void)
{
    TEXTDISP_LoadSourceConfig();
}

void GROUP_AM_JMPTBL_KYBD_InitializeInputDevices(void)
{
    KYBD_InitializeInputDevices();
}

void GROUP_AM_JMPTBL_ESQ_CheckCompatibleVideoChip(void)
{
    ESQ_CheckCompatibleVideoChip();
}

void GROUP_AM_JMPTBL_ESQ_CheckAvailableFastMemory(void)
{
    ESQ_CheckAvailableFastMemory();
}

void * GROUP_AM_JMPTBL_STRUCT_AllocWithOwner(void *owner, long size)
{
    return STRUCT_AllocWithOwner(owner, size);
}

void GROUP_AM_JMPTBL_GCOMMAND_ResetBannerFadeState(void)
{
    GCOMMAND_ResetBannerFadeState();
}

void GROUP_AM_JMPTBL_TLIBA3_InitPatternTable(void)
{
    TLIBA3_InitPatternTable();
}

long GROUP_AM_JMPTBL_ESQ_FormatDiskErrorMessage(void)
{
    return ESQ_FormatDiskErrorMessage();
}

void GROUP_AM_JMPTBL_SCRIPT_PrimeBannerTransitionFromHexCode(void)
{
    SCRIPT_PrimeBannerTransitionFromHexCode();
}

void GROUP_AM_JMPTBL_LOCAVAIL_ResetFilterStateStruct(struct LocAvailFilterState *st)
{
    LOCAVAIL_ResetFilterStateStruct(st);
}

void GROUP_AM_JMPTBL_ESQ_InitAudio1Dma(void)
{
    ESQ_InitAudio1Dma();
}

void GROUP_AM_JMPTBL_LIST_InitHeader(long *list)
{
    LIST_InitHeader(list);
}

void GROUP_AM_JMPTBL_ESQ_SetCopperEffect_OnEnableHighlight(void)
{
    ESQ_SetCopperEffect_OnEnableHighlight();
}

long GROUP_AM_JMPTBL_LOCAVAIL_LoadAvailabilityDataFile(struct LaState *group1,
                                       struct LaState *group2)
{
    return LOCAVAIL_LoadAvailabilityDataFile(group1, group2);
}

void GROUP_AM_JMPTBL_GCOMMAND_InitPresetDefaults(void)
{
    GCOMMAND_InitPresetDefaults();
}

void GROUP_AM_JMPTBL_OVERRIDE_INTUITION_FUNCS(void)
{
    OVERRIDE_INTUITION_FUNCS();
}

void GROUP_AM_JMPTBL_BUFFER_FlushAllAndCloseWithCode(long code)
{
    BUFFER_FlushAllAndCloseWithCode(code);
}

void GROUP_AM_JMPTBL_FLIB2_ResetAndLoadListingTemplates(void)
{
    FLIB2_ResetAndLoadListingTemplates();
}

long GROUP_AM_JMPTBL_WDISP_SPrintf(char *buf, char *fmt, ...)
{
    va_list ap;
    long n;

    va_start(ap, fmt);
    n = WDISP_VSPrintf(buf, fmt, (void *)ap);
    va_end(ap);

    return n;
}

void GROUP_AM_JMPTBL_ESQ_SetCopperEffect_OffDisableHighlight(void)
{
    ESQ_SetCopperEffect_OffDisableHighlight();
}

void GROUP_AM_JMPTBL_CLEANUP_ShutdownSystem(void)
{
    CLEANUP_ShutdownSystem();
}

void GROUP_AM_JMPTBL_LADFUNC_AllocBannerRectEntries(void)
{
    LADFUNC_AllocBannerRectEntries();
}
