/* RESTORES: (jump table -- 10 forwarding thunks)
 * MODULE:   modules/groups/a/b/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void ESQPARS_RemoveGroupEntryAndReleaseStrings(short mode);
extern void ESQFUNC_FreeLineTextBuffers(void);
extern void ESQIFF_DeallocateAdsAndLogoLstData(void);
extern void LADFUNC_FreeBannerRectEntries(void);
extern void UNKNOWN2A_Stub0(void);
extern void NEWGRID_ShutdownGridResources(void);
extern void LOCAVAIL_FreeResourceChain(struct LocavailState *s);
extern void GRAPHICS_FreeRaster(char *who, long line, void *p, long width, long height);
extern void IOSTDREQ_Free(struct IOStdReq *io);
extern void ESQIFF2_ClearLineHeadTailByMode(short mode);

void GROUP_AB_JMPTBL_ESQPARS_RemoveGroupEntryAndReleaseStrings(short mode)
{
    ESQPARS_RemoveGroupEntryAndReleaseStrings(mode);
}

void GROUP_AB_JMPTBL_ESQFUNC_FreeLineTextBuffers(void)
{
    ESQFUNC_FreeLineTextBuffers();
}

void GROUP_AB_JMPTBL_ESQIFF_DeallocateAdsAndLogoLstData(void)
{
    ESQIFF_DeallocateAdsAndLogoLstData();
}

void GROUP_AB_JMPTBL_LADFUNC_FreeBannerRectEntries(void)
{
    LADFUNC_FreeBannerRectEntries();
}

void GROUP_AB_JMPTBL_UNKNOWN2A_Stub0(void)
{
    UNKNOWN2A_Stub0();
}

void GROUP_AB_JMPTBL_NEWGRID_ShutdownGridResources(void)
{
    NEWGRID_ShutdownGridResources();
}

void GROUP_AB_JMPTBL_LOCAVAIL_FreeResourceChain(struct LocavailState *s)
{
    LOCAVAIL_FreeResourceChain(s);
}

void GROUP_AB_JMPTBL_GRAPHICS_FreeRaster(char *who, long line, void *p, long width, long height)
{
    GRAPHICS_FreeRaster(who, line, p, width, height);
}

void GROUP_AB_JMPTBL_IOSTDREQ_Free(struct IOStdReq *io)
{
    IOSTDREQ_Free(io);
}

void GROUP_AB_JMPTBL_ESQIFF2_ClearLineHeadTailByMode(short mode)
{
    ESQIFF2_ClearLineHeadTailByMode(mode);
}
