/* RESTORES: (jump table -- 4 forwarding thunks)
 * MODULE:   modules/groups/_main/a/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void ESQ_MainExitNoOpHook(void);
extern void ESQ_MainEntryNoOpHook(void);
extern void MEMLIST_FreeAll(void);
extern void ESQ_ParseCommandLineAndRun(char *cmd);

void GROUP_MAIN_A_JMPTBL_ESQ_MainExitNoOpHook(void)
{
    ESQ_MainExitNoOpHook();
}

void GROUP_MAIN_A_JMPTBL_ESQ_MainEntryNoOpHook(void)
{
    ESQ_MainEntryNoOpHook();
}

void GROUP_MAIN_A_JMPTBL_MEMLIST_FreeAll(void)
{
    MEMLIST_FreeAll();
}

void GROUP_MAIN_A_JMPTBL_ESQ_ParseCommandLineAndRun(char *cmd)
{
    ESQ_ParseCommandLineAndRun(cmd);
}
