/* RESTORES: (jump table -- 36 forwarding thunks)
 * MODULE:   modules/groups/b/a/newgrid2_p2.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern char * COI_SelectAnimFieldPointer(struct AnimEntry *entry, short key, short mode);
extern void DISPTEXT_SetCurrentLineIndex(long pen);
extern long DISPTEXT_LayoutAndAppendToBuffer(struct RastPort *rp, char *src);
extern long DISPTEXT_GetTotalLineCount(void);
extern long TLIBA_FindFirstWildcardMatchIndex(char *pattern);
extern long DISPTEXT_BuildLayoutForSource(void *src, char *fmt);
extern void BEVEL_DrawBevelFrameWithTopRight(void *rp, long a, long b, long c, long d);
extern void * ESQDISP_GetEntryAuxPointerByMode(long index, long mode);
extern void BEVEL_DrawVerticalBevel(struct RastPort *rp, long x, long y, long w);
extern long DISPTEXT_LayoutSourceToLines(struct RastPort *rp, char *src);
extern void CLEANUP_UpdateEntryFlagBytes(void *entry, short mode);
extern void COI_RenderClockFormatEntryVariant(char *entry, char *aux, long slot,
                                       char *out, long mode);
extern long ESQDISP_TestEntryBits0And2(struct EsqDispEntry *e);
extern long DISPTEXT_ComputeVisibleLineCount(long minLines);
extern void * ESQDISP_GetEntryPointerByMode(long index, long mode);
extern void DISPTEXT_RenderCurrentLine(struct RastPort *rp, long x, long y);
extern long COI_ProcessEntrySelectionState(struct CoiEntry *entry, void *aux,
                                    short slot, long window, long fallback);
extern void CLEANUP_FormatClockFormatEntry(long slot, char *out);
extern void BEVEL_DrawBevelFrameWithTop(void *rp, long a, long b, long c, long d);
extern long ESQ_GetHalfHourSlotIndex(struct ClockSlotRec *c);
extern char * STR_SkipClass3Chars(char *s);
extern char * STRING_AppendN(char *dst, char *src, long n);
extern long ESQDISP_ComputeScheduleOffsetForRow(short row, unsigned char variant);
extern long PARSE_ReadSignedLongSkipClass3_Alt(char *s);
extern long CLEANUP_TestEntryFlagYAndBit1(struct CleanupEntry *e, short mode, long idx);
extern long DISPTEXT_IsCurrentLineLast(void);
extern long DISPTEXT_IsLastLineSelected(void);
extern void BEVEL_DrawBeveledFrame(struct RastPort *rp, long x, long y, long c, long d);
extern long DISPLIB_FindPreviousValidEntryIndex(unsigned char *ctx, void *table,
                                         long index);
extern void DISPTEXT_ComputeMarkerWidths(struct RastPort *rp, long a, long b);
extern long ESQ_TestBit1Based(unsigned char *base, long bit);
extern void BEVEL_DrawVerticalBevelPair(struct RastPort *rp, long xLeft, long yTop,
                                 long xRight, long yBottom);
extern long DISPTEXT_MeasureCurrentLineLength(struct RastPort *rp);
extern long DISPTEXT_SetLayoutParams(long width, long lines, long pen);
extern long DISPTEXT_HasMultipleLines(void);
extern void BEVEL_DrawHorizontalBevel(struct RastPort *rp, long x2, long unused,
                               long x1, long y);

char * NEWGRID2_JMPTBL_COI_SelectAnimFieldPointer(struct AnimEntry *entry, short key, short mode)
{
    return COI_SelectAnimFieldPointer(entry, key, mode);
}

void NEWGRID2_JMPTBL_DISPTEXT_SetCurrentLineIndex(long pen)
{
    DISPTEXT_SetCurrentLineIndex(pen);
}

long NEWGRID2_JMPTBL_DISPTEXT_LayoutAndAppendToBuffer(struct RastPort *rp, char *src)
{
    return DISPTEXT_LayoutAndAppendToBuffer(rp, src);
}

long NEWGRID2_JMPTBL_DISPTEXT_GetTotalLineCount(void)
{
    return DISPTEXT_GetTotalLineCount();
}

long NEWGRID2_JMPTBL_TLIBA_FindFirstWildcardMatchIndex(char *pattern)
{
    return TLIBA_FindFirstWildcardMatchIndex(pattern);
}

long NEWGRID2_JMPTBL_DISPTEXT_BuildLayoutForSource(void *src, char *fmt)
{
    return DISPTEXT_BuildLayoutForSource(src, fmt);
}

void NEWGRID2_JMPTBL_BEVEL_DrawBevelFrameWithTopRight(void *rp, long a, long b, long c, long d)
{
    BEVEL_DrawBevelFrameWithTopRight(rp, a, b, c, d);
}

void * NEWGRID2_JMPTBL_ESQDISP_GetEntryAuxPointerByMode(long index, long mode)
{
    return ESQDISP_GetEntryAuxPointerByMode(index, mode);
}

void NEWGRID2_JMPTBL_BEVEL_DrawVerticalBevel(struct RastPort *rp, long x, long y, long w)
{
    BEVEL_DrawVerticalBevel(rp, x, y, w);
}

long NEWGRID2_JMPTBL_DISPTEXT_LayoutSourceToLines(struct RastPort *rp, char *src)
{
    return DISPTEXT_LayoutSourceToLines(rp, src);
}

void NEWGRID2_JMPTBL_CLEANUP_UpdateEntryFlagBytes(void *entry, short mode)
{
    CLEANUP_UpdateEntryFlagBytes(entry, mode);
}

void NEWGRID2_JMPTBL_COI_RenderClockFormatEntryVariant(char *entry, char *aux, long slot,
                                       char *out, long mode)
{
    COI_RenderClockFormatEntryVariant(entry, aux, slot, out, mode);
}

long NEWGRID2_JMPTBL_ESQDISP_TestEntryBits0And2(struct EsqDispEntry *e)
{
    return ESQDISP_TestEntryBits0And2(e);
}

long NEWGRID2_JMPTBL_DISPTEXT_ComputeVisibleLineCount(long minLines)
{
    return DISPTEXT_ComputeVisibleLineCount(minLines);
}

void * NEWGRID2_JMPTBL_ESQDISP_GetEntryPointerByMode(long index, long mode)
{
    return ESQDISP_GetEntryPointerByMode(index, mode);
}

void NEWGRID2_JMPTBL_DISPTEXT_RenderCurrentLine(struct RastPort *rp, long x, long y)
{
    DISPTEXT_RenderCurrentLine(rp, x, y);
}

long NEWGRID2_JMPTBL_COI_ProcessEntrySelectionState(struct CoiEntry *entry, void *aux,
                                    short slot, long window, long fallback)
{
    return COI_ProcessEntrySelectionState(entry, aux, slot, window, fallback);
}

void NEWGRID2_JMPTBL_CLEANUP_FormatClockFormatEntry(long slot, char *out)
{
    CLEANUP_FormatClockFormatEntry(slot, out);
}

void NEWGRID2_JMPTBL_BEVEL_DrawBevelFrameWithTop(void *rp, long a, long b, long c, long d)
{
    BEVEL_DrawBevelFrameWithTop(rp, a, b, c, d);
}

long NEWGRID2_JMPTBL_ESQ_GetHalfHourSlotIndex(struct ClockSlotRec *c)
{
    return ESQ_GetHalfHourSlotIndex(c);
}

char * NEWGRID2_JMPTBL_STR_SkipClass3Chars(char *s)
{
    return STR_SkipClass3Chars(s);
}

char * NEWGRID2_JMPTBL_STRING_AppendN(char *dst, char *src, long n)
{
    return STRING_AppendN(dst, src, n);
}

long NEWGRID2_JMPTBL_ESQDISP_ComputeScheduleOffsetForRow(short row, unsigned char variant)
{
    return ESQDISP_ComputeScheduleOffsetForRow(row, variant);
}

long NEWGRID2_JMPTBL_PARSE_ReadSignedLongSkipClass3_Alt(char *s)
{
    return PARSE_ReadSignedLongSkipClass3_Alt(s);
}

long NEWGRID2_JMPTBL_CLEANUP_TestEntryFlagYAndBit1(struct CleanupEntry *e, short mode, long idx)
{
    return CLEANUP_TestEntryFlagYAndBit1(e, mode, idx);
}

long NEWGRID2_JMPTBL_DISPTEXT_IsCurrentLineLast(void)
{
    return DISPTEXT_IsCurrentLineLast();
}

long NEWGRID2_JMPTBL_DISPTEXT_IsLastLineSelected(void)
{
    return DISPTEXT_IsLastLineSelected();
}

void NEWGRID2_JMPTBL_BEVEL_DrawBeveledFrame(struct RastPort *rp, long x, long y, long c, long d)
{
    BEVEL_DrawBeveledFrame(rp, x, y, c, d);
}

long NEWGRID2_JMPTBL_DISPLIB_FindPreviousValidEntryIndex(unsigned char *ctx, void *table,
                                         long index)
{
    return DISPLIB_FindPreviousValidEntryIndex(ctx, table, index);
}

void NEWGRID2_JMPTBL_DISPTEXT_ComputeMarkerWidths(struct RastPort *rp, long a, long b)
{
    DISPTEXT_ComputeMarkerWidths(rp, a, b);
}

long NEWGRID2_JMPTBL_ESQ_TestBit1Based(unsigned char *base, long bit)
{
    return ESQ_TestBit1Based(base, bit);
}

void NEWGRID2_JMPTBL_BEVEL_DrawVerticalBevelPair(struct RastPort *rp, long xLeft, long yTop,
                                 long xRight, long yBottom)
{
    BEVEL_DrawVerticalBevelPair(rp, xLeft, yTop, xRight, yBottom);
}

long NEWGRID2_JMPTBL_DISPTEXT_MeasureCurrentLineLength(struct RastPort *rp)
{
    return DISPTEXT_MeasureCurrentLineLength(rp);
}

long NEWGRID2_JMPTBL_DISPTEXT_SetLayoutParams(long width, long lines, long pen)
{
    return DISPTEXT_SetLayoutParams(width, lines, pen);
}

long NEWGRID2_JMPTBL_DISPTEXT_HasMultipleLines(void)
{
    return DISPTEXT_HasMultipleLines();
}

void NEWGRID2_JMPTBL_BEVEL_DrawHorizontalBevel(struct RastPort *rp, long x2, long unused,
                               long x1, long y)
{
    BEVEL_DrawHorizontalBevel(rp, x2, unused, x1, y);
}
