/* RESTORES: (jump table -- 13 forwarding thunks)
 * MODULE:   modules/groups/b/a/wdisp_p1_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void ESQIFF_RestoreBasePaletteTriples(void);
extern long ESQFUNC_TrimTextToPixelWidthWordBoundary(struct RastPort *rp,
                                              long maxPixels, char *text);
extern void GCOMMAND_ExpandPresetBlock(unsigned char *block);
extern void ESQIFF_QueueIffBrushLoad(long mode);
extern void ESQIFF_RunCopperDropTransition(void);
extern struct Brush4 * BRUSH_FindBrushByPredicate(char *want, struct Brush4Head *h);
extern void BRUSH_FreeBrushList(unsigned char **head, long mode);
extern long BRUSH_PlaneMaskForIndex(long index);
extern void ESQ_SetCopperEffect_OnEnableHighlight(void);
extern short ESQIFF_RenderWeatherStatusBrushSlice(struct GridPanel *panel,
                                           struct WeatherBrush *brush);
extern void BRUSH_SelectBrushSlot(struct BrushRecord *brush, long x0, long y0, long x1,
                           long y1, struct RastPort *rp, long override);
extern char * NEWGRID_DrawWrappedText(struct RastPort *rp, long x, long y, long maxWidth,
                              char *text, long drawFlag);
extern void NEWGRID_ResetRowTable(struct NewgridRowTable *t);

void WDISP_JMPTBL_ESQIFF_RestoreBasePaletteTriples(void)
{
    ESQIFF_RestoreBasePaletteTriples();
}

long WDISP_JMPTBL_ESQFUNC_TrimTextToPixelWidthWordBoundary(struct RastPort *rp,
                                              long maxPixels, char *text)
{
    return ESQFUNC_TrimTextToPixelWidthWordBoundary(rp, maxPixels, text);
}

void WDISP_JMPTBL_GCOMMAND_ExpandPresetBlock(unsigned char *block)
{
    GCOMMAND_ExpandPresetBlock(block);
}

void WDISP_JMPTBL_ESQIFF_QueueIffBrushLoad(long mode)
{
    ESQIFF_QueueIffBrushLoad(mode);
}

void WDISP_JMPTBL_ESQIFF_RunCopperDropTransition(void)
{
    ESQIFF_RunCopperDropTransition();
}

struct Brush4 * WDISP_JMPTBL_BRUSH_FindBrushByPredicate(char *want, struct Brush4Head *h)
{
    return BRUSH_FindBrushByPredicate(want, h);
}

void WDISP_JMPTBL_BRUSH_FreeBrushList(unsigned char **head, long mode)
{
    BRUSH_FreeBrushList(head, mode);
}

long WDISP_JMPTBL_BRUSH_PlaneMaskForIndex(long index)
{
    return BRUSH_PlaneMaskForIndex(index);
}

void WDISP_JMPTBL_ESQ_SetCopperEffect_OnEnableHighlight(void)
{
    ESQ_SetCopperEffect_OnEnableHighlight();
}

short WDISP_JMPTBL_ESQIFF_RenderWeatherStatusBrushSlice(struct GridPanel *panel,
                                           struct WeatherBrush *brush)
{
    return ESQIFF_RenderWeatherStatusBrushSlice(panel, brush);
}

void WDISP_JMPTBL_BRUSH_SelectBrushSlot(struct BrushRecord *brush, long x0, long y0, long x1,
                           long y1, struct RastPort *rp, long override)
{
    BRUSH_SelectBrushSlot(brush, x0, y0, x1, y1, rp, override);
}

char * WDISP_JMPTBL_NEWGRID_DrawWrappedText(struct RastPort *rp, long x, long y, long maxWidth,
                              char *text, long drawFlag)
{
    return NEWGRID_DrawWrappedText(rp, x, y, maxWidth, text, drawFlag);
}

void WDISP_JMPTBL_NEWGRID_ResetRowTable(struct NewgridRowTable *t)
{
    NEWGRID_ResetRowTable(t);
}
