/* RESTORES: (jump table -- 6 forwarding thunks)
 * MODULE:   modules/groups/a/l/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern long LADFUNC_ComposePackedPenByte(unsigned char high, unsigned char low);
extern long LADFUNC_GetPackedPenLowNibble(unsigned char packed);
extern void LADFUNC_UpdateEntryFromTextAndAttrBuffers(long index, char *text,
                                               char *attr);
extern void ESQ_WriteDecFixedWidth(char *buf, int value, int width);
extern void LADFUNC_BuildEntryBuffersOrDefault(long index, char *text, char *attrs);
extern long LADFUNC_GetPackedPenHighNibble(unsigned char packed);

long GROUP_AL_JMPTBL_LADFUNC_PackNibblesToByte(unsigned char high, unsigned char low)
{
    return LADFUNC_ComposePackedPenByte(high, low);
}

long GROUP_AL_JMPTBL_LADFUNC_ExtractLowNibble(unsigned char packed)
{
    return LADFUNC_GetPackedPenLowNibble(packed);
}

void GROUP_AL_JMPTBL_LADFUNC_UpdateEntryBuffersForAdIndex(long index, char *text,
                                               char *attr)
{
    LADFUNC_UpdateEntryFromTextAndAttrBuffers(index, text, attr);
}

void GROUP_AL_JMPTBL_ESQ_WriteDecFixedWidth(char *buf, int value, int width)
{
    ESQ_WriteDecFixedWidth(buf, value, width);
}

void GROUP_AL_JMPTBL_LADFUNC_BuildEntryBuffersOrDefault(long index, char *text, char *attrs)
{
    LADFUNC_BuildEntryBuffersOrDefault(index, text, attrs);
}

long GROUP_AL_JMPTBL_LADFUNC_ExtractHighNibble(unsigned char packed)
{
    return LADFUNC_GetPackedPenHighNibble(packed);
}
