/* RESTORES: (jump table -- 28 forwarding thunks)
 * MODULE:   modules/groups/b/a/parseini_p2_p1_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

#include <stdarg.h>

extern long STRING_CompareNoCase(char *a, char *b);
extern void ED1_WaitForFlagAndClearBit0(void);
extern void DISKIO2_ParseIniFileFromDisk(void);
extern char * STR_FindCharPtr(char *s, long ch);
extern long HANDLE_OpenWithMode(char *path, char *mode);
extern void ESQIFF_QueueIffBrushLoad(long mode);
extern void ESQIFF_HandleBrushIniReloadHotkey(char key);
extern void BRUSH_FreeBrushResources(struct BrushResHead *h);
extern void ESQFUNC_RebuildPwBrushListFromTagTable(void);
extern char * GCOMMAND_FindPathSeparator(char *path);
extern char * DISKIO_ConsumeLineFromWorkBuffer(void);
extern void ED1_DrawDiagnosticsScreen(void);
extern void BRUSH_FreeBrushList(unsigned char **head, long mode);
extern void GCOMMAND_ValidatePresetTable(struct GcommandPresetTable *table);
extern void * BRUSH_AllocBrushNode(char *name, struct BrushNode *tail);
extern long UNKNOWN36_FinalizeRequest(struct PreallocHandleNode *node);
extern void GCOMMAND_InitPresetTableFromPalette(struct GCommandPresetTable *t);
extern long STRING_CompareNoCaseN(char *a, char *b, long n);
extern char * STRING_AppendAtNull(char *dst, char *src);
extern long DISKIO_LoadFileToWorkBuffer(char *path);
extern void ED1_WaitForFlagAndClearBit1(void);
extern long WDISP_VSPrintf(char *buf, char *fmt, void *args);
extern char * STREAM_ReadLineWithLimit(char *buf, long limit,
                               struct PreallocHandleNode *node);
extern char * STR_FindAnyCharPtr(char *s, char *set);
extern void ED1_ExitEscMenu(void);
extern char * ESQPARS_ReplaceOwnedString(char *newstr, char *old);
extern void ED1_EnterEscMenu(void);
extern void ESQFUNC_DrawEscMenuVersion(void);

long PARSEINI_JMPTBL_STRING_CompareNoCase(char *a, char *b)
{
    return STRING_CompareNoCase(a, b);
}

void PARSEINI_JMPTBL_ED1_WaitForFlagAndClearBit0(void)
{
    ED1_WaitForFlagAndClearBit0();
}

void PARSEINI_JMPTBL_DISKIO2_ParseIniFileFromDisk(void)
{
    DISKIO2_ParseIniFileFromDisk();
}

char * PARSEINI_JMPTBL_STR_FindCharPtr(char *s, long ch)
{
    return STR_FindCharPtr(s, ch);
}

long PARSEINI_JMPTBL_HANDLE_OpenWithMode(char *path, char *mode)
{
    return HANDLE_OpenWithMode(path, mode);
}

void PARSEINI_JMPTBL_ESQIFF_QueueIffBrushLoad(long mode)
{
    ESQIFF_QueueIffBrushLoad(mode);
}

void PARSEINI_JMPTBL_ESQIFF_HandleBrushIniReloadHotkey(char key)
{
    ESQIFF_HandleBrushIniReloadHotkey(key);
}

void PARSEINI_JMPTBL_BRUSH_FreeBrushResources(struct BrushResHead *h)
{
    BRUSH_FreeBrushResources(h);
}

void PARSEINI_JMPTBL_ESQFUNC_RebuildPwBrushListFromTagTableFromTagTable(void)
{
    ESQFUNC_RebuildPwBrushListFromTagTable();
}

char * PARSEINI_JMPTBL_GCOMMAND_FindPathSeparator(char *path)
{
    return GCOMMAND_FindPathSeparator(path);
}

char * PARSEINI_JMPTBL_DISKIO_ConsumeLineFromWorkBuffer(void)
{
    return DISKIO_ConsumeLineFromWorkBuffer();
}

void PARSEINI_JMPTBL_ED1_DrawDiagnosticsScreen(void)
{
    ED1_DrawDiagnosticsScreen();
}

void PARSEINI_JMPTBL_BRUSH_FreeBrushList(unsigned char **head, long mode)
{
    BRUSH_FreeBrushList(head, mode);
}

void PARSEINI_JMPTBL_GCOMMAND_ValidatePresetTable(struct GcommandPresetTable *table)
{
    GCOMMAND_ValidatePresetTable(table);
}

void * PARSEINI_JMPTBL_BRUSH_AllocBrushNode(char *name, struct BrushNode *tail)
{
    return BRUSH_AllocBrushNode(name, tail);
}

long PARSEINI_JMPTBL_UNKNOWN36_FinalizeRequest(struct PreallocHandleNode *node)
{
    return UNKNOWN36_FinalizeRequest(node);
}

void PARSEINI_JMPTBL_GCOMMAND_InitPresetTableFromPalette(struct GCommandPresetTable *t)
{
    GCOMMAND_InitPresetTableFromPalette(t);
}

long PARSEINI_JMPTBL_STRING_CompareNoCaseN(char *a, char *b, long n)
{
    return STRING_CompareNoCaseN(a, b, n);
}

char * PARSEINI_JMPTBL_STRING_AppendAtNull(char *dst, char *src)
{
    return STRING_AppendAtNull(dst, src);
}

long PARSEINI_JMPTBL_DISKIO_LoadFileToWorkBuffer(char *path)
{
    return DISKIO_LoadFileToWorkBuffer(path);
}

void PARSEINI_JMPTBL_ED1_WaitForFlagAndClearBit1(void)
{
    ED1_WaitForFlagAndClearBit1();
}

long PARSEINI_JMPTBL_WDISP_SPrintf(char *buf, char *fmt, ...)
{
    va_list ap;
    long n;

    va_start(ap, fmt);
    n = WDISP_VSPrintf(buf, fmt, (void *)ap);
    va_end(ap);

    return n;
}

char * PARSEINI_JMPTBL_STREAM_ReadLineWithLimit(char *buf, long limit,
                               struct PreallocHandleNode *node)
{
    return STREAM_ReadLineWithLimit(buf, limit, node);
}

char * PARSEINI_JMPTBL_STR_FindAnyCharPtr(char *s, char *set)
{
    return STR_FindAnyCharPtr(s, set);
}

void PARSEINI_JMPTBL_ED1_ExitEscMenu(void)
{
    ED1_ExitEscMenu();
}

char * PARSEINI_JMPTBL_ESQPARS_ReplaceOwnedString(char *newstr, char *old)
{
    return ESQPARS_ReplaceOwnedString(newstr, old);
}

void PARSEINI_JMPTBL_ED1_EnterEscMenu(void)
{
    ED1_EnterEscMenu();
}

void PARSEINI_JMPTBL_ESQFUNC_DrawEscMenuVersion(void)
{
    ESQFUNC_DrawEscMenuVersion();
}
