/* RESTORES: (jump table -- 4 forwarding thunks)
 * MODULE:   modules/groups/a/a/xjump.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern long STRING_CompareNoCase(char *a, char *b);
extern long STRING_CompareN(char *a, char *b, long n);
extern char * GCOMMAND_FindPathSeparator(char *path);
extern long GRAPHICS_AllocRaster(char *who, long line, long width, long height);

long GROUP_AA_JMPTBL_STRING_CompareNoCase(char *a, char *b)
{
    return STRING_CompareNoCase(a, b);
}

long GROUP_AA_JMPTBL_STRING_CompareN(char *a, char *b, long n)
{
    return STRING_CompareN(a, b, n);
}

char * GROUP_AA_JMPTBL_GCOMMAND_FindPathSeparator(char *path)
{
    return GCOMMAND_FindPathSeparator(path);
}

long GROUP_AA_JMPTBL_GRAPHICS_AllocRaster(char *who, long line, long width, long height)
{
    return GRAPHICS_AllocRaster(who, line, width, height);
}
