/* RESTORES: (jump table -- 2 forwarding thunks)
 * MODULE:   modules/groups/b/a/tliba2_p2_p0.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern void DST_AddTimeOffset(struct DstRec *d, short hours, short minutes);
extern long ESQ_TestBit1Based(unsigned char *base, long bit);

void TLIBA2_JMPTBL_DST_AddTimeOffset(struct DstRec *d, short hours, short minutes)
{
    DST_AddTimeOffset(d, hours, minutes);
}

long TLIBA2_JMPTBL_ESQ_TestBit1Based(unsigned char *base, long bit)
{
    return ESQ_TestBit1Based(base, bit);
}
