/* RESTORES: (jump table -- 10 forwarding thunks)
 * MODULE:   modules/groups/b/a/tliba1_p1_p1.s
 * STATUS:   behavioural
 *
 * Generated by tools/jmptbl_to_c.py, then read.
 *
 * Each function here replaces a two-instruction `JMP` thunk. The parameter
 * lists are copied from the targets' own restorations, so the arguments are
 * FORWARDED. A thunk written `void f(void)` would compile, link, and pass
 * nothing to a callee that expects arguments.
 *
 * SASC-MISMATCH: tail-jump
 *   ref:     JMP target          the caller's return address is reused
 *   got:     BSR.W target / RTS  a call and a return
 *   summary: SAS/C emits no tail jump for a call in return position, so each
 *            thunk costs two bytes and one extra frame for the duration of
 *            the call. Same arguments, same result.
 *   scope:   every jump table in the program.
 *   retest:  a compiler that turns a call in return position into a jump.
 */

extern char * COI_GetAnimFieldPointerByMode(struct AnimEntry *entry, short key,
                                    short mode);
extern void * ESQDISP_GetEntryAuxPointerByMode(long index, long mode);
extern long LADFUNC_GetPackedPenLowNibble(unsigned char packed);
extern void * ESQDISP_GetEntryPointerByMode(long index, long mode);
extern long COI_TestEntryWithinTimeWindow(struct CoiEntry *entry, void *aux,
                                   short slot, long window, long fallback);
extern void CLEANUP_FormatClockFormatEntry(long slot, char *out);
extern long ESQDISP_ComputeScheduleOffsetForRow(short row, unsigned char variant);
extern char * ESQ_FindSubstringCaseFold(char *hay, char *needle);
extern long DISPLIB_FindPreviousValidEntryIndex(unsigned char *ctx, void *table,
                                         long index);
extern long LADFUNC_GetPackedPenHighNibble(unsigned char packed);

char * TLIBA1_JMPTBL_COI_GetAnimFieldPointerByMode(struct AnimEntry *entry, short key,
                                    short mode)
{
    return COI_GetAnimFieldPointerByMode(entry, key, mode);
}

void * TLIBA1_JMPTBL_ESQDISP_GetEntryAuxPointerByMode(long index, long mode)
{
    return ESQDISP_GetEntryAuxPointerByMode(index, mode);
}

long TLIBA1_JMPTBL_LADFUNC_ExtractLowNibble(unsigned char packed)
{
    return LADFUNC_GetPackedPenLowNibble(packed);
}

void * TLIBA1_JMPTBL_ESQDISP_GetEntryPointerByMode(long index, long mode)
{
    return ESQDISP_GetEntryPointerByMode(index, mode);
}

long TLIBA1_JMPTBL_COI_TestEntryWithinTimeWindow(struct CoiEntry *entry, void *aux,
                                   short slot, long window, long fallback)
{
    return COI_TestEntryWithinTimeWindow(entry, aux, slot, window, fallback);
}

void TLIBA1_JMPTBL_CLEANUP_FormatClockFormatEntry(long slot, char *out)
{
    CLEANUP_FormatClockFormatEntry(slot, out);
}

long TLIBA1_JMPTBL_ESQDISP_ComputeScheduleOffsetForRow(short row, unsigned char variant)
{
    return ESQDISP_ComputeScheduleOffsetForRow(row, variant);
}

char * TLIBA1_JMPTBL_ESQ_FindSubstringCaseFold(char *hay, char *needle)
{
    return ESQ_FindSubstringCaseFold(hay, needle);
}

long TLIBA1_JMPTBL_DISPLIB_FindPreviousValidEntryIndex(unsigned char *ctx, void *table,
                                         long index)
{
    return DISPLIB_FindPreviousValidEntryIndex(ctx, table, index);
}

long TLIBA1_JMPTBL_LADFUNC_ExtractHighNibble(unsigned char packed)
{
    return LADFUNC_GetPackedPenHighNibble(packed);
}
