/* MERGED MODULE: modules/groups/a/w/ladfunc_p1_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: LADFUNC_DisplayTextPackedPens, LADFUNC_DrawEntryLineWithAttrs
 */
#include "ladfunc_display_text_packed_pens.c"
#include "ladfunc_draw_entry_line_with_attrs.c"
