/* RESTORES: HANDLE_GetEntryByIndex
 * MODULE:   modules/submodules/unknown23.s
 * STATUS:   behavioural
 *
 * SAS/C library code, and the FIRST restoration to reach the A4 near-data area
 * from C. It validates a file-handle index and returns a pointer to the table
 * entry, or NULL with the error code set.
 *
 * THE A4 GLOBALS ARE ORDINARY GLOBALS. `Global_DosIoErr(A4)` and its siblings
 * look like SAS/C runtime state hidden somewhere unreachable; they are named
 * addresses in our own DATA section. A4 is `_Global_REF_LONG_FILE_SCRATCH` at
 * DATA offset 32768, each `Global_*` is an equate giving a displacement from it,
 * and `src/c/esq-neardata.h` -- generated by `tools/a4_resolve.py` -- turns each
 * into an accessor. Nothing in the assembly had to change.
 *
 * THE HEADER GIVES TWO FORMS PER SYMBOL AND THE CHOICE MATTERS.
 * `Global_HandleTableCount_A4` READS a long, matching `CMP.L sym(A4),D7`.
 * `Global_HandleTableBase_A4_ADDR` is an ADDRESS, matching
 * `LEA sym(A4),A0` -- the table base is an array, never a long. Reading it as a
 * value would give the first entry's flags word and index from there, which is
 * exactly the class of defect `tools/data_shape_audit.py` exists to catch and
 * which no byte comparison can see.
 *
 * THE ENTRY IS EIGHT BYTES, flags first. `ASL.L #3` is the index scale and
 * src/structs.s gives `Struct_HandleEntry_Size = 8` and
 * `Struct_HandleEntry__Flags = 0`.
 *
 * IT CLEARS THE IO ERROR ON ENTRY, unconditionally, before it validates
 * anything. A caller that reads the error after a successful call sees zero, not
 * whatever the last DOS call left.
 *
 * A NEGATIVE INDEX IS REJECTED SEPARATELY from an out-of-range one -- `TST.L D7 /
 * BMI` then `CMP.L count / BGE` -- because the comparison is SIGNED and a
 * negative index would otherwise pass an unsigned bound test.
 *
 * SASC-MISMATCH: near-data-addressing
 *   ref:     MOVE.L D0,Global_DosIoErr(A4)   16-bit displacement off A4
 *   got:     an absolute reference through the enclosing array
 *   summary: the original addresses near-data through A4; a DATA=FAR build
 *            addresses every global absolutely. Same address, 2 bytes more per
 *            site.
 *   scope:   every A4 reference in modules/submodules/, 59 symbols.
 *   retest:  a build using SAS/C near data, which this project does not use.
 */
#include "esq-neardata.h"

struct HandleEntry {
    long  flags;        /* +0, Struct_HandleEntry__Flags */
    void *ptr;          /* +4 */
};                      /* Struct_HandleEntry_Size = 8 */

struct HandleEntry *HANDLE_GetEntryByIndex(long index)
{
    struct HandleEntry *table = (struct HandleEntry *)Global_HandleTableBase_A4_ADDR;

    Global_DosIoErr_A4 = 0;

    if (index >= 0 && index < Global_HandleTableCount_A4
            && table[index].flags != 0)
        return &table[index];

    Global_AppErrorCode_A4 = 9;
    return 0;
}
