/* MERGED MODULE: modules/groups/b/a/newgrid_p4.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: NEWGRID_DrawGridFrame, NEWGRID_ShouldOpenEditor
 */
#include "newgrid_draw_grid_frame.c"
#include "newgrid_should_open_editor.c"
