/* MERGED MODULE: modules/groups/b/a/newgrid1b_p1_2_p0_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: NEWGRID_SetSelectionMarkers, NEWGRID_GetEntryStateCode, NEWGRID_TestEntryState, NEWGRID_DrawEntryRowOrPlaceholder
 */
#include "newgrid_set_selection_markers.c"
#include "newgrid_get_entry_state_code.c"
#include "newgrid_test_entry_state.c"
#include "newgrid_draw_entry_row_or_placeholder.c"
