/* MERGED MODULE: modules/groups/b/a/newgrid1b_p2_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: NEWGRID_HandleGridEditorState, NEWGRID_FindNextEntryWithFlags
 */
#include "newgrid_handle_grid_editor_state.c"
#include "newgrid_find_next_entry_with_flags.c"
