/* MERGED MODULE: modules/groups/b/a/newgrid_p2_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: NEWGRID_ComputeDaySlotFromClock, NEWGRID_ComputeDaySlotFromClockWithOffset, NEWGRID_AdjustClockStringBySlot, NEWGRID_AdjustClockStringBySlotWithOffset
 */
#include "newgrid_compute_day_slot_from_clock.c"
#include "newgrid_compute_day_slot_from_clock_with_offset.c"
#include "newgrid_adjust_clock_string_by_slot.c"
#include "newgrid_adjust_clock_string_by_slot_with_offset.c"
