/* MERGED MODULE: modules/groups/b/a/parseini2_p1.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: PARSEINI_NormalizeClockData, PARSEINI2_JMPTBL_CLOCK_ConvertAmigaSecondsToClockData, PARSEINI2_JMPTBL_ESQ_CalcDayOfYearFromMonthDay, PARSEINI2_JMPTBL_CLOCK_CheckDateOrSecondsFromEpoch, PARSEINI2_JMPTBL_BATTCLOCK_GetSecondsFromBatteryBackedClock, PARSEINI2_JMPTBL_DATETIME_IsLeapYear, PARSEINI2_JMPTBL_BATTCLOCK_WriteSecondsToBatteryBackedClock, PARSEINI2_JMPTBL_CLOCK_SecondsFromEpoch
 */
#include "parseini_normalize_clock_data.c"
