/* MERGED MODULE: modules/groups/b/a/textdisp3_p1_p1_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: TEXTDISP_DrawInsetRectFrame, TEXTDISP_BuildEntryShortName
 */
#include "textdisp_draw_inset_rect_frame.c"
#include "textdisp_build_entry_short_name.c"
