/* MERGED MODULE: modules/groups/b/a/textdisp2_p0_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: TEXTDISP_DrawNextEntryPreview, TEXTDISP_UpdateHighlightOrPreview
 */
#include "textdisp_draw_next_entry_preview.c"
#include "textdisp_update_highlight_or_preview.c"
