/* MERGED MODULE: modules/groups/b/a/textdisp_p2_p1.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: TEXTDISP_ClearSourceConfig, TEXTDISP_ApplySourceConfigToEntry, TEXTDISP_ApplySourceConfigAllEntries
 */
#include "textdisp_clear_source_config.c"
#include "textdisp_apply_source_config_to_entry.c"
#include "textdisp_apply_source_config_all_entries.c"
