/* MERGED MODULE: modules/groups/b/a/tliba3_p4_p0.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: TLIBA3_DumpCurrentViewModePattern, TLIBA3_DumpAllViewModePatterns
 */
#include "tliba3_dump_current_view_mode_pattern.c"
#include "tliba3_dump_all_view_mode_patterns.c"
