/* MERGED MODULE: modules/groups/b/a/tliba1_p1.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: TLIBA1_DrawInlineStyledText, TLIBA1_DrawFormattedTextBlock
 */
#include "tliba1_draw_inline_styled_text.c"
#include "tliba1_draw_formatted_text_block.c"
