/* MERGED MODULE: modules/submodules/unknown29.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: ESQ_ParseCommandLineAndRun, UNKNOWN29_JMPTBL_ESQ_MainInitAndRun
 */
#include "lib_parse_command_line_and_run.c"
#include "jmptbl_submodules_unknown29.c"
