/* MERGED MODULE: modules/submodules/unknown.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: UNKNOWN_ParseRecordAndUpdateDisplay, UNKNOWN_ParseListAndUpdateEntries, ESQPROTO_VerifyChecksumAndParseRecord, ESQPROTO_VerifyChecksumAndParseList, ESQPROTO_ParseDigitLabelAndDisplay, ESQPROTO_CopyLabelToGlobal
 */
#include "unknown_parse_record_and_update_display.c"
#include "unknown_parse_list_and_update_entries.c"
#include "esqproto_parse.c"
