/* MERGED MODULE: modules/submodules/unknown42.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: CLOCK_CheckDateOrSecondsFromEpoch, CLOCK_SecondsFromEpoch, PARALLEL_WriteCharStackArg, PARALLEL_WriteCharD0, PARALLEL_WriteStringStackArg, PARALLEL_WriteStringLoop, PARALLEL_WaitReady, PARALLEL_CheckReady, PARALLEL_RawDoFmtArgPtr, PARALLEL_RawDoFmtStackArgs, PARALLEL_RawDoFmtCommon, PARALLEL_RawDoFmtWithData, PARALLEL_WriteCharHwStackArg, PARALLEL_WriteCharHw, PARALLEL_RawDoFmt, PARALLEL_CheckReadyStub
 */
#include "lib_clock_utility_thunks.c"
#include "lib_parallel_debug_port.c"
