/* MERGED MODULE: modules/groups/b/a/wdisp_p1.s
 *
 * A C replacement substitutes for a WHOLE module, so every label in this
 * one has to be present before any of it can be linked. Each restoration
 * below is finished and lives in its own file; this unit only puts them in
 * the module's own order. Generated by tools/merge_module_c.py -- edit the
 * included files, never this one.
 *
 * RESTORES: WDISP_TickWeatherCycleOffset, WDISP_RenderWeatherStatusBrushSliceForIndex
 */
#include "wdisp_tick_weather_cycle_offset.c"
#include "wdisp_render_weather_status_brush_slice_for_index.c"
