#!/usr/bin/env python3
"""Resolve every `<name>(A4)` reference to the DATA label it actually names.

    python3 tools/a4_resolve.py              # the whole table
    python3 tools/a4_resolve.py --unlabelled # only the ones needing a label

`modules/submodules/` is full of references like `Global_DosIoErr(A4)`, and they
look like SAS/C runtime state hidden in a near-data area that a `DATA=FAR` build
cannot reach. They are not. **A4 is `_Global_REF_LONG_FILE_SCRATCH`**, loaded by
ESQ_StartupEntry in its fourth instruction and never changed, and each `Global_*`
name is an equate in `src/Prevue.asm` giving a displacement from it.

So an A4 reference is an ordinary global with a name, and restoring it in C is
faithful rather than an analogue. The only divergence is the addressing mode: a
16-bit displacement off A4 becomes an absolute reference, which is what
`DATA=FAR` means.

Two things make it more work than a regex:

**Most equates are EXPRESSIONS.** `Global_AppErrorCode` is
`Global_FormatCallbackByteCount+Type_Long_Size`. Matching `= <number>` resolves
only 14 of the 59, so the definitions are evaluated to a fixed point here.

**Some land on unlabelled space.** They point into the middle of a `DS.B`/`DS.L`
block that carries no label. Those need a label adding -- byte-neutral, like
every other labelling in this project -- before C can name them. `--unlabelled`
lists exactly those, with the enclosing label and the offset into it, which is
what you need to place the new one.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))

A4_BASE_LABEL = '_Global_REF_LONG_FILE_SCRATCH'


def equates():
    """Every `NAME = expr` in Prevue.asm, evaluated to a fixed point."""
    raw = {}
    for line in open(os.path.join(ROOT, 'src', 'Prevue.asm')):
        m = re.match(r'^([A-Za-z_][\w]*)\s*=\s*(.+?)\s*$', line.split(';')[0])
        if m:
            raw[m.group(1)] = m.group(2).strip()
    # also the shared headers, for Type_Long_Size and friends
    for f in sorted(os.listdir(os.path.join(ROOT, 'src'))):
        if not f.endswith('.s'):
            continue
        for line in open(os.path.join(ROOT, 'src', f)):
            m = re.match(r'^\s*([A-Za-z_][\w]*)\s*(?:=|EQU)\s*(.+?)\s*$',
                         line.split(';')[0])
            if m:
                raw.setdefault(m.group(1), m.group(2).strip())

    vals, changed = {}, True
    while changed:
        changed = False
        for k, e in raw.items():
            if k in vals:
                continue
            expr = e.replace('$', '0x')
            try:
                v = eval(expr, {'__builtins__': {}}, dict(vals))
            except Exception:
                continue
            if isinstance(v, int):
                vals[k] = v
                changed = True
    return vals


def data_map():
    """DATA offset -> [labels], and the ordered span list for enclosing lookups."""
    import gen_units as gu
    import data_to_c as d
    old = os.environ.copy()
    os.environ.pop('C_REPLACEMENTS', None)
    os.environ.pop('ESQ_FARCALLS', None)
    try:
        prelude, incs = gu.read_root()
        os.makedirs(gu.OUT, exist_ok=True)
        gu.far_rewrite(incs)
        sizes, ncode = gu.measure(incs)
        size = dict(zip(incs, sizes))
    finally:
        os.environ.clear()
        os.environ.update(old)

    at, spans, off = {}, [], 0
    for p in [i for i in incs if i.startswith('data/')]:
        try:
            ss, tot, cond = d.parse(p)
        except d.Unsupported:
            off += size[p]
            continue
        o = off
        for lab, items in ss:
            at.setdefault(o, []).append(lab)
            n = d.span_bytes(items)
            spans.append((o, n, lab, p))
            o += n
        off += size[p]
    return at, spans


def emit_header(eq, at, spans, base, used):
    """Write src/c/esq-neardata.h: one accessor per A4 symbol.

    Nothing in the assembly has to change. Every unlabelled A4 address falls
    inside a block that is ALREADY a C array -- the big DS reservations that the
    SAS/C runtime carves up -- so the accessor indexes that array at the right
    displacement. That is exactly what the original does through A4, expressed
    absolutely.
    """
    out = ['/* A4 near-data accessors. GENERATED by tools/a4_resolve.py.',
           ' *',
           ' * modules/submodules/ reaches its globals as `Global_DosIoErr(A4)`.',
           ' * A4 is _Global_REF_LONG_FILE_SCRATCH, at DATA offset %d, and each name'
           % base,
           ' * is an equate in src/Prevue.asm giving a displacement from it. So each of',
           ' * these is an ordinary global, and restoring one in C is faithful rather',
           ' * than an analogue.',
           ' *',
           ' * Most of them carry no label of their own: they sit inside the big DS',
           ' * reservations the runtime carves up. Those are reached by indexing the',
           ' * enclosing array, which needs no change to the assembly at all.',
           ' *',
           ' * Each symbol gets TWO forms. `<name>_A4` READS the datum, matching',
           ' * `MOVE.L sym(A4),Dn`. `<name>_A4_ADDR` is its ADDRESS, matching',
           ' * `LEA sym(A4),An`. Picking the wrong one is the defect',
           ' * data_shape_audit.py exists to catch, and it is invisible in a byte',
           ' * comparison -- Global_HandleTableBase is an array base, never a long.',
           ' */',
           '#ifndef ESQ_NEARDATA_H',
           '#define ESQ_NEARDATA_H',
           '']
    arrays, defs, skipped = set(), [], []
    for s in sorted(used):
        if s not in eq:
            skipped.append((s, 'equate does not evaluate'))
            continue
        addr = base + eq[s]
        labs = at.get(addr)
        if labs:
            defs.append((s, None, labs[0], 0))
            continue
        encl = [(o, n, l, p) for o, n, l, p in spans if o <= addr < o + n]
        if not encl:
            skipped.append((s, 'outside every parsed span'))
            continue
        o, n, l, p = encl[0]
        arrays.add(l)
        defs.append((s, l, l, addr - o))

    for a in sorted(arrays):
        out.append('extern unsigned char %s[];' % a.lstrip('_'))
    out.append('')
    for s, arr, lab, disp in defs:
        name = lab.lstrip('_')
        # TWO forms, and picking the wrong one is the defect data_shape_audit.py
        # exists to catch: `MOVE.L sym(A4),Dn` READS the datum, while
        # `LEA sym(A4),An` takes its ADDRESS. Global_HandleTableBase is only ever
        # LEA'd -- it is an array base, not a long.
        if arr is None:
            out.append('/* %s is its own symbol. */' % s)
            out.append('extern unsigned char %s[];' % name)
            out.append('#define %s_A4       (*(long *)%s)' % (s, name))
            out.append('#define %s_A4_ADDR  ((void *)%s)' % (s, name))
        else:
            out.append('#define %s_A4       (*(long *)(%s + %d))' % (s, name, disp))
            out.append('#define %s_A4_ADDR  ((void *)(%s + %d))' % (s, name, disp))
        out.append('')
    if skipped:
        out.append('/* NOT RESOLVED, and left out on purpose rather than guessed at:')
        for s, why in skipped:
            out.append(' *   %-40s %s' % (s, why))
        out.append(' */')
    out.append('#endif')
    dst = os.path.join(ROOT, 'src', 'c', 'esq-neardata.h')
    open(dst, 'w').write('\n'.join(out) + '\n')
    sys.stderr.write('wrote %s: %d accessors, %d skipped\n'
                     % (dst, len(defs), len(skipped)))


def main():
    eq = equates()
    at, spans = data_map()
    base = next(o for o, ls in at.items() if A4_BASE_LABEL in ls)

    used = set()
    for dp, _, fs in os.walk(os.path.join(ROOT, 'src', 'modules')):
        for f in fs:
            if f.endswith('.s'):
                used |= set(re.findall(r'([A-Za-z_][\w]*)\(A4\)',
                                       open(os.path.join(dp, f)).read()))

    if '--header' in sys.argv:
        emit_header(eq, at, spans, base, used)
        return

    only_bad = '--unlabelled' in sys.argv
    named = unnamed = unknown = 0
    rows = []
    for s in sorted(used):
        if s not in eq:
            unknown += 1
            rows.append((s, None, 'equate does not evaluate', ''))
            continue
        addr = base + eq[s]
        labs = at.get(addr)
        if labs:
            named += 1
            rows.append((s, eq[s], ', '.join(labs), ''))
        else:
            unnamed += 1
            encl = [(o, n, l, p) for o, n, l, p in spans if o <= addr < o + n]
            where = ('inside %s +%d  (%s)' % (encl[0][2], addr - encl[0][0], encl[0][3])
                     if encl else 'outside every parsed span')
            rows.append((s, eq[s], '<< NO LABEL >>', where))

    for s, v, lab, where in rows:
        if only_bad and lab != '<< NO LABEL >>':
            continue
        print('%-42s %8s  %s' % (s, v if v is not None else '', lab))
        if where:
            print('%-42s %8s      %s' % ('', '', where))

    sys.stderr.write('\nA4 base %s at DATA offset %d\n' % (A4_BASE_LABEL, base))
    sys.stderr.write('%d symbols: %d named, %d need a label, %d unevaluated\n'
                     % (len(used), named, unnamed, unknown))


if __name__ == '__main__':
    main()
