#!/bin/bash
# Build ESQ with NO ASSEMBLY AT ALL, for the port.
#
#   tools/portable_build.sh
#
# WHAT THIS IS FOR
#
# The next phase of this project is to take the C and run it on another
# platform behind a layer that emulates the Amiga APIs. That needs a source set
# with no .s file in it. The ordinary maximum-C build is 99.98% there and stops
# at 44 bytes: three strings a DATA table holds the addresses of.
#
# This build adds those three to the manifest as C, which takes the assembly
# contribution to ZERO.
#
# READ THIS BEFORE RUNNING THE RESULT ON AN AMIGA
#
# THE BINARY THIS PRODUCES IS NOT A WORKING AMIGA BUILD, and that is by
# construction rather than by accident. SAS/C places string literals in `data`,
# so those 44 bytes land in hunk1 and every data symbol after them moves.
# AGENTS.md records that a DATA hunk which grows by even FOUR bytes froze the
# display, measured twice on data/flib.s. Expect this one to do the same.
#
# Its purpose is the SOURCE SET, not the artifact: it proves the C compiles and
# links with nothing else, and it is the thing to hand to the port. For a build
# to actually run on the box, use the ordinary command, which leaves the
# assembly module alone:
#
#   ESQ_FARCALLS=1 SCOPTS="NOSTKCHK DATA=FAR CODE=FAR CODENAME=S_0 DATANAME=S_1 IDLEN=128" \
#     C_REPLACEMENTS=src/c/replacements-all.txt ./build-split.sh
#
# The two differ by one manifest row and one define. Nothing else in the tree
# changes, so the byte-exact gates are untouched either way.
set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

BASE=src/c/replacements-all.txt
OUT=src/c/replacements-portable.txt
ROW='modules/submodules/unknown36_p0_strings.s                              c/data_debug_abort_strings.c'

[ -f "$BASE" ] || { echo "no $BASE -- run tools/gen_all_manifest.py first"; exit 1; }

{
    echo "# GENERATED by tools/portable_build.sh -- do not hand-edit."
    echo "#"
    echo "# $BASE plus one row: the three Ctrl-C requester strings as C."
    echo "# That row is what takes the assembly contribution to zero, and it is"
    echo "# also what makes the resulting binary unusable on an Amiga -- the"
    echo "# strings land in the DATA hunk and shift every symbol after them."
    echo "# See the header of this script."
    echo
    cat "$BASE"
    echo "$ROW"
} > "$OUT"

echo "==> $OUT: $(grep -vc '^\s*#\|^\s*$' "$OUT") entries"

ESQ_FARCALLS=1 \
SCOPTS="NOSTKCHK DATA=FAR CODE=FAR CODENAME=S_0 DATANAME=S_1 IDLEN=128 DEFINE=ESQ_PORTABLE=1" \
C_REPLACEMENTS="$OUT" \
    ./build-split.sh
RC=$?

echo
echo "==> assembly remaining in the linked image"
python3 - <<'PY'
import re
tot={'a':0,'c':0}; mods=[]
try:
    lines = open('build/ESQ.map')
except OSError:
    print("  no build/ESQ.map -- the link did not get that far"); raise SystemExit(1)
for line in lines:
    m = re.match(r'\s+(\S+):\s+(.*) hex\s*$', line)
    if not m: continue
    k = 'a' if m.group(1).endswith('.asm') else 'c'
    for sec, sz in re.findall(r'(S_[01])\s+[0-9a-f]+\(([0-9a-f]+)\)', m.group(2)):
        n = int(sz, 16); tot[k] += n
        if k == 'a' and n: mods.append((n, m.group(1)))
print(f"  assembly {tot['a']} bytes   C {tot['c']} bytes")
for s, n in sorted(mods, reverse=True):
    print(f"    {s:5d}  {n}")
if tot['a'] == 0:
    print("\n  ZERO ASSEMBLY. The source set is pure C.")
else:
    print(f"\n  {tot['a']} bytes still come from assembly.")
PY
exit $RC
